### ISSUE TITLE
[Add] 에코레일 자전거 열차

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#101]
![image](https://user-images.githubusercontent.com/10726524/112625686-9a3c6f80-8e72-11eb-9bec-df5b31de7f2a.png)

 * 그래픽 개선 작업 필요할 수 있음
 * 레퍼런스 필요
   * 수화물차 개조한 차량
   * https://images.app.goo.gl/zAZASMbTnCfHGafX6
 * 넣을지 말지 의견 필요
 * Author: 오픈기차

**Comment by opentrain** [comment]
지금 소화물차 리메이크 작업 들어가고있습니다.

**Comment by telk5093** [comment]
@opentrain 관광열차 도색은 더이상 안 들어갈 가능성이 높습니다. 작업을 권장하지 않습니다.
또 본 이슈와 관련없는 이야기는 지양해주세요.
