### ISSUE TITLE
[Add] 동해산타열차

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#106]
![image](https://user-images.githubusercontent.com/10726524/112628721-9dd1f580-8e76-11eb-8676-cac55b6fe1fa.png)

**Comment by kiwitreekor** [comment]
![NURIRO_santa](https://user-images.githubusercontent.com/24273113/113005036-10144400-91af-11eb-864f-4ae7a6da88be.png)

선두차
팬터그래프(짝수)
팬터그래프(홀수)
객차(짝수)
객차(홀수)
선두차(뒤,짝수)
선두차(뒤,홀수)

**Comment by telk5093** [comment]
![NURIRO_SANTA](https://user-images.githubusercontent.com/10726524/113023000-2b3b7f80-91c0-11eb-8cef-50ae13edfd18.png)

선두차(뒤, 짝홀수)에 파란 선이 남아있어서 교정

**Comment by telk5093** [comment]
반영되었습니다.
