### ISSUE TITLE
미카 3형, 마터 2형, 파시 5형 증기기관차 스프라이트 수정

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#107]
![증기기관차 마터 2형 2차 완성](https://user-images.githubusercontent.com/75788864/112713012-28b5fd00-8f16-11eb-9de3-c67702290777.png)
![증기기관차 미카 3형 2차 완성](https://user-images.githubusercontent.com/75788864/112713014-29e72a00-8f16-11eb-9afc-0e9f9b13e1af.png)
![증기기관차 파시 5형 4차 완성](https://user-images.githubusercontent.com/75788864/112713015-2a7fc080-8f16-11eb-9704-6362f3e52ce2.png)

마지막 수정 버전입니다. 

정말 죄송합니다만 모두 사이즈가 바뀌어서 전부 스프라이트 조정 새로 하셔야 할 것 같습니다.. 기존 것들은 스프라이트에 익숙하지 않을 때 작업한 것들이라, 인게임상에서 어색한 게 너무 눈에 보여서 정말 고칠 수밖에 없었습니다.

마터 2형, 파시 5형은 길이 0.9를, 미카 3형은 0.8을 추천해드립니다. 애초에 길이를 정하고 사이즈를 맞춘거라 아마 맞을겁니다.

반드시 스프라이트 오른쪽에 있는 '탄수차와 결합한 모습' 예상도에 최대한 맞춰서 조정해주세요. (중련, 1번과 5번 방향은 제외) 

상당히 신경써서 만든거라 그럴 가능성은 거의 없다고 생각하지만 만의 하나라도 예상도대로 스프라이트 조정을 했는데 어색한 곳이 있다면, 그냥 텔크님이 보시기에 괜찮은대로 수정해주세요. 

제 스프라이트 잘 적용해주셔서 정말 감사합니다.

**Comment by Gamunbi** [comment]
아 그리고 건의해드릴 게 있는데 'OO X형' 뒤에 '증기기관차' 라고 이름 추가로 붙여주시면 좋겠습니다. 디젤이나 전기 기관차들은 'OOOO호대 디젤기관차' 라고 되어있는데 증기들만 없으면 보기에 조화롭지 않을 것 같아서요.

**Comment by telk5093** [comment]
길이 0.9, 0.8은 기술적 한계로 불가능한 길이입니다. (NML은 열차 1량의 길이를 8로 가정하고, 1~8 까지만 지정 가능)
이름은 변경해두겠습니다 :)

**Comment by Gamunbi** [comment]
윽.. 알겠습니다 ㅠㅠ

**Comment by kiwitreekor** [comment]
> 길이 0.9, 0.8은 기술적 한계로 불가능한 길이입니다. (NML은 열차 1량의 길이를 8로 가정하고, 1~8 까지만 지정 가능)
> 이름은 변경해두겠습니다 :)

현재도 탄수차와 articulated vehicle 형태로 구현된 상태 아닌가요?

**Comment by telk5093** [comment]
@kiwitreekor 
> 현재도 탄수차와 articulated vehicle 형태로 구현된 상태 아닌가요?
Articulated vehicle 형태로 구현되어있고, 현재는 증기 기관차 본체는 길이 ``8``(=1), 탄수차는 ``5``(=5/8=0.625)로 지정되어 있습니다.
게임 상에서는 세 차량 모두 0.9로 취급되고 있는 거 보니 0.9 길이는 크게 신경쓰지 않아도 되겠네요.
0.8 길이가 가능할지는 모르겠습니다.

**Comment by Gamunbi** [comment]
그렇군요. 0.8은 타협을 봐야겠네요.

**Comment by telk5093** [comment]
@Gamunbi 
![image](https://user-images.githubusercontent.com/10726524/112743940-b48f5e00-8fd6-11eb-86e9-3695c67d8b90.png)
파시 5형의 탄수차 3, 7번의 가로 길이가 다른 것은 의도한 것인가요?


![image](https://user-images.githubusercontent.com/10726524/112744020-472ffd00-8fd7-11eb-9c35-d9ec5d34b762.png)
의도하신 게 아니라면 위 그림과 같이 7번의 맨 좌측 1px을 떼서 3번의 맨 우측 1px에 붙여넣어 가로 길이 21px로 통일하겠습니다.

**Comment by Gamunbi** [comment]
![증기기관차 파시 5형 4차 완성](https://user-images.githubusercontent.com/75788864/112752084-3baaf900-900c-11eb-9dcb-0d7876ed4064.png)

으앗.. 다시 올려드렸습니다~!

**Comment by telk5093** [comment]
반영하였습니다.
