### ISSUE TITLE
[Add] 무궁화호 특실차량

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#113]
![Mugunghwa_Firstclass](https://user-images.githubusercontent.com/81485156/112730189-8cbade80-8f73-11eb-8b17-3364f6f16711.png)

해태특실 구도장
해태특실 신도장
한진특실 

순,

Ref,
https://m.blog.naver.com/7174dl/220955433749
한진
https://m.blog.naver.com/PostView.nhn?blogId=7174dl&logNo=221271130922
http://blog.naver.com/PostView.nhn?blogId=01160ui&logNo=100043081587
해태

**Comment by telk5093** [comment]
#174 로 이관합니다.
