### ISSUE TITLE
[Add] 무궁화호 카페객차

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#114]
![Mugunghwa_C](https://user-images.githubusercontent.com/81485156/112730271-05219f80-8f74-11eb-990d-4bd0ac39dfc5.png)

구형 카페객차
신형(리미트) 카페객차.

*신형은 원래 있었으나 도트가 이상하게 찍혀있어 기존의 것을 수정함.

Ref,

https://ko.m.wikipedia.org/wiki/%ED%8C%8C%EC%9D%BC:Minimini-cafe.JPG
구형 카페

https://m.blog.naver.com/PostView.nhn?blogId=npbs1122&logNo=221198195682
리미트 카페

**Comment by telk5093** [comment]
#117 과 대치되는 상황이라 이 그래픽 스프라이트는 안타깝지만 잠시 보류해야할 것 같습니다.

**Comment by telk5093** [comment]
#180 에서 본 이슈를 승계한 것으로 보고 본 이슈를 닫겠습니다.

**Comment by ChuoSpecialRapid201** [comment]
이거 진작에 닫혔어야 하는데 ;;;;;
