### ISSUE TITLE
[Add] 1호선 신저항

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#115]
![New_1000](https://user-images.githubusercontent.com/81485156/112730336-647faf80-8f74-11eb-9688-7ac292fa9c7b.png)
![New_1000_OC](https://user-images.githubusercontent.com/81485156/112730337-65184600-8f74-11eb-8fd9-7b1bd295aca6.png)

신도색
구도색 순,

**Comment by telk5093** [comment]
중기 저항과 후기 저항(신저항)이 도트 그래픽 상 거의 분간이 불가능하기때문에 굳이 추가할 필요가 없을 수도 있습니다.

**Comment by telk5093** [comment]
![diff](https://user-images.githubusercontent.com/10726524/112745013-01c3fd80-8fe0-11eb-8d5a-e030d0f30c0b.gif)
비교를 위한 움짤

**Comment by telk5093** [comment]
반영되었습니다. 2.0.0에 적용될 것입니다.
