### ISSUE TITLE
7x00 기관차 스프라이트 수정 제안

### ISSUE THREAD

**Issue by kimgas** [KoreanGRF/KoreanTrainSet#116]
현재 기관차의 3,7번 스프라이트가 다른 기관차보다 1칸 작게 잡혀있어 비율상 어색함이 있습니다.

때문에 다른 차량과의 비율 등을 고려해서 아래와 같이 세로 크기를 1칸 키우는 것이 좋다고 봅니다.

![1](https://user-images.githubusercontent.com/79271602/112742818-c966f400-8fcc-11eb-8bb3-c80022b97bd8.jpg)

실제크기: https://t1.daumcdn.net/thumb/R720x0/?fname=http://t1.daumcdn.net/brunch/service/user/3fuW/image/uxnN0bfItY-AfZaAp91m_ywLz2k.JPG

수정제안
![2](https://user-images.githubusercontent.com/79271602/112742858-32e70280-8fcd-11eb-93af-bb8809ebc745.jpg)

실제 추가되어야 할 차량은 더 있지만 현재까지 업로드 된 차량 기반으로 우선 작업해서 올려봅니다.

![7x00r](https://user-images.githubusercontent.com/79271602/112742920-d6381780-8fcd-11eb-81f5-6b5cc582db68.png)
3,7만 수정을 했습니다.

사용하신다면 한 번 더 색상 확인을 하는 것을 추천드립니다.

**Comment by telk5093** [comment]
감사합니다. 적용해보겠습니다.

**Comment by telk5093** [comment]
적용되었습니다.
