### ISSUE TITLE
발전차 크기 수정 제안

### ISSUE THREAD

**Issue by kimgas** [KoreanGRF/KoreanTrainSet#117]
발전차의 제원은 구형은 약 13m, 신형은 약 17m이나 일반 객차 크기와 비슷한 20m급 크기로 제작이 되어있어 비율 조정이 필요하다고 봅니다.

크기비교
![g1](https://user-images.githubusercontent.com/79271602/112743080-1fd53200-8fcf-11eb-8799-6a0b650b12da.png)

제작된 발전차
![generator](https://user-images.githubusercontent.com/79271602/112743086-2e234e00-8fcf-11eb-8bf9-9208bf5efa50.png)

![2](https://user-images.githubusercontent.com/79271602/112743135-9eca6a80-8fcf-11eb-883a-c79b27cc5d39.jpg)
제작 참고용

종류 추가 필요.

**Comment by telk5093** [comment]
G-train, S-train에도 발전차가 있어서 지금 당장 이 그래픽을 적용하는 것이 불가능할 것 같습니다.
 * G-train 발전차 (맨 아랫줄): https://github.com/KoreanGRF/KoreanTrainSet/blob/master/src/wagon/mugunghwa_car/G-train.png
 * S-train 발전차 (위에서 2, 4번째 줄): https://github.com/KoreanGRF/KoreanTrainSet/blob/master/src/wagon/mugunghwa_car/S-train.png

**Comment by kimgas** [comment]
![generator2](https://user-images.githubusercontent.com/79271602/112832695-a7569a00-90d0-11eb-8d5c-e99eebc52bdc.png)

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/112839481-3798dd00-90d9-11eb-9460-58a310c364e4.png)

혹시 이 발전차는 실수로/작업 시간상의 이유로 빠진 건가요?

**Comment by telk5093** [comment]
![generator_car_new](https://user-images.githubusercontent.com/10726524/112840333-27353200-90da-11eb-884a-6b3eb4011ee7.png)

일부 Pure white가 들어있어서 수정하고 두 스프라이트를 합쳐놨습니다.

**Comment by kimgas** [comment]
@telk5093 아직 구현하지 못한 구형 종류가 저걸 포함해서 전망형이나 난방개조 등 많이 남아있습니다

**Comment by kimgas** [comment]
구형 일반형 (120km)
1. 통일호 발전차 (1986)
2. 무궁화 발전차 (1995, 1에서 재도색 추정)
3. 무궁화 발전차 (2005~6?, 2에서 코레일 로고만 추가)

구형 장대형(포함되지 않음)

신형 장대형(150km)
4. 무궁화 발전차 (1995, 색상 차이)
5. 무궁화 발전차 (1995, 색상 차이)
6. 무궁화 발전차 (2005~6?, 파란줄 재도색 추정)
7. 새마을 구도색 발전차 (1990)
8. 새마을 신도색 발전차 (2005~6? 재도색)

년도 차이가 생길 수 있는데 다른 분들의 도움이 필요합니다.

**Comment by telk5093** [comment]
감사합니다. 확인해보겠습니다.

**Comment by telk5093** [comment]
@kimgas A-train 발전차도 작업해주실 수 있을까요? 윗쪽 보라색 차량입니다.
https://github.com/KoreanGRF/KoreanTrainSet/blob/master/src/locomotive/K7x00/A-train_wagon.png

**Comment by telk5093** [comment]
문제가 발생했습니다.
OpenTTD의 길이는 1~8 사이의 정숫값만 지정할 수 있는데 아래와 같이 떨어지거나 겹치는 현상이 발생합니다.

구형 일반에 ``7``, 장대형에 ``8``: (구형 일반이 겹치고 장대형이 떨어짐)
![image](https://user-images.githubusercontent.com/10726524/113602163-3fc6be80-967d-11eb-833b-7a1a4e0eb471.png)

구형 일반에 ``6``, 장대형에 ``7``: (모두 겹침)
![image](https://user-images.githubusercontent.com/10726524/113602331-71d82080-967d-11eb-925f-dbcf73269d27.png)

모든 차량에 길이 ``7``: (모두 겹침)
![image](https://user-images.githubusercontent.com/10726524/113602542-b5cb2580-967d-11eb-985f-ede76a06a71a.png)


코드 상에서 이를 해결할 방법이 없고 이건 그래픽을 조정해야합니다.

**Comment by telk5093** [comment]
길이 ``7`` 기준,
←, →방향: 27px 안쪽으로 조정해야함
↑↗↘↓↙↖방향: 문제 없음. 현재 그래픽 스프라이트를 유지해도 됨
![image](https://user-images.githubusercontent.com/10726524/113603287-badca480-967e-11eb-9c9d-cc90d57332bd.png)

다만 모든 도색을 연결해보니 대각선 방향이 조금 어색해보이는 건 제 착각인가요?

**Comment by kiwitreekor** [comment]
![](http://www.ttdpatch.de/grfspecs/img/TTD%20sizes.png)

**Comment by kimgas** [comment]
![gen](https://user-images.githubusercontent.com/79271602/113659859-eb9ff680-96dd-11eb-9bb7-870886567eb2.png)

위의 기준표에 맞춰서 3, 7을 조정해봤습니다 (구형: 25->24, 장대형 29->28)

1안은 연결부 도트를 삭제, 2안은 차체 길이 조정인데 편한대로 쓰시면 될 것 같습니다.

a트레인은 상황을 보고 따로 올리겠습니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/113751820-46ba0380-9747-11eb-9cbc-2fac82d63539.png)
2안에서 객차 연결부를 제거하여 27px로 변경

결과물:
![image](https://user-images.githubusercontent.com/10726524/113751802-41f54f80-9747-11eb-925f-4606ea57721c.png)

**Comment by ChuoSpecialRapid201** [comment]
구형 발전차 (무궁화호 신도장) 누락.

![Gen_Chosun](https://user-images.githubusercontent.com/81485156/113801176-47788700-9793-11eb-9b76-e1dcdb5aebb3.png)

2012년경까지 굴러다닌걸로 추정.

**Comment by telk5093** [comment]
A-train만 완성되면 발전차 길이 수정은 완료됩니다.

**Comment by kimgas** [comment]
죄송합니다 잘못눌렀습니다;;

**Comment by telk5093** [comment]
괜찮습니다.

**Comment by opentrain** [comment]
![초기 새마을호 발전차 도색](https://user-images.githubusercontent.com/81477455/115144769-704d2600-a089-11eb-9c5c-4a1e57ab04a8.png)
새마을호 발전차 초기도색입니다.

**Comment by telk5093** [comment]
> ![초기 새마을호 발전차 도색](https://user-images.githubusercontent.com/81477455/115144769-704d2600-a089-11eb-9c5c-4a1e57ab04a8.png)
> 새마을호 발전차 초기도색입니다. 위아래 빨간색추가

![image](https://user-images.githubusercontent.com/10726524/115148406-6253d100-a09a-11eb-9b95-b8a4964ff275.png)

1. 길이가 안 맞습니다.
2. 구형 발전차의 새마을호 초기 도색을 말씀하시는 건가요? 레퍼런스 링크와 사진을 부탁드립니다.

**Comment by opentrain** [comment]
https://m.cafe.daum.net/msts/3iYL/1570?q=%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8%20%EC%9E%A5%EB%8C%80%ED%98%95%20%EA%B0%9D%EC%B0%A8(111XX%ED%98%B8%EB%8C%80)+%ED%8A%B9%EC%8B%A4+%EC%8B%9D%EB%8B%B9+%EC%A0%84%EC%9A%A9%EB%B0%9C%EC%A0%84%EC%B0%A8%20%EC%85%8B%ED%8A%B8&
길이가 안맞을면 다시 새로 올리겠습니다.

**Comment by telk5093** [comment]
> https://m.cafe.daum.net/msts/3iYL/1570?q=%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8%20%EC%9E%A5%EB%8C%80%ED%98%95%20%EA%B0%9D%EC%B0%A8(111XX%ED%98%B8%EB%8C%80)+%ED%8A%B9%EC%8B%A4+%EC%8B%9D%EB%8B%B9+%EC%A0%84%EC%9A%A9%EB%B0%9C%EC%A0%84%EC%B0%A8%20%EC%85%8B%ED%8A%B8&
> 길이가 안맞을면 다시 새로 올리겠습니다.
> 구형 아니고 밑에 있는 발전차요

가상의 이미지는 레퍼런스가 아닙니다. 그런 차량이 실존한다는 **증거**를 가져와주세요.

**Comment by opentrain** [comment]
![Uploading 1618791241013.png…]()

**Comment by opentrain** [comment]
![1618791241013](https://user-images.githubusercontent.com/81477455/115166777-d371a380-a0ef-11eb-92c9-423bee85e905.png)
새마을호 초기 발전차 실물사진 입니다.

**Comment by opentrain** [comment]
![통일호 초록발전차도색](https://user-images.githubusercontent.com/81477455/116783766-96cc8180-aacb-11eb-8657-ef69b53c261a.png)
실제로 존재했던 발전차 도색입니다.

https://www.google.co.kr/search?q=%ED%86%B5%EC%9D%BC%ED%98%B8+%EB%B0%9C%EC%A0%84%EC%B0%A8&tbm=isch&ved=2ahUKEwid1NGly6jwAhURNKYKHTPMDK8Q2-cCegQIABAA&oq=%ED%86%B5%EC%9D%BC%ED%98%B8+%EB%B0%9C%EC%A0%84%EC%B0%A8&gs_lcp=CgNpbWcQAzICCAA6BAgAEBhQ-A5YphlgkyJoAHAAeACAAYkBiAGECZIBAzAuOZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=hVeNYN39DJHomAWzmLP4Cg&bih=657&biw=1366&hl=ko#imgrc=fkisQw1jcPOumM

**Comment by telk5093** [comment]
@kimgas A-train 발전차 작업을 부탁드립니다.

**Comment by telk5093** [comment]
> ![초기 새마을호 발전차 도색](https://user-images.githubusercontent.com/81477455/115144769-704d2600-a089-11eb-9c5c-4a1e57ab04a8.png)
> 새마을호 발전차 초기도색입니다. 위아래 빨간색추가



> ![통일호 초록발전차도색](https://user-images.githubusercontent.com/81477455/116784712-b31eed00-aad0-11eb-8119-c898dd61699f.png)
> 실제로 존재했던 통일호 구형발전차 도색입니다.
> 94년도 역삼각도색나올때까지사용한거로 압니다.

이 두 건은 현 시점에서 반영하지 않고 별도 이슈에서 관리하겠습니다.
