### ISSUE TITLE
[Add] 새마을호 특실/식당차 등

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#118]
![Restaurant,First_class](https://user-images.githubusercontent.com/81485156/112743695-7c871b80-8fd4-11eb-934a-b331f224e345.png)

새마을 특실 (구도장)

새마을 식당차 (구도장)

무궁화 식당차 (유선형)

새마을 특실 (신도장) 순서

Ref.

새마을 특실(구도장)/새마을 특실(신도장)
https://m.blog.naver.com/PostView.nhn?blogId=korail5148&logNo=50074957564

무궁화 식당차(유선형)
https://m.blog.naver.com/PostView.nhn?blogId=belamode87&logNo=10144677319

**Comment by telk5093** [comment]
새마을 식당차, 무궁화 식당차는 3fee813 에서 구현됨

**Comment by telk5093** [comment]
@ChuoSpecialRapid201 새마을호 특실이 4방향만 존재하는 게(=도장이 점대칭인 게) 맞나요?

**Comment by telk5093** [comment]
일단 반영되었으므로 닫습니다.
