### ISSUE TITLE
NDC초기도색입니다.

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#119]
한국철도 무궁화호도색하고 신도색 무궁화호 도색만 있는데 초기도색 없는거같아서 올립니다.
퀄리티를 보고말씀해주세요
[![NDC 초기도색](https://user-images.githubusercontent.com/81477455/112746360-2c668400-8fe9-11eb-9842-224d2612af95.png)
](url)

대각선 동력차량 윗쪽부분이 안찍혀있네요
죄송합니다.

이 NDC전개도를 참고했습니다.
https://m.blog.daum.net/ddddddddd-dddddddddd/121

향후 컨테이너 평판차도 구색 찍고있긴한데 시간이 많이 걸린듯합니다.

**Comment by EightonEight** [comment]
another reference: 
1.  ​<https://youtu.be/A3UNHKX2tvU>
2.  <https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:DAEWOO_NDC.jpg>
3.  <https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:979000_420910_0204.jpg>

**Comment by telk5093** [comment]
반영되었습니다.
