### ISSUE TITLE
[Add] Seoul Line 4: 3rd gen. in 2020/07 (48x, a.k.a. Baptong car)

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#12]
4호선 2020년 7월 3차 도입분(48x편성; 일명 밥통 차량)

Reference: https://i.ytimg.com/vi/TtBJVsavGfM/maxresdefault.jpg

**Comment by kiwitreekor** [comment]
![4K_VVVF_2ND](https://user-images.githubusercontent.com/24273113/111904498-9f707780-8a8a-11eb-92c1-c89740a16147.png)
