### ISSUE TITLE
비둘기호 누락된 도색 갈색,녹색버전입니다.

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#120]
![비둘기호 갈색,녹색](https://user-images.githubusercontent.com/81477455/112747207-c54bce00-8fee-11eb-89b3-c199909c0bcf.png) 가문비님한테 허락받고 비둘기호 도색 2종 추가했습니다.

**Comment by Gamunbi** [comment]
저는 '갈색'이라고만 하셔서 3등 객차의 갈색 도색 말하시는 줄 알았는데... 으음..

**Comment by opentrain** [comment]
https://m.blog.daum.net/korailtime/8394781
여기 참고했습니다.

**Comment by Gamunbi** [comment]
https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=110893&search_pos=-112463&s_type=search_subject_memo&s_keyword=%ED%86%B5%EC%9D%BC%ED%98%B8&page=1

녹색은 74년~에 도입된 통일호 객차입니다. 저 도색은 무궁화호에 들어가 있긴 하지만 이미 있습니다. https://github.com/KoreanGRF/KoreanTrainSet/blob/master/src/wagon/mugunghwa_car/MUGUNGHWA_CAR.png

갈색은 불분명합니다. 저건 아마 63년~68년에 통일호로 도입됐다 비둘기호로 격하된 차량인 것 같은데요. 이 도색도 이미 있습니다.

**Comment by Gamunbi** [comment]
카페글에도 말씀드렸다시피, 통일호로 도입됐다 비둘기호로 격하됐다거나 하는 식의 객차는 많은데 제대로 정리된 건 없어서 자료 찾기가 힘들었습니다. 그래서 보수적으로 사진자료가 정확하게 존재(대차부터 지붕까지 다 보이는)하는 것만 작업했습니다. 그리고 저는 철도박물관 도색은 참고하지 않았습니다. 철박은 도색을 조금 부정확하게 했다는 언급을 많이 봐서요..

**Comment by opentrain** [comment]
https://m.search.naver.com/search.naver?where=m_image&sm=mtb_jum&query=%EB%B9%84%EB%91%98%EA%B8%B0%ED%98%B8#imgId=r1_image_sas%3Acafe13267663%7C45%7C10072_1585181334
비둘기호 전용 녹색도색입니다.
갈색도색을 제가 더 찾아보고 말씀드리겠요

**Comment by Gamunbi** [comment]
링크의 녹색차량은 저도 스프라이트 찍으려고 자료 찾을 때 보기는 했습니다만, 과거에 운행할 당시의 사진자료가 없어서 제외했습니다. 비둘기호가 특히나 자료 찾기가 힘들죠..

**Comment by Gamunbi** [comment]
찾아보니 에덴의 동쪽 드라마에 쓰이기 위해 도색한 것이네요. 추가할 필요는 없겠습니다.

**Comment by Gamunbi** [comment]
디시 모노레일 갤러리에 비둘기호 객차를 정리한 글이 올라왔습니다. 정말 죄송합니다만 비둘기호 객차는 제가 한 번 전체적으로 다시 손봐야 할 것 같습니다. 스프라이트 찍느라 정말 고생하셨습니다. 고증 검증에 도움 주셔서 정말 감사합니다.
