### ISSUE TITLE
2000호대 철도청 도색입니다.

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#122]
[![2000호대 철도청도색](https://user-images.githubusercontent.com/81477455/112747977-d945fe80-8ff3-11eb-95f6-f7aed4c5e598.png)](url)

구글에 검색해서 찾아봤습니다.

**Comment by telk5093** [comment]
#90

**Comment by kiwitreekor** [comment]
@opentrain 도트를 찍을 때 한 가지 색상만 쓰는것보다는 여러가지 색을 조금씩 섞어서 질감을 넣어주면 더 퀄리티가 좋아보이게 됩니다.

**Comment by opentrain** [comment]
좋은지적 감사합니다. 안그래도 한가지 색상만 쓰는거 고칠려고 노력중입니다.^^

**Comment by telk5093** [comment]
이슈를 하나로 묶겠습니다. 이 이후로는 #90 에서 이어서 이야기하겠습니다.
