### ISSUE TITLE
[Add] 무궁화호 침대차

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#123]
![Mugunghwa_SleepingCar](https://user-images.githubusercontent.com/81485156/112753662-811ef480-9013-11eb-8b6b-c7e72497c737.png)

Ref.

신도장
http://mlbpark.donga.com/mlbpark/b.php?&b=bullpen&id=1891510

구도장
https://m.blog.naver.com/PostView.nhn?blogId=superheavy&logNo=100165724844

**Comment by telk5093** [comment]
* 정원: 28명 ([출처](https://news.joins.com/article/23170433))
 * 도입연도: 1966년 ([출처](https://gall.dcinside.com/mgallery/board/view?id=monorail&no=4308))

기타 구현되지 않은 구 도색 참고 자료: https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=35888

**Comment by telk5093** [comment]
@ChuoSpecialRapid201 https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=35888 에 있는 사진에 의하면 천장에 냉방기(혹은 환풍기)가 6개 있는 것 같습니다. 그래픽 수정이 필요합니다.

**Comment by telk5093** [comment]
92a6578 에서 반영되었습니다만, 천장 냉방기(환풍기) 그래픽 수정이 필요할 것 같습니다.

**Comment by ChuoSpecialRapid201** [comment]
> [92a6578](https://github.com/KoreanGRF/KoreanTrainSet/commit/92a6578cf0a8344d93f123854b581a718f4bf3f9) 에서 반영되었습니다만, 천장 냉방기(환풍기) 그래픽 수정이 필요할 것 같습니다.

저건 탕앵제 구형 침대객차임.
2001년 신조된 신조(리미트)기반 침대차는 에어컨 안달려있음..

![Uploading 1280px-Korail_Mugunghwa-ho_Sleeping_Car.jpg…]()

**Comment by telk5093** [comment]
@ChuoSpecialRapid201 확인 감사합니다. 그럼 이슈를 닫겠습니다.
