### ISSUE TITLE
[Add] 무궁화호 유선형 특실

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#124]
![Mugunghwa_Firstclass_S](https://user-images.githubusercontent.com/81485156/112755284-f215da80-901a-11eb-9eb7-baa20804ac9e.png)

Ref.
https://m.blog.naver.com/PostView.nhn?blogId=npbs1122&logNo=221412520959

**Comment by telk5093** [comment]
#174 로 이관합니다.
