### ISSUE TITLE
우편차

### ISSUE THREAD

**Issue by kimgas** [KoreanGRF/KoreanTrainSet#126]
누락이 있을 수 있습니다.

![post](https://user-images.githubusercontent.com/79271602/112756058-51c1b500-901e-11eb-82ed-4b7cd19bf6a7.png)

![Untitled-1](https://user-images.githubusercontent.com/79271602/112756061-57b79600-901e-11eb-97be-e54ad7623ea5.jpg)

**Comment by opentrain** [comment]
ㅎㄷㄷ 안그래도 제가 찍었던 소화물차보다 낫네요
고퀄이십니다. ㄷㄷ

**Comment by telk5093** [comment]
It requires splitting a Mail car(``MAIL_CAR``) from the Baggage car

**Comment by opentrain** [comment]
혹시 기존에 찍었던 소화물차 대신해서 저 소화물차로 도색개조 해도될까요?

**Comment by kimgas** [comment]
@opentrain 제 승인은 없어도 됩니다

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/112960447-62d60780-917f-11eb-9126-474f2c9dea8f.png)
From #135

**Comment by telk5093** [comment]
![MAIL_CAR](https://user-images.githubusercontent.com/10726524/112960553-7e411280-917f-11eb-9595-2024c54ccda9.png)

현재 수정된 그래픽 스프라이트

**Comment by telk5093** [comment]
우편차로 분리하여 반영되었으나 '소화물'로 분류하신 것은
우편차로 넣을지 수화물차로 넣을지 제 쪽에서 분간이 안 가서 일단 그래픽만 https://github.com/KoreanGRF/KoreanTrainSet/blob/c168b18f6914922ed0a7c479a4a1d90b7e45ad32/src/wagon/baggage_car/BAGGAGE_CAR.png 에 넣어놓고 실제 반영은 안 되었습니다.

**Comment by kimgas** [comment]
@telk5093 
가장 아래 있는 우편 차량은 독립 제작된 우편차가 아니라 소화물(小貨物이 맞다고 합니다) 차를 개조하여 만들어졌기에 같이 제작을 한 것입니다.

다만 게임에서까지 그 고증을 따라서 소화물 개조로 구현될 필요는 없다고 생각합니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/112973799-a7b46b00-918c-11eb-9ecb-c89d234d05cb.png)
제가 말씀드린 '반영되지 않은 스프라이트'는 요놈 얘기입니다.
이놈이 '소화물차를 개조한 우편차'인지 확실치 않아서 말씀드린 겁니다.

![image](https://user-images.githubusercontent.com/10726524/112973872-be5ac200-918c-11eb-83fb-0a6483ceb489.png)
이놈은 수화물차가 아니라 우편 차로 개조되도록 만들었습니다.

참고로 [위키백과 '수화물차'](https://ko.wikipedia.org/wiki/%EC%88%98%ED%99%94%EB%AC%BC%EC%B0%A8)의 "수화물차가 소화물을 싣고 다니기도 했다"는 설명을 따라 한국 열차 세트의 소화물차는 수화물차로 명명하고 있습니다.

**Comment by kimgas** [comment]
아 이해를 잘못 했네요.

저건 그냥 소화물 차량입니다.

우편차를 만들다보니 기본이 같아서 만들어본겁니다.

![image](https://user-images.githubusercontent.com/79271602/112981799-a25c1e00-9196-11eb-8876-8ef0ae847e14.png)


명칭에 대해서는 의견을 따르겠습니다.

**Comment by telk5093** [comment]
>![image](https://user-images.githubusercontent.com/10726524/112973799-a7b46b00-918c-11eb-9ecb-c89d234d05cb.png)
>제가 말씀드린 '반영되지 않은 스프라이트'는 요놈 얘기입니다.
>이놈이 '소화물차를 개조한 우편차'인지 확실치 않아서 말씀드린 겁니다.

소화물차에 추가
