### ISSUE TITLE
G-train 명암 오류

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#127]
![image](https://user-images.githubusercontent.com/10726524/112757061-f514c900-9022-11eb-9046-5b828e7b8eb7.png)

명암이 잘못됨. 아마도 2번 스프라이트를 단순 좌우대칭한 것으로 보임

**Comment by opentrain** [comment]
아 죄송합니다. 불편을 드렸네요 급한건가요?
제가 새로 다시 리메이크해서 올리겠습니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/112758684-8e93a900-902a-11eb-9608-a3441c4490de.png)

자체 수정 완료
