### ISSUE TITLE
비둘기호 객차 (수정)

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#128]
https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=133498&s_type=search_subject_memo&s_keyword=%EB%B9%84%EB%91%98%EA%B8%B0&page=1

https://gall.dcinside.com/mgallery/board/view?id=monorail&no=130342
레퍼런스 

곧 작업할 예정이며, 완성하면 텔크님께 알려드리겠습니다.

**Comment by Gamunbi** [comment]
![객차 비둘기호 5차 완성](https://user-images.githubusercontent.com/75788864/112875161-c9671100-90fe-11eb-976b-c5dcea8be482.png)

**Comment by Gamunbi** [comment]
3등 객차를 제외하고 모두 조금씩 수정이 되었습니다. 

개조 목록 이렇게 부탁합니다.

'3등객차'
'붉은 도색'
'기본 도색'
'후기 도색'

저 네 개의 객차는 저번처럼 똑같이 랜덤으로 등장했으면 좋겠습니다. 등장 비율은 동등하게 하면 될 것 같습니다.

**Comment by Gamunbi** [comment]
저 고정의자니 장의자니는 객차들을 구분하기 위해서 적은 것입니다. 개조 목록이 너무 복잡해 보일 것 같아 저 이름들로 부탁드렸습니다~

**Comment by Gamunbi** [comment]
아 3등 객차도 수정되었습니다. 빼먹어서 다시 올렸습니다.

**Comment by telk5093** [comment]
반영되었습니다.
