### ISSUE TITLE
381k 2세대 preview 오류

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#129]
싱글암이 아닌 더블암 팬터그래프로 되어 있음

**Comment by kiwitreekor** [comment]
팬터그래프가 아예 사라졌는데 의도하신 부분인가요?

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/112839603-5ac38c80-90d9-11eb-9c86-4353463c97b8.png)

싱글암이 뒤쪽에 있어서 빨간색 정도만 잘라서 쓰는지라 구매 이미지 상에서는 나타나지 않는게 맞습니다.
