### ISSUE TITLE
새마을호 빨간색없는 객차+노란줄반영 객차버전입니다.

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#130]
![유선형 새마을호 빨간색없는버전](https://user-images.githubusercontent.com/81477455/112797244-166ac900-90a6-11eb-96f0-a90a5ab89daa.png)

![유선형 새마을호 노란색버전](https://user-images.githubusercontent.com/81477455/112801023-5ed8b580-90ab-11eb-8124-6eb07b491b18.png) 
새마을호 객차 빨간색없는 버전하고 초기 노란색 버전 도색을 만들어봤습니다.

**Comment by telk5093** [comment]
참고용 링크: https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=22383

**Comment by telk5093** [comment]
#190 으로 이전합니다.
