### ISSUE TITLE
무궁화호 1960~1970년 우등도색입니다.

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#131]
[![무궁화호 우등(갈색)도색](https://user-images.githubusercontent.com/81477455/112947841-4384ad80-9172-11eb-8cc3-f9fca8794333.png)
](url)
한열세에 있는 무궁화호 모든도색이 끝난줄알았는데
정보를 통해 다른도색도 있다는거 알았습니다.
무궁화호 1960~1970년 우등도색 갈색 버전입니다.

**Comment by Gamunbi** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/blob/master/src/wagon/mugunghwa_car/MUGUNGHWA_CAR.png

첫번째는 이미 있습니다.

**Comment by opentrain** [comment]
아 그게 그도색이였냐보네요
감사합니다. 갈색버전만 넣어야겠네요 ㅎㅎ

**Comment by opentrain** [comment]
@Gamunbi 아 그게 그도색인가보네요
제보 감사합니다. 수정만해서 갈색버전만 올리겠습니다.
