### ISSUE TITLE
CDC에 동력차 편성 불가능 하네요

### ISSUE THREAD

**Issue by NuclearBread** [KoreanGRF/KoreanTrainSet#132]
CDC 차량에 승객 수송 차량 (동력차) 가 편성되지 않습니다
의도하신 부분인지는 모르겠으나, 다른 차량은 정상적으로 편성되는 점으로 보아 버그인 것 같습니다

**Comment by telk5093** [comment]
CDC 차에는 동력차가 붙지 않는 현상은 의도된 현상입니다.

**Comment by telk5093** [comment]
다시 알아본 결과 CDC 편성이 ``Mc + M + M + Mc``인 것을 확인했습니다.
동력차도 붙일 수 있도록 변경하겠습니다.
