### ISSUE TITLE
통일호 객차

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#134]
![객차 통일호 1차 완성](https://user-images.githubusercontent.com/75788864/112953333-5dc18a00-9178-11eb-8460-ec0893c95ca4.png)

레퍼런스
https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=123790&search_pos=-122977&s_type=search_subject_memo&s_keyword=%ED%86%B5%EC%9D%BC%ED%98%B8&page=1, 객차번호표편, 1~8편 전부

마지막 노랑초록 도색은 제가 만든게 아니고 기존에 있던 것입니다.

'붉은 도색'
'초록 도색 (초기)'
'초록 도색 (비냉방)'
'초록 도색 (냉방)'
'노랑·남색 도색'
'노랑·초록 도색'

비냉방 도색 2개는 비둘기 때와 마찬가지로 무작위 등장 부탁드립니다~

**Comment by opentrain** [comment]
통일호 준비하고있었는데 뜻밖이네요 ㅎㅎ 찍을필요가 없겠네요

**Comment by telk5093** [comment]
반영되었습니다.
