### ISSUE TITLE
[Add] 새마을 카페차/식당차(신도색)

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#136]
![NewVillage_Cafeteria](https://user-images.githubusercontent.com/81485156/112972936-c2d2ab00-918b-11eb-912b-d9e461568aff.png)

Ref,

https://blog.daum.net/algoseo/8706067
카페

https://blog.naver.com/co0977/10106276209
식당차 (신도색)

**Comment by telk5093** [comment]
6945b33 에서 식당차를 반영하였습니다.

**Comment by telk5093** [comment]
식당차는 반영하지 않기로 결정
