### ISSUE TITLE
4x00호대의 높이가 다름

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#137]
NE(↗쪽) 방향:
![image](https://user-images.githubusercontent.com/10726524/112984682-2bc11f80-919a-11eb-88a6-c57a5c928e52.png)

SE(↘쪽) 방향:
![image](https://user-images.githubusercontent.com/10726524/112984704-3085d380-919a-11eb-856c-543dbdbb90d9.png)

보다시피 기관차의 뒷부분 높이가 NE방향은 객차 높이를 넘어서보이는데 SE 방향은 낮아보임. (SE쪽이 맞는 높이)

**Comment by opentrain** [comment]
V 트레인 제가 찍지 않았는데 새로 찍든가 하겠습니다.

**Comment by kimgas** [comment]
![4400](https://user-images.githubusercontent.com/79271602/114568107-d06d5200-9cae-11eb-9c65-f75d9a47e25e.png)

새로 제작해봤습니다.
괜찮으면 다른 것도 만들겠습니다.

**Comment by telk5093** [comment]
@kimgas 그럼 부탁드리겠습니다 :)
아래 도색이 현재 4x00호대 전부입니다.
![image](https://user-images.githubusercontent.com/10726524/114574917-a323a280-9cb4-11eb-8733-7d336c8c03d6.png)

**Comment by kimgas** [comment]
![K4x00](https://user-images.githubusercontent.com/79271602/115036173-3accff00-9f08-11eb-84e5-56a6df5abb43.png)

맨 아래는 무도색차량입니다.
