### ISSUE TITLE
유개화차

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#138]

**Comment by opentrain** [comment]
>

**Comment by telk5093** [comment]
유개화차 그래픽은 필요하기 때문에 이슈는 열어두겠습니다

**Comment by opentrain** [comment]
@telk5093 유개차 제가아는선에서 3가지종류 올려서 반영하겠습니다.

**Comment by opentrain** [comment]
@telk5093  ![유개차](https://user-images.githubusercontent.com/81477455/114260623-14dbc200-9a11-11eb-92b9-09f9454f4ad4.png)
오늘 완성했는데 혹시 수정할부분있거라 그러시면 말씀해주세요
아그리고 혹시 곡물차같은경우 텔크님의 결정에 따라 추가하든가 하겠습니다.
1.구형(검정,하늘,초록,파란)
2.일반형(검정,하늘,초록,파란)
3.전개형(검정,하늘,초록,파란)
총 12가지 유개차를 찍어봤습니다.

**Comment by telk5093** [comment]
> #138 대체해서 이글로 올리겠습니다.
> ![image](https://user-images.githubusercontent.com/10726524/115994091-8cfcd700-a610-11eb-9d06-855a8ac19829.png)
> 유개화차
> 저번에 찍었던 유개화차를 개조해서 찍었는데 이상하게 되는바람에 제가 직접 찍었어 작업했습니다.
> 이번에 찍게되면서 다양한시도를 해봤습니다.
> 그리고 4방향으로 되어있는거 곡물차이긴한데 여기밑에 있는 화차 설명관련영상으로 대체하겠습니다.
> 유개화차전용 가축차도 있다고하는데 이거 정보가 없어서 안넣었습니다.
> 
> 화차 설명관련영상
> https://www.youtube.com/watch?v=pe3qRgGusHs
> 
> 구형,일반형,전개형 유개화차링크
> https://www.youtube.com/watch?v=pe3qRgGusHs

**Comment by telk5093** [comment]
그래픽 작업에 수고하신 것은 잘 알고 있으나, 솔직히 명암이 너무 단순해서 이대로 반영하기는 곤란합니다.
더 나은 그래픽이 준비되기를 기다렸다가, 결국 더 나은 그래픽이 나오지 않았을 때에 위 그래픽을 사용하겠습니다.

**Comment by telk5093** [comment]
> 아 어디부분 말씀하세요? 지붕쪽 말씀하세요?
> 아니면 문쪽 말씀하세요? 수정해놓고 올리겠습니다.

그냥 전체적으로 디테일한 명암이 아예 없습니다.

**Comment by opentrain** [comment]
일단 유개화차같은경우 저거 말고도 이전에 존재했던 유개화차도 여기에 올려놓겠습니다.

**Comment by EightonEight** [comment]
![BOX_CAR](https://user-images.githubusercontent.com/77984422/130804282-4cf5a72a-b7be-4803-8387-ea32b2c0edc4.png)
`BOX_CAR`
* 현재 운행하고 있는 유개화차만 작업하였습니다.
* 위에서부터 전개형 유개차(신형), 전개형 유개차, 유개차입니다.
* 해당 화차의 계산(화차 길이)은 1.1(전개형 유개차), 1.0(유개차)으로 스프라이트를 이에 맞게 제작하였습니다.
* 전개형 유개차와 유개차가 서로 높이가 다른 것을 스프라이트에 반영하였습니다.

**Vehicle specification**
| Name                             | Code                | Speed             | Speed (designed) | Capacity | Power         | Weight | Introduction |
|---------------------------|-----------------|-----------------|---------------------|----------|--------------|---------|---------------|
| Full Door Box car (new) | ``BOX_CAR``     |  **120 km/h** | **120 km/h**         | ?            |                    | **25t** | **2003**      |
| Full Door Box car           | 〃                     | **100 km/h** | **100 km/h**         | ?            |                    | **28t** | **1998**      |
| Boxcar                            | 〃                     | **90 km/h**   | **90 km/h**           | ?            |                    | **26t** | **1996**      |

제원 중 속력과 중량에 차이가 있으나, 게임적 허용으로 평균값을 적용해도 될 것 같습니다.

**References**
* 전개형 유개차(신형)
 <https://librewiki.net/wiki/%ED%8C%8C%EC%9D%BC:Korail-Car-20844.jpg>
 <https://cafe.daum.net/carg/9Y8/3212>
* 전개형 유개차
 <https://images.app.goo.gl/RGaJiQ6bi5G7skHB8>
 <https://youtu.be/SI1M4-8ZQi0?t=40>
* 유개차
 <https://librewiki.net/wiki/%ED%8C%8C%EC%9D%BC:Korail-Car-20416.jpg>
 <https://images.app.goo.gl/GwbZ3AgWyhNghudr7>
 <https://youtu.be/f0d-RikAnpk?t=25>
* 제원
<https://blog.naver.com/trainholic/90162339813> 
한국철도공사 물류본부 물류수송차량팀, 「화차제원」, 2010.10

**Comment by opentrain** [comment]
옛날 유개화차 검정도색모음

![유개화차 옛날검정도색](https://user-images.githubusercontent.com/81477455/131476836-4f8dff8f-6001-43df-a7b8-49faad88dc4d.png)

1.1934~1940년 유개차
![image](https://user-images.githubusercontent.com/81477455/131477108-58ba1d5c-4baa-43eb-8430-0223da59e326.png)

2.1941년 유개차
![image](https://user-images.githubusercontent.com/81477455/131477216-ea6badd9-5249-4e24-b9cd-70a965db68ef.png)

3.1954년 유개차
![image](https://user-images.githubusercontent.com/81477455/131477481-e2a74819-6f8d-402a-92c1-1faa7357177f.png)

4.1907년 유개차
![image](https://user-images.githubusercontent.com/81477455/131477672-77fd456c-e839-4d69-bf15-ebb0940dc00d.png)

**Comment by Gamunbi** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/issues/284#issue-1007103982

1941년 유개화차입니다. 여기 유개화차 이슈가 진행되고 있는 걸 이제 봤네요;

**Comment by Gamunbi** [comment]
> 
> 
> ![BOX_CAR](https://user-images.githubusercontent.com/77984422/130841726-50c29b4d-8857-42f5-be20-b57407c5eb0a.png) `BOX_CAR`
> 
>     * 확인가능한 종류와 도색만 작업하였습니다.
> 
>     * 위에서부터 전개형 유개차(신형), 전개형 유개차, 유개차, 유개차(구형)입니다.
> 
>     * 해당 화차의 계산(화차 길이)은 1.1(전개형 유개차), 1.0(유개차)으로 스프라이트를 이에 맞게 제작하였습니다.
> 
>     * 전개형 유개차와 유개차가 서로 높이가 다른 것을 스프라이트에 반영하였습니다.
> 
> 
> **Vehicle specification**
> Name 	Code 	Speed 	Speed (designed) 	Capacity 	Power 	Weight 	Introduction
> Full Door Box car (new) 	`BOX_CAR` 	**120 km/h** 	**120 km/h** 	? 		**25t** 	**2003**
> Full Door Box car 	〃 	**100 km/h** 	**100 km/h** 	? 		**28t** 	**1998**
> Boxcar 	〃 	**90 km/h** 	**90 km/h** 	? 		**26t** 	**1996**
> Boxcar (old) 	〃 	90 km/h 	90 km/h 	? 		**22t** 	**1966**
> 
> 제원 중 속력과 중량에 차이가 있으나, 게임적 허용으로 평균값을 적용해도 될 것 같습니다.
> 
> **References**
> 
>     * 전개형 유개차(신형)
>       https://librewiki.net/wiki/%ED%8C%8C%EC%9D%BC:Korail-Car-20844.jpg
>       https://cafe.daum.net/carg/9Y8/3212
> 
>     * 전개형 유개차
>       https://images.app.goo.gl/RGaJiQ6bi5G7skHB8
>       https://youtu.be/SI1M4-8ZQi0?t=40
>       http://photozou.jp/photo/show/50802/22084086
> 
>     * 유개차
>       https://librewiki.net/wiki/%ED%8C%8C%EC%9D%BC:Korail-Car-20416.jpg
>       https://images.app.goo.gl/GwbZ3AgWyhNghudr7
>       https://youtu.be/f0d-RikAnpk?t=25
>       https://blog.naver.com/lovtrout/221014094488
> 
>     * 유개차(구형)
>       https://youtu.be/pe3qRgGusHs?t=70
>       https://www.flickr.com/photos/japanrail/albums/72157627094515336
> 
>     * 제원
>       https://blog.naver.com/trainholic/90162339813
>       한국철도공사 물류본부 물류수송차량팀, 「화차제원」, 2010.10
>       (사)철도차량기술검정단, 「한국철도차량 100년사」, 1999, 1035p

링크 사진을 보니 수송량이 48톤~51톤(화차 겉면에 적힌 하중) 정도로 보입니다. 50톤으로 하면 될 것 같습니다.

**Comment by opentrain** [comment]
![유개화차 화물적재칸](https://user-images.githubusercontent.com/81477455/137464332-a88f7361-1834-4f82-b45b-55d304ebac8b.png)
처음으로 해본 화물수송량 표시 % 입니다.
이게 맞는지 안맞는지 모르겠지만 찍어봤습니다.

**Comment by EightonEight** [comment]
### 60년대~현재 유개화차 최종(안) ###

![BOX_CAR_2003](https://user-images.githubusercontent.com/77984422/140779446-877bcf01-bff8-488f-a825-dd28196e55ab.png)
`BOX_CAR_2003`

---
![BOX_CAR_1998](https://user-images.githubusercontent.com/77984422/140779709-4d1b7a67-f492-4126-85f8-62383d0cb52d.png)
`BOX_CAR_1998`
* 측문 부분 수정
* 화물 상하차 스프라이트 개선

---
![BOX_CAR_1996](https://user-images.githubusercontent.com/77984422/140780588-18480666-e041-40b1-9eb0-dbc51b27963d.png)
`BOX_CAR_1996`
* 화물 상하차 스프라이트 개선

---
![BOX_CAR_1972](https://user-images.githubusercontent.com/77984422/140780871-b806a767-9772-4be0-8986-c78618c9b462.png)
`BOX_CAR_1972`
* 측문 부분 수정(ref: (사)철도차량기술검정단, 「한국철도차량 100년사」, 1999, 1039p)
* 화물 상하차 스프라이트 개선

---
![BOX_CAR_1966](https://user-images.githubusercontent.com/77984422/140780974-84ed5f84-357b-40cd-980f-fa8c60a58f47.png)
`BOX_CAR_1966`
* 화물 상하차 스프라이트 개선

---
**Vehicle specification (final)**
| Name                             | Code                | Speed             | Speed (designed) | Capacity | Power         | Weight | Introduction |
|---------------------------|-----------------|-----------------|---------------------|----------|--------------|---------|---------------|
| Full Door Box car (2003) | ``BOX_CAR_2003`` | **120 km/h** | **120 km/h**   | ?            |                    | **25t** | **2003**      |
| Full Door Box car (1998) | ``BOX_CAR_1998`` | **100 km/h** | **100 km/h**   | ?            |                    | **28t** | **1998**      |
| Boxcar (1996)                 | ``BOX_CAR_1996`` | **90 km/h**   | **90 km/h**      | ?            |                    | **26t** | **1996**      |
| Boxcar (1972)                 | ``BOX_CAR_1972`` | 90 km/h         | 90 km/h            | ?            |                    | **22t** | **1972**      |
| Boxcar (1966)                 | ``BOX_CAR_1966`` | 90 km/h         | 90 km/h            | ?            |                    | **22t** | **1966**      |

---
60년대 이전 유개화차는 포함하지 않았습니다.
> 2021.8.30.월 소화물 급행전용 유개화차(주황색)
> ![유개화차(소화물 급행)](https://user-images.githubusercontent.com/81477455/131324320-32cf60bf-d048-4a98-ac30-55d51f58676f.png)
> 화물적재칸
> ![유개화차(소화물 급행) 화물적재칸](https://user-images.githubusercontent.com/81477455/137471469-fe6c57db-d3f1-4ba4-9cfb-9b529ae0ac4a.png)

급행 소화물차는 유개화차보단 소화물차에 포함하는 것이 좀 더 어울릴 것 같습니다.
화물 상하차 스프라이트는 위 [comment](https://github.com/KoreanGRF/KoreanTrainSet/issues/138#issuecomment-933001187)를 참고하였습니다.
