### ISSUE TITLE
Check DEC(Diesel Electric Car)'s spec

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#14]
Reference: https://namu.wiki/w/DEC%20%EB%94%94%EC%A0%A4%EB%8F%99%EC%B0%A8

**Comment by kiwitreekor** [comment]
![DEC](https://user-images.githubusercontent.com/24273113/112015097-d9b34500-8b6e-11eb-8cd8-fc4c66a31ee7.png)

워낙 오래된 차량이다보니 자료가 별로 없어서 고증에 맞지 않는 부분이 있을 수 있습니다.

**Comment by telk5093** [comment]
@kiwitreekor 공장장이세요?ㄷㄷ

**Comment by kiwitreekor** [comment]
요즘 좀 바빠서 아마 오늘 이후로는 다시 찍기 힘들 것 같습니다.. ㅋㅋ

**Comment by kiwitreekor** [comment]
3번째 도색 객차 2번째 스프라이트에 창문이 하나 빠졌네요... 반영 시 수정해주시면 감사하겠습니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/112019742-12551d80-8b73-11eb-92bb-1256802d7557.png)
이 부분 말씀이시죠? 알겠습니다.

**Comment by telk5093** [comment]
It is implemented at 59f249 but we need to check its
 * Capacity
 * Power
 * Livery names

**Comment by kiwitreekor** [comment]
https://blog.naver.com/PostView.nhn?blogId=changdong412&logNo=100156665624

참고자료

**Comment by telk5093** [comment]
* Power: 주 엔진 출력 970hp + 보조 엔진 출력 112hp = 1082hp(≒807 kW)로 반영
 * Capacity: 엔진 28명, 객차 56명으로 반영
