### ISSUE TITLE
누리로의 팬터그래프 방향이 잘못됨

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#140]
![image](https://user-images.githubusercontent.com/10726524/112999710-28ce2b00-91aa-11eb-9014-6dcff3492485.png)

 * 동쪽(3번, →방향), 서쪽(7번, ←방향)의 팬터그래프 방향은 교정해두었음.

 * 참고 영상 1: https://www.youtube.com/watch?v=SpTlV-Jz5GA
 * 참고 영상 2: https://www.youtube.com/watch?v=TzSf5dXsjWY

**Comment by kimgas** [comment]
![nuriro](https://user-images.githubusercontent.com/79271602/115124465-536b1100-9ffd-11eb-82c5-6c72394ce69f.png)

1. 팬터그래프 수정 (5번 방향 높이 조정, +2)
2. 운전석 수정
3. 에어컨 수정
4. 동해산타 추가
 - 홀수는 편성이 홀수일때 적용 할 수 있도록 만든 것입니다. (실제로는 없음)
 - 싱글 팬터는 새로 적용한 것을 다음에도 사용 가능하도록 별도로 빼서 놓은 것입니다.

**Comment by telk5093** [comment]
@kimgas 동해산타열차의 기존 그래픽에 비해 다소 붉은 색이 바랜 느낌인데, 의도하신 건가요?
제가 보기에는 기존에 이미 있는 걸 깜빡하시고 아예 처음부터 새로 찍으신 느낌이 강하긴 한데 혹시 맞나요?
![image](https://user-images.githubusercontent.com/10726524/115135168-3bbd7800-a051-11eb-9ebe-ddbefdad91a8.png)

**Comment by kimgas** [comment]
@telk5093 
없는줄 알았는데 이미 있었군요;;;
색상은 영상 보면서 새로 만들었습니다. 어떻게 처리할까요?

**Comment by telk5093** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/blob/master/src/locomotive/nuriro/NURIRO_SANTA.png
여기에 있는 기존 그래픽을 보면 제공해주신 그래픽 스프라이트가 조금 모자랍니다.
색감은 기존 게 더 맞는 것 같습니다. #106 을 참고해주세요.

**Comment by kimgas** [comment]
@telk5093 
![santa](https://user-images.githubusercontent.com/79271602/115136673-46c9d580-a05c-11eb-9f05-16b629de0e52.png)

색상을 기존 것과 유사하게 조정 해봤습니다

**Comment by telk5093** [comment]
죄송합니다, 동해산타열차의 실물 사진을 다시 살펴보니 새로 찍어주신 색감이 더 맞는 것 같습니다.
의견을 번복해서 죄송합니다.

![image](https://user-images.githubusercontent.com/10726524/116190824-4620f580-a766-11eb-919d-900f62742a20.png)
또한, 이 틀에 맞춰서 제작해주시면 감사하겠습니다.
(맨 위부터 ``전두부, 팬터그래프, 팬터그래프 반전, 기본 객차, 기본 객차 반전, 후두부, 후두부 반전``입니다)

**Comment by kimgas** [comment]
![santa](https://user-images.githubusercontent.com/79271602/116244614-0c221480-a7a3-11eb-9816-7bdb84fb12ac.png)

변수가 될 부분은 다 추가를 해봤습니다

**Comment by telk5093** [comment]
반영되었습니다.
