### ISSUE TITLE
[Add]무궁화호 신조객차(리미트) 식당차

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#141]
![Mugunghwa_Snackcar_NEW](https://user-images.githubusercontent.com/81485156/113002638-f4a83980-91ac-11eb-845f-2162c9e34f2f.png)

Ref,
https://blog.naver.com/eros2735/50004372520

https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=656

**Comment by telk5093** [comment]
반영되었습니다.
