### ISSUE TITLE
통일호 객차 수정

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#146]
![객차 통일호 1차 완성 긴급](https://user-images.githubusercontent.com/75788864/113102166-9f196e80-9238-11eb-8235-2e00e2eb9462.png)

비냉방 객차 두개의 지붕이 서로 매치가 안 되어 수정해서 올립니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/113102933-9c6b4900-9239-11eb-820a-ca342f8fe7eb.png)

그 밑(4, 5, 6번째 줄) 차량도 북동방향(↗) 지붕의 명암이 이상한 것 같아 수정했는데, 확인 바랍니다.
일단 이걸로 반영하겠습니다.

**Comment by Gamunbi** [comment]
4, 5, 6번째 차량은 (다른 분이 만들었던) 7번째 차량을 참고해서 만든거라, 제가 임의로 수정하기가 조금 그랬습니다.
