### ISSUE TITLE
비둘기호 니가타 동차 도색모음

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#148]
![니가타 동차 도색](https://user-images.githubusercontent.com/81477455/113112493-2e784f00-9244-11eb-9c75-723230450f41.png)
@Gamunbi 이분의 니가타 동차를 활용해서 도색을 넣어봤습니다.

도색순서
1.비둘기호 철도청 연한녹색버전(1996년도색) 비둘기호객차하고 같은색상
2.철도청 진한 녹색버전(1996년 도색) 
https://blog.naver.com/bluenix37/220168994709

3.통일호 승격 초록도색(1985년)
http://mlbpark.donga.com/mp/b.php?p=1&b=bullpen&id=202103170052677117&select=&query=&user=&site=&reply=&source=&pos=&sig=hgjLGY-YjhjRKfX2h6j9Gf-g5mlq

4.무궁화 승격 빨간도색(1990년초)
https://blog.naver.com/daniel4409/221915825426

https://ko.wikipedia.org/wiki/%ED%86%B5%EA%B7%BC%ED%98%95_%EB%94%94%EC%A0%A4_%EC%95%A1%EC%95%95_%EB%8F%99%EC%B0%A8

이번주안에를 컨테이너 평판화차 도색 완성될듯 싶네요

**Comment by telk5093** [comment]
6f3b500 에서 반영되었습니다.
