### ISSUE TITLE
협궤 객차, 동차, 증기기관차 

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#149]
![협궤 객차, 동차, 증기기관차 1차 완성](https://user-images.githubusercontent.com/75788864/113144101-dbb08e80-9267-11eb-9024-eb77420e1f64.png)

기관차 https://namu.wiki/w/%ED%98%80%EA%B8%B0%ED%98%95%20%EC%A6%9D%EA%B8%B0%EA%B8%B0%EA%B4%80%EC%B0%A8#s-2.7
혀기 7형 증기기관차
도입년도:1952년
최고 속도:50km/h 추정
마력:불명

기관차와 탄수차 추천 총길이:8 (기관차, 탄수차 각각 6, 2 혹은 5, 3 추천)

객차 
https://ko.wikipedia.org/wiki/%ED%98%91%EA%B6%A4_%EA%B0%9D%EC%B0%A8 
https://www.kyeonggi.com/news/articleView.html?idxno=2327285
제가 찍었던 객차들이 여태 그래왔듯이 역시 두개가 랜덤 등장으로 부탁드립니다.
추천 길이:6

동차
https://ko.wikipedia.org/wiki/%ED%98%91%EA%B6%A4_%EB%94%94%EC%A0%A4_%EC%95%A1%EC%95%95_%EB%8F%99%EC%B0%A8
협궤 디젤 액압 동차
도입년도:1965년

일단 완성해서 올려둡니다. 아마 언젠가는 협궤 철도도 구현되겠죠....

**Comment by Gamunbi** [comment]
![협궤 철도 2](https://user-images.githubusercontent.com/75788864/113170886-ef68ee80-9281-11eb-9683-a0cf79af79ab.png)

일단 일본 철도 세트에서 추가되는 협궤 선로에는 잘 맞는 걸 확인했습니다(그림판에서 합성).

일단 처음 제 계획엔 이처럼 다른 grf의 선로를 그대로 갖다 쓰는 걸 염두해서 제작했는데, 생각해보니 비록 이걸로 수익을 낸다거나 하지는 않지만 그래도 다른 사람이 애써 만든 걸 그냥 그대로 가져다 쓰면 좀 그렇지 않을까 합니다. 

그대로 쓸까요, 아니면 참고해서 새로 만들까요? 아님 아예 허락을 받아볼까요?

**Comment by telk5093** [comment]
다른 선로에서 굴러갈 수 있게 만드는 건 한국 열차 세트 내에서만으로도 처리할 수 있어서 허락을 필요로하지 않습니다. 
다만 한국 열차 세트 본연의 협궤가 없는 상태에서 다른 grf의 협궤에 기생하는 형태는 적절치 않아보이네요. 의논이 필요할 것 같습니다.

**Comment by Gamunbi** [comment]
일본 철도 세트의 협궤 선로를 쓴다는 게 아니고, 이런 외부 grf의 선로 스프라이트를 그대로 혹은 약간 수정해서 가져다가 한철셋에서 협궤 선로를 새로 만들어도 되는가라는 뜻이었습니다.

**Comment by Gamunbi** [comment]
그렇군요. 참고해서 찍는 경우에도 위반이 될까요? 일단 완성된 걸 봐야 판단이 가능할까요?

**Comment by telk5093** [comment]
참고한 걸 알아낼 수 있는 방법이 있을 지 모르겠네요

**Comment by Gamunbi** [comment]
근데 아마 최대한 비슷하지 않게 만드려고 해도 한계는 있을 것 같습니다. 규격이 정해져있으니까요.. 다른 협궤 선로 grf도 찾아보고 알려드리겠습니다.

**Comment by Gamunbi** [comment]
![일반 철도 베이스 03](https://user-images.githubusercontent.com/75788864/113258720-4369e680-9307-11eb-99e1-621421681df9.png)
![일반 철도 땅](https://user-images.githubusercontent.com/75788864/113258728-4533aa00-9307-11eb-9e63-6c8953d0061b.png)
![일반 철도 건널목](https://user-images.githubusercontent.com/75788864/113258733-482e9a80-9307-11eb-8f7f-f676ce2eda2b.png)

![협궤 철도 02](https://user-images.githubusercontent.com/75788864/113259145-c4c17900-9307-11eb-98aa-c33dacda5256.png)
![협궤 철도 03 600mm](https://user-images.githubusercontent.com/75788864/113260423-38b05100-9309-11eb-9aa0-84287ef18020.png)

![경전철 선로](https://user-images.githubusercontent.com/75788864/113258740-495fc780-9307-11eb-89d1-4d90791f4044.png)



레퍼런스로 쓸 grf 들입니다. 맨 위에서 건널목까지는 opengfx trains grf에서 갖고온 것들이고, 협궤 선로 3종류가 있는 사진은 왼쪽 위에서부터 일본철도세트, 수인선 grf, narrow gauge track types 입니다. 그 아래 가장 좁은 선로는 600mm grf 입니다. 

아마 일철셋 협궤보다 좁고 600mm보단 두껍게 만들게 될 것 같습니다. 선로는 주로 opengfx trains grf 의 선로를 가져다 적절하게 수정하거나, 새로 찍으면 될 것 같습니다.

맨 아래 한철셋 경전철은 일단 최소한으로 만들어볼 종류의 스프라이트들 목록입니다.

어떻게 생각하시는지요?

**Comment by telk5093** [comment]
괜찮은 것 같습니다.

**Comment by Gamunbi** [comment]
그럼 그렇게 하겠습니다~
