### ISSUE TITLE
[Add] EEC(Express Electric Car)

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#15]
Reference:
 * https://namu.wiki/w/EEC%20%EC%A0%84%EB%8F%99%EC%B0%A8
 * http://photozou.jp/photo/photo_only/50802/197311295

**Comment by kiwitreekor** [comment]
![DEC](https://user-images.githubusercontent.com/24273113/112323367-11e49000-8cf5-11eb-8671-084135ff4d36.png)

DEC 스프라이트 개선 / EEC 스프라이트

**Comment by telk5093** [comment]
https://images.app.goo.gl/mPmu5QAAHC98WQXh8

EEC의 팬터그래프가 싱글암이라는 제보가 있었습니다.

**Comment by kiwitreekor** [comment]
![DEC](https://user-images.githubusercontent.com/24273113/112324691-650b1280-8cf6-11eb-9a25-470ca6fceda2.png)

수정본

**Comment by telk5093** [comment]
객차 가로 길이가 33px이라 가로 제한을 넘쳐버리네요.
DEC, EEC와 함께 NDC도 엔진/객차의 3/7번 그래픽(↔)의 가로 길이를 31px로 줄여주실 수 있는지요?

![image](https://user-images.githubusercontent.com/10726524/112329316-70f8d380-8cfa-11eb-9af8-0b947ca3e54d.png)

**Comment by kimgas** [comment]
![eec2](https://user-images.githubusercontent.com/79271602/112329511-9daceb00-8cfa-11eb-8583-fc48679d5844.png)

객차부 무단수정

**Comment by telk5093** [comment]
@kimgas 그러네요, 싱글암이면 8방향이어야하네요.

**Comment by kimgas** [comment]
![eec2](https://user-images.githubusercontent.com/79271602/112332695-4e1bee80-8cfd-11eb-8d70-a037794311fa.png)

무단수정2

팬터그래프가 반대로 되어있습니다

**Comment by telk5093** [comment]
![EEC](https://user-images.githubusercontent.com/10726524/112333243-c5518280-8cfd-11eb-8875-e9329fd91814.png)
세로 위치 수정

**Comment by kiwitreekor** [comment]
![DEC](https://user-images.githubusercontent.com/24273113/112334413-c0410300-8cfe-11eb-9a6a-854c956758b8.png)

객차 사이즈 조절함

**Comment by kiwitreekor** [comment]
@kimgas 
이렇게 먼저 혼자 수정하시면 작업이 중복되니 먼저 댓글로 남겨주세요.

**Comment by kiwitreekor** [comment]
혹시 엔진도 사이즈 변경이 필요한가요?

**Comment by telk5093** [comment]
@kiwitreekor 급한 건 객차가 제일 급하고요, 엔진도 변경되면 좋습니다.
제가 마지막으로 올린 그래픽을 기준으로 작업 부탁드립니다.

**Comment by kiwitreekor** [comment]
@telk5093 
오늘 중으론 힘들 것 같고 내일 해보겠습니다.

**Comment by telk5093** [comment]
@kimgas 그러면 EEC 그래픽은 @kiwitreekor 님께 부탁드리겠습니다.
그런데 https://github.com/KoreanGRF/KoreanTrainSet/issues/15#issuecomment-805896674 에 말씀하신 팬터그래프 방향을 제가 이해한 게 아래 그림이 맞나요?
![image](https://user-images.githubusercontent.com/10726524/112337349-2e86c500-8d01-11eb-8c4a-77693405bdf7.png)


만약 그렇다면 https://github.com/KoreanGRF/KoreanTrainSet/issues/15#issuecomment-805908163 에 작업된 그래픽 스프라이트에도 팬터그래프 방향이 잘못되어 있습니다.

**Comment by kiwitreekor** [comment]
@telk5093 
저도 그런 줄 알았는데요, 올려주신 사진을 자세히 보니 _>_____ 형태로 되어 있습니다.

**Comment by telk5093** [comment]
그러네요. ``_>______ →`` 방향이군요.
어쨌든 팬터그래프 차량의 팬터그래프가 어디에는 왼쪽에, 어디에는 오른쪽에 적용되어 있는 문제가 있네요.

**Comment by kiwitreekor** [comment]
> 그러네요. `_>______ →` 방향이군요.
> 어쨌든 팬터그래프 차량의 팬터그래프가 어디에는 왼쪽에, 어디에는 오른쪽에 적용되어 있는 문제가 있네요.

제가 마지막으로 올린 스프라이트에는 그 문제가 없습니다.

**Comment by kiwitreekor** [comment]
그리고 kimgas님이 추가하신 혹시 뚜껑(?) 3개 달린 객차 그래픽도 필요한가요? 존재하는 걸 알고는 있었는데 구현이 까다로울 것 같아서 일부러 안 찍은 거였습니다.

**Comment by telk5093** [comment]
http://photozou.jp/photo/photo_only/50802/197311295 를 보면 뚜껑(?) 3개 달린 객차가 대부분인 것 같습니다.
일반 지붕 객차가 거의 안 보이네요. (아마도 팬터그래프를 접은 모양으로 추정됩니다. @kimgas 확실하게 답변해주실 수 있나요?)

**Comment by kimgas** [comment]
@telk5093 @kiwitreekor 
http://js3vxw-02.cocolog-nifty.com/photos/korail_9900_/

설명보다는 사진이 더 나을 것 같습니다
이 사이트를 참고해주세요

**Comment by kiwitreekor** [comment]
![DEC](https://user-images.githubusercontent.com/24273113/112471807-b2978600-8daf-11eb-8bf2-0bf50fa93dce.png)

EEC
Tc(앞)
Tc(뒤)
M(판토)
M(일반실)
T(싸롱카)
T(특실)
T(일반실)

**Comment by telk5093** [comment]
반영되었습니다.
