### ISSUE TITLE
대구 1호선 천장색

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#151]
한국열차 세트 소개 홈페이지에서 봤는데 대구 지하철 1호선
천장쪽이 어둡네요

**Comment by telk5093** [comment]
해당 이미지는 교정되기 전에 찍은 이미지입니다.

**Comment by opentrain** [comment]
아 천장색 수정하겠습니다. 죄송합니다.

**Comment by opentrain** [comment]
천장색 수정분 올리겠습니다.

**Comment by telk5093** [comment]
대구 1호선의 천장 색이 지금보다 밝아야한다고 말씀하시는 건가요?

**Comment by opentrain** [comment]
예 그말대로 입니다.
제가 오늘은 시간 없어서 내일정도 수정본 올려드리겠요
불편을 끼쳐 죄송합니다.

**Comment by opentrain** [comment]
대구지하철 수정본입니다.

![DAEGU_METRO_1K](https://user-images.githubusercontent.com/81477455/113263009-3a2f4880-930c-11eb-9ebc-5851e041ecee.png)
대구 1호선 천장 및 팬터그래프 바퀴색상 수정

![DAEGU_METRO_2K](https://user-images.githubusercontent.com/81477455/113263028-41565680-930c-11eb-8155-7bcbc6722929.png)
대구1호선 확인김에 대구2호선도 동시에 확인했는데 바퀴색상 수정 및 동력차 끝부분 도색 안돼있는부분 수정
