### ISSUE TITLE
화차의 길이가 실제보다 긺

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#157]
https://www.youtube.com/watch?v=KxbwaLZawEU
![image](https://user-images.githubusercontent.com/24273113/113272660-d0686c00-9316-11eb-9adb-886b94d54233.png)
(위 영상 캡처)

https://blog.naver.com/PostView.nhn?blogId=cabin5786&logNo=221330552593
위 영상에 나타나는 평판화차 재원표의 "계산"을 잘 보면 모두 0.9~1.1 수준인데, 위 링크의 재원표 읽는 법에 따르면 1.0을 14m로 환산해야 하므로 무개화차와 길이가 똑같아야 함

* [x] 컨테이너 화차(Flat car)
* [x] 평판 화차(Stake car)

**Comment by telk5093** [comment]
이걸 반영하려면 그 수많은 stake car, flat car의 그래픽을 모두 교정할 필요가 있습니다.

**Comment by kimgas** [comment]
![container](https://user-images.githubusercontent.com/79271602/113588147-bc9c6d00-966a-11eb-9304-a82ebf2fb7b1.png)

![m](https://user-images.githubusercontent.com/79271602/113590131-3afa0e80-966d-11eb-8467-f46e6361dc50.jpg)


컨테이너화차 길이 조정

박스 크기는 발전차에 맞춰져 있습니다

**Comment by kimgas** [comment]
관련: https://github.com/KoreanGRF/KoreanTrainSet/issues/117#issuecomment-813513474

길이 재조정 (29->28)

![container](https://user-images.githubusercontent.com/79271602/113686777-9b875b00-9702-11eb-86b9-830941a140c2.png)

**Comment by kiwitreekor** [comment]
음.. 무개화차 length가 6이니 이것도 6으로 맞추는 것이 좋지 않을까요?

**Comment by telk5093** [comment]
> 음.. 무개화차 length가 6이니 이것도 6(24px)으로 맞추는 것이 좋지 않을까요? 20m : 15m = 8 : 6이니..

그러면 너무 짧아질 것 같습니다. 게임적 허용으로 둬도 괜찮지 않을까 하네요

**Comment by kiwitreekor** [comment]
평판화차 작업중인데, 평판화차의 기둥은 어딜 찾아봐도 나오지가 않습니다. 지우는 게 낫지 않을까요?

**Comment by telk5093** [comment]
> 평판화차 작업중인데, 평판화차의 기둥은 어딜 찾아봐도 나오지가 않습니다. 지우는 게 낫지 않을까요?

어떤 기둥을 말씀하시는 거죠? 컨테이너 화차(``FLAT_CAR``) 말고 평판 화차(``STAKE_CAR``)를 말씀하시는 건가요?
그거라면 [장물차](https://www.google.com/search?q=%EC%9E%A5%EB%AC%BC%EC%B0%A8)로 검색하면 됩니다.

**Comment by kiwitreekor** [comment]
@telk5093 
https://www.youtube.com/watch?v=54vVTa3XMeg
https://www.youtube.com/watch?v=ubmmKmWryHc
https://namu.wiki/w/%ED%99%94%EC%B0%A8(%EC%B2%A0%EB%8F%84)

일단 한국의 평판화차/열연코일차에는 양옆 기둥이 없는 것 같습니다.

**Comment by kiwitreekor** [comment]
![STAKE_CAR](https://user-images.githubusercontent.com/24273113/113893969-84c82d80-9802-11eb-8882-9ecec4f5ce94.png)
![cargo_BUBL](https://user-images.githubusercontent.com/24273113/113893971-85f95a80-9802-11eb-907d-93f0aea39c22.png)
![cargo_COPR](https://user-images.githubusercontent.com/24273113/113893973-85f95a80-9802-11eb-9e9d-5df525dca724.png)
![cargo_PAPR](https://user-images.githubusercontent.com/24273113/113893977-8691f100-9802-11eb-9e5e-61c7800e1f3c.png)
![cargo_STEL](https://user-images.githubusercontent.com/24273113/113893980-8691f100-9802-11eb-8308-371f28d0264f.png)
![cargo_TYRE](https://user-images.githubusercontent.com/24273113/113893983-872a8780-9802-11eb-8bc2-a109fbba9b65.png)

일단 몇개만

**Comment by telk5093** [comment]
> 일단 한국의 평판화차/열연코일차에는 양옆 기둥이 없는 것 같습니다.

그러면 ``STEL``이나 ``METL``은 없애는 게 맞겠네요.
중간 과정보다는 전체 완성 후에 올려주시면 감사하겠습니다.

**Comment by kimgas** [comment]
개방형 코일강판차가 2 종류인게 확인되어서 새로 찍고 있었습니다.
좌측은 평판화차에 얹는 방식이고, 우측은 전용으로 제작된 것으로 보고 있습니다.

![Untitled-1](https://user-images.githubusercontent.com/79271602/113949536-7998f000-984a-11eb-908b-a6516856efaa.jpg)

아직 완성단계가 아니라서 업로드는 안했습니다만 필요하시다면 올려서 합치는 것도 좋을 것 같습니다.
컨테이너도 가로 길이를 28로 잡아서 올려놨었는데 실제 반영은 27이라서 이거도 새로 조정하려 합니다.

**Comment by opentrain** [comment]
어 stake_car 구도색 작업하고있었는데
이렇게되면 다시 해야겠네요

**Comment by telk5093** [comment]
@kimgas 가로 길이는 27px로 맞춰주시면 감사하겠습니다. 두 사진은 별도로 분리할 필요는 없을 것 같고 하나로 합쳐서 표현하는 게 좋을 듯 합니다.
@opentrain 구 도색 작업은 일단 지금은 멈춰주세요.

**Comment by kimgas** [comment]
![container](https://user-images.githubusercontent.com/79271602/114302797-afb5c880-9b05-11eb-8105-ebbdb3d14cee.png)
container (27px)

![steel](https://user-images.githubusercontent.com/79271602/114302801-b47a7c80-9b05-11eb-941c-6b85b6f2ed0d.png)
steel (27px)

![stake](https://user-images.githubusercontent.com/79271602/114302806-b6444000-9b05-11eb-8574-2b9b258098ef.png)
stake (27px)

**Comment by telk5093** [comment]
작업 감사합니다.
FIRS 화물 그래픽도 작업될 때까지 일단 코딩 작업은 보류하고 있겠습니다.

**Comment by EightonEight** [comment]
![flat](https://user-images.githubusercontent.com/77984422/130496599-21208f22-b40f-49c4-8615-e4d12e6c2e33.png)
`FLAT_CAR_*`
* 검정, 갈색 도색 추가
---
![hopper](https://user-images.githubusercontent.com/77984422/130497294-99b45885-e111-4c59-a2c4-a2eae1149b9a.png)
![temp_cargo_hopper](https://user-images.githubusercontent.com/77984422/130501027-6d069984-68ad-4b98-99bf-c90b1917c1ad.png)
`HOPPER_CAR`
* FIRS 화물 추가
* 무개 컨테이너 추가
* 기본 적재 그래픽 추가 (상자, 방수포)
---
![stake](https://user-images.githubusercontent.com/77984422/130501053-74a7e3bc-7bbc-4bc6-b888-ef19d98c0cb2.png)
![temp_cargo_stake](https://user-images.githubusercontent.com/77984422/130501064-e85bfd9c-0d19-4696-92e6-04775f2a59da.png)
`STAKE_CAR`
* FIRS 화물 추가
* 자동차 수송화차 길이 조정
* 기본 적재 그래픽 추가 (유개형 냉연코일차, ref: <https://images.app.goo.gl/eLcNdR3QkAYQYj5M9>, <https://youtu.be/xeL1QAObY_M?t=20>)
---
무개화차 스프라이트 중 `GRVL`, `SAND`는 자갈차를 표현하고자 기존 스프라이트를 길이에 맞게 수정만 하고 그대로 사용하였습니다. (ref: <https://images.app.goo.gl/jLqMPQ6dm8PcNHxHA>)

평판화차는 화물들의 특성에 어울리도록 세 종류를 모두 사용했습니다.

**Comment by Gamunbi** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/issues/157#issuecomment-904044583

만드신 무개화차는 hopper car 가 아니고 gondola 입니다. 호퍼차는 아래쪽으로 화물을 쏟아낼 수 있는 기능을 가지고, 쉽게 쏟아내기 위해 깔대기처럼 생긴 화물차를 말합니다. 

[호퍼차 hopper_car](https://www.google.com/search?q=hopper+car&client=firefox-b-d&channel=trow5&sxsrf=APq-WBuKebJizM6Mtm-10BeZ9Og-EDcrlw:1643783191144&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiYn8jJseD1AhVRklYBHcgTC9sQ_AUoAXoECAEQAw&biw=1920&bih=955&dpr=1)

[무개화차 gondola](https://www.google.com/search?q=gondola+train&tbm=isch&ved=2ahUKEwjY_9zKseD1AhVGEKYKHTSKBGQQ2-cCegQIABAA&oq=gondola+train&gs_lcp=CgNpbWcQAzIHCCMQ7wMQJzIECAAQEzIECAAQEzIECAAQEzIICAAQCBAeEBMyCAgAEAgQHhATMggIABAFEB4QEzIICAAQCBAeEBMyCAgAEAgQHhATMggIABAIEB4QEzoFCAAQgAQ6BAgAEB46CAgAEIAEELEDOgsIABCABBCxAxCDAToECAAQAzoKCCMQ7wMQ6gIQJzoGCAAQHhATUMMKWJsjYNwjaAJwAHgAgAG2AYgBjhKSAQQwLjE2mAEAoAEBqgELZ3dzLXdpei1pbWewAQrAAQE&sclient=img&ei=GST6YZiPI8agmAW0lJKgBg&bih=955&biw=1920&client=firefox-b-d)

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.

**Comment by telk5093** [comment]
#403 inherits this issue
