### ISSUE TITLE
통일호 객차 등장년도 조정이 필요합니다.

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#163]
https://ko.m.wikipedia.org/wiki/%ED%86%B5%EC%9D%BC%ED%98%B8

통일호 운영이 1955~2004년까지라네요
게임상에서 1988로 출시되어있었어 말씀드립니다.

**Comment by Gamunbi** [comment]
55~63년은 도색 정보가 없어서 저는 스프라이트를 만들지 않았습니다(아마 3등 객차 도색이었을 것 같긴 한데 확실하지 않아서). 확인되기 전에는 일단 맨 첫 차량(붉은 도색)을 55년으로 땡겨놔야 할 듯 합니다.

**Comment by telk5093** [comment]
사료에 따르면 '통일호'라는 명칭 자체가 1984년 이후에 나온 것으로 보입니다. (교차 검증 완료)
@opentrain 님이 말씀하시는 1955년은 https://ko.m.wikipedia.org/wiki/%ED%86%B5%EC%9D%BC%ED%98%B8_(%EC%9A%B4%ED%96%89_%EA%B3%84%ED%86%B5 를 말하는 걸로 보입니다.
따라서 1955년으로 조정하는 게 아니라 1984년으로 변경하는 게 맞아보입니다.

**Comment by Gamunbi** [comment]
http://info.korail.com/mbs/www/subview.jsp?id=www_020102000000

만일 통일호 등장년도를 84년으로 조정한다면, 84년 이전 새마을호, 무궁화호, 비둘기호도 전부 조정해야 할 듯 싶습니다. 

개인적으로는 그냥 현상유지가 나아보입니다.

**Comment by Gamunbi** [comment]
꼭 조정해야 한다면 개조 이름에 84년까지 '특급'이란 이름을 추가하고 84 이후엔 '통일호'를 추가하는 게 제일 좋아보입니다.

**Comment by telk5093** [comment]
새마을호, 통일호 객차의 등장 연도를 각각 새마을호 객차 1987→1984년, 통일호 객차 1988→1984년으로 통일하되
무궁화호 객차의 1972년, 비둘기호 1927년은 그 이전 도색 차량이 같이 존재하기 때문에 그대로 존치하겠습니다.
