### ISSUE TITLE
FMSP, ENSP 8방향 오류

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#167]
서로 다른 종류의 스프라이트끼리 그룹으로 묶여있는 것 같음. (코드상으로만 확인한 것이라 추가 확인 필요)

**Comment by telk5093** [comment]
Duplicate of #160

**Comment by telk5093** [comment]
>A A
B B 형식으로 정렬되어야 하는데
>
>A B
A B 형식으로 정렬되어 있음.

**Comment by telk5093** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/blob/1353943ec0b87ec4b3b0dc90ba5f04c71685c3b7/src/wagon/stake_car/stake_car_ENSP_graphic.pnml#L18
에서,
``loading`` 부분에 순서대로 empty, full
``loaded`` 부분에 순서대로 empty, full 이 들어간 게 문제인 것 같다는 말씀이신지요?

[NML:Spritegroup](https://newgrf-specs.tt-wiki.net/wiki/NML:Spritegroup) 문서에 따르면
``loading`` 속성은 열차가 역에서 화물을 적재할 때의 그래픽이고,
``loaded`` 속성은 열차가 운행 중일 때의 그래픽이며,
각 속성에 [ ~ ] 형식의 스프라이트 셋을 n개 지정하면 첫 번째 스프라이트 셋은 적재율 0%, i번째는 ``i/n×100``% 적재율에 나타나는 그래픽입니다.

따라서
``loading`` 속성에 빈 그래픽, (가득) 실은 그래픽,
``loaded`` 속성에 빈 그래픽, (가득) 실은 그래픽
을 지정하는 게 맞습니다.

**Comment by kiwitreekor** [comment]
아니요, 스프라이트 부분에 포크레인과 트랙터끼리 정렬되어있지 않고 섞여있다는 말입니다.

**Comment by kiwitreekor** [comment]
![image](https://user-images.githubusercontent.com/24273113/113432944-3d642a80-9419-11eb-8026-ad8bedae8aa6.png)

**Comment by telk5093** [comment]
잘 알겠습니다. 교정해두겠습니다 :)
