### ISSUE TITLE
컨테이너 평판화차 철도청 도색 추가

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#173]
우선 이스프라이트를 제공해주신 skyu님한테 감사를 드립니다.
일주일정도 걸렸네요
호퍼차하고 유조차를 도색이 있는데 컨테이너 평판화차 도색이 없어서 넣어봤습니다.
일단 다음계획 평판화차 도색 추가목적입니다.

![FLAT_CAR-검정도색](https://user-images.githubusercontent.com/81477455/113470156-5ce96a80-948e-11eb-9a38-e13a8cb592f8.png) 
첫번째 검정도색입니다. 철도청 구도색(검정)
1960~2006년정도로 갈색도색하고도 같이사용한거로암

![FLAT_CAR-갈색도색](https://user-images.githubusercontent.com/81477455/113470159-61ae1e80-948e-11eb-9e72-3a0d8db4aee9.png)
두번째 갈색도색입니다. 철도청 구도색(갈색)
1996~2006년까지 사용한 도색으로 알고있습니다.

도색참고용입니다.
https://www.google.co.kr/search?q=%ED%8F%89%ED%8C%90%ED%99%94%EC%B0%A8+%EA%B5%AC%EB%8F%84%EC%83%89&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjI2OSMtuHvAhXw-GEKHW0bCegQ_AUoAXoECAEQAw&biw=1366&bih=657#imgrc=36gvAqJzzFGfiM

현재 컨테이너 평판화차 구도색를 반영한다면 기존도색를 한국철도공사 신도색(파란)으로 바꾸는거 어떤지요?

**Comment by telk5093** [comment]
반영되었습니다.
