### ISSUE TITLE
무궁화호 객차 8방향화

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#174]
현재 무궁화호 객차는 4방향 그래픽으로 되어있으나, 실제 문 위치가 한쪽에 치우진 것을 고려해보면 8방향으로 고치는 것이 맞음.

**Comment by opentrain** [comment]
제가 시도해보겠습니다.

**Comment by ChuoSpecialRapid201** [comment]
작업 시작, 2시간정도 걸릴것같음.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/113577886-f1092c80-965c-11eb-936a-c8f8ca8dcd51.png)

From #177 

> 80년대 도장 198?~
> 90년대 도장 1993?~
> 신도장, 2003~ (구형객차)
> 신조객차 등장시 도장, 2001~
> 신조객차 현재 도장, 2003~
> 유선형 구특전, 1993~2006
>
> ----------(추가되지 않은 차량↓)----------
>
> 해태중공업 특실(등장시), 1998~
> 해태중공업 특실객차(현재 도장), 2007~
> 한진중공업 특실객차, 1991~2004
> 유선형 특실객차(현재 도장), 2007~
> 신조 침대객차(등장시), 2001~
> 신조 침대객차(현재 도장), 2012~
>
> 순서.
> 80년대 이전 도장은 자료가 거의 없다시피 해서 작업 안함.

**Comment by telk5093** [comment]
Related: #113 #123 #124

**Comment by telk5093** [comment]
24ad9f1 에서 반영되었습니다.
다만 침대객차는 #123 에서 말씀드렸듯이 천장의 수정이 추가로 필요할 것 같습니다. 해당 사안은 #123 에서 이야기해주세요.
