### ISSUE TITLE
5000/6000호대 그래픽

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#176]
![image](https://user-images.githubusercontent.com/24273113/113515967-a92dcb00-95b2-11eb-9ec9-3b5538bf632d.png)

**Comment by opentrain** [comment]
5000~6000호대를 구분이 안가더라구요
구도색을 제가  찾아보고 넣겠습니다.

**Comment by kiwitreekor** [comment]
> 5000~6000호대를 구분이 안가더라구요
> 구도색을 제가 찾아보고 넣겠습니다.

5000~6000호대는 다른 도색이 없습니다. 무슨 말씀을 하시는지 모르겠네요.

**Comment by opentrain** [comment]
> > 5000~6000호대를 구분이 안가더라구요
> > 구도색을 제가 찾아보고 넣겠습니다.
> 
> 5000~6000호대는 다른 도색이 없습니다. 무슨 도색을 말씀하시는지 모르겠네요.



> > 5000~6000호대를 구분이 안가더라구요
> > 구도색을 제가 찾아보고 넣겠습니다.
> 
> 5000~6000호대는 다른 도색이 없습니다. 무슨 도색을 말씀하시는지 모르겠네요.

관광호도색하고 역삼각마크 도색 존재안해요?

**Comment by kiwitreekor** [comment]
> > > 5000~6000호대를 구분이 안가더라구요
> > > 구도색을 제가 찾아보고 넣겠습니다.
> > 
> > 
> > 5000~6000호대는 다른 도색이 없습니다. 무슨 도색을 말씀하시는지 모르겠네요.
> 
> 관광호도색하고 역삼각마크 도색 존재안해요?

역삼각 CI 도입이 95년이고, 폐차가 97년이라 시기상 없다고 보는 게 맞을 것 같습니다. 실제 자료사진도 나오지 않습니다.

**Comment by kiwitreekor** [comment]
6x00호대는 7x00호대처럼 생겨서 5000/6000호대라고 하는 게 맞을 것 같습니다. (6300호대 참고)

**Comment by telk5093** [comment]
f1c58a3 에서 이름 변경에 대한 건이 반영되었습니다.

**Comment by telk5093** [comment]
b57dd5a05d2bc28354c9b5b13cc61996e7349140 에서 반영되었습니다.
