### ISSUE TITLE
[수정완료]무궁화호 객차 8방향화

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#177]
![Mugunghwa_Edit](https://user-images.githubusercontent.com/81485156/113576152-fc0e8d80-9659-11eb-9250-32c21b97dea0.png)

80년대 도장 198?~

90년대 도장 1993?~

신도장, 2003~ (구형객차)

신조객차 등장시 도장, 2001~

신조객차 현재 도장, 2003~

유선형 구특전, 1993~2006

----------(추가되지 않은 차량↓)----------

해태중공업 특실(등장시), 1998~

해태중공업 특실객차(현재 도장), 2007~

한진중공업 특실객차, 1991~2004

유선형 특실객차(현재 도장), 2007~

신조 침대객차(등장시), 2001~

신조 침대객차(현재 도장), 2012~

순서.

* 80년대 이전 도장은 자료가 거의 없다시피 해서 작업 안함.

**Comment by telk5093** [comment]
#174로 이관합니다.
