### ISSUE TITLE
7x00호대 32bpp 스프라이트?

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#178]
![K7x00_32bpp](https://user-images.githubusercontent.com/24273113/113593984-0b013a00-9672-11eb-8a76-b91a3dd137b7.png)

예전에 모델링했던 거 썩히기는 아까워 여기에라도 올려봅니다.
규격이 안 맞을 수도 있습니다.

**Comment by telk5093** [comment]
oh my god

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/113607178-e01fe180-9683-11eb-87ff-fe9dae56a40a.png)

Suez canal openttd version 🤣

**Comment by kiwitreekor** [comment]
![K7x00_32bpp](https://user-images.githubusercontent.com/24273113/113654107-1d12c500-96d2-11eb-8339-338dc6443a12.png)

규격 수정 & 디테일 개선

**Comment by telk5093** [comment]
Close this since it is staled.
