### ISSUE TITLE
[緊急] 무궁화 객차 도트 오류 수정.

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#180]
![Mugunghwa_Edit](https://user-images.githubusercontent.com/81485156/113824718-11e79400-97bb-11eb-8a16-e140580f0e21.png)

* 카페객차에 심각한 도트 오류가 발견되어 수정
* 일부 도트 수정 안된것(단순 좌우반전 등) 수정함.
* 특실 객차 일부 수정

**Comment by telk5093** [comment]
반영되었습니다.
