### ISSUE TITLE
부산 1호선 도트 버그

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#183]
![BUSAN_METRO_1K_1ST](https://user-images.githubusercontent.com/81485156/113857674-c397bc80-97dd-11eb-82e6-a5a77f39308c.png)

객차가 여전히 4비차로 되어있어 수정함.

**Comment by opentrain** [comment]
열차문쪽 말씀하세요?

**Comment by ChuoSpecialRapid201** [comment]
> 열차문쪽 말씀하세요?

이미 수정했으니까 상관없을듯.

**Comment by telk5093** [comment]
8bpp 팔레트 지정이 안 되어 있네요. 다음에는 꼭 지정해주세요.

**Comment by ChuoSpecialRapid201** [comment]
수정본 
![BUSAN_METRO_1K_1ST](https://user-images.githubusercontent.com/81485156/114010065-b262b480-989e-11eb-81c9-2afa7775d1f0.png)

**Comment by telk5093** [comment]
12ad66e 에서 반영되었습니다.
