### ISSUE TITLE
새마을 객차 도트 8방향화

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#184]
![KNR_S_Renewal](https://user-images.githubusercontent.com/81485156/114034109-daf7a800-98b8-11eb-87c0-10e3125ee65b.png)

* 등장시 도장 (일반실)
* 등장시 도장 (특실) --추가 안됨--
* 구 도장 (일반실)
* 구 도장 (특실)
* 신 도장 (일반실)
* 신 도장 (특실)
* 신 도장 (식당차) --추가 안됨--

순서....

특실 차량 창문 일부 수정함.
+ 초기 도장 특실객차 추가.

**Comment by telk5093** [comment]
2.0.3에서 반영되었습니다.
