### ISSUE TITLE
[Add] 무궁화 식당차(1980년대 도장)

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#185]
![Mugunghwa_Snackcar1](https://user-images.githubusercontent.com/81485156/114051251-e1d9e700-98c7-11eb-800f-da07ee840e73.png)

이녀석이 빠져있더라

Ref

![1617894809](https://user-images.githubusercontent.com/81485156/114051879-75131c80-98c8-11eb-94d1-923af5bf127a.png)

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/114069643-2e2e2280-98da-11eb-9444-bbc82152d634.png)


@ChuoSpecialRapid201 
이 차량들의 이름을 순서대로 정리해주실 수 있으신가요?
현재 제가 파악한 이름이 이렇게인데 문제가 있다면 알려주세요.
```
무궁화 식당차 / 1984~1994 (이 이슈에서 추가한 것)
무궁화 스낵차 / 1994~2006
무궁화 카페차 / 구 차량
무궁화 식당차 / 신 차량
무궁화 카페차 / 신 차량
```

**Comment by telk5093** [comment]
3d8dac6 에서 반영되었습니다.
