### ISSUE TITLE
특실용 객차 별도 분리

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#186]
특실 그래픽이 많이 생김에 따라 특실용 객차를 별도로 분리하는 안에 대해 고려해볼 필요가 있음

 * [x] 구매 이미지(purchase image)에 나올 특실 객차 이미지(가로 방향)가 필요
 * 여러 군데에 흩어져있는 특실 그래픽을 잘라서 한 폴더로 이동
   * [ ] KTX-1
   * [ ] KTX-산천
   * [ ] 새마을호 객차
   * [ ] 무궁화호 객차

고유 코드는 ``EXECUTIVE_CAR``로, livery_override 블록으로 작동하도록 변경

**Comment by opentrain** [comment]
이제 무궁화호,새마을호 KTX,산천 전부다 공통 객차처럼 따로 분리되는건가요?

**Comment by EightonEight** [comment]
![EXECUTIVE_CAR](https://user-images.githubusercontent.com/77984422/118228253-d2e8e480-b4c4-11eb-9f82-11d3b0fe51a7.png)
공통 특실 객차 스프라이트를 제작하였습니다.  

**1안**: 공통 객차 기반, 여러 특실 객차를 참고하여 제작한 도색
**2안**: 공통 객차, 공통 객차(동력차)와 동일한 종류의 도색  

어떤 것이 좋으신지 1안은 🎉으로, 2안은 🚀으로 반응해주시면 감사하겠습니다.

**Comment by telk5093** [comment]
개인적으로는 1안이 마음에 드네요.

**Comment by EightonEight** [comment]
> 개인적으로는 1안이 마음에 드네요.

![EXECUTIVE_CAR2](https://user-images.githubusercontent.com/77984422/118294720-f8eaa500-b515-11eb-962f-30433c45b0e4.png)
1안을 좀 더 다듬어보았습니다.

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.
