### ISSUE TITLE
새마을 PP동차(신도장) 도트 수정

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#187]
![DHC](https://user-images.githubusercontent.com/81485156/114173381-0e4a3d80-9972-11eb-8953-b664b63bab05.png)

* 출입문 수정
* 라이트 수정
* 행선판 추가

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/114259418-bb6f9500-9a08-11eb-8896-89d60d20757c.png)

 1. 명암이 잘못되었습니다.
 2. E 방향(→) 연결부는 삭제하겠습니다

**Comment by ChuoSpecialRapid201** [comment]
![DHC](https://user-images.githubusercontent.com/81485156/116672834-9786ea00-a9dd-11eb-8b6c-8aea47208aa6.png)

**Comment by telk5093** [comment]
맨 아래 6번도 명암이 잘못되어 있으나, 이건 제가 수정해서 반영하겠습니다.
