### ISSUE TITLE
부산 1호선 18m화(?)

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#189]
![BUSAN_METRO_1K_1ST](https://user-images.githubusercontent.com/81485156/114221568-7156c700-99a8-11eb-9a12-e451c0500773.png)

* 통로막을 1칸 늘림(길이는 같으니 그냥 덮어씌우면 됨)
* 우측 선두칸 도트 1칸 늘어남(적용시 수정 요함)
* 차량 상부에 주황 띠 추가
* 선두부 파란 띠 수정
* 통로문 수정

게임상에서 어떻게 보일지는 모르겠으나 객차 길이는 현실과 같이 짧아보이게 함.

**Comment by telk5093** [comment]
일반적인 지하철 중전철 차량의 경우, 대형 중전철(eg. 서울 지하철 차량)이나 중형 중전철(eg. 인천 지하철 1호선 차량)을 모두 포함, 길이를 건드릴 생각이 없습니다.
(cf. 중전철 지하철 차량은 모두 거의 하나의 템플릿으로 관리되고 있고 주둥이 차량을 제외하면 예외가 없습니다)

이전 이미지와의 차이를 보니, 연결부가 왼쪽/오른쪽에 모두 추가되어 있는데 이러면 zoom 2단계(=기본) 상태에서 연결부가 2px 떨어져보이게 되고, 이는 어색하게 보일 것입니다.

따라서 개인적으로 차량 길이를 수정하는 안에 찬성하지 않습니다.
