### ISSUE TITLE
화차 수송량 관련

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#191]
한국철도세트에 홈페이지 보면 원래 화차 수송량이 50톤 아닌가요? 밸런스조정으로 하향 먹은건가요?

**Comment by telk5093** [comment]
1. Github의 Issues는 질문 게시판이라기보다는 버그 신고의 장소입니다.
특히나 TELKLAND 사이트와 관련된 글이라면 [TELKLAND 사이트](https://telk.kr)에 해주시는 게 맞습니다.

1. 어떤 화차를 말씀하시는지 모르겠습니다. 1.6.x와 2.0.x 버전에 공통으로 있는 화차인 평판화차, 호퍼차(무개화차), 유조화차 세 종을 모두 확인해봤으나 수송량이 50 단위였던 적도 없고, 무게가 50t이었던 적도 없습니다.
