### ISSUE TITLE
서울교통공사 5k VVVF 4차 도색의 줄이 끊어져 보임

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#193]
![image](https://user-images.githubusercontent.com/10726524/114564911-bc742100-9cab-11eb-95d8-ef910af985a8.png)

그래픽 개선 작업이 필요함

**Comment by opentrain** [comment]
https://blog.naver.com/990104ms/222249448351 여기링크에 참고해서 봤는데 줄이 위쪽 아래쪽식으로 되어있어요

**Comment by opentrain** [comment]
![SMETRO_5K_4TH](https://user-images.githubusercontent.com/81477455/114675391-2095f400-9d43-11eb-9a58-51c2225c2b9b.png)
대각선 방향 수정해봤습니다.

**Comment by telk5093** [comment]
@opentrain 줄 위치를 동일하게 맞추는 안은 고증에 맞지 않는 것 같습니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/115137787-189bc400-a063-11eb-9a5e-b0e8f513b089.png)
위 그래픽으로 제가 직접 수정하여 반영합니다.
줄을 조금 선명하게 하고, 대각선 방향에서 S자가 지나치게 끊어져보이는 것을 개선했습니다.

반영 모습:
![image](https://user-images.githubusercontent.com/10726524/115137802-29e4d080-a063-11eb-8087-b8bac956f67f.png)
