### ISSUE TITLE
새마을호 객차 모음 8방향으로 통합

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#195]
#130 이것로 대신해서 올리겠습니다.

![새마을호 빨간색위아래버전](https://user-images.githubusercontent.com/81477455/115145335-ff5b3d80-a08b-11eb-9c97-e35ce3803c21.png)
기관차 전용 새마을호 도색

https://www.google.co.kr/search?q=%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8+%EA%B0%9D%EC%B0%A8%EB%8F%84%EC%83%89&tbm=isch&ved=2ahUKEwjOioe44IfwAhUBUJQKHWx8A34Q2-cCegQIABAA&oq=%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8+%EA%B0%9D%EC%B0%A8%EB%8F%84%EC%83%89&gs_lcp=CgNpbWcQA1DXnQFYo6gBYIepAWgBcAB4AIABfYgBtwWSAQMwLjaYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=gSB8YI7GJYGg0QTs-I3wBw&bih=609&biw=1366#imgrc=KO55JsBhboL-KM

![새마을호 빨간색없는버전](https://user-images.githubusercontent.com/81477455/115144985-6e379700-a08a-11eb-8702-fa54cbaaa846.png)
#130 초기 새마을호 도입당시 도색

![새마을호 노란색버전](https://user-images.githubusercontent.com/81477455/115144964-56f8a980-a08a-11eb-81d1-1f7e0bbfddcf.png)
#130 무궁화호 특실 도색 4방향으로 있던 새마을호 객차를 8방향으로 새로 수정해서 했습니다.

![새마을호 파란신도색](https://user-images.githubusercontent.com/81477455/115144993-78599580-a08a-11eb-8c39-f1994a34fa41.png)
이버전은 기존 DHC-PP열차 운행종료후에 객차형 새마을호 진한버전으로 도색된 신도색입니다.
이것도 예전에 4방향만 되어있었는데 수정해서 8방향으로 수정했습니다.

https://www.google.co.kr/search?q=%EA%B0%9D%EC%B0%A8%ED%98%95+%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8&tbm=isch&ved=2ahUKEwi4rNKs4ofwAhVXAN4KHQP0DGgQ2-cCegQIABAA&oq=%EA%B0%9D%EC%B0%A8%ED%98%95+%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8&gs_lcp=CgNpbWcQA1C32wlY298JYKPhCWgAcAB4AIABc4gB4AGSAQMwLjKYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=giJ8YLjjIdeA-AaD6LPABg&bih=609&biw=1366#imgrc=u2HlnSg6-kyNiM

기존에 제가 예전에 찍었던 4방향 있었던 새마을호 객차를 8방향으로 수정해서 올려봅니다.

**Comment by telk5093** [comment]
일단, OpenTTD의 그래픽 상 저게 손쉽게 분간이 될지도 모르겠고 추가할 의미가 있을지 모르겠습니다.
오히려 개조 목록이 지나치게 중구난방이 될 가능성도 있습니다.
마찬가지로 게임적 허용, 또는 데포르메로 간주하고 추가하지 않는 것을 방향으로 잡고자 합니다.
