### ISSUE TITLE
계획상에 있었던 통일호 신도색

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#196]
![통일호 노란신도색](https://user-images.githubusercontent.com/81477455/115147183-c378a600-a094-11eb-8726-266139cb60df.png)
당시 철도청에서 KTX개통하고서도 통일호 노란신도색으로 운영준비예정이였다고하네요

https://www.youtube.com/watch?v=cdNMd-nbJeI

**Comment by telk5093** [comment]
계획만 있었고 실제 운영한 적이 없기 때문에 추가할 계획이 없습니다.
