### ISSUE TITLE
GTX-A 차량

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#197]
https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=139781

**Comment by EightonEight** [comment]
Vehicle specification
| Name                             | Code                | Speed             | Speed (designed) | Capacity  | Power          | Weight     | Introduction |
|---------------------------|-----------------|-----------------|---------------------|-----------|--------------|------------|---------------|
| GTX-A                            | ``-``                   |  **180 km/h** | **198 km/h**        |                |                     |                 | 2023             |

References:
이번에 공개된 목업의 제원표
<https://blog.naver.com/vbnm0821/222317150818>
GTX-A 노선 차량 제작설명서(2019.12 기준)
<https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=62458>
<https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=62459>

EMU-260의 사례처럼 실차가 제작되어야만 정확한 제원 확인이 가능할 것 같습니다.

**Comment by telk5093** [comment]
KTX-이음의 경험으로 미루어볼 때 향후 이름, 속력, 수용량, 출력 등의 스펙 변동 사항이 생길 수 있어 지금 당장 그래픽 스프라이트가 마련된다고 해도 추가하는 것을 고민해봐야 합니다.

**Comment by opentrain** [comment]
![GTX-A 노선차량](https://user-images.githubusercontent.com/81477455/115955713-3b324f00-a533-11eb-8a09-f237dc58283f.png)
일단 오늘 할거도 없고 해서 만들긴했는데
팬터 차량을 제외시켰습니다.
추후 팬터차량이 추가되면 다시 수정예정입니다.

**Comment by evepoi** [comment]
혹시 YST set에서 선공개해도 괜찮을련지 여쭤보고 싶습니다.

**Comment by telk5093** [comment]
> 혹시 YST set에서 선공개해도 괜찮을련지 여쭤보고 싶습니다.

개인적으로는 다소 부정적인 의견을 드립니다만, 그걸 제외하면 아무 상관 없습니다.

**Comment by evepoi** [comment]
> > 혹시 YST set에서 선공개해도 괜찮을련지 여쭤보고 싶습니다.
> 
> 개인적으로는 다소 부정적인 의견을 드립니다만, 그걸 제외하면 아무 상관 없습니다.

어느부분이 부정적이신지 정확히 말씀해주실수 있으실련지요??

**Comment by telk5093** [comment]
> 어느부분이 부정적이신지

그래픽 스프라이트가 아주 100% 완성된 게 아니라는 점을 들겠습니다.

**Comment by evepoi** [comment]
> > 어느부분이 부정적이신지
> 
> 그래픽 스프라이트가 아주 100% 완성된 게 아니라는 점을 들겠습니다. ~+ 추가로 YST의 저작권이 불분명합니다. 가져가시려면 YST 역시 CC-BY-NC-SA v3.0 를 따르셔야 합니다.~ 따르고 있네요

네 최근 한국열차세트의 일부를 가져가면서 저작권을 지키고 있습니다 ^^
YST에 적용할지 여부는 좀더 고민해보고 적용해보겠습니다.

추후 공개후에 어떻게 조치할지여부도 고민해야야할 거 같습니다.

**Comment by evepoi** [comment]
> ![GTX-A 노선차량](https://user-images.githubusercontent.com/81477455/115955713-3b324f00-a533-11eb-8a09-f237dc58283f.png) 일단 오늘 할거도 없고 해서 만들긴했는데 팬터 차량을 제외시켰습니다. 추후 팬터차량이 추가되면 다시 수정예정입니다. 이그래픽 수정하셔도 상관없습니다.

> ![GTX-A 노선차량](https://user-images.githubusercontent.com/81477455/115955713-3b324f00-a533-11eb-8a09-f237dc58283f.png) 일단 오늘 할거도 없고 해서 만들긴했는데 팬터 차량을 제외시켰습니다. 추후 팬터차량이 추가되면 다시 수정예정입니다. 이그래픽 수정하셔도 상관없습니다.

혹시 스프라이트 가져다가 YST에 추가해도 될지 여쭤보고 싶습니다.

**Comment by telk5093** [comment]
#340 으로 병합합니다.
