### ISSUE TITLE
코레일 1호선 13분~14분차 주둥이(1호선노선색깔버전)

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#199]
최근 1호선 주둥이 수정완료
2021.10.10 수정완료 운전실쪽 에어컨 추가반영
![LINE_1_2021](https://user-images.githubusercontent.com/81477455/136698613-f25fa7b3-e853-4e23-91b1-6b98a3686812.png)

1호선 주둥이 2019년에 들어온 주둥이가 빨간색버전인데
이번에 들어온 주둥이를 1호선 노선색깔에 맞춰진 노선 
파란버전이네요

</font>앞으로 13~14분 반영차 듣기로는 도색이 이렇게 적용된다는 얘기가 있네요 
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">또다른 1호선 신차도 계속 반영된다는 얘기가 있긴한데 나오고나서 찍든가하겠습니다.

**Comment by opentrain** [comment]
https://namu.wiki/w/%ED%95%9C%EA%B5%AD%EC%B2%A0%EB%8F%84%EA%B3%B5%EC%82%AC%2031x000%ED%98%B8%EB%8C%80%20%EC%A0%84%EB%8F%99%EC%B0%A8/%EC%B0%A8%ED%98%B8%EB%B3%84%20%EC%83%81%EC%84%B8%EC%84%A4%EB%AA%85#s-2.11
오늘 올라왔다고 합니다.

**Comment by telk5093** [comment]
#295 로 이관
