### ISSUE TITLE
부산 1호선 2세대 가로 그래픽이 통일되어 있지 않음

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#200]
![image](https://user-images.githubusercontent.com/10726524/115525474-17b89b80-a2ca-11eb-8c4a-810d4f7ffca4.png)

전후두부와 객차의 그래픽이 다름

**Comment by opentrain** [comment]
제보 감사합니다.

**Comment by telk5093** [comment]
@opentrain Assignees를 보시면 제가 등록되어 있는데, 이건 제가 직접하겠다는 뜻입니다.
