### ISSUE TITLE
협궤 철도(762mm)

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#204]
![협궤 선로 1차 완성](https://user-images.githubusercontent.com/75788864/115966187-85352800-a567-11eb-97b7-a7757ee1f797.png)

보나마나 수정해야 할 곳이 여기저기 있을 거라 예상합니다. 선로는 처음 만들어보기 때문에..

건널목은 코딩 구조가 어떻게 되어 있을지 몰라 일단 최소한 구색이라도 갖출 수는 있게 기본적인 스프라이트는 찍어놓았습니다. 건널목은 다시 만들 수 있습니다.

**Comment by telk5093** [comment]
https://newgrf-specs.tt-wiki.net/wiki/NML:Railtypes
건널목, 울타리 등의 그래픽 스프라이트 구조에 대해서는 이 문서를 참고해주세요.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/116727461-8fe83500-aa1f-11eb-89f2-6d5f86106f59.png)

수정된 그래픽 스프라이트입니다.

**Comment by Gamunbi** [comment]
![협궤 선로 건널목](https://user-images.githubusercontent.com/75788864/116729711-74caf480-aa22-11eb-9359-45c69498318c.png)
건널목입니다.

**Comment by telk5093** [comment]
반영 완료

**Comment by Gamunbi** [comment]
![협궤 선로 건널목](https://user-images.githubusercontent.com/75788864/116772381-901d1a80-aa89-11eb-934c-e9ce9ebd5e4e.png)

https://www.youtube.com/watch?v=4kXg0FlU4Rc

2종 건널목입니다. 차단봉 올라간 스프라이트는 혹시나 쓸 수 있지 않을까 해서 따로 만들어 같이 올립니다. 점멸등은 앞뒤로 있습니다. 앞뒤구분은 X멈춤 표지판으로 하시면 됩니다.

**Comment by Gamunbi** [comment]
![건널목](https://user-images.githubusercontent.com/75788864/117110119-a0523400-adc0-11eb-993e-e3ab02b17516.png)

기존에서 약간 수정하고 1종, 2종 나누었습니다. 1종은 당장은 아니고 나중에 혹시나 표준궤에 쓰게 될 때 쓰시면 좋겠고, 2종은 협궤에 그대로 쓰시면 됩니다.

앞뒤구분 쉽게 할 수 있게 표시해놓았습니다.

1종 건널목에서 'A' 라고 쓴 부분(빔)의 빨간불은 점멸하지 않기 때문에 점멸등 색 (255,0,0)이 아닌 일반 빨간색 (252,0,)으로 칠했습니다. 

경보기(기둥)의 점멸등은 번갈아가면서 점멸하는데 이건 구현이 어떻게 될지 몰라 일단 그대로 두었습니다.

**Comment by telk5093** [comment]
건널목은 2종으로 반영되었습니다. 이슈를 닫겠습니다.
