### ISSUE TITLE
혀기 7형 증기기관차, 협궤 객차·동차

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#205]
![협궤 객차, 동차, 증기기관차 1차 완성](https://user-images.githubusercontent.com/75788864/115966899-a0edfd80-a56a-11eb-814a-23d06dbef37b.png)

혀기 7형 증기기관차
https://namu.wiki/w/%ED%98%80%EA%B8%B0%ED%98%95%20%EC%A6%9D%EA%B8%B0%EA%B8%B0%EA%B4%80%EC%B0%A8#s-2.7 
도입시기:1952년
최고속도:50km/h (추정)
차중:42.95톤 https://blog.daum.net/kieury/11301398

원래는 11형까지 있지만, 실제로 구 수인선을 달렸고 인천 소래포구에 전시되어 있는 혀기 7형 증기기관차를 모델로 했습니다.

**탄수차 화차 포함 길이 8 로 하면 되겠습니다. 각자의 길이는 어떻게 하시든 상관 없고 총합만 8이 되면 됩니다. 탄수차와 화차는 어처피 늘 같이 붙어다니니 각각의 길이는 6과 2가 되든 5와 3이 되든 상관 없습니다.**

협궤 객차
https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=133498&s_type=search_subject_memo&s_keyword=%EB%B9%84%EB%91%98%EA%B8%B0%ED%98%B8&page=1
차중:14톤
정원:50명
도입시기:1965년이라 위의 증기기관차와 맞지 않는데, 이전 객차는 자료가 없어서 그냥 증기기관차와 동일하게 하면 좋겠습니다.

비둘기호 객차와 똑같이 두개가 랜덤 등장으로 해주시면 되겠습니다. 추천 길이는 6입니다.

협궤 동차
https://ko.wikipedia.org/wiki/%ED%98%91%EA%B6%A4_%EB%94%94%EC%A0%A4_%EC%95%A1%EC%95%95_%EB%8F%99%EC%B0%A8
차중:21톤
정원:90명(45석, 롱시트)
도입시기:1965년(협궤 객차와 동시에 들여옴)
최고속도:55km/h (위 링크 일본어판 출처)
힘:149.1kw, 200마력

비둘기호 동차처럼 앞뒤가 같습니다. 같이 들여온 객차를 사이에 끼워넣거나 뒤에 달고 다녔습니다.

**Comment by telk5093** [comment]
혀기 7형과 협궤 객차는 a7d7714 에서 반영되었습니다. 협궤 동차만 추후 구현하겠습니다.

**Comment by Gamunbi** [comment]
![협궤 객차, 동차 1차 완성](https://user-images.githubusercontent.com/75788864/116776882-016ac680-aaa6-11eb-9d7a-4e9c0b721ccd.png)

https://www.news1.kr/articles/?3035484
http://epoque.egloos.com/m/4164456

누락된 도색 다 넣어서 올립니다.

**Comment by Gamunbi** [comment]
협궤 객차 동차 아직 추가하지 말아주세요. 살짝 도색 수정할 게 있습니다.

**Comment by Gamunbi** [comment]
![협궤 객차, 동차 1차 완성](https://user-images.githubusercontent.com/75788864/116820025-de2b3e80-abad-11eb-9fc2-de303fd79b06.png)

달라진 부분은 초록색 차량들의 지붕색입니다. 텔크님께서 보시고 이전 것과 이번 것 중 색이 튀어 보이지 않고 보기 편한 걸 정해서  써주세요. 저는 선택장애가 와서 뭐가 더 나은지 정하지 못하겠습니다.
