### ISSUE TITLE
KTX-이음의 수송량이 2배로 적용되는 현상

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#206]
화물 수송량 매개변수 ``x2``로 적용시:
![image](https://user-images.githubusercontent.com/10726524/115981223-476aea80-a5cd-11eb-96b5-e2456deac0f0.png)

아울로, 구매 목록 상 수송량과 실제 수송량을 엇비슷하게 맞출 필요도 있음

**Comment by kudzufatsia** [comment]
반대로 ITX새마을은 수송량이 많이 적더라고요.

**Comment by telk5093** [comment]
> 반대로 ITX새마을은 수송량이 많이 적더라고요.

화물 수송량의 기본 매개변숫값인 x1/2 수준에서 22명이 뜨는 게 맞습니다.
혹시나 해서 확인해봤습니다만 문제가 없었습니다.

**Comment by kudzufatsia** [comment]
> > 반대로 ITX새마을은 수송량이 많이 적더라고요.
> 
> 화물 수송량의 기본 매개변숫값인 x1/2 수준에서 22명이 뜨는 게 맞습니다.
> 혹시나 해서 확인해봤습니다만 문제가 없었습니다.

앗 그런가요?
ITX새마을 전동차 조합할 때 승객수송 객차 4대를 넣어보는데 수송총량이 264명이더라고요.. (현실에서 210000호대 1편성 6량 수송량은 376명)
참고로 저는 매개변수 x1 값을 적용하고 있습니다.

**Comment by telk5093** [comment]
> > > 반대로 ITX새마을은 수송량이 많이 적더라고요.
> > 
> > 
> > 화물 수송량의 기본 매개변숫값인 x1/2 수준에서 22명이 뜨는 게 맞습니다.
> > 혹시나 해서 확인해봤습니다만 문제가 없었습니다.
> 
> 앗 그런가요?
> ITX새마을 전동차 조합할 때 승객수송 객차 4대를 넣어보는데 수송총량이 264명이더라고요.. (현실에서 210000호대 1편성 6량 수송량은 376명)
> 참고로 저는 매개변수 x1 값을 적용하고 있습니다.

아마 실 수송량을 일일이 적용할 수 없어서 적당히 평균치를 냈을 겁니다.
