### ISSUE TITLE
유개화차 리뉴얼

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#207]
#138  대체해서 이글로 올리겠습니다.
![유개화차](https://user-images.githubusercontent.com/81477455/115985497-13042800-a5e7-11eb-94ca-7a4560ccf72a.png)
저번에 찍었던 유개화차를 개조해서 찍었는데 이상하게 되는바람에 제가 직접 찍었어 작업했습니다.
이번에 찍게되면서 다양한시도를 해봤습니다.
그리고 4방향으로 되어있는거 곡물차이긴한데 여기밑에 있는 화차 설명관련영상으로 대체하겠습니다.
유개화차전용 가축차도 있다고하는데 이거 정보가 없어서 안넣었습니다.

화차 설명관련영상
https://www.youtube.com/watch?v=pe3qRgGusHs

구형,일반형,전개형 유개화차링크
https://www.youtube.com/watch?v=pe3qRgGusHs

**Comment by kiwitreekor** [comment]
유개차도 15m 길이가 아닐까 생각되는데 거기에 맞추는 게 좋지 않을까요?

**Comment by telk5093** [comment]
#138 로 이관합니다.
