### ISSUE TITLE
구매 목록 이미지 개선

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#209]
1. 구매 목록 이미지의 정렬 위치 결정: **왼쪽**
 2. 각 기관차의 작동 방식(eg. 증기, 디젤, 전기), 지하철 아이콘을 앞에 표시: **예**

 * **아이콘**
   * [x] 증기: ![image](https://user-images.githubusercontent.com/10726524/120351611-fcb26000-c33a-11eb-9ab9-db2f36eb77e0.png)
   * [x] 디젤: ![image](https://user-images.githubusercontent.com/10726524/120351586-f7551580-c33a-11eb-8453-5ab0e0b8d17d.png)
   * [x] 전기: ![image](https://user-images.githubusercontent.com/10726524/120215029-3702fb00-c270-11eb-8814-9486a0e57959.png)
   * [x] 지하철: ![image](https://user-images.githubusercontent.com/10726524/120322295-370e0400-c31f-11eb-9640-a54acb74d0ec.png)

 * **적용 기준:**
   * 모든 구매 이미지는 반드시 70×15px 크기로 고정하고 좌측으로 정렬
   * 아이콘은 좌측 2px, 아래 0px, 우측 2px의 여백을 둠 (아래 여백은 향후 1px로 변동될 수도 있음)
   * 기존 구매 이미지를 아이콘의 여백을 준수한 상태에서 그대로 왼쪽으로 이동하고 남는 오른쪽 여백은 파란 배경으로 처리

 * **샘플**(``KTX2N``):
  ![image](https://user-images.githubusercontent.com/10726524/120215355-952fde00-c270-11eb-9e81-4bdb9ec590ca.png)

 * **적용 예시:**
 ![image](https://user-images.githubusercontent.com/10726524/120216517-18056880-c272-11eb-905c-a67347144c47.png)

**Comment by telk5093** [comment]
**[의견 수렴용 댓글]**
1. 구매 목록 이미지의 정렬 위치
``왼쪽`` 정렬을 선호하면 👍 으로, ``오른쪽`` 정렬을 선호하면 👎 으로 반응해주세요.

**Comment by telk5093** [comment]
**[의견 수렴용 댓글]**
2. 아이콘 표시
아이콘 표시를 원하면 👍 으로, 원하지 않으면 👎 으로 반응해주세요.

**Comment by opentrain** [comment]
음 혹시 한국열차세트GRF에도 다른나라GRF처럼 국기넣는거 어떤가요?

**Comment by telk5093** [comment]
[의견 수렴용 댓글]
3. 국기 표시
국기 표시를 원하면 👍 으로, 원하지 않으면 👎 으로 반응해주세요.

**Comment by Gamunbi** [comment]
작동방식, 지하철 표식은 2cc train 에서도 저 아이콘 그대로 쓰고 있으니, 아이콘은 문의해보고 가능하면 그대로 썼으면 좋겠습니다.

**Comment by opentrain** [comment]
음혹시 지하철(전철)아이콘에 노선호선에 따라 색깔반영도 나쁜지 않을거같습니다.

**Comment by Gamunbi** [comment]
> 
> 
> 음혹시 지하철(전철)아이콘에 노선호선에 따라 색깔반영도 나쁜지 않을거같습니다.

같은 노선 지하철들은 이미 한 종류로 합쳐져 개조만으로 구분하고 있기 때문에(목록이 다르면 곧 다른 전철임을 알 수 있음), 굳이 색깔로 나누는 의미는 없을 것 같습니다.

**Comment by telk5093** [comment]
> 작동방식, 지하철 표식은 2cc train 에서도 저 아이콘 그대로 쓰고 있으니, 아이콘은 문의해보고 가능하면 그대로 썼으면 좋겠습니다.

[2ccts의 라이선스](https://dev.openttdcoop.org/projects/2ccts/repository/entry/docs/license.txt)가 GPL v2라서 해당 이미지를 가져다가 쓰면 라이선스 문제가 발생할 수도 있습니다. 안타깝지만 불가능할 것 같습니다.

**Comment by telk5093** [comment]
전기 기관차 앞에 붙을 아이콘 이미지 샘플을 만들어보았습니다: ![image](https://user-images.githubusercontent.com/10726524/120215029-3702fb00-c270-11eb-8814-9486a0e57959.png)

 * 모든 구매 이미지는 반드시 70×15px 크기로 고정하고 좌측으로 정렬
 * 아이콘은 좌측 2px, 아래 0px, 우측 2px의 여백을 둠 (아래 여백은 향후 1px로 변동될 수도 있음)
 * 기존 구매 이미지를 아이콘의 여백을 준수한 상태에서 그대로 왼쪽으로 이동하고 남는 오른쪽 여백은 파란 배경으로 처리

샘플(``KTX2N``):
![image](https://user-images.githubusercontent.com/10726524/120215355-952fde00-c270-11eb-9e81-4bdb9ec590ca.png)


적용 예시:
![image](https://user-images.githubusercontent.com/10726524/120214992-2a7ea280-c270-11eb-89b8-4fc524853e6b.png)

**Comment by Gamunbi** [comment]
![로고](https://user-images.githubusercontent.com/75788864/120323422-6d984e80-c320-11eb-95aa-cae59beedaf6.png)
1안 2안 (개인적으로는 1안이 더 나은 듯)

**Comment by Gamunbi** [comment]
![로고](https://user-images.githubusercontent.com/75788864/120325062-3cb91900-c322-11eb-9e2d-882088c19e86.png)

**Comment by ChuoSpecialRapid201** [comment]
![gas-station](https://user-images.githubusercontent.com/81485156/120328493-d209dc80-c325-11eb-8a90-edf0e858879c.png)

디젤

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/120351486-e4dadc00-c33a-11eb-881a-3f6e435de57f.png)

Almost done

**Comment by telk5093** [comment]
091ef9f4da1ad0c262079bc70fccfdfbfb845b39 및 27c04c9f8a5ebe03035ad55a6f1d89cce866f5d4 에서 반영됨
