### ISSUE TITLE
미카 3형, 마터 2형, 파시 5형 증기기관차 스프라이트 수정

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#210]
![증기기관차 미카 3형 3차 완성](https://user-images.githubusercontent.com/75788864/116278608-9d07e880-a7c1-11eb-94ee-4a743852ec48.png)
![증기기관차 마터 2형 3차 완성](https://user-images.githubusercontent.com/75788864/116278593-9aa58e80-a7c1-11eb-9595-1dce965e2fca.png)
![증기기관차 파시 5형 5차 완성](https://user-images.githubusercontent.com/75788864/116278624-a2653300-a7c1-11eb-8dac-d58d54cd1c26.png)

이번엔 정말로 완벽하게 만들었음을 확신합니다..;; 이젠 1픽셀 정도의 간단한 수정이면 몰라도 스프라이트 사이즈가 아예 달라지는 일은 없을 것입니다. 

중련했을 때도 어색해 보이지 않도록 4의 배수로 규격을 맞추었습니다.

미카 3형 추천 길이:11(44픽셀)
마터 2형 추천 길이:12(48픽셀)
파시 5형 추천 길이:12(48픽셀)

**Comment by opentrain** [comment]
볼수록 퀄리티가 ㅎㄷㄷ 하네요
