### ISSUE TITLE
의정부 경전철, 에코비 스프라이트 수정

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#211]
![경전철 의정부 2차 완성](https://user-images.githubusercontent.com/75788864/116359270-9452f900-a839-11eb-990b-6e58fd2cd058.png)
의정부 경전철:살짝 짧던 길이를 8(32픽셀)로 늘렸습니다. 

게임에서 구현된 것보다 실제 폭이 훨씬 작아(일반 기차 폭이 대략 3.2미터, 게임에선 8픽셀인데 의정부 경전철은 2미터지만 홀수인 5픽셀로 할 수 없어서 6픽셀로 했었음) 게임 속 모습이 짧아보였기 때문입니다. 

![자기부상철도 에코비 2차 완성](https://user-images.githubusercontent.com/75788864/116359414-bc425c80-a839-11eb-851e-72c8ddb445b2.png)
에코비:길이를 6(28픽셀)으로 조정했습니다.

에코비는 실제 길이 12미터로 매우 짧아야 하지만 폭 또한 3미터로 작아서, 게임에서는 길이만 약간 줄였습니다. 현실에서의 작달막한 느낌이 잘 나올겁니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/116376393-2dd6d680-a84b-11eb-8c83-a0dc2f8b25be.png)

의정부경전철 후두부의 그래픽 스프라이트가 전두부와 순서만 바꾼 거라 불필요하므로 잘라냅니다.
(+ 스프라이트 사이의 간격 조정)

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/116383586-f0297c00-a851-11eb-869a-a56987234ee2.png)

간격 및 위치 조정
