### ISSUE TITLE
경북순환열차 천장명암오류+스프라이트 수정

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#212]
경북순환(구도색)
![대한민국 철도청의 게임 (2123-05-03)](https://user-images.githubusercontent.com/81477455/116370033-f7965880-a844-11eb-833b-b8a054164d0d.png)
↘ 주황색 동력차량 천장쪽이 안맞네요 
아그리고 객차순서가 바꿔져있습니다. 초록,파란,분홍,주황이여야하는데 
초록,분홍,파랑,주황 이렇게되어있습니다.

![대한민국 철도청의 게임 (2123-05-07)](https://user-images.githubusercontent.com/81477455/116370081-01b85700-a845-11eb-8d37-f8131ceafc97.png)
↙이방향 천장

![대한민국 철도청의 게임 (2123-05-12)](https://user-images.githubusercontent.com/81477455/116370150-14329080-a845-11eb-8ae5-909516f2edd8.png)
↖이방향 천장

![대한민국 철도청의 게임 (2123-05-17)](https://user-images.githubusercontent.com/81477455/116370303-36c4a980-a845-11eb-86a9-2285fa755b09.png)
↙이방향 천장

경북순환(신도색)
![대한민국 철도청의 게임 (2123-05-29)](https://user-images.githubusercontent.com/81477455/116370485-6a073880-a845-11eb-9470-e5476888a741.png)
↖↘ 동력차량끝쪽이 적용안돼있는부분

![대한민국 철도청의 게임 (2123-05-31)](https://user-images.githubusercontent.com/81477455/116370514-71c6dd00-a845-11eb-9487-1192f8fe62e0.png)
↙ 색이 반대쪽천장하고 같은색깔사용문제

![대한민국 철도청의 게임 (2123-06-05)](https://user-images.githubusercontent.com/81477455/116370552-7ab7ae80-a845-11eb-8650-c15a4ff00ec9.png)
↖천장하고 따로문제

![대한민국 철도청의 게임 (2123-06-11)](https://user-images.githubusercontent.com/81477455/116370599-830fe980-a845-11eb-9e7b-da21f8e77fc9.png)
↙이방향 반대쪽차량문제

(경북순환 구,신도색) 스프라이트 개선
1안
![경북순환(구도색,신도색)](https://user-images.githubusercontent.com/81477455/116381312-bd7e8400-a84f-11eb-9376-f33390011166.png)

2안
![경북순환(구도색,신도색)수정판](https://user-images.githubusercontent.com/81477455/116381335-c53e2880-a84f-11eb-9c64-4ce9162b0882.png)

명암이 각자 따로 노는거 저의 고증오류때문에 이렇게 되어버렸습니다.
늘 코딩 담당해주시는 텔크님한테 죄송합니다.
천장명암문제를 개선하고자 저번에 명암 지적하셨던부분도 개선해버렸습니다.
경북순환 1,2안중 마음에 드시는거로 사용하면될듯합니다.
아하 과거에는 제가 무슨생각으로 저거 다 넣겠다한거지..... 무리한짓을 해서 저렇게되어버렸네요

구도색(2009~2013)
(초록-파랑-분홍-주황)
(주황-분홍-파랑-초록)

신도색(2013~2016)
(초록-보라-초록-보라)
(보라-초록-보라-초록)

**Comment by telk5093** [comment]
@opentrain 하나의 이슈에 여러 개의 안건을 넣지 말아주세요.
