### ISSUE TITLE
협궤 유개화차

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#215]
![협궤 화차 유개화차 1차 완성](https://user-images.githubusercontent.com/75788864/116775284-3e7e8b00-aa9d-11eb-968d-9aa4629c1474.png)

위키백과, 문화재청 국가문화유산 포털, 실제 화차가 전시되어 있는 의왕 철도박물관 그 아무데서도 무게, 적재량이 나와있질 않습니다..;; 세부수치는 약간의 상상력을 발휘해야 할 듯 합니다. 제 생각엔 표준궤 화차의 한 1/3 정도면 될 것 같습니다.

무개화차도 우리나라에서 쓰였고 실물도 있기 때문에 만들 수 있는데, 문제는 탱크차와 평판화차입니다. 얘네는 우리나라에 쓰였던 기록과 사진자료가 없습니다. 만들면 안 쓰였던 걸 구현해낸거라 문제가 되고, 안 만들자니 게임속에서 등장하는 화물을 전부 커버할 수 없어서 문제고, 고민입니다.

**Comment by Gamunbi** [comment]
길이는 4입니다.

**Comment by Gamunbi** [comment]
![협궤 화차 유개화차 1차 완성](https://user-images.githubusercontent.com/75788864/116775652-21e35280-aa9f-11eb-8a7a-915767d6ce54.png)

![협궤 객차 03](https://user-images.githubusercontent.com/75788864/116775668-3e7f8a80-aa9f-11eb-9799-7a8302213504.jpg)


유개화차 수정 가능하신지요? 아무래도 높이를 한 칸 낮추는 게 더 좋다고 생각합니다. 사진을 보니 객차보다 탄수차 높이에 더 가까운 것 같아서요.

**Comment by Gamunbi** [comment]
그냥 맨 처음 스프라이트를 써주세요. 높이가 약간 낮은 무개화차가 따로 있었습니다..;;

**Comment by opentrain** [comment]
![구형유개화차(협궤)](https://user-images.githubusercontent.com/81477455/118390777-dd91ae00-b66b-11eb-9154-c2d023866451.png)
컬러로 복원한 유개화차 협궤입니다.
