### ISSUE TITLE
서울교통공사 7호선 5차분

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#216]
![SMETRO_7K_5TH](https://user-images.githubusercontent.com/81477455/116520356-94bcc400-a90d-11eb-88c5-a6dc024c96b0.png)

일단 이번에 5호선도 이차량으로 도입된거로 알고있습니다.
7호선 열차 5차분 열차도 5호선하고 같은차량으로 도입된다고하네요
1차분대체 목적으로 반입예정이라고 합니다.
일단 올려놓겠습니다.

5,7호선 336량:https://gall.dcinside.com/board/view/?id=train&no=1108810

목업용:https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=52468
2022.4.18일 기준으로 운영시작함
https://namu.wiki/w/%EC%88%98%EB%8F%84%EA%B6%8C%20%EC%A0%84%EC%B2%A0%207%ED%98%B8%EC%84%A0%207000%ED%98%B8%EB%8C%80%20%EC%A0%84%EB%8F%99%EC%B0%A8?from=%EC%84%9C%EC%9A%B8%20%EC%A7%80%ED%95%98%EC%B2%A0%207%ED%98%B8%EC%84%A0%207000%ED%98%B8%EB%8C%80%20%EC%A0%84%EB%8F%99%EC%B0%A8#s-4.5

**Comment by EightonEight** [comment]
추가 Ref: 
<https://youtu.be/x2IGrCAMuDw?t=75>
여기에서 5, 7호선 및 8호선(별내선 54량) 렌더링 확인이 가능합니다.

**Comment by opentrain** [comment]
@EightonEight 8호선 제보도 감사합니다.^^
