### ISSUE TITLE
협궤 무개화차

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#217]
![협궤 화차 무개화차 1차 완성](https://user-images.githubusercontent.com/75788864/116775237-eb0c3d00-aa9c-11eb-9dd7-96abdbe11680.png)

한철셋 표준궤 무개화차에 있는 것들은 모두 만들었습니다. 빠진 게 있다면 알려주세요. 길이는 4입니다.

**Comment by opentrain** [comment]
협궤전용 화물열차들이 많이 존재했었는지요?

**Comment by Gamunbi** [comment]
> 
> 
> 협궤전용 화물열차들이 많이 존재했었는지요?

![협궤 객차 03](https://user-images.githubusercontent.com/75788864/116775348-8ac9cb00-aa9d-11eb-9a2f-562510ad15d4.jpg)

일제강점기 때는 소금을 공출하는 화물열차가 많이 있었는데, 해방 뒤에는 화물열차의 비중이 거의 사라졌습니다.
