### ISSUE TITLE
비둘기호 갈색도색+역삼각 마크 진한초록추가

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#219]
![비둘기호 갈색도색+역삼각마크 초록](https://user-images.githubusercontent.com/81477455/116809955-f4b8a200-ab7b-11eb-8897-063772e28a43.png)

@Gamunbi 님의 비둘기호 도색 추가했습니다.
저번에 논란이 있었던 비둘기호 갈색도색 이번에 확실한 자료를 가지고 왔습니다.
그리고 역삼각마크도색 객차에 초록색깔도 추가했습니다.

![image](https://user-images.githubusercontent.com/81477455/116809989-2a5d8b00-ab7c-11eb-9317-64eedc074b4b.png)

밑에 링크를 위에사진하고 다른사진입니다.
https://blog.naver.com/bann1280/222186462264 우연히 돌아다니다가 찾았습니다.(갈색)

![image](https://user-images.githubusercontent.com/81477455/116810099-ace64a80-ab7c-11eb-897e-2007183b01ae.png)
애는 밑에쪽에 초록색이 있었어 넣어봤습니다.

**Comment by Gamunbi** [comment]
저는 저 초록줄, 흰 마크 이상해보여서 빼버렸는데 괜찮으신 분도 있나보군요.

**Comment by opentrain** [comment]
@Gamunbi 저도 비둘기호 누락된 도색 찾다보니 저기밑에 역삼각 초록도색도 있어가지고 넣어봤어요~~

**Comment by Gamunbi** [comment]
기존 비둘기호 객차들과 이질감이 있어서 제가 살짝 수정해서 다시 올리겠습니다. 

그리고 초록줄은 개인적으로 저렇게 출입문 자리에서 끊는 것보다 이어버리는 게 더 나을 것 같은데 어떠신지요?

**Comment by opentrain** [comment]
@Gamunbi 아 초록줄을 수정해서 해보겠습니다.
이거 저는 도색개조한거 말고없어서 
원작자분께서 마음대로 하셔도 저 상관없습니다.

**Comment by Gamunbi** [comment]
![객차 비둘기호 5차 완성](https://user-images.githubusercontent.com/75788864/116819293-7c1d0a00-abaa-11eb-9c4a-b0c5fc715947.png)

개조목록은 그림 가장 오른쪽에 있는 것대로 바꿔주셨으면 좋겠습니다.

90년대만 '객차' 가 아니라 '도색'인 것은 잘못된 것이 아닙니다. 80년대 객차까지는 통일호에게서 물려받은 객차도 몇몇 있기 때문에 '객차' 로 썼습니다. 안 어울리신다면 '도색' 이나 '객차' 둘 중 하나로 통일하셔도 상관없습니다.

기존 비둘기호가 그런 것처럼 하나로 묶인 네 객차들은 랜덤 등장입니다.

**Comment by opentrain** [comment]
역삼각마크 도색도 초록색있는거하고 없는거도 있으면 좋을거같에요

**Comment by Gamunbi** [comment]
그럼 만들겠습니다. 안그래도 맨 처음 동차가 도입됐을 때인 60년대 초록주황도색도 넣는 중입니다.

**Comment by opentrain** [comment]
#148 안그래도 여기에 제가 그도색에 대해 정보는 몰라서 안넣었고 
비둘기호 역삼각마크도색하고,통일호,무궁화호 도색만 있습니다.
초록주황도색을 제가 무슨색을 사용해야될지 몰라서 제가 건들지않았습니다.
듣기로는 코코아도색이 있다고하는데 이거 찾아봐야알수있을거같습니다.

**Comment by Gamunbi** [comment]
![객차 도색](https://user-images.githubusercontent.com/75788864/116852274-fa22f480-ac2e-11eb-9dfe-48797829a72c.png)

코코아 도색은 여기 있는 거 말씀하시는 거 같은데 저도 비둘기호 객차 한창 만들 때 저 정보를 보기는 했습니다. 하지만 사진자료찾지 못해 만들지 않았습니다.

**Comment by Gamunbi** [comment]
그리고 저 초록줄 도색에 대해서 다시 생각해봤는데, 초록줄이 없는 것과 있는 것 둘 다 만드는 건 좀 과한 것 같습니다. 같은 시기에 쓰였던 도색을 굳이 둘로 나눌 이유는 없어보입니다. 

제 생각에는 둘 중 하나만 쓰는 게 좋을 것 같습니다. 저는 초록줄 있는 쪽이 더 좋을 것 같습니다.

**Comment by opentrain** [comment]
아 저는 상관없습니다.~~^^

**Comment by Gamunbi** [comment]
![객차 비둘기호 5차 완성](https://user-images.githubusercontent.com/75788864/116855303-20975e80-ac34-11eb-834c-6b5a1d5ecfbf.png)

비둘기호 객차 최종버전입니다. 

달라진 점:갈색도색 추가, 중요성이 부족하다고 생각해 뺐던 DC동차 부수객차(초록주황도색) 추가, 비둘기호 마지막 노랑초록 도색에 초록줄 추가

**개조 이름은 가장 오른쪽에 쓰여진 걸 토대로 바꿔주셨으면 좋겠습니다(통일호와 통일성 맞추기 위함)**

레퍼런스
갈색 도색
https://m.blog.daum.net/pzkpfw3485/2247997

동차 부수객차 초록주황도색
https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=133498&search_pos=-133067&s_type=search_subject_memo&s_keyword=%EB%B9%84%EB%91%98%EA%B8%B0%ED%98%B8&page=1 
https://namu.wiki/w/DC%20%EB%94%94%EC%A0%A4%EB%8F%99%EC%B0%A8?from=RC%EB%8F%99%EC%B0%A8#s-3.4

초록줄
https://m.blog.naver.com/PostView.nhn?blogId=lovtrout&logNo=80012895018&proxyReferer=https:%2F%2Fwww.google.com%2F

초록주황도색 DC동차는 다른 이슈로 바로 추가하겠습니다.

**Comment by opentrain** [comment]
![image](https://user-images.githubusercontent.com/81477455/118501073-545da280-b763-11eb-9299-2d51773506d2.png)
비둘기호 전환식의자 객차 버전입니다.
해당 이슈와 관련해서 여기에 다시올려봅니다.
또다른 조사에 의하면 노란+초록 도색이 총3가지네요 ㄷㄷ
초록줄 추가되기전에는 고정의자 객차라고하네요 초록줄없는버전
그이후로 초록줄 추가 및 녹색버전은 전부 전환식의자 객차라고 합니다.

![비둘기호 전환식의자 객차 녹색버전](https://user-images.githubusercontent.com/81477455/118501235-79eaac00-b763-11eb-8d30-3439897759a2.png)

**Comment by telk5093** [comment]
> 비둘기호 전환식의자 객차 버전입니다.
> 해당 이슈와 관련해서 여기에 다시올려봅니다.
> 또다른 조사에 의하면 노란+초록 도색이 총3가지네요 ㄷㄷ
> 초록줄 추가되기전에는 고정의자 객차라고하네요 초록줄없는버전
> 그이후로 초록줄 추가 및 녹색버전은 전부 전환식의자 객차라고 합니다.

게임 내에서 눈에 띌 정도로 큰 변화가 없습니다.
게임적 허용으로 넣지 않겠습니다.

**Comment by opentrain** [comment]
![BIDULGI 천장회색객차 갈색도색](https://user-images.githubusercontent.com/81477455/120104776-1b74f300-c191-11eb-920d-f2dbf3b4dc2d.png)

레퍼런스
![image](https://user-images.githubusercontent.com/81477455/120104708-cdf88600-c190-11eb-92ee-3d4883c9f544.png)

이번 도색 버전은 천장부분이 회색으로 되어있는부분객차도 있네요
이거 올려놓고 텔크님의 결정에 따르겠습니다.

**Comment by telk5093** [comment]
천장만 회색인 걸 별도로 추가할 생각이 없습니다.
