### ISSUE TITLE
무궁화호 침대차 도색추가

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#220]
![무궁화호 침대차 도색](https://user-images.githubusercontent.com/81477455/116844597-795bfc80-ac1e-11eb-98e4-0a48b0e8da8c.png)

![image](https://user-images.githubusercontent.com/81477455/116814888-e1b2cb80-ab95-11eb-9e97-a4223db03eb8.png)
초기형 무궁화호 침대차

초기형 무궁화호 침대차도 있었다고 해서 넣었습니다.
일단 제가 아는선에선에서 추가를 해봤습니다.
단 맨밑에 있는 신도색같은경우 존재했는지 안존재했는지 다른분의 도움이 필요합니다.

https://www.google.co.kr/search?q=%EA%B5%AC%ED%98%95+%EB%AC%B4%EA%B6%81%ED%99%94+%EC%B9%A8%EB%8C%80%EC%B0%A8&tbm=isch&ved=2ahUKEwiVvP7xh6vwAhVE0pQKHWz7A_cQ2-cCegQIABAA&oq=%EA%B5%AC%ED%98%95+%EB%AC%B4%EA%B6%81%ED%99%94+%EC%B9%A8%EB%8C%80%EC%B0%A8&gs_lcp=CgNpbWcQAzoCCABQ0QZYpBBg2xFoAXAAeAGAAXqIAf0GkgEDMC44mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=fqOOYJWFOcSk0wTs9o-4Dw&bih=657&biw=1366#imgrc=UxVFQukLP_LBrM

**Comment by EightonEight** [comment]
해당 차량은 신도색으로 변경되지 않고 폐차된 것으로 보입니다.
> <https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=35888> _본문 중_
> 2001년에 디자인리미트에서 신형 무궁화 침대차 5량(10212~10216호) 도입되면서 77년산이 퇴역하기 시작했었어.
> 2002년 08월 19일에 청량리-강릉 간 침대차 운행이 제외되면서 77년산이 전량 퇴역하고,
> 2004년 02월 09일에 81년산이 전량 퇴역하면서 서울-목포 간 침대차 운행이 제외되었지.

**Comment by opentrain** [comment]
@EightonEight 도움주셔서 감사를 드립니다. 덕분에 침대차 해결했어요^^
빨간색 침대차도 찾고있었는데 감사합니다. ㅎㅎ
