### ISSUE TITLE
승객용 객차의 우편 수송 기능 추가

### ISSUE THREAD

**Issue by BrightEne** [KoreanGRF/KoreanTrainSet#222]
2.0 버전 이전에는 승객용 객차나 동차들이 우편수송이 가능하게 개조할수 있던거 같은데
2.0 버전으로 올라오고나서부터는 승객용 객차에는 승객만 수송할 수 있는걸로 바뀐거 같네요?
혹시 이전처럼 승객용 객차나 동차에 우편 수송이 가능하게 바꿔주실수 없는지 여쭤봅니다.

**Comment by telk5093** [comment]
우편차가 있기 때문에 의도적으로 제외했습니다.
애당초 승객 수송 차량이 우편을 싣는 게 말이 안되기도 하고요.
