### ISSUE TITLE
G-TRAIN(서해금빛열차) 객차 및 디젤기관차 수정

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#223]
![G-TRAIN 디젤기관차 리뉴얼](https://user-images.githubusercontent.com/81477455/116990206-c074eb00-ad0d-11eb-82da-38466bf2de90.png)

![image](https://user-images.githubusercontent.com/81477455/116990065-93c0d380-ad0d-11eb-954c-09e4ae69af1b.png)
디젤기관차같은경우 반때쪽에 다른노란색이 반영되어있어가지고 이번에 넣었습니다.
이거 이제봤네요 죄송합니다.

![G-train](https://user-images.githubusercontent.com/81477455/116990174-b8b54680-ad0d-11eb-844c-fcd4757efdaa.png)
#174 무궁화호 객차 8방향화에 맟춰서 G-TRIAN객차도 4방향에서 8방향으로 수정했습니다.
↓↙←↘ 이방향추가
1호차를 천장손점 많이 봤습니다. 2~4호차하고  도색어울리게 통일했습니다.
지금 한열세에 있는 관광열차도 8방향요청있으면 하겠습니다.

늘 불편을 드려 대단히 죄송할따름이네요 ㅠㅠ

**Comment by telk5093** [comment]
기관차는 객차와 색감이 달라 반영하지 않습니다.
객차 8방향은 명암이 잘못되어 있는데, 제가 수정해서 f827a25 에서 반영되었습니다.
