### ISSUE TITLE
[Add] Caboose (차장차)

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#224]
![CABOOSE](https://user-images.githubusercontent.com/77984422/117018646-a77d3180-ad2f-11eb-97e5-5b864c41367a.png)
※ 소화물차(수화물차)에서 개조된 차장차만 제작하였습니다.
※ @kimgas 님의 소화물차 스프라이트(#126)를 수정한 것입니다.

**Vehicle specification**
| Name                             | Code                | Speed             | Speed (designed) | Capacity | Power | Weight     | Introduction |
|---------------------------|-----------------|-----------------|---------------------|----------|---------|------------|---------------|
| Caboose                        | ``CABOOSE``     |  120 km/h       | 120 km/h              |               |             | **26t**     | 2006             |

**References**
* <https://blog.naver.com/izoa0486/221395936120>
![image](https://user-images.githubusercontent.com/77984422/117025280-bc5cc380-ad35-11eb-9c82-0561a0e2feb2.png)

* <https://blog.naver.com/990104ms/221195386154>
![image](https://user-images.githubusercontent.com/77984422/117025581-ffb73200-ad35-11eb-8c9d-bc1442fcd1e2.png)

* <https://www.yna.co.kr/view/AKR20110517199400063>
>소화물 화차는 신문, 잡지 등 부피가 작고 가벼운 화물들을 운송하기 위해 제작된 철도 화물차량으로, 지난 2006년 5월 철도 소화물 운송사업이 폐지된 이후 활용처를 찾지 못하고 있다.
>도입 당시 한 량에 8천여만원을 웃돌던 소화물 화차들은 아직도 잔여 내구연한이 17∼18년씩 남아있다. 코레일은 1998(71량)과 1999년(37량)에 이들 소화물 화차를 대부분 구매했다.

**Example**
![예상도](https://user-images.githubusercontent.com/77984422/117026329-a7346480-ad36-11eb-9aab-8f13441af787.png)

**Comment by telk5093** [comment]
@EightonEight Introduction 이 2006년인 게 아니라 Retired year가 2006년인 게 아닌지요?

**Comment by EightonEight** [comment]
@telk5093 2006년에 소화물운송사업이 중단되어 소화물차가 남아돌게 되자 일부를 침식차, 차장차 등으로 개조했다고 합니다. 다만 정확한 차장차 개조시기는 찾을 수가 없어 **소화물차가 운행중단된 2006년**을 도입년도로 한 것입니다.

* https://www.yna.co.kr/view/AKR20060403003700063
> 한국철도공사(사장 이철)는 적자운영이 계속돼온 철도소화물 운송사업을 5월부터 폐지한다고 3일 밝혔다.

* https://www.yna.co.kr/view/AKR20110517199400063 
> 코레일에 따르면 현재 보유하고 있는 소화물 화차는 164량으로 이 가운데 56량은 특수화물 운반 승무원 등의 침식(寢食)차 등으로 쓰고 있지만 나머지 108량(66%)은 사용이 중단된 상태이다.

* https://blog.naver.com/deainitea2018/222296522773

* https://blog.naver.com/krriblog/221128543494

**Comment by EightonEight** [comment]
등장년도가 너무 늦는 것 같다면, 2006년 이전에는 #225 의 구형 차장차 스프라이트가 나오게 하는것도 괜찮은 것 같습니다.

**Comment by EightonEight** [comment]
![CABOOSE](https://user-images.githubusercontent.com/77984422/132080436-be67380f-6f55-463e-a680-c818d4bf00dc.png)
`CABOOSE`
* 소화물차 개조형 차장차 스프라이트를 수정하고, 2축형, 유개차 개조형 차장차 스프라이트를 추가하였습니다.
* 실제 구도색은 주황색에 가깝지만 스프라이트 색상 표현 및 제작자의 한계로 갈색에 가깝게 제작되었습니다..

**Vehicle specification**
| Name                             | Code                | Speed             | Speed (designed) | Capacity | Power         | Weight | Introduction |
|---------------------------|-----------------|-----------------|---------------------|----------|--------------|---------|---------------|
| Caboose (baggage car) | ``CABOOSE``     |  **120 km/h** | **120 km/h**        |               |                    | **26t** | 2006             |
| Caboose (2 axis)            | 〃                     | **120 km/h**  | **120 km/h**         |               |                    | **17t** | **2000**      |
| Caboose (2 axis, old liv) | 〃                     | 〃                   | 〃                           |               |                    | 〃         | 〃                |
| Caboose (boxcar)           | 〃                     | 90 km/h         | 90 km/h                 |               |                    | **22t** | **1992**      |

고증에 맞추면 도입년도(개조년도)는 위와 같으나, 게임적 허용으로 구도색에 한해 1970년대에 등장하도록 만드는 것이 괜찮을 것 같습니다.

**References**
* 2축형 차장차
 <https://blog.naver.com/sggs1116/221404301873>
 <https://blog.naver.com/200044kjg/221337554526>
* 2축형 차장차(구도색)
 <https://blog.naver.com/eros2735/50003658994>
 <https://blog.naver.com/gt36cw/100109165272>
 <https://youtu.be/pe3qRgGusHs?t=585>
* 유개차 개조형 차장차
 <https://blog.naver.com/7174dl/221174569216>
 <https://blog.naver.com/gt36cw/100024453059>
* 제원
한국철도공사 물류본부 물류수송차량팀, 「화차제원」, 2010.10
(사)철도차량기술검정단, 「한국철도차량 100년사」, 1999, 1103p

**Comment by EightonEight** [comment]
### 최종(안)
![CABOOSE](https://user-images.githubusercontent.com/77984422/217930398-3822f083-b1f3-4fd8-9852-d522a65b0526.png)

| Property | Suggest value (소화물차 개조) | (2축) | (유개차 개조)
|--------|--------|--------|--------|
| 이름(Name in Korean) | 소화물차 개조 / 노랑 | 2축 / 노랑 | 유개차 개조 / 주황 |
| 영문 이름(Name in English) | Baggage car type / Yellow | 2-axle type / Yellow | Box car type / Orange |
| 코드(Code) | `CABOOSE_BAGGAGE_YELLOW` | `CABOOSE_2_AXLE_*` | `CABOOSE_BOX_*` |
| 운영 속력(Speed) | **120 km/h** | **120 km/h** | 90 km/h |
| 화물 수송량(Capacity) | - | - | - |
| 출력(Power) | - | - | - |
| 중량(Weight) | **26t** | **17t** | **22t** |
| 도입연도(Introduction year) | **1999** | **2000** | **1992** |

**Comment by EightonEight** [comment]
![CABOOSE](https://github.com/KoreanGRF/KoreanTrainSet/assets/77984422/6d303ebb-3da9-46cc-92d6-df441b5399bb)
* `tmpl_standard` 적용
