### ISSUE TITLE
소화물차 8방향(관광없음) 소화물차만 해당

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#225]
![소화물차](https://user-images.githubusercontent.com/81477455/117123989-b668f000-add2-11eb-8aaa-d3847ca43d0d.png)

@kimgas  이분이 만드신 소화물차를 4방향에서 8방향으로 수정했습니다. 
소화물차 저작권 저분한테 넘겨주세요~~
3번째 있었던 열차도색 자료부족으로 못했습니다.

https://www.youtube.com/watch?v=LHeWwG0LqYQ  주행영상
방향별로 한가지만 나눠져있는게 있었어 8방향으로 반영했습니다.

분홍,주황 차장차
https://search.naver.com/search.naver?sm=tab_hty.top&where=image&query=%EC%B0%A8%EC%9E%A5%EC%B0%A8&oquery=%EC%86%8C%ED%99%94%EB%AC%BC%EC%B0%A8&tqi=h54iJlprvmZssn9PQ08ssssstKC-421856#imgId=image_sas%3Ablog64100181%7C39%7C221174569216_513561289

하늘색소화물차
https://www.google.co.kr/search?q=%EC%86%8C%ED%99%94%EB%AC%BC%EC%97%B4%EC%B0%A8&tbm=isch&ved=2ahUKEwi19uGr4bHwAhXTDd4KHZzPAo8Q2-cCegQIABAA&oq=%EC%86%8C%ED%99%94%EB%AC%BC%EC%97%B4%EC%B0%A8&gs_lcp=CgNpbWcQAzICCABQjg5YiBFgzBJoAHAAeACAAaMBiAH7BJIBAzAuNJgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=mSaSYPXFEdOb-Aacn4v4CA&bih=657&biw=1366#imgrc=N7jsDLL3cFIYEM

**Comment by EightonEight** [comment]
소화물차도 (소화물차에서 개조된) 차장차와 마찬가지로 탑승구 쪽에만 쪽창이 있는것으로 보입니다.
  
<https://cafe.naver.com/hkct/72516>
![image](https://user-images.githubusercontent.com/77984422/117115187-bdd6cc00-adc7-11eb-9eeb-b5988600e2c1.png)

<https://blog.naver.com/rkdnl605/98746399>
![image](https://user-images.githubusercontent.com/77984422/117115970-bf54c400-adc8-11eb-9619-c2950a0ca99a.png)

**Comment by opentrain** [comment]
@EightonEight  늘 항상 제보에 감사합니다.^^

**Comment by EightonEight** [comment]
![117115187-bdd6cc00-adc7-11eb-9eeb-b5988600e2c1](https://user-images.githubusercontent.com/77984422/117127641-4c067e80-add7-11eb-978c-ce249755b07b.png)
제가 말씀드린건 이건데, 혹시 다시한번 확인해주실 수 있나요?

**Comment by opentrain** [comment]
@EightonEight 제가 잘못해석했네요 죄송합니다. 제가 그 부분 다시 수정하겠습니다.

**Comment by EightonEight** [comment]
아니요 괜찮습니다... 다음부턴 더 상세히 알려드릴게요.

**Comment by opentrain** [comment]
![소화물차](https://user-images.githubusercontent.com/81477455/117131203-14e69c00-addc-11eb-9dd8-2c563be86491.png)
일단 수정했습니다.

**Comment by opentrain** [comment]
소화물차 다른 소화물차 추가반영

2021.9.28.다른 소화물차 반영
![소화물차](https://user-images.githubusercontent.com/81477455/135065313-67ca743d-473f-42af-ada0-39beae40ff4e.png)

레퍼런스:https://blog.naver.com/jsh6034/220109246753
![image](https://user-images.githubusercontent.com/81477455/135066375-ef2cdc82-88f3-46d7-988e-25d6c59591d7.png)
이소화물차는 무슨소화물차라고 불러야될지 모르겠습니다.


신도색추정
https://blog.naver.com/korailbaksa/50014812299
![image](https://user-images.githubusercontent.com/81477455/135068281-a969024a-850a-4156-b5f5-64baad157de6.png)

구도색 및 신도색가 존재해서 한번 넣어봤습니다.

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.
