### ISSUE TITLE
통일호 소화물차(도색모음)

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#226]
2021.10.06 천장쪽수정
![통일호 소화물차](https://user-images.githubusercontent.com/81477455/136180244-ec43d013-bfd6-47af-bff6-759e5d9733b4.png)

@Gamunbi 이분의 비둘기호 소화물차를 활용해서 통일호소화물차도 만들어봤습니다.
1.초록구도색 통일호 소화물차
2.초록+노란 통일호 구도색 소화물차

통일호 소화물차 두번째도색

통일호 소화물차 링크
https://blog.naver.com/bf101/10148880295

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.

**Comment by EightonEight** [comment]
#439 로 이관합니다.
