### ISSUE TITLE
[Add] 객차형 ITX-새마을 객차

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#227]

**Comment by EightonEight** [comment]
![ITX_SAEMAEUL_CAR png](https://user-images.githubusercontent.com/77984422/117258691-32713f80-ae88-11eb-971c-fb1a816aece6.png)

※ ITX-새마을 스프라이트를 참고하여 무궁화호 객차를 수정한 것으로, 어색하거나 잘못된 부분이 있을 수 있습니다.

References
* <https://namu.wiki/w/%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8#s-3.1.4>
![image](https://user-images.githubusercontent.com/77984422/117258866-68162880-ae88-11eb-84d9-e13fc40136be.png)

* <https://youtu.be/bckubziNV5Y>
![image](https://user-images.githubusercontent.com/77984422/117258885-6f3d3680-ae88-11eb-83c8-1c3a1acea91d.png)
