### ISSUE TITLE
비둘기호 소화물차 도색모음

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#228]
![BIDULGI(구도색)](https://user-images.githubusercontent.com/81477455/117273657-4d977b80-ae97-11eb-9091-9e1a6e01751f.png)
@Gamunbi 이분의 비둘기호 소화물차 기존파란도색에서 노란+초록 도색을 넣었습니다.

https://gall.dcinside.com/mgallery/board/view?id=monorail&no=130342
![image](https://user-images.githubusercontent.com/81477455/117273738-5e47f180-ae97-11eb-8142-9fedbb445d44.png)

갈색도색 소화물차
![image](https://user-images.githubusercontent.com/81477455/120101746-866afd80-c182-11eb-8c20-ca9b499ae87e.png)

비둘기호 소화물차도 혹시나 파란구도색만 있는거같지않아서 찾아보니 노란+초록 도색도 있네요
얘는 밑에 진한초록이 반영되어있지않습니다.

**Comment by Gamunbi** [comment]
이 객차는 화물과 승객을 같이 운송했다고 해서 만들지 않았습니다.

**Comment by opentrain** [comment]
@Gamunbi 아 그래서 안하셨군요
만들긴했는데 애매모하게되었네요 죄송합니다.

**Comment by Gamunbi** [comment]
아닙니다 ㅎㅎ

**Comment by opentrain** [comment]
ㅡ

**Comment by opentrain** [comment]
@Gamunbi  한번 도색 수정해봤습니다.
![BIDULGI 도색모음](https://user-images.githubusercontent.com/81477455/135440300-c3f6d7f0-309b-4efb-a069-88229f9c9b63.png)
이번에 그 화물/승객 같이 싣는 열차빼고 넣었습니다.

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.
