### ISSUE TITLE
건널목 수정

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#229]
![건널목 2차 완성](https://user-images.githubusercontent.com/75788864/117433896-f95bcc80-af66-11eb-9fa0-c85f820c40a0.png)

한국 신호기 세트에 맞추어 좀 더 크고 굵게 수정해봤습니다. 스프라이트 조정 가이드(예상도)도 같이 만들었습니다.

.
.
.

5.7 수정
- 빔 높이 3픽셀 올림
- 빔이 달린 기둥 1픽셀 올림

**Comment by telk5093** [comment]
지나치게 크고 굵은 게 아닌가 하는 생각이 드는데요

**Comment by Gamunbi** [comment]
> 
> 
> 지나치게 크고 굵은 게 아닌가 하는 생각이 드는데요

혹시 작업하셨나요? 저도 이슈 올리면서 이 생각을 하긴 했습니다. 

기존것은 그 자체로 볼 땐 괜찮지만 한국식 신호기와 같이 놓고 보면 얇아 보인다고 생각해서 작업해본 겁니다.

너무 안 어울린다 싶으면 롤백해주세요.

**Comment by telk5093** [comment]
> > 지나치게 크고 굵은 게 아닌가 하는 생각이 드는데요
> 
> 저도 이슈 올리면서 이 생각을 하긴 했습니다. 기존것은 그 자체로 볼 땐 괜찮지만 한국식 신호기와 같이 놓고 보면 얇아 보인다고 생각해서 작업해본 겁니다.
> 
> 처음 이슈 쓸 때는 너무 크고 굵게 느껴질 수 있으니 마음에 안 드신다면 작업 안 하셔도 된다고 써놨었는데, 지우지 말고 그대로 둘 걸 그랬군요..
> 
> 너무 안 어울린다 싶으면 롤백해주세요.

죄송합니다. 처음에 들었던 생각을 써놓고 지운다는 걸 깜빡했네요.
그래도 혹시 몰라서 실제 적용해봤는데 제 생각이 기우였습니다. d1db8fc 에서 변경된 건널목 그래픽을 반영해두었습니다.

**Comment by Gamunbi** [comment]
아닙니다. 저도 만들고보니 좀 미묘하긴 했거든요.
