### ISSUE TITLE
[add] 4호선 GEC 초퍼제어 전동차

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#230]
![unname](https://user-images.githubusercontent.com/81485156/117574912-7b402700-b11a-11eb-898d-654d9aaf297e.jpg)

개통 당시부터 90년대 중반까지 운행함.
그래픽은 기존 3호선 차량의 것을 활용하면 될듯.

**Comment by telk5093** [comment]
4호선에 도색을 추가하는 것보다는 단말 유저들이 처음부터 3호선 열차를 구입하게 하는 게 직관적으로 쉬울 것 같습니다.
굳이 코드를 늘릴 필요는 없을 것 같습니다.

**Comment by EightonEight** [comment]
@telk5093 분당선에는 4호선 VVVF 1세대 도색을 추가(#156)하셨는데, 이것도 같은 방식으로 추가하면 되지 않을까요?

**Comment by telk5093** [comment]
@EightonEight 타당한 의견입니다. 다시 이슈를 열어두겠습니다.

**Comment by opentrain** [comment]
이슈가 닫아져있긴한데 4호선 운영당시 현:서울교통공사로 되어있어가지구 서울지하철 공사 4k 초퍼로 명칭 바꾸는거 어떨까요?

**Comment by telk5093** [comment]
> 이슈가 닫아져있긴한데 4호선 운영당시 현:서울교통공사로 되어있어가지구 혼란이 있을까봐 서울지하철 공사 4k 초퍼로 명칭 바꾸는거 어떨까요?

해당 명칭이 3호선에서도 사용 중이라 불가능합니다.
