### ISSUE TITLE
팬터그래프 달린 칸의 위치를 실제와 맞게 수정

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#231]
![Adams   Co 의 게임 (2022-07-11)](https://user-images.githubusercontent.com/77984422/117805081-84a0cf00-b293-11eb-9e3c-fa8a15570aca.png)

다음의 열차들은 **모든** 동력차(M차, 동력객차)에 팬터그래프가 달려 있기 때문에 위치를 실제에 맞게 ~~바꿀지, 아니면 그대로 유지할지 의견수렴이 필요함~~ 수정이 필요함

10량 1편성 (TC - M' - M' - T - M' - T - T - M' - M' - TC)
- [x] 서울교통공사 1k VVVF (``SMETRO_1K_VVVF``)
- [x] 철도청 3k VVVF / 구 도색 (``3K_VVVF_1ST_1``)
- [x] Korail 3k VVVF / 현재 도색 (``3K_VVVF_1ST_2``)
- [x] SMetro 4k 1·2세대 VVVF (``SMETRO_4K_VVVF_1ST_2ND``)

8량 1편성 (TC - M' - M' - T - T - M' - M' - TC)
- [x] 인천교통공사 1k VVVF 1세대 (``INCHEON_METRO_1K_VVVF_1ST``)

6량 1편성 (TC - M' - M' - T - M' - TC)
- [x] 신분당선 (``D00``)

References
* <https://youtu.be/ZJ05DsnbfPI?t=30>
* <https://youtu.be/ijoii-0sOxY?t=15>
* <https://youtu.be/E4Hfg-1GqLM?t=55>
* <https://youtu.be/zYyQJC5Y6DQ?t=65>
* <https://youtu.be/4aFt4tRGByU>

**Comment by telk5093** [comment]
버그입니다. 고증을 맞춰야 합니다.

**Comment by telk5093** [comment]
팬터그래프 위치는 현실의 차량이 n량일 때 n, 2n, 3n, ... 마다 반복되기만 하면 됩니다.
따라서 현실 편성을 기준으로 정하기만 하면 되므로, _팬터그래프의 위치를 조사하기만_ 하면 됩니다.
코드도 숫자 몇 개만 조정하면 되는 일이라 코드보다는 전수 조사가 더 큰 일이 될 겁니다.

**Comment by opentrain** [comment]
처음보는 버그네요 한열세 전동차 쓰면서 저런버그있다는거 이글을 통해 처음 알게되었네요 ㅎㅎ

**Comment by EightonEight** [comment]
다양한 플레이를 위해 최대한의 경우의 수를 생각해보고자 합니다.

먼저 2010년대 이후로 제작되고 있는 VVVF제어 전동차의 기본적인 편성구조는 다음과 같습니다.
TC(무동력제어차), M(동력차), M'(팬터그래프 있는 동력차), T(무동력차)
4량 1편성 / TC - M' - M' - TC
6량 1편성 / TC - M - M' - T - M' - TC
8량 1편성 / TC - M - M' - T - T - M - M' - TC
10량 1편성 / TC - M - M' - T - M' - T - T - M - M' - TC
이외에 편성구조가 다른 것은 따로 후술하겠습니다.

수도권 1호선, 통근형
* 저항제어 전동차
(철도청 1k 저항 초기형 / 초기 도색), (철도청 1k 저항 초기형 / 구 도색), (철도청 1k 저항 중기형 / 초기 도색), (철도청 1k 저항 중기형 / 구 도색), (Korail 1k 저항 중기형 / 현 도색), (철도청 1k 저항 후기형 / 구 도색), (Korail 1k 저항 후기형 / 현 도색), (서울지하철공사 1k 초기 저항), (서울메트로 1k 개조 저항)
1) - [ ] 10량 1편성 / TC - M - M' - T - M - M' - T - M - M' - TC
<https://youtu.be/HjpbiiKDWZc?t=340>
<https://youtu.be/yk4_zcKsXfY?t=160>
<https://youtu.be/WEb1yTsx3QQ?t=15>
2) - [ ] 6량 1편성(도입 초기) / TC - M - M' - M - M' - TC
<https://youtu.be/nSGzLIqLnLY?t=5>
<https://youtu.be/tHFPfaDiheA?t=160>
3) - [ ] 4량 1편성(임시 편성) / TC - M - M' - TC
<https://youtu.be/w-N7X5byn7g?t=30>

* VVVF제어 전동차
(철도청 311k 초기형 / 구 도색), (Korail 311k 초기형 / 현 도색), (Korail 311k / 초기 도색), (Korail 311k / 현 도색), (Korail 3xxk ST), (Korail 3xxk AL), (Korail 371k / 무도색), (Korail 371k, 381k 1차), (Korail 381k 2차), (Korail 391k / 서해선), (Korail 1호선 2019년 도입분)
1) - [ ] 10량 1편성
2) - [ ] 8량 1편성
<https://youtu.be/bbjSW0kX7ow?t=15>
3) - [ ] 6량 1편성
<https://youtu.be/TYur9kZ7e00>
<https://youtu.be/S3akgKrsLwk>
4) - [ ] 4량 1편성
<https://youtu.be/U3wyrnxDZ0s?t=25>
<https://youtu.be/U8LB1-YnKUI?t=180>
<https://youtu.be/jcu3ZOyNq14>
<https://youtu.be/zv8BN4DWWug?t=85>
<https://youtu.be/6ftnPYZbtC8?t=45>

* (Korail 321k 자전거 열차 도색)
1) - [ ] 8량 1편성
<https://youtu.be/spTDk3IfqhE?t=55>
2) - [ ] 6량 1편성 
<https://youtu.be/2WD4YO7UiBo?t=20>

**Comment by telk5093** [comment]
1차 수정본을 f548a7d 에서 반영하였습니다.
https://github.com/KoreanGRF/KoreanTrainSet/suites/2759905220/artifacts/61069404 에서 해당 커밋의 빌드를 받아서 테스트해볼 수 있습니다.

**Comment by EightonEight** [comment]
2차 수정 요청사항입니다. 
운전실부터 첫번째로 계산합니다.

* ``3XXK_ST``
  - [ ] 10량 (3, 5, 9 또는 2, 6, 8번째) - 1호선
  - [x] 8량 (3, 7 또는 2, 6번째) - 경의중앙선
  - [ ] 4량 (2, 3번째) - 광명셔틀

* ``1K_RHEO_FIRST_1``, ``1K_RHEO_FIRST_2``, ``1K_RHEO_SECOND_1``, ``1K_RHEO_SECOND_2``, ``1K_RHEO_SECOND_3``, ``1K_RHEO_LAST_1``, ``1K_RHEO_LAST_2``, ``SMETRO_1K_RHEO_FIRST``, ``SMETRO_1K_RHEO_MODIFIED``
  - [ ] 10량 (3, 6, 9 또는 2, 5, 8번째)
  - [x] 6량 (3, 5 또는 2, 4번째) - 개통 초기
  - [x] 4량 (3 또는 2번째) - 임시 편성

* ``LINE_1_2019``
  - [ ] 10량 (3, 5, 9 또는 2, 6, 8번째) - 1호선
  - [ ] 6량 (3, 5 또는 2, 4번째) - 연천셔틀

**Comment by telk5093** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/suites/2796041698/artifacts/62113433 에서 나머지를 수정했습니다.
확인해보시고 추가로 수정해야할 부분이 있으면 얘기해주세요.

**Comment by EightonEight** [comment]
`SMETRO_1K_RHEO_FIRST`를 6량 기준으로 하셨는데, 그렇다면 `1K_RHEO_FIRST_1`, `1K_RHEO_SECOND_1`(초기 도색)도 6량 기준으로 하면 좋지 않을까요? 

ref: http://photozou.jp/photo/photo_only/50802/190354601
![image](https://user-images.githubusercontent.com/77984422/119139422-f6d89700-ba7d-11eb-971e-5f09cf833626.png)

그 외는 수정할 부분이 없습니다.

**Comment by telk5093** [comment]
> `SMETRO_1K_RHEO_FIRST`를 6량 기준으로 하셨는데, `1K_RHEO_FIRST_1`, `1K_RHEO_SECOND_1`(초기 도색)도 6량 기준으로 하면 좋지 않을까요?

기술적으론 가능하긴 하겠는데 코드가 지나치게 복잡해질 것 같습니다.
이 정도 수준에서 멈출까 합니다.

**Comment by EightonEight** [comment]
> 기술적으론 가능하긴 하겠는데 코드가 지나치게 복잡해질 것 같습니다.
> 이 정도 수준에서 멈출까 합니다.

그렇다면 더이상 수정할 부분이 없으므로 본 이슈는 닫도록 하겠습니다. 감사합니다.
