### ISSUE TITLE
새마을형 발전차

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#232]
* **Sprite**:
![image](https://user-images.githubusercontent.com/10726524/118304009-12ddb500-b521-11eb-9329-b99343b3ba26.png)

 * **Reference image**:
![image](https://user-images.githubusercontent.com/10726524/118303989-0c4f3d80-b521-11eb-86be-fc26a20c386f.png)

 * From https://github.com/KoreanGRF/KoreanTrainSet/issues/117#issuecomment-821996797
> ![image](https://user-images.githubusercontent.com/10726524/115148406-6253d100-a09a-11eb-9b95-b8a4964ff275.png)
> 
> 1. 길이가 안 맞습니다.
> 2. 구형 발전차의 새마을호 초기 도색을 말씀하시는 건가요? 레퍼런스 링크와 사진을 부탁드립니다.

가로 길이 작업이 필요함

**Comment by opentrain** [comment]
![초기 새마을호 발전차 도색](https://user-images.githubusercontent.com/81477455/118387740-17a68400-b65b-11eb-8a3f-42d9f12c8257.png)

수정판입니다. 밑에는 발전차 원본입니다.
