### ISSUE TITLE
통일호 구형 발전차

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#233]
From https://github.com/KoreanGRF/KoreanTrainSet/issues/117#issuecomment-830633283

 * **Sprite**:
 ![image](https://user-images.githubusercontent.com/10726524/118304230-6223e580-b521-11eb-8077-2d232984d9be.png)
 * **Reference**:
 ![image](https://user-images.githubusercontent.com/10726524/118304213-59cbaa80-b521-11eb-9829-258f1c6ae084.png)

**Comment by opentrain** [comment]
![통일호 초록발전차초기도색](https://user-images.githubusercontent.com/81477455/120096301-a63ff880-c165-11eb-94b5-aae12f3a9a3d.png)
저 구형발전차 생기기전에 또다른 초기도색이 있었다고 합니다.
난방차를 개조해서 사용했다고합니다.

레퍼런스
![image](https://user-images.githubusercontent.com/81477455/120096266-7264d300-c165-11eb-8031-46f3609b7a3c.png)

**Comment by telk5093** [comment]
도색만 늘어날 것 같습니다. 추가를 거부합니다.
