### ISSUE TITLE
'Korail 321k 자전거 열차 도색' 표시 오류

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#235]
![Higgins   Co 의 게임 (2029-12-24)](https://user-images.githubusercontent.com/77984422/118389524-52adb500-b665-11eb-9222-7bbb2144bec3.png)
운전실 두 칸 모두 하늘색인 상태

ref: <https://youtu.be/fm4gBpHvKmQ>
![image](https://user-images.githubusercontent.com/77984422/118389910-4591c580-b667-11eb-9f8c-53e7bfbbcce8.png)

**Comment by telk5093** [comment]
기술적 문제로 전/후두부 모두 주황색, 또는 모두 파란색이 나타날 수 있습니다.
