### ISSUE TITLE
철도청 1호선 초기저항(등장시 도장/냉방 차량)

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#239]
![1K_RHEO_FIRST_1](https://user-images.githubusercontent.com/81485156/119349069-ab6df500-bcd8-11eb-8879-bc2db1b5a653.png)

Ref,
![1610463666470](https://user-images.githubusercontent.com/81485156/119349286-f556db00-bcd8-11eb-80bc-41a156bd5bbb.jpg)

.

**Comment by telk5093** [comment]
#194 로 이관합니다.
