### ISSUE TITLE
1호선 저항제어 차량 도트 오류.

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#240]
![m1816](https://user-images.githubusercontent.com/81485156/119425658-c37a5e80-bd42-11eb-99b5-47d7e188b9e4.jpg)

판토그래프와 에어컨의 위치가 약간 뒤로 가야함.

수정 대상

 - [x] 초기 저항(등장시 도색 비냉방, ``1K_RHEO_FIRST_1``)
 - [x] 초기 저항(구도장, ``1K_RHEO_FIRST_2``)
 - [ ] 초기 저항(서울지하철공사 도장 비냉방, ``SMETRO_1K_RHEO_FIRST``)
 - [x] 개조 저항(서울메트로, ``SMETRO_1K_RHEO_MODIFIED``)
 - [x] 중기 저항(등장시 도장, ``1K_RHEO_SECOND_1``) 
 - [x] 중기 저항(구도장, ``1K_RHEO_SECOND_2``)
 - [x] 중기 저항(신도장, ``1K_RHEO_SECOND_3``)
 - [x] 신조 저항(구도장, ``1K_RHEO_LAST_1``)
 - [x] 신조 저항(신저항, ``1K_RHEO_LAST_2``)

- 초저항(서지공) 냉방차는 추후 제작예정.
- 초저항(철도청) 등장시 도장 냉방차
 -> https://github.com/KoreanGRF/KoreanTrainSet/issues/194#issuecomment-847459262

**Comment by ChuoSpecialRapid201** [comment]
![1K_RHEO_FIRST_2](https://user-images.githubusercontent.com/81485156/119429889-bb262180-bd4a-11eb-96d2-70cc510ffbbf.png)

초저항(구도장)

**Comment by telk5093** [comment]
수정이 필요한 그래픽이 후첨하신 초기 저항(구 도색) 하나 뿐인가요?
그게 아니라면 모든 차량의 이름을 리스트로 만들어주시겠어요?

**Comment by ChuoSpecialRapid201** [comment]
> 수정이 필요한 그래픽이 후첨하신 초기 저항(구 도색) 하나 뿐인가요?
> 그게 아니라면 모든 차량의 이름을 리스트로 만들어주시겠어요?

리스트 추가 완료

**Comment by ChuoSpecialRapid201** [comment]
![1K_RHEO_MODIFIED_2](https://user-images.githubusercontent.com/81485156/119455258-626b7e80-bd74-11eb-9c6d-d4462f6ae09a.png)
![1K_RHEO_MODIFIED_3](https://user-images.githubusercontent.com/81485156/119455471-98a8fe00-bd74-11eb-8684-aff0258e0cfd.png)

중저항(구도장,신도장)

**Comment by ChuoSpecialRapid201** [comment]
![1K_RHEO_SECOND_1](https://user-images.githubusercontent.com/81485156/119481926-3b21ab00-bd8e-11eb-83be-4dee16201483.png)

중저항(등장시 도장)

**Comment by ChuoSpecialRapid201** [comment]
![SMETRO_1K_RHEO_MODIFIED](https://user-images.githubusercontent.com/81485156/119510624-a24e5800-bdac-11eb-9c66-77bf6318a20c.png)

개조 저항

**Comment by ChuoSpecialRapid201** [comment]
![1K_RHEO_FIRST_1](https://user-images.githubusercontent.com/81485156/119516965-29ea9580-bdb2-11eb-8483-5dbab0e29b5d.png)

초저항(등장시/비냉방)

**Comment by ChuoSpecialRapid201** [comment]
![New_1000_OC](https://user-images.githubusercontent.com/81485156/119974040-2e4fc200-bfef-11eb-98a5-659ed79f3275.png)

신저항(구도장)

![New_1000](https://user-images.githubusercontent.com/81485156/119974047-2f80ef00-bfef-11eb-917d-5b4475f5d959.png)

신저항(신도장)

**Comment by telk5093** [comment]
@ChuoSpecialRapid201 ``SMETRO_1K_RHEO_FIRST``를 수정해주시면 반영하고 본 이슈를 닫겠습니다.
