### ISSUE TITLE
관광호 + 6300호대 기관차

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#241]
![관광호 1차 완성](https://user-images.githubusercontent.com/75788864/120080633-e024e680-c0f4-11eb-8f8f-ffa5ee5e88c2.png)

![8000호대 전기기관차 관광호 도색](https://user-images.githubusercontent.com/75788864/119805457-3a1e8400-bf1c-11eb-826e-58d58fdf29ee.png)
이것은 기존 8000호대 전기기관차 우유도색도 수정한 것입니다. 위가 원 도색, 아래가 수정한 버전입니다.

도입년도:1969년

객차 차량제원
- 승객 수용량:56(일반실)

기관차 차량제원(6300호대 기준)
- 이름:6300호대 디젤기관차(EMD G26CW)
- 무게:99톤
- 최고속도:153km/h (그냥 150으로 하셔도 될 듯)
- 힘:1491.4KW, 2000마력
- 길이:17,063mm, 17m
7x00호대 디젤을 토대로, 길이를 7로 줄이고 객차와 어울리게 채색을 살짝 수정했습니다.
약간 길이가 긴 것들(7x00호대 수정, 7500호대 관광호 외관)은 그대로 8입니다. #250 의 6100, 6200호대와 똑같은 외관이지만 1.5미터 짧기 때문에 →와 ←방향 스프라이트를 1px 짧게 했습니다(31px).

전망차
- 반식당 반객차와 발전차가 따로 있습니다. 반식반객 전망차의 경우 객차로 취급하실지 식당차로 취급하실지 아니면 끝에만 붙는 특수객차로 취급하실지는 텔크님께 맡기겠습니다.
- 발전차형 전망차의 경우, 혹시 가능하다면 그냥 청색백색 발전차를 끝에 달면 자동으로 발전차형 전망차로 바뀔 수 있게 하면 좋을 것 같습니다.
- 차량 행렬에서 맨 뒤, 혹은 맨 앞에 달렸습니다.

레퍼런스
- 기관차
https://namu.wiki/w/EMD%20G26CW
https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD_%EC%B2%A0%EB%8F%84%EC%B2%AD_6300%ED%98%B8%EB%8C%80_%EB%94%94%EC%A0%A4_%EA%B8%B0%EA%B4%80%EC%B0%A8
- 객차
https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=19267&search_pos=-20982&s_type=search_name&s_keyword=%EC%B9%A8%EB%8C%80%ED%8A%B9%EA%B8%89&page=1
- 식당차
https://gall.dcinside.com/board/view/?id=train&no=1093303
- 관광호 전반적인 모습
https://www.bobaedream.co.kr/view?code=skybr&No=11552

7x00호대 관광호 외관과, 6300호대 관광호 외관이 미묘하게 다릅니다. 6300호대는 새로 만든 거니 수정이 자유로웠지만 7x00호대는 기존의 다른 7x00호대 도색들과 형태를 맞춰야 했기 때문입니다.

※이 이슈를 작업하신다면 https://github.com/KoreanGRF/KoreanTrainSet/issues/250 이 이슈와 같이 하시는 걸 추천해드립니다.

**Comment by ChuoSpecialRapid201** [comment]
관광호 기관차는 7500호대였던걸로 알고있음.

**Comment by Gamunbi** [comment]
> 
> 
> 관광호 기관차는 7500호대였던걸로 알고있음.

7500호대는 71년에 들어왔습니다. 관광호가 처음 운행을 시작한 건 69년입니다. 1969년에 처음 관광호를 몰았던 기관차는 당시 대형 7000호대였습니다. 이 대형 7000호대는 나중에 특대형 7100호대, 7200호대, 7000호대가 들어오면서 6300호대로 차번이 바뀌었습니다.

**Comment by Gamunbi** [comment]
https://gall.dcinside.com/board/view/?id=train&no=808954

관광호 만들면서 본 글이긴 한데, 다시 보니 6300호대만 저런 신칸센 외관을 가진 건 아닌 것 같습니다. 7500호대도 신칸센 외관 버전 따로 만들까요?

**Comment by ChuoSpecialRapid201** [comment]
![7500](https://user-images.githubusercontent.com/81485156/119491470-e9325280-bd98-11eb-9683-e0b9007e91e3.png)

짭 0系(7500)

**Comment by Gamunbi** [comment]
> 
> 
> ![7500](https://user-images.githubusercontent.com/81485156/119491470-e9325280-bd98-11eb-9683-e0b9007e91e3.png)
> 
> 짭 0系(7500)
> 
> 그래픽 보완 필요할수도 있음.

적절하게 수정해서 맨 위 png에 같이 올리겠습니다.

**Comment by ChuoSpecialRapid201** [comment]
#244

**Comment by ChuoSpecialRapid201** [comment]
![7100](https://user-images.githubusercontent.com/81485156/119502554-02410080-bda5-11eb-9039-a0577d420450.png)

7x00 수정

**Comment by Gamunbi** [comment]
> 
> 
> ![7100](https://user-images.githubusercontent.com/81485156/119502554-02410080-bda5-11eb-9039-a0577d420450.png)
> 
> 7x00 수정

**Comment by Gamunbi** [comment]
7x00 수정하신 거 위로 올려드렸습니다.

**Comment by opentrain** [comment]
![image](https://user-images.githubusercontent.com/81477455/119775521-b013f280-befe-11eb-8a98-64e417d11573.png)

![직각 새마을호 빨간객차](https://user-images.githubusercontent.com/81477455/119775539-b73b0080-befe-11eb-921f-bb686f68fe78.png)

파란도색말고도 빨간도색이 존재했었네요

![관광호(하늘+빨강+파랑)](https://user-images.githubusercontent.com/81477455/119775598-ca4dd080-befe-11eb-8978-959b0ca2da1a.png)

관광호열차입니다 객차하고 식당차밖에 없습니다.
발전차를 자료가 없어서 안했습니다.

**Comment by Gamunbi** [comment]
위 빨간 도색은 잘 모르겠지만, 아래 하늘색 도색은 관광열차입니다. 이 쪽은 관광 열차에 대한 처우가 결정되고 나서나 한열셋에 반영될 것으로 보입니다. 

그와는 별도로 관광용으로 굴렸던 저 미카 3형 161호 관광도색은따로 제가 제작중입니다.

**Comment by opentrain** [comment]
빨간도색이 1968~69년에 도입된 객차라고하네요 빨간색하고 관광호 도색 두가지로 있었네요

**Comment by Gamunbi** [comment]
아 그리고 저 전망차는 발전차형 전망차입니다. 관광호 전망차는 발전차 겸용과 식당차 겸용이 따로 있었습니다. 지붕을 보시면 알 수 있습니다. 더 높고 둥근 것이 발전 전망차고, 낮지만 에어컨이 세 개 달린 게 반식반객 전망차입니다. 지금 구현된 건 반식반객 전망차고, 발전 전망차는 지금 제가 만들 생각입니다.

**Comment by opentrain** [comment]
https://gall.dcinside.com/board/view/?id=train&no=1093303 빨간색 새마을호 링크입니다.

**Comment by Gamunbi** [comment]
댓글로 보면 저건 무궁화 식당차로 격하된 이후 사진 같습니다. 특급 기차인데 하위 등급인 무궁화호와 동일한 도색을 했을 가능성은 매우 낮아보입니다. 그리고 위에서 올리신 사진(베이지색 반, 빨강 반)의 출처도 궁금합니다.

**Comment by opentrain** [comment]
![image](https://user-images.githubusercontent.com/81477455/119803015-07738c00-bf1a-11eb-9db6-7718c9a8384a.png)

![image](https://user-images.githubusercontent.com/81477455/119803279-430e5600-bf1a-11eb-85a4-1a35d2f9ff96.png)

출처가 없어서 제가 자료를 올려보겠습니다.

**Comment by Gamunbi** [comment]
자료 감사합니다. 다만 특실이라 일단 보류해야 할 듯 합니다. 아직 특실은 한열셋에서 구현이 안 되어있고, 또 특실만 저 도색이었는지 일반실 등 관광호 전체가 저 도색이었는지는 아직 불명이라서요.

**Comment by opentrain** [comment]
![image](https://user-images.githubusercontent.com/81477455/119804774-9f25aa00-bf1b-11eb-9062-2f53c2e64aa6.png)

@Gamunbi  예 있네요

**Comment by Gamunbi** [comment]
제 말은 저 하양빨강 도색의 일반실 사진이나 운행하고 있는 사진이 있냐는 뜻이었습니다.

**Comment by opentrain** [comment]
저 운행하고있는 자료를 없고 객차 자료만 준비가 되있네요 컬러사진은 제가 찾아보고나서 올려보겠습니다.

**Comment by ChuoSpecialRapid201** [comment]
생각해보니 싸롱카가 없는듯?

**Comment by Gamunbi** [comment]
수정된 버전 스프라이트 묶음에 반영되었습니다.

**Comment by Gamunbi** [comment]
> 
> 
> 생각해보니 싸롱카가 없는듯?
> 
> ![m_1362139017_»õ¸¶À»È£](https://user-images.githubusercontent.com/81485156/119837262-61d21400-bf3d-11eb-81f8-e44a97e21002.jpg)

수정된 버전 스프라이트 묶음에 반영되었습니다.

**Comment by Gamunbi** [comment]
ChuoSpecialRapid201 수정된 버전 스프라이트 묶음에 반영되었습니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/119857365-77036e80-bf4e-11eb-9129-47e912a9bd31.png)

위 레퍼런스 사진과
<br /><br />
* * *

![image](https://user-images.githubusercontent.com/10726524/119857480-90a4b600-bf4e-11eb-868d-b7bb686123b5.png)
그래픽 스프라이트에 차이가 있는 것 같습니다.
<br /><br />
* * *
![image](https://user-images.githubusercontent.com/10726524/119857760-c9dd2600-bf4e-11eb-9f81-9a75463d8764.png)
와 같이 변경할 것을 제안합니다.

**Comment by telk5093** [comment]
Checklist for myself:

 - [ ] ``7x00호대 기관차 (청백) 기존 것을 수정함``
   - K7x00.png 파일에서 해당 그래픽만 바꿔치기 할 것 (easy)
 - [ ] ``7500호대 기관차 (관광호)``
   - ``K7x00``에 신규 도색으로 추가. 도색 개조 이름은 `` (7500호대: 관광호)``로
 - [ ] ``6300호대 기관차`` (검정주황, 청백, 관광호)
   - ``K6300`` 열차를 신규 추가
 - [ ] ``8000호대 전기 기관차 우유 도색``
   - K8000.png 파일에서 해당 그래픽만 바꿔치기 할 것 (easy)
 - 전망형 발전차와 전망형 식당차
   - ``position_in_consist_from_end == 0``이면 전망차로, 아니면 비 전망차로
 - 관광호 기관차(aka. 짭0계)의 경우, 중련을 못 하게 막을 방법이 있는지 확인 필요
   - ``STORE_TEMP()``로 가능한지 확인

**Comment by Gamunbi** [comment]
코... 라고 해야 될지 약간 좁아보입니다.
![tq](https://user-images.githubusercontent.com/75788864/119874272-63f99a00-bf60-11eb-93f8-63942e1828ca.png)
이건 어떠신지요? 

그리고 6300호대 다시보니 수정할 것이 생겼습니다. 내일 내로 수정 완성할 예정이니 일단 보류해주세요.

**Comment by Gamunbi** [comment]
대신 그림자를 약간 수정했습니다. 좀 더 납득이 가실 거라고 생각합니다.

**Comment by opentrain** [comment]
디젤기관차 6300호대 검정주황 6100~6300호대로 변경해도 괜찮을거같습니다.

**Comment by Gamunbi** [comment]
스펙이 비슷비슷하네요. 6x00호대는 6300호대까지만 나왔으니, 이름을 6300호대가 아니라 6x00호대로 바꾸겠습니다.

**Comment by Gamunbi** [comment]
스펙을 다시 찬찬히 봤는데, 6000, 6100, 6200호대는 전장 18.5미터, 힘 1800마력, 최고 속도 105km/h로 동일하지만 6300호대는 전장 17미터, 힘 2000마력, 최고속도 153km/h(나중에 105km/h로 개조)로 다릅니다. opentrain님께서 만드신 6000호대를 6x00으로 바꾸고, 6300호대는 그대로 6300호대로 하는 게 더 나아보입니다.

**Comment by Gamunbi** [comment]
opentrain님, 다시 보니 또 5000, 6000호대랑 6100, 6200호대끼리도 생김새가 약간 다르네요;; 6100, 6200호대도 제가 나중에 올리겠습니다.

**Comment by opentrain** [comment]
@Gamunbi 6100호대하고 6200호대 모습이 비슷해서 똑같지 않은가요?
저도 시간이 나는데로 올리겠습니다.

**Comment by Gamunbi** [comment]
#250 에 제가 말씀드린 것들 반영했습니다.

**Comment by opentrain** [comment]
#198에 여기에 청백도색 열차 수정했습니다.
