### ISSUE TITLE
6300호대 청백도장(AkA 우유 도장)

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#244]
![6300(NoN0)](https://user-images.githubusercontent.com/81485156/119492376-f56adf80-bd99-11eb-964f-49ea28ee3be2.png)

그래픽 보완 필요할수도 있음.

Ref,
![78569bbaace5681757adf8d2864b5b69](https://user-images.githubusercontent.com/81485156/119492673-4e3a7800-bd9a-11eb-812f-de62125ca443.jpg)

**Comment by Gamunbi** [comment]
#241 통일성 있게 살짝 수정하고 종합했습니다.

**Comment by telk5093** [comment]
#241 로 이관합니다.
