### ISSUE TITLE
2호선 개조 저항(초퍼)차량 그래픽 오류.

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#245]
![maxresdefault](https://user-images.githubusercontent.com/81485156/119624539-3b7c7d80-be44-11eb-9dd5-70fda532da76.jpg)

+ 판토는 2짝이 달려있어야 하나 1짝만 달려있음.
+ 일부 편성은 에어컨이 2짝만 달려있음.

수정 대상(판토)

 - [x] 개조 저항(``2K_RHEO_MODIFIED``)
 - [x] 멜코 초퍼(``2K_MELCO``)
 
추가 대상(에어컨)

 - [x] 개조 저항(``2K_RHEO_MODIFIED``)
 - [x] 멜코 초퍼(``2K_MELCO``)

P.s 2호선 차량 일부의 명칭 변경이 필요할듯?

 개조 저항 -> 개조 초퍼(개조저항)
 멜코 초퍼 -> 멜코 초퍼(저항)

두 차량중 일부는 초퍼제어인 차도 있지만 저항제어인 차도 있음.

**Comment by telk5093** [comment]
> 두 차량중 일부는 초퍼제어인 차도 있지만 저항제어인 차도 있음.

일부를 위해 전체를 변경할 생각은 없습니다. 지나친 현실 고증은 하지 않을 생각입니다.

**Comment by ChuoSpecialRapid201** [comment]
![2K_RHEO_MODIFIED](https://user-images.githubusercontent.com/81485156/119922095-17d34780-bfaa-11eb-97d2-9734b88db6a4.png)

개조저항(판토 수정)

![2K_RHEO_MODIFIED_2AC](https://user-images.githubusercontent.com/81485156/119922093-16a21a80-bfaa-11eb-8366-3b2a22f8bcc0.png)

개조저항(에어컨 2개짜리)

**Comment by ChuoSpecialRapid201** [comment]
![2K_MELCO](https://user-images.githubusercontent.com/81485156/119934153-5411a280-bfc0-11eb-875d-5aa66ea763f6.png)

멜코초퍼(판토 수정)

![2K_MELCO_2AC](https://user-images.githubusercontent.com/81485156/119934161-55db6600-bfc0-11eb-8f25-10bb2763b3ea.png)

멜코초퍼(에어컨 2개짜리)

**Comment by telk5093** [comment]
에어컨 개수는 코드 간략화를 위해 반영하지 않겠습니다.

**Comment by JukjeonWani** [comment]
에어컨 두개짜리는 GEC쵸퍼 차량입니다.
멜코형 GEC쵸퍼로 분리해도 괜찮을 듯 합니다.
