### ISSUE TITLE
마터 2형, 파시 5형, 미카 3형, 혀기 7형 수정, 터우 6형 추가

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#247]
![증기기관차 마터 2형 4차 완성](https://user-images.githubusercontent.com/75788864/120071917-36c9fa80-c0cc-11eb-8991-228e2a08bbce.png)
![증기기관차 파시 5형 6차 완성](https://user-images.githubusercontent.com/75788864/120071919-392c5480-c0cc-11eb-9ff5-31306dda9f27.png)
![증기기관차 미카 3형 4차 완성](https://user-images.githubusercontent.com/75788864/120071922-3a5d8180-c0cc-11eb-8afc-d38183654e4b.png)
![협궤 증기기관차 혀기 7형 2차 완성](https://user-images.githubusercontent.com/75788864/120076306-dcd33000-c0df-11eb-8efd-049dbfc10a4d.png)
![증기기관차 터우 5·6형 2차 완성](https://user-images.githubusercontent.com/75788864/120072148-40a02d80-c0cd-11eb-9e3a-77e8f1a00bba.png)

사이즈를 현실에 최대한 맞게 맞추었습니다. 전반적으로 매우 짧아졌습니다.

마터 2형
- 전장 : 23,266mm (약 37px)
- 의도한 길이 : 40px
- 추천 길이 : 기관차 7 (26px), 탄수차 3 (14px)

파시 5형
- 전장 : 23,756mm (약 37~38px)
- 의도한 길이 : 40px
- 추천 길이 : 기관차 7 (26px), 탄수차 3 (14px)

미카 3형 
- 전장 : 22,035mm (약 35~36px)
- 의도한 길이 : 36px
- 추천 길이 : 기관차 6 (24px), 탄수차 3 (12px)

혀기 7형
- 전장 : 14,600mm (약 23~24px)
- 의도한 길이 : 24px
- 추천 길이 : 기관차 4 (16px), 탄수차 2 (8px)

터우 6형
- 전장 : 18,424mm (약 29~30px)
- 의도한 길이 : 28px
- 추천 길이 : 기관차 5 (20px), 탄수차 2 (8px)
- 도입년도 : 1927년
- 중량 : 약 127.4톤
- 최고 속도 : 95km/h

터우 6형 레퍼런스
https://namu.wiki/w/%ED%84%B0%EC%9A%B0%ED%98%95%20%EC%A6%9D%EA%B8%B0%EA%B8%B0%EA%B4%80%EC%B0%A8#s-3.6
https://ko.wikipedia.org/wiki/%ED%84%B0%EC%9A%B0%ED%98%95_%EC%A6%9D%EA%B8%B0_%EA%B8%B0%EA%B4%80%EC%B0%A8
https://en.wikipedia.org/wiki/Sentetsu_Tehoro-class_locomotive

마터와 파시의 길이는 실제로는 9(36px)에 더 가깝지만, 한 단계 작은 기차인 미카와 차별화를 위해 의도적으로 1(4px) 늘렸습니다.

터우 6형의 마력에 대한 자료는 찾을 수 없었습니다. 제 생각에는 한 단계 위인 파시 5형이 1050마력이니, 이보다 약간 작게 하면 될 것 같습니다(예:800~900마력 정도)

저기의 '전시도색'은 전쟁 때 쓰였던 도색이 아니라, 현재 박물관 등에 전시되어 있는 도색이란 뜻입니다.

**Comment by opentrain** [comment]
증기기관차 퀄리티 볼때마다 매우 놀랍네요 ㄷㄷ

**Comment by Gamunbi** [comment]
현재 쓰고 있는 사이즈로 롤백하겠습니다. 이 스프라이트는 적용하지 말아주세요. 미카 관광용 열차 이슈도 닫아둔 뒤 수정하고 다시 열겠습니다.
