### ISSUE TITLE
전망형 구형 발전차 도색추가

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#248]
#241 @Gamunbi  이분의 관광호(새마을호) 전망형 발전차 활용해서
도색을 넣어봤습니다.

![전망형 발전차 통일호+무궁화 도색](https://user-images.githubusercontent.com/81477455/120072443-ebfdb200-c0ce-11eb-92dd-24f5ceb8b32a.png)

통일호 도색 및 무궁화호 구,신도색 여기에 사진있습니다.
https://www.google.co.kr/search?q=%EC%A0%84%EB%A7%9D%ED%98%95+%EB%B0%9C%EC%A0%84%EC%B0%A8&tbm=isch&ved=2ahUKEwi8tIaU-u7wAhXBIqYKHdIpCKcQ2-cCegQIABAA&oq=%EC%A0%84%EB%A7%9D%ED%98%95+%EB%B0%9C%EC%A0%84%EC%B0%A8&gs_lcp=CgNpbWcQAzICCAA6BQgAELEDOggIABCxAxCDAVC5-YQBWKWIhQFg7omFAWgAcAB4AIABhgKIAaoSkgEGMS4xNi4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=5juyYLypHcHFmAXS06C4Cg&bih=657&biw=1366

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.
