### ISSUE TITLE
[관광] 미카 3형 (161호, 1981년 관광도색)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#249]
![증기기관차 미카 3형 관광도색 1차 완성](https://user-images.githubusercontent.com/75788864/130934718-3fe8bae9-aee4-4e60-9fac-213c0a7da308.png)

레퍼런스
![기차 미카 3형 161호 01](https://user-images.githubusercontent.com/75788864/120072629-c624dd00-c0cf-11eb-94d6-93e654615b9a.jpg)
![기차 미카 3형 161호 03](https://user-images.githubusercontent.com/75788864/120072631-c91fcd80-c0cf-11eb-9878-d15150934d3e.jpg)

https://blog.daum.net/kys56/8532329

일반 색에서는 도저히 마음에 드는 색을 찾을 수가 없어서 가장 비슷한 **회사 색상을 썼습니다.** 관광용이니 사실 회사 색상을 써도 괜찮을 것 같습니다. 회사 색상이 어두운 파랑색일 때 실제와 가장 비슷한 도색이 될 것입니다. 

차량제원은 기존 미카 3형과 같습니다. 개조로 하시면 됩니다.
스프라이트 사이즈도 모두 동일합니다.
객차, 식당차, 전망차는 관광호입니다. 역시 개조로 하시면 됩니다.

**Comment by kiwitreekor** [comment]
"colour_mapping" callback에 PALETTE_CC_FIRST를 리턴하면 회사 색상 관계없이 그대로 어두운 파란색 표현이 가능합니다. 참고하세요.

**Comment by Gamunbi** [comment]
그렇다면 저 색을 그대로 일반색으로 쓸 수 있다는 뜻인가요?

**Comment by Gamunbi** [comment]
수정중

**Comment by telk5093** [comment]
Will not be implemented, since it is a tour livery.
