### ISSUE TITLE
5000, 6000호대 디젤기관차 (수정)

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#250]
![디젤기관차 5000·6000호대](https://user-images.githubusercontent.com/75788864/120080098-4825fd80-c0f2-11eb-8da2-92f5c5e45221.png)

|차량제원|도입년도|길이 (코드상 길이)|무게|힘|최고속도|비고|
|-|-|-|-|-|-|-|
|5000호대|1957년|18.5m (7)|141톤|1750마력|105km/h|-|
|6000호대|1963년|18.5m (7)|136톤|1800마력|105km/h|-|
|6100호대|1966년|18.5m (7)|139톤|1800마력|105km/h|-|
|6200호대|1967년|18.5m (7)|139톤|1800마력|105km/h|-|
|6300호대|1969년|17m (7)|99톤|2000마력|153km/h|https://github.com/KoreanGRF/KoreanTrainSet/issues/241|

||구현내용|차량 목록|
|-|-|-|
|1안|5000·6000을 통합, 6100·6200을 통합|5000·6000호대, 6x00호대|
|2안|모두 하나로 통합|5000·6x00호대|
|3안|5000을 분리, 6000·6100·6200을 통합|5000호대, 6x00호대|

원래 네가지 안이 있었는데 3안으로 줄였습니다. 스프라이트도 그냥 넷 중 두 개(2안의 경우 한 개) 골라서 하시면 될 것 같습니다.

**Comment by telk5093** [comment]
3안으로 갑니다
