### ISSUE TITLE
통일호 90~97년 남색도색

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#251]
![image](https://user-images.githubusercontent.com/81477455/120096987-303d9080-c169-11eb-95ee-6626821d82e5.png)

![통일호 90~97년 남색도색](https://user-images.githubusercontent.com/81477455/120097007-44818d80-c169-11eb-9269-579a706fed6d.png)
흰색+노란+초록+흰색으로 96 04도색 변경되기전도색 흰색+노란+남색+흰색 90 97년도에 이렇게 운영했다고합니다.
이도색이 없어서 넣어봤습니다.

**Comment by ChuoSpecialRapid201** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/issues/134

이미 있음.
