### ISSUE TITLE
그래픽 스프라이트 규격 통일

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#252]
현재 그래픽 스프라이트가 어디는 왼쪽에서 64px, 어디는 왼쪽에서 60px에서 시작하고
각 방향별 스프라이트 조각들도 간격이 제멋대로임. 특히 지하철의 경우 더욱 심함.

이 간격을 모두 동일한 간격으로 조정해야 함

eg) ``EUM``
왼쪽에서 60px부터 시작, 그 이후 순서대로 0, 15, 45, 95, 125, 140, 175, 225px 에 그래픽이 있음
https://github.com/KoreanGRF/KoreanTrainSet/blob/master/src/locomotive/KTX/EUM_graphic.pnml#L11
```
spriteset(set_EUM_engineH, "./src/locomotive/KTX/EUM.png") {
    [60+0,        0,     8,    22,    -3,   -11]
    [60+15,       0,    21,    15,   -15,    -6]
    [60+45,       0,    33,    12,   -18,    -8]
    [60+95,       0,    21,    16,    -6,    -9]
    [60+125,      0,     8,    22,    -3,   -11]
    [60+140,      0,    21,    16,   -15,    -8]
    [60+175,      0,    33,    12,   -19,    -8]
    [60+225,      0,    21,    15,    -6,    -7]
}
```

eg2) ``NDC``
https://github.com/KoreanGRF/KoreanTrainSet/blob/master/src/locomotive/NDC/NDC_graphic.pnml#L8
https://github.com/KoreanGRF/KoreanTrainSet/blob/master/src/locomotive/NDC/NDC_graphic.pnml#L32
왼쪽에서 60px에서 시작, 그 이후 순서대로 0, 15, 45, 95, 125, 140, **170**, **220**px에 그래픽이 있음
```
template tmpl_NDC(x, y) {
    [x+0,        y,     8,    22,     -3,   -11]
    [x+15,       y,    21,    17,    -14,    -8]
    [x+45,       y,    30,    12,    -16,    -8]
    [x+95,       y,    21,    17,     -6,    -8]
    [x+125,      y,     8,    22,     -3,   -11]
    [x+140,      y,    21,    17,    -14,    -8]
    [x+170,      y,    31,    12,    -16,    -8]
    [x+220,      y,    21,    17,     -6,    -8]
}
```

eg3) 각종 지하철
https://github.com/KoreanGRF/KoreanTrainSet/blob/master/src/template/metro.pnml#L7
왼쪽에서 **64**px에서 시작, 그 이후 순서대로 완전 제멋대로
```
template tmpl_engine_head(x, y) {
    [x+64,     y,    8,    22,     -3,   -11]
    [x+80,     y,   21,    17,    -13,    -9]
    [x+112,    y,   30,    12,    -16,    -8]
    [x+161,    y,   21,    17,     -6,    -8]
    [x+191,    y,    8,    22,     -3,   -11]
    [x+207,    y,   21,    17,    -13,    -9]
    [x+239,    y,   31,    12,    -16,    -8]
    [x+288,    y,   21,    17,     -6,    -8]
}
```

**Comment by EightonEight** [comment]
규격 통일 후 스프라이트 가이드라인을 만들어주신다면 제작할 때 편리할 것 같습니다.

**Comment by telk5093** [comment]
> 규격 통일 후 스프라이트 가이드라인을 제시해주신다면 제작할 때 편리할 것 같습니다.

아직 정하지 않았는데, 되도록 10의 배수로 정리하고자 합니다. (eg. 0, 20, 50, 100, 130, 150, 180, 230px)
현재 혹시 제작하고 계시는 그래픽 스프라이트가 있다면 이 건과 무관하게 작업하시면 추후 제가 정리할 예정입니다.

**Comment by telk5093** [comment]
현재 지하철을 80, 100, 130, 180, 200, 220, 250, 300px 위치로 놓고 있음
