### ISSUE TITLE
서울교통공사 8호선 3차분(별내선 도입신차)

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#256]
![SMETRO_8K_3TH](https://user-images.githubusercontent.com/81477455/122629641-8c0c9100-d0f9-11eb-8b7a-410416663519.png)
2021.4.21일에 미리 만들어놓고 올리지않고 있었습니다.
서울교통공사 5호선4차분열차하고 같은 열차입니다.

@EightonEight 이분이 제공해주신 8호선 렌더링 영상입니다.
https://youtu.be/x2IGrCAMuDw?t=75

부산국제철도기술산업전에서 공개된 8호선신차
https://www.youtube.com/watch?v=fClDRsD9nJg

**Comment by EightonEight** [comment]
5, 7호선 열차와 달리 8호선 열차는 전면부에 노선색이 추가되었습니다.

![수정됨_20210618_142802 (2)](https://user-images.githubusercontent.com/77984422/122652702-0a5d4780-d17b-11eb-9dee-2c369f8f6550.png)

![SMETRO_8K_3RD(2)](https://user-images.githubusercontent.com/77984422/122652674-e6016b00-d17a-11eb-9c87-28c65cd749c7.png)
이에 따라 TC칸 스프라이트를 수정하고, 각 스프라이트 위치도 규격(#252)에 맞게 변경해 보았습니다.
