### ISSUE TITLE
새마을호 도색년도 표기오류

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#258]
![텔크 운송의 게임 (2407-11-20)](https://user-images.githubusercontent.com/81477455/124575412-594af280-de86-11eb-8ecc-ad65a2c0e2b8.png)

실제 새마을호 동력열차가 1987년도에 운영을 시작함
openttd에서 도색 개조사용할경우 A도색:1970 1983년도 까지 사용이 되어있는데 
혹시 새마을호 A도색  관광호(새마을호)객차하고 헷갈리신거아닌신지 
많은 유저들이 도색개조 사용하면서 A도색같은경우 1970 1983으로 되어있어가지고 혼란스럽지 않을까 해서 건의 드립니다.

제가  도색리스트 만들어봤습니다.
A도색>철도청 구 도색 : 빨간 & 파란(1987 1994년)
철도청 구 도색 : 녹색 & 노란(1995 2006년) 황색이 아니고 노란이였음
현재도색>코레일 도색 또는 한국철도공사 도색 : 하늘 & 노란(2006 2013년) 
새마을호 객차같은경우 1983년에 등장
관광호 객차가 반영된다면 1969년으로 조정이 필요하지 않을까 싶습니다.

**Comment by EightonEight** [comment]
#241 이 [2.2.0-rc1](https://github.com/KoreanGRF/KoreanTrainSet/releases/tag/2.2.0-rc1)에서 반영되었으므로, #299 와 연계하여 년도를 수정하면 좋을 것 같습니다.

**Comment by telk5093** [comment]
Close by d98c9c470051d2eefe9b08b01eeeee66854cc0fd
