### ISSUE TITLE
분당선 2세대에 4호선 2세대 구도색 추가건의

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#259]
#156 이슈에서 현재 분당선 1세대에만 구도색이  적용이 되어있는데 반면 2세대에는 신도색만 존재하고 구도색이 존재하지 않네요 분당선 2세대 구도색도 1세대처럼 구도색 가능하지 않을까싶네요 4호선 및 분당선에 운영했습니다.

분당선 2세대 구도색 사진
https://m.search.naver.com/search.naver?where=m_image&sm=mtb_jum&query=%EB%B6%84%EB%8B%B9%EC%84%A0+%EA%B5%AC%EB%8F%84%EC%83%89#imgId=r10_image_sas%3Acafe21475912%7C2%7C74375_1966316094

**Comment by telk5093** [comment]
해당 열차가 분당선에서 운행하였다는 근거를 찾지 못했습니다.
첨부하신 링크에 나온 차량 사진에는 '안산'행이 적혀있어서 4호선에서 운행하던 차량으로 보입니다.
해당 열차가 분당선에서 운행했다는 다른 근거를 올려주시기 바랍니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/124792641-22f59c00-df88-11eb-8355-601be06b3dee.png)
해당 열차 도입부터 노란색 도색으로 운행한 것으로 보입니다.

**Comment by EightonEight** [comment]
추가 ref: 
![image](https://user-images.githubusercontent.com/77984422/124792992-8384d900-df88-11eb-8739-f619825aad45.png)
![image](https://user-images.githubusercontent.com/77984422/124793012-87186000-df88-11eb-9299-0c7cb8cc852e.png)
<https://cafe.daum.net/kicha/ANn/9859>
