### ISSUE TITLE
서해선 신조 차량

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#260]
정확한 도입 명칭 (eg. 서해선 n차분) 및 스펙 추후 조사 필요
한국 열차 세트에는 해당 열차가 서해선에 시운전을 시작하는 시기에 잠정적으로 도입하는 것으로...

 * Reference: https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=168585

**Comment by EightonEight** [comment]
![391K_2ND](https://user-images.githubusercontent.com/77984422/128113983-cc1f9e7e-403f-4337-acd9-f4fad3ab6b86.png)
`391K_2ND`

* 원본: `2K_VVVF_3RD` / 참고: `3K_VVVF_1ST_2`, `3XXK_ST`, `391K`
* 스프라이트 크기 한계로 지붕 일부까지 도색한 투톤도색(안)도 추가합니다.
* 추가 ref: <https://gall.dcinside.com/board/view/?id=train&no=1092006>

**Comment by EightonEight** [comment]
![391K_2ND(2)](https://user-images.githubusercontent.com/77984422/144838940-80563967-0082-4e34-a6b4-53350070e15a.png)
* 변경된 도색(추정)
* references: <https://youtu.be/KFEQ7qiDav8>, <https://youtu.be/f96Mz5G9nnk>

**Comment by JukjeonWani** [comment]
2023.04.22
영업운행 시작했다고 합니다.

**Comment by telk5093** [comment]
5f917970c0405e09a4903235f77d87259d4e4828 에서 반영되어 닫습니다.
