### ISSUE TITLE
3등 객차 검정도색 및 빨간도색

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#261]
2021.07.14.수요일 수정
![3등 객차 검정색+빨간도색](https://user-images.githubusercontent.com/81477455/125623061-6ae642a4-46fc-4fcf-a7be-b881e28c2d99.png)

일단 이번에 2.0.0에 업데이트 반영된 3등 객차 도색추가분
이번에 일제강점기때 사용한 3등객차 검정도색분입니다.
3등객차가 1960년대부터 녹색도색으로 변하고나서
1965년부터 빨간도색사용하지않았을까 추정합니다. 
아마 이제 미국에서 가져와서 운영했던 우리나라 1,2등 객차도 시간이 나는데로
별도의 이슈로 올리겠습니다.

사진하고 무관
https://m-en.yna.co.kr/view/PYH20200610095400315

사진
![열차27](https://user-images.githubusercontent.com/81477455/125195713-d369e580-e291-11eb-8926-630c8a7b482b.png)

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.
