### ISSUE TITLE
ITX-새마을 전동차량 수송량

### ISSUE THREAD

**Issue by kudzufatsia** [KoreanGRF/KoreanTrainSet#263]
![itx새마을 수송량](https://user-images.githubusercontent.com/82313174/125696680-e5349e03-2ed1-4249-bbee-0c7da3e38692.png)

일전에 다른 issue에 댓글로 달긴 했지만

ITX-새마을 전동차량 수송량 수정이 되면 좋겠습니다.

선두차는 44명이 맞다고 쳐도, 중간 부수객차/동력객차는 64명 싣게끔 수정하면 어떤지 제안해 봅니다.

실제로 210000호대 전동차량 6량 편성하면 정원이 376명인데, 오픈트타 속에서는 264명으로 되니 고증 오류가 되지 않나 싶습니다.

**Comment by telk5093** [comment]
자세한 정원을 확인해서 사실 관계를 확인한 후에 반영하겠습니다.

**Comment by opentrain** [comment]
http://info.korail.com/mbs/www/subview.jsp?id=www_020109040000 이 자료가 도움되지 않을까싶어
올려봅니다.

**Comment by telk5093** [comment]
https://neuru76.tistory.com/23
 * 1호차(전두부): 58석
 * 2호차: 74석
 * 3호차: 46석 + 장애인석 4석
 * 4호차: 62석
 * 5호차: 74석 (2호차와 동일)
 * 6호차(후두부): 58석

으로 확인되었습니다.
다만, 이건 고정 편성인 경우에만 해당되고, 현재 한국 열차 세트의 ITX-새마을 열차는 자유 편성이 가능하기 때문에 자유 편성에 대한 고민을 해봐야합니다.
일단 전후두부 동력차를 제외하고 객차 4량 부분만 정원 수를 로테이션해서 ``(4n+k)``호차의 정원을 k호차와 동일하게 적용할까 합니다. (eg. 2호차=6호차=10호차... / 3호차=7호차=11호차...)

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/127856866-d2bc40b3-c2a2-4493-8c62-3525d7f2eb5e.png)
위 댓글 내용과 동일하게 적용되었습니다.
