### ISSUE TITLE
[Bug] NDC 동차의 매연이 엉뚱한 곳에서 나옴

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [KoreanGRF/KoreanTrainSet#264]
![bug](https://user-images.githubusercontent.com/81485156/126863029-91e245a6-3522-41de-b7bd-30ed1e808294.PNG)
![bug1](https://user-images.githubusercontent.com/81485156/126863030-c734c739-301d-49e2-a5e5-834da8579b02.PNG)

**Comment by telk5093** [comment]
96e17abca2c84a6b7e75fa19099907679666f9c8 에서 수정었으나 연기가 정가운데에서 나오는 형태로 반영되었고, 전후두부를 별도로 처리하려면 별도의 코드가 필요합니다. 지금은 시간적인 여유가 없어 일단 이대로 반영해둡니다.
