### ISSUE TITLE
통일호에 속력제한 적용 안됨

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#265]
![통일호 150](https://user-images.githubusercontent.com/88026704/127119518-b91d44af-92fd-4847-807c-1d81bab74cd4.jpg)

통일호 객차로만 열차를 조성할 겨우 120km 속력제한 없이 150km로 주행

**Comment by telk5093** [comment]
한국 열차 세트 2.0.0 이후로 모든 객차는 속력 제한이 걸려있지 않습니다.
따라서 화물차 속력 제한을 걸어도 속력 제한이 적용되지 않으므로 버그가 아닙니다.

**Comment by JukjeonWani** [comment]
비둘기호객차에는 110km/h 속도제한이 있습니다. 어느정도 현실고증을 챙기려면 통일호 객차에도 속도제한이 있었으면 하는 바입니다.

**Comment by telk5093** [comment]
> 비둘기호객차에는 110km/h 속도제한이 있습니다. 어느정도 현실고증을 챙기려면 통일호 객차에도 속도제한이 있었으면 하는 바입니다.

그러면 비둘기호 객차에 속력 제한이 있는 게 버그입니다. 해당 부분을 제거하겠습니다.
