### ISSUE TITLE
증기기관차 연기 오류

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#266]
![미카3 연기오류](https://user-images.githubusercontent.com/88026704/127128030-325a937a-8b90-4424-923e-e2d42fa296d7.jpg)
![파시5 연기오류](https://user-images.githubusercontent.com/88026704/127128055-43d81963-9f7c-4053-9c44-1b9f30582394.jpg)
![마터2 연기오류](https://user-images.githubusercontent.com/88026704/127128061-6e44e076-d571-4549-b818-240d17b707c9.jpg)
![혀기7 연기오류](https://user-images.githubusercontent.com/88026704/127128069-2fea405e-cbf2-443a-85c8-2bccc12b8b24.jpg)
한국열차세트의 증기기관차를 보면 탄수차에서도 증기기관차의 연기가 나와 부자연스러운 모습을 보이고 있습니다. 정상적인 경우를 예시로 들기 위해 일본열차세트의 증기기관차에서 연기가 나오는 모습도 캡쳐해 가져왔습니다.
![C57 정상](https://user-images.githubusercontent.com/88026704/127128254-43c17ffd-15b8-4275-b4e5-8bc513af3a3a.jpg)

**Comment by telk5093** [comment]
이미 알고 있던 현상이며 기술적 문제로 해결되지 못했습니다

**Comment by kiwitreekor** [comment]
visual_effect_and_powered callback으로 해결 가능한 이슈 같습니다.

**Comment by Gamunbi** [comment]
오 드디어 고쳤군요..!!
