### ISSUE TITLE
4호선 한국철도공사 2세대 VVVF전동차 고증오류

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#267]
![4호선 2세대 고증오류](https://user-images.githubusercontent.com/88026704/127157849-4158f800-4ccd-4dfb-9692-e64846c05ec3.jpg)
왼쪽에서부터 1호선 2세대 VVVF전동차, 4호선 2세대 VVVF전동차, 4호선 1세대 VVVF전동차입니다. 1호선 2세대 VVVF전동차와 4호선 1세대 VVVF전동차는 비교를 위해 넣었으며 오류가 있는 차량은 4호선 2세대 VVVF전동차입니다. 4호선 2세대 VVVF전동차는 1999년 생산된 전동차로 외부모습으로 봤을때 1세대 VVVF전동차와 전두부 형상만 다르고 나머지는 비슷하게 생겼습니다. 즉, 상부기기또한 집중식이 아닌 준집중식이기때문에 1개가 아닌 2개가 그려져 있어야 고증에 맞습니다. 제가 촬영한 사진 같이 첨부하겠습니다.
![4호선 납작이_20181111](https://user-images.githubusercontent.com/88026704/127158927-e7a26b7d-1d48-408f-a8bc-f7c06c3d7ae3.jpg)
![4호선 동글이_20181111](https://user-images.githubusercontent.com/88026704/127158939-4b0af89b-5389-4ef3-a3a9-4057d644792b.jpg)

**Comment by EightonEight** [comment]
![341K_VVVF_2ND_1](https://user-images.githubusercontent.com/77984422/127262717-ac855d64-1f55-4f8b-b247-4ce35f1e537d.png)
![341K_VVVF_2ND_2](https://user-images.githubusercontent.com/77984422/127262721-70c63d6f-a92e-4e37-9577-3051c3b0c5ae.png)
에어컨을 실제와 맞게 수정하였습니다.

**Comment by JukjeonWani** [comment]
확인했습니다! GRF에 반영되길 기다리겠습니다!

**Comment by telk5093** [comment]
``SMETRO_4K_VVVF_1ST_2ND``
``SMETRO_4K_VVVF_1ST_2ND``

**Comment by JukjeonWani** [comment]
@telk5093 잘못달으신 것 같습니다
