### ISSUE TITLE
'철도청 3k VVVF / 구 도색' 그래픽 오류

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#268]
![#268](https://user-images.githubusercontent.com/77984422/127267109-3a86aa0c-5135-4458-9960-512329235948.png)
해당 도색(위에서 첫번째)에서 외부 공조장치가 실제와 맞지 않으므로 다음과 같이 수정

![3K_VVVF_1ST_1](https://user-images.githubusercontent.com/77984422/127267305-7cc1b0e9-f5dc-416b-b56f-02f3be3d7082.png)

References:
 * <https://youtu.be/RV_3Q2sK3TM?t=25>
 * <https://youtu.be/2p4xu-WoMR4?t=765>
 * <https://youtu.be/8AOSoAeiZBQ?t=15>

**Comment by JukjeonWani** [comment]
추가로 저기 보이는 1,4호선 서울교통공사 3VF는 가로방향 선로에서 서쪽 끝 TC칸 공조기 스프라이트가 잘못되어있습니다.(2개로 보임) 이부분도 확인 부탁드립니다.

**Comment by telk5093** [comment]
> 추가로 저기 보이는 1,4호선 서울교통공사 3VF는 가로방향 선로에서 서쪽 끝 TC칸 공조기 스프라이트가 잘못되어있습니다.(2개로 보임) 이부분도 확인 부탁드립니다.
> ![Screenshot_2021-07-28-17-58-33~2](https://user-images.githubusercontent.com/88026704/127295194-a330539d-a006-4432-b8da-61e2bd22a9c2.png)

별개의 이슈로 등록 바랍니다.

**Comment by telk5093** [comment]
``3K_VVVF_1ST_1``
