### ISSUE TITLE
서울교통공사 1000호대, 4000호대 공조기 스프라이트 오류

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#269]
![Screenshot_2021-07-28-17-58-33~2](https://user-images.githubusercontent.com/88026704/127308491-6f959ea0-29ea-4576-80aa-6ba4dd7d0cdd.png)
사진에 보이는 것처럼 (게임기준)가로방향 선로에서 서쪽 끝 TC칸의 공조기 스프라이트가 2개로 보이는 문제가 있습니다.

**Comment by EightonEight** [comment]
![SMETRO_1K_VVVF](https://user-images.githubusercontent.com/77984422/127337474-d24cdae0-2288-4950-8a05-b2a84af60d22.png)
![SMETRO_4K_VVVF_1ST_2ND (2)](https://user-images.githubusercontent.com/77984422/127337482-641ecd0a-10ce-4b83-a402-fb5b78599717.png)
해당 오류를 수정한 스프라이트입니다.

**Comment by telk5093** [comment]
``SMETRO_1K_VVVF``
