### ISSUE TITLE
코레일 전동차 스프라이트 개선 및 추가

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#271]
### 1. 개선 ###
![371K_381K_1ST](https://user-images.githubusercontent.com/77984422/127517440-f258b991-c864-4a64-90eb-3e8dc04cf263.png)
`371K_381K_1ST`
* **팬터그래프를 실제와 같은 싱글암으로 수정**(ref: <https://youtu.be/_RhdhVMXt8I?t=115>, <https://youtu.be/ZaxxEpKWaCs?t=240> )
---
![371K_BLANK](https://user-images.githubusercontent.com/77984422/127517643-4eadc396-7bed-4084-837e-a2f4b18de54a.png)
`371K_BLANK`
* **팬터그래프를 실제와 같은 싱글암으로 수정**(ref: <https://youtu.be/33N2CkX0S8U?t=60> )
---
![LINE_1_2019](https://user-images.githubusercontent.com/77984422/127520300-c8df9832-62cf-4dd6-8c13-d967214a2b87.png)
`LINE_1_2019`
* 스프라이트 크기 변경(운전실 칸, 코드 작업 시 좌표 재정렬 필요)
---
![LINE_4_2019](https://user-images.githubusercontent.com/77984422/127518814-8c894c2d-84b1-441f-b757-bbb8b58ff434.png)
`LINE_4_2019`
* **팬터그래프 개수를 실제와 같게 수정**(도입 시 1개였으나 시운전 후 2개로 개조됨, ref: <https://youtu.be/nHPvSRezalQ>, <https://youtu.be/lDBwwUrLnIc?t=255> )
* 스프라이트 크기 변경(팬터그래프 칸, 운전실 칸, 코드 작업 시 좌표 재정렬 필요)
---
### 2. 추가 ###
![371K_CC](https://user-images.githubusercontent.com/77984422/127517723-d95db791-fb7e-45d1-9c29-dff9ab284070.png)
`371K_CC`
* 회사 색상(Company Color) 적용 버전(_무도색 버전도 있으니 회사 색상 버전도...?_)
---
![3XXK_ST_SINGLE_ARM](https://user-images.githubusercontent.com/77984422/127511812-b017ea70-dee8-41f8-b213-c67303826dab.png)
`3XXK_ST_SINGLE_ARM`
* `3XXK_ST`의 싱글암 버전 추가([e5ec117](https://github.com/KoreanGRF/KoreanTrainSet/commit/e5ec1170ab6ab2359e7dc09d4e50797e88a02c37#diff-404d64ab6de69932519365cdada1163639e6b3cd5b960a2502adf916a21706f2)와 같이 무작위로 적용, ref: <https://youtu.be/-L6JXy43w3g?t=45> )

**Comment by EightonEight** [comment]
> * 스프라이트 크기 변경(운전실 칸, 코드 작업 시 좌표 재정렬 필요)

![#271-2](https://user-images.githubusercontent.com/77984422/127599368-61a9c5cb-389e-4283-82a6-006fe0d62c66.PNG)
@telk5093 이 방향의 운전실 칸만 길이가 짧은데, 의도하신 부분인가요?

**Comment by telk5093** [comment]
> > * 스프라이트 크기 변경(운전실 칸, 코드 작업 시 좌표 재정렬 필요)
> 
> ![#271-2](https://user-images.githubusercontent.com/77984422/127599368-61a9c5cb-389e-4283-82a6-006fe0d62c66.PNG)
> @telk5093 이 방향의 운전실 칸만 길이가 짧은데, 의도하신 부분인가요?

@kiwitreekor

**Comment by kiwitreekor** [comment]
붙여넣기가 잘못 된 것 같네요. 창문쪽이 오른쪽으로 1px 밀려있네요. 수정하셔도 될 것 같습니다.

**Comment by EightonEight** [comment]
> ![LINE_1_2019](https://user-images.githubusercontent.com/77984422/127520300-c8df9832-62cf-4dd6-8c13-d967214a2b87.png)
> ![LINE_4_2019](https://user-images.githubusercontent.com/77984422/127518814-8c894c2d-84b1-441f-b757-bbb8b58ff434.png)

그렇다면 해당 사항이 수정된 이 파일 그대로 작업하시면 될 것 같습니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/127850585-ac7e7ea7-96aa-49c5-a7af-1d76042e6d5f.png)
@EightonEight ``381KK_2ND`` 역시 길이가 짧으므로 작업 부탁드립니다.

**Comment by telk5093** [comment]
5e72c696a10243cbc4723dc6f4f61ff738e00c20 에 반영되었습니다.
