### ISSUE TITLE
객차 (구한말~일제강점기)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#275]
![객차 구한말~일제강점기 1차 완성](https://user-images.githubusercontent.com/75788864/136677692-6f1efc83-472a-4217-9875-b5e8491c3910.png)

|코드|이름|수송량|길이|무게|도입년도|추천 제한속도|
|-|-|-|-|-|-|-|
|``ko_train_PASSENGER_CAR_MODERN``|객차|84명?|6|?톤|1899년|75km/h?|
|``ko_train_PASSENGER_CAR_DA3``|객차|104명|8|30톤|1912년|95km/h?|
|``ko_train_PASSENGER_CAR_DA8``|객차|128명|8|42.7톤|1933년|95km/h?|

- 1899년 객차
최초의 객차입니다. 물음표는 정보가 없다는 뜻입니다. 텔크님이 임의로 정해주시면 되겠습니다.

- 1912년 객차
일제 초기 많이 쓰였던 '다 3형' 객차 중의 한 형태입니다. 

- 1933년 객차
일제 후기 주로 쓰였던 '다 8형' 객차 중 한 형태입니다.

이 시대 객차를 모두 구현한 것은 아닙니다. '~중의 한 형태' 라고 썼듯이, 이 사이사이에 여러 종류의 객차가 제작되었습니다. 제가 보기에 스펙이 비슷하거나 외형상 흡사한 것들은 굳이 제작할 필요성을 느끼지 못해 모두 뺐습니다.  

**후대에 등장한 객차들과 비교해, 무겁지만 수송량이 상위호환입니다. 속도제한(95km/h 정도)같은 걸 주는 게 좋을 것 같습니다.**

레퍼런스
![Screenshot 2021-08-20 at 23-24-25 1장 8부 객차 pdf](https://user-images.githubusercontent.com/75788864/130258005-bf5f8c2a-e0fc-40c0-835a-1a5ea9d08fe0.png)
![Screenshot 2021-08-20 at 22-13-09 1장 8부 객차 pdf](https://user-images.githubusercontent.com/75788864/130258024-8423b101-e7a6-4e06-8962-c822dca8f410.png)
출처: 한국철도차량 100년사 (1999) 1장 8부 객차

**Comment by Gamunbi** [comment]
꼭 바로 추가하실 필요는 없습니다. 왜냐하면 동시대에 쓰였던 기관차를 아직 안 만들었기 때문에..

**Comment by opentrain** [comment]
일제강점기때 운영했던 경객차입니다.

경객차운영 내용을 보니 3등 객차로 개조해서 운영했다고 합니다.
![3등객차 경객차](https://user-images.githubusercontent.com/81477455/135752840-ffdb5d0d-7b0c-4aca-ad3c-76c5a4b02b96.png)
크기가 너무 크면 다시 조정하도록 하겠습니다. 얘가 두가지 종류가 있긴한데 큰거 작은거 있긴한데
우선 큰쪽만 만들었습니다.

경객차 내용설명
![image](https://user-images.githubusercontent.com/81477455/135753734-8119019a-d8e9-4a64-a3b0-0272303450e0.png)
수송량같은경우 기존 한국열차세트에 있는 3등객차로 활용하면될듯합니다.
생산년도:1925년
톤은 26톤이라고 합니다.
일단 제가 아는 이열차도색는 검정색정보만 얻었습니다.
다른도색 없습니다. 1969년까지 사용한거로 압니다.


레퍼런스:https://www.koreatimes.co.kr/www/nation/2018/06/721_249224.html
경객차사진
![image](https://user-images.githubusercontent.com/81477455/135752887-1d506daa-d248-4399-9f04-8d7aed9239c8.png)

**Comment by Gamunbi** [comment]
제가 만든 건 다형이고 opentrain 님께서 올리신 건 거다형입니다. 이슈를 따로 만드는 게 더 좋울 것 같습니다.

**Comment by opentrain** [comment]
알겠습니다. 이슈따로 만들어서 처리하겠습니다.

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.

**Comment by SerpensNebula** [comment]
다른 GRF로 독립해서 열지 않으셔도 됩니다.
