### ISSUE TITLE
증기기관차 터우 5·6형 추가

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#277]
![터우](https://user-images.githubusercontent.com/75788864/130357350-6d169d6d-d9e0-4c82-9ae8-81483253d7fa.png)

- 터우형
원래 6형만 적용하려고 했는데, 아까워서 추가했습니다. 도입년도와 무게만 살짝 다르고, 외관상으로나 스펙상으로나 큰 차이는 없어서 합치고 개조로 구분하시면 됩니다.  뭐 분리하셔도 상관없습니다.

둘 다 힘 정보는 찾을 수 없었습니다. 다음 세대 여객용 기관차인 파시 5형이 약 1000마력이므로 이보다 살짝 낮게 하면 될 것 같습니다.

- 공통 스펙
  - 힘 : 800마력? 내외로 하시면 될 듯?
  - 길이 : 기관차 7, 탄수차 4
  - 최고 속도 : 95km/h

- 터우 5형
  - 도입년도 : 1917년
  - 중량 : 115.97톤

- 터우 6형
  - 도입년도 : 1927년
  - 중량 : 123.6~131.2톤

기관차는 사이즈가 서로 같지만 탄수차는 ↗→←↖방향이 살짝 다릅니다.

**Comment by SerpensNebula** [comment]
다른 GRF로 독립해서 닫습니다.

**Comment by SerpensNebula** [comment]
다른 GRF로 독립해서 닫습니다.
