### ISSUE TITLE
수인분당선 1세대 VVVF 신도색 공조기 스프라이트가 잘못됨 

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#281]
![화면 캡처 2021-09-05 155301](https://user-images.githubusercontent.com/88026704/132118330-1c3c58cd-9faf-4f3e-9633-5ba592de5cd3.jpg)

**Comment by EightonEight** [comment]
![351K_VVVF_1ST](https://user-images.githubusercontent.com/77984422/132119265-f4542a42-6c42-4078-baa3-a45765306d69.png)
`351K_VVVF_1ST`
해당 오류(M', TC칸)을 수정한 스프라이트입니다.

**Comment by telk5093** [comment]
ed24fd2 에서 수정 반영되었습니다.
