### ISSUE TITLE
의정부 경전철 수정

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#283]
![경전철 의정부 3차 완성](https://user-images.githubusercontent.com/75788864/134772667-8ab501f5-753d-4e9b-9d5b-0a781cdf9170.png)

방향별로 폭이 어울리게 조정했습니다.  스프라이트 사이즈는 바뀌지 않았습니다.

**Comment by telk5093** [comment]
Closed by 00ecc70f546798b04623e65cbc561df427da991c
