### ISSUE TITLE
또다른 미카형 1952년 증기기관차 추가

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#286]
@Gamunbi 이분이 만든 미카3형 증기기관차는 활용해서 미카5형 증기기관차로 개조했습니다.

미카5형 수정예정

미카3형으로 개조 했는데 어색함이 있을수도 있을겁니다.

미카5형 증기기관차 실물사진
![image](https://user-images.githubusercontent.com/81477455/135715223-81bc54a2-074a-4c87-b0f2-2e20168aca85.png)

미카형 증기기관차들 레퍼런스
https://namu.wiki/w/%EB%AF%B8%EC%B9%B4%ED%98%95%20%EC%A6%9D%EA%B8%B0%EA%B8%B0%EA%B4%80%EC%B0%A8#s-2.5

그외의 미카형 증기관차 1형,2형,4형,6형,7형을 이것도 일단 완성하고 이 이슈로 통해서 올리겠습니다.

**Comment by Gamunbi** [comment]
좀 더 사진과 비슷하게 수정 부탁드립니다.

**Comment by opentrain** [comment]
@Gamunbi 예 알겠습니다.
