### ISSUE TITLE
일제강점기 경객차

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#288]
일제강점기때 운영했던 경객차입니다.

경객차운영 내용을 보니 3등 객차로 개조해서 운영했다고 합니다.
![3등객차 경객차](https://user-images.githubusercontent.com/81477455/135752840-ffdb5d0d-7b0c-4aca-ad3c-76c5a4b02b96.png)
크기가 너무 크면 다시 조정하도록 하겠습니다. 얘가 두가지 종류가 있긴한데 큰거 작은거 있긴한데
우선 큰쪽만 만들었습니다.

1936년에 운영시작한 아카쓰키호 통일호전신도색 열차
![경객차 아카스끼](https://user-images.githubusercontent.com/81477455/135857514-27945ecc-cb43-4d4e-9fff-6f198d8f7d4e.png)
수송량:72
무게:32.1톤
일단 이열차도 경객차로 개조해서 만들었다고하길래
경객차로 활용한 아카쓰키호열차로 만들어봤습니다.
사진은 보니 지붕있는것도 있고 없는것도 있습니다.

경객차 내용설명
![image](https://user-images.githubusercontent.com/81477455/135753734-8119019a-d8e9-4a64-a3b0-0272303450e0.png)
수송량:112명
생산년도:1932년
톤은 26.5톤이라고 합니다.
일단 제가 아는 이열차도색는 검정색정보만 얻었습니다.
다른도색 없습니다. 1969년까지 사용한거로 압니다.

레퍼런스:https://www.koreatimes.co.kr/www/nation/2018/06/721_249224.html
경객차 흑백사진
![image](https://user-images.githubusercontent.com/81477455/135752887-1d506daa-d248-4399-9f04-8d7aed9239c8.png)

경객차 컬러사진
![경객차 컬러사진](https://user-images.githubusercontent.com/81477455/135754744-d67ed974-41ff-4d3d-8d26-119aae12f98b.jpg)

**Comment by telk5093** [comment]
새 객차를 추가하기에는 그닥 쓸모가 없고, 객차가 너무 많아지는 단점이 있기 때문에
새 열차를 추가하지 않고 3등 객차 등에 도색 개조로 추가할 생각이므로 livery 태그를 붙였습니다.

**Comment by Gamunbi** [comment]
알겠습니다.

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.

**Comment by SerpensNebula** [comment]
한국초기열차세트에 적용되었기 때문에 리오픈하지 않으셔도 됩니다.
