### ISSUE TITLE
(일제강점기~해방후) 옛날구형통일호도색

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#289]
저기 아래에 있는 사진은 보니 3등객차같다는 느낌이 들어서 만들어봤습니다.
1906년부터 융희호>초특급 아카츠키호>8·15해방 후 조선해방자>1955년 남북통일의 염원을 담아 통일호

검정도색
![1938년 3등객차](https://user-images.githubusercontent.com/81477455/136005490-49535519-c981-401a-9ee8-4e878e60a987.png)
일제강점기에서 해방후 1969년까지 사용한 구형통일호 열차로 압니다.
해당열차는 한국열차세트에 있는 3등객차 크기참고해서 직접 만들었습니다.
추후 계획 69년대까지 사용한 도색도 추가예정

1938년 3등객차 사진
![image](https://user-images.githubusercontent.com/81477455/135997427-1c27d3cb-05f3-4b5e-910a-643984ce5f5e.png)

통일호 검정도색
![통일호 검정도색 컬러](https://user-images.githubusercontent.com/81477455/136006157-930e515f-3caa-4425-9178-7f12852707af.jpg)

1938년 3등 검정색객차
![image](https://user-images.githubusercontent.com/81477455/135999027-8e64801c-9905-4f72-beac-5535fb0a4a0e.png)
탄수차에서 2번째칸에 있는 객차가 3등 객차 통일호검정도색으로 압니다.
혹시나 작업하시는분이 계시지 모르겠지만 제가 일단 만들어두었습니다.

**Comment by Gamunbi** [comment]
제 이슈의 https://github.com/KoreanGRF/KoreanTrainSet/issues/275#issue-975724272 3등 객차 다8형이 현재 글에 있는 객차 자료를 포함해서 만든겁니다(이슈 본문에도 적혀있다시피 등장년도가 비슷하거나 스펙이 같은 여러 객차중 하나를 적당하게 추려냄). 

그리고 http://info.korail.com/mbs/www/subview.jsp?id=www_020102000000 이 글을 보시면 아시겠지만, 당시에는 열차이름이 굉장히 많았습니다. 현재 한열셋의 객차 구분법대로 구분하면 사실 통일호 뿐만 아니라 재건호, 태극호, 맹호호, 건설호.... 등등의 객차들도 다 만들어야 합니다. 이것이 제가 비둘기호를 제작할 때 비둘기호의 등장년도를 30년대까지 당기려고 하려다가 그냥 1960년대까지만 반영했던 이유입니다. 혹시 다른 객차들을 더 만드려고 하실까봐 알려드립니다.

저는 이 이슈까지는 그럭저럭 괜찮다고 생각하지만, 이보다 더 많은 객차가 더 생길 필요는 없을 것 같습니다. 생긴다면 침대차(다치형 객차)나 식당차(다시형 객차)는 괜찮을 것 같습니다.

**Comment by opentrain** [comment]
![Screenshot_20211005-234516_NAVER](https://user-images.githubusercontent.com/81477455/136046145-f501c123-71a0-451a-bda0-151f7c6914b2.jpg)
위에서 말씀한거처럼 그외의 열차는 저도 자료부족으로 할 생각이 없습니다. 현재 있다면 도색추가외에는 없을듯 합니다.

**Comment by telk5093** [comment]
지금 당장 한국 열차 세트에서 굳이 필요하지 않을 것 같습니다.
따라서 이슈는 닫아두겠습니다.
