### ISSUE TITLE
현재 있는 화차들의 스펙 재조정 필요

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#291]
![호퍼차](https://user-images.githubusercontent.com/75788864/136032214-37b8d02b-73be-42cd-a713-c768186cdd3d.jpg)
![유조차](https://user-images.githubusercontent.com/75788864/136032231-06177a41-71f6-4dea-a359-f42f86064e46.jpg)
![컨테이너_평판차](https://user-images.githubusercontent.com/75788864/136032247-299116fc-c930-429f-bb33-4f7abbec2caf.jpg)
![113272660-d0686c00-9316-11eb-9adb-886b94d54233](https://user-images.githubusercontent.com/75788864/136033357-cca9401c-6288-4659-b832-7a5c7b90af39.png)

https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=cabin5786&logNo=221330552593
링크의 블로그 글에 의하면 현재 한열셋에 구현된 화차들의 기본 수송량(하중)은 50톤이 되어야 합니다. 현재는 (1배 기준)34톤으로 되어 있습니다. 

그리고 무게(자중)도 살짝 조정해야 합니다. 호퍼차는 24톤으로, 조차는 21톤, 평판화차는 17.7톤으로 현재 구현된 17톤과 거의 같지만 분명 다릅니다(단 코일평판차는 수송량 52톤에 무게 22.9톤으로 일반 평판차와 약간 다름).

![001](https://user-images.githubusercontent.com/75788864/136035006-871bc694-6abe-4786-a4fc-8fa0ae14f8ab.png)
![002](https://user-images.githubusercontent.com/75788864/136035022-fcf36049-d971-4c8a-acb2-a3390b8c066e.png)

또 평판화차(장물차)의 경우, 게임에서는 1950년 등장으로 되어있지만, 실제로는 1930~40년대에 등장한 걸로 보입니다. 저 사진에 있는 평판차가 지금 게임에 있는 평판차의 모델과 흡사한 종 or 같은 종인지는 모르겠지만, 외관상으로는 맨 위의 사진에 있는 현대 평판차와 같아보입니다. 물론 확실한 건 아니니, 이 부분은 좀 더 논의가 필요합니다.

**이슈에서 제안하는 스펙 표**
|코드|개임내 이름|최초 도입년도 (같은 생김새와 스펙을 가진 화차 중 가장 이른 년도)|수송량|무게|비고|
|-|-|-|-|-|-|
|``HOPPER_CAR``|무개화차|1972년?|50톤|24톤|https://github.com/KoreanGRF/KoreanTrainSet/issues/157#issue-848290527|
|``TANK_CAR``|유조차|1968년?|50톤|21톤|-|
|``STAKE_CAR``|컨테이너 평판화차|1972년?|50톤|18톤|https://github.com/KoreanGRF/KoreanTrainSet/issues/157#issue-848290527|
|``FLAT_CAR``|평판화차(장물차)|1937년 or 1940년|52톤|23톤|https://github.com/KoreanGRF/KoreanTrainSet/issues/157#issue-848290527|

**Comment by Gamunbi** [comment]
혹시 이 이슈를 반영하게 된다면, 1930~40년대 화차들 추가보다 먼저 해주세요.

**Comment by EightonEight** [comment]
#80 과 작업을 연계하면 좋을 것 같습니다.

**Comment by opentrain** [comment]
1940년 평판화차
혹시 몰라서 이미지 2개 준비해봤습니다.
![image](https://user-images.githubusercontent.com/81477455/136150709-7f323adc-6b06-4138-b306-5e96ca315b15.png)
![image](https://user-images.githubusercontent.com/81477455/136150872-c60c557e-b623-46be-92d6-8b0bf25912ca.png)

https://www.youtube.com/watch?v=E-LgisCFLa8
6:50~7:00사이 보시면될듯합니다.

**Comment by opentrain** [comment]
30톤을 굳이 기존 평판화차가 별차이 없을거 같습니다. 제가 사진 올린건중에 두번째 사진에 있는 목재 싣는 열차가 1940년에 사용한 평판차 아닐까싶습니다.
이것도 부족하면 제가 다른 사진으로 구해보겠습니다
