### ISSUE TITLE
코레일 전동차('19, '21 도입분) 스프라이트 개선 및 추가

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#295]
### 1. 개선 ###
![381K_2ND](https://user-images.githubusercontent.com/77984422/139524475-cd8037d3-6716-41c1-93c6-6162631cb3f4.png)
`381K_2ND`
* **운전실 부분 수정**(ref: <https://images.app.goo.gl/wLBDxSgutMQra9Vq6> )
---
![LINE_1_2019](https://user-images.githubusercontent.com/77984422/139524057-0c74c593-efc2-47a3-8609-52a1cbdee6b5.png)
`LINE_1_2019`
* **운전실 부분 수정**(ref: <https://images.app.goo.gl/X6qjDNJhLHVD2ARWA> )
---
![LINE_4_2019](https://user-images.githubusercontent.com/77984422/139524133-0187cc6d-cf5d-40df-9ec1-cb0d306fa509.png)
`LINE_4_2019`
* **운전실 부분 수정**(ref: <https://images.app.goo.gl/Q9pTbWi69Qvb78JZ9> )
---
### 2. 추가 ###
![LINE_1_2021](https://user-images.githubusercontent.com/77984422/139524186-fefb3561-215f-45c4-a51e-a12ef29eebea.png)
`LINE_1_2021`
* from #199 
* 운전실 부분 수정(ref: <https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=174857>)
* 운전실 공조장치 위치 조정
* 도색 개선
---
![LINE_4_2021](https://user-images.githubusercontent.com/77984422/139524377-46f92fb2-119f-4dad-bb37-0735aced3000.png)
`LINE_4_2021`
* ref: <https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=202883>
---
![351K_2021](https://user-images.githubusercontent.com/77984422/139524407-701a9027-1c0b-4b82-a37a-b41579dcd6cf.png)
`351K_2021`
*  ref: <https://images.app.goo.gl/Au38iSmaYbxRKXeN7>, <https://youtu.be/Vnv6h7BOqeM?t=20>
---
(실차 공개 후 업로드 예정)
`LINE_3_2021`

---
위 스프라이트들은 이전 것과 크기가 동일하므로 코드 작업 시 좌표 재정렬할 필요가 없습니다.

**Comment by telk5093** [comment]
``LINE_3_2021``은 추후에 본문에 본 이슈 번호를 참조하여 별도 이슈로 올려주세요.

**Comment by JukjeonWani** [comment]
``Line_4_2019``, ``Line_4_2021`` 해당차량 싱글암 판토를 더블암으로 교체하는 작업이 진행될 것 같습니다.
![image](https://user-images.githubusercontent.com/88026704/181263573-7921f1ac-a93b-485c-b1c2-a236245a76cd.png)
https://www.open.go.kr/othicInfo/infoList/infoListDetl2.do

**Comment by EightonEight** [comment]
@JukjeonWani 이미 스프라이트를 제작하였으나, 실물 사진이 공개된 이후에 별도의 discussion으로 올리도록 하겠습니다.
