### ISSUE TITLE
DC디젤동차 또다른 1980년도 도색관련

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#297]
레퍼런스:https://namu.wiki/w/%EA%B4%91%EC%9A%B4%EB%8C%80%EC%97%AD#s-6
![image](https://user-images.githubusercontent.com/81477455/141644203-a4f462f9-730d-4819-a5e3-d61687f29232.png)
이열차가 혹시 말로만 들었던 코코아 열차도색인지 아니면 다른도색인지가 알수가 없어서 다른분들 도움이 필요합니다.

**Comment by EightonEight** [comment]
추가 ref: <https://gall.dcinside.com/mgallery/board/view?id=monorail&no=3742>, <https://station215.tistory.com/91>

해당 글에 따르면 보급열차 등급의 도색으로 보입니다.

**Comment by opentrain** [comment]
보급열차 도색 반영
@EightonEight 감사합니다. 덕분에 열차도색을 추가했습니다.
![Uploading 보급열차 도색.png…]()
1974~1983년까지 운영했던 보급열차 도색입니다.
저기위에 있는 사진으로 보아하니 객차도색도 존재해서 객차도색도 넣었습니다.
비둘기호객차 갈색도색활용해서 개조했습니다.
보급열차같은경우 1984년부터 통일호로 통합되서 운영했다고합니다.

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.
