### ISSUE TITLE
도시철도 전동차 스프라이트 개선

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#303]
![2K_VVVF_3RD](https://user-images.githubusercontent.com/77984422/149184927-7009e9e8-7c14-4150-b873-1f97b48599f2.png)
`2K_VVVF_3RD`
* **기관실용 공조장치 추가**(ref: <https://images.app.goo.gl/6CkFhJgnNe21K3wD7>)
* 배장기 부분 수정
---
![INCHEON_METRO_1K_VVVF_1ST](https://user-images.githubusercontent.com/77984422/149184959-619050b3-d802-4b00-9855-ad9ddc4fa2d5.png)
`INCHEON_METRO_1K_VVVF_1ST`
* **운전실 부분 수정**(ref: <https://images.app.goo.gl/FxmdKRQN7jcH62MEA>)
* 도색 수정
---
![DAEJEON_METRO_1K](https://user-images.githubusercontent.com/77984422/149185002-bd46a3d1-da7f-4791-a066-2f212c37a6a6.png)
`DAEJEON_METRO_1K`
* **운전실 부분 수정**(ref: <https://images.app.goo.gl/4FJ6MsyvVRJWpcYD7>)
* **도색 수정**
---
![DAEGU_METRO_2K](https://user-images.githubusercontent.com/77984422/149185158-f7b551c3-61f8-4d15-b389-3a81d8a2790d.png)
`DAEGU_METRO_2K`
* **운전실 부분 수정**(ref: <https://images.app.goo.gl/mLpaUtXcxUizLhMr8>)
* 도색 수정
---
![GWANGJU_METRO_1K](https://user-images.githubusercontent.com/77984422/149185193-a16dcbdd-a778-44f7-ad58-410512c7cf3b.png)
`GWANGJU_METRO_1K`
* **운전실 부분 수정**(ref: <https://youtu.be/tA8w293kgho?t=30>)
* 도색 수정
---
![BUSAN_METRO_1K_2ND](https://user-images.githubusercontent.com/77984422/149185261-92a6229b-287b-459d-be7b-ef9be76e2658.png)
`BUSAN_METRO_1K_2ND`
* **운전실 부분 수정**(ref: <https://images.app.goo.gl/bKU4kE41fK7DpFeF6>)
* 도색 수정
* 운전실 부분 출입문 위치 교정
---
![BUSAN_METRO_3K](https://user-images.githubusercontent.com/77984422/149185315-26480685-1a01-4175-a966-57a1ac7f0645.png)
`BUSAN_METRO_3K`
* **운전실 부분 수정**(ref: <https://images.app.goo.gl/7zeqFrt2VxDZqrF1A>)
* 도색 수정
---
_OpenTTD 팔레트 적용 완료 (2022.01.13)_

**Comment by telk5093** [comment]
OpenTTD 팔레트 적용하여 반영 예정
