### ISSUE TITLE
서울교통공사 4호선 신차 4차분

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#304]
#51 이스프라이트는 활용해서 올해 2022년 9월에 반영된다는 4호선 신차 4차분을 만들어봤습니다.

2022.1.1 4안 디자인 
![4K_SMETRO_VVVF_4ND](https://user-images.githubusercontent.com/81477455/147849193-5e054b11-2ef2-4c69-9bbe-4d40ef43d0cd.png)
 
2022.1.14 3안 디자인
![4K_SMETRO_VVVF_4ND 3안 디자인](https://user-images.githubusercontent.com/81477455/149524690-1a8ddad5-158d-4d6c-b8f2-839a9039f205.png)

3안디자인 같은경우는 4안 디자인으로 활용해서 수정했는데 어색함이 있을수도 있습니다.

혹시나 모르니 나중에 디자인 3,4안중 하나 도입되지않을까 추정해봅니다.

레퍼런스:
11https://namu.wiki/w/%EC%84%9C%EC%9A%B8%EA%B5%90%ED%86%B5%EA%B3%B5%EC%82%AC%204000%ED%98%B8%EB%8C%80%20VVVF%20%EC%A0%84%EB%8F%99%EC%B0%A8#s-3.4

다원시스 서울교통공사 4호선 차량조감도 :http://dawonsys.com/kr/business/business_04_01.php

**Comment by EightonEight** [comment]
서울시에서 진행한 [디자인 선호도 조사](https://mvoting.seoul.go.kr/mvoting/voting/policyvote/selectPolicyvote.do?vote_no=57003)에 따르면 다른 디자인이 선정된 것으로 보입니다.

실제 제작된 사진이 나와야 정확하게 확인이 가능할 것 같네요.

**Comment by opentrain** [comment]
일단 혹시나 모르니 4안디자인을 활용해서 3안 디자인으로 수정했습니다. 
도색자료사진 감사합니다.^^

**Comment by JukjeonWani** [comment]
https://cafe.naver.com/smartvip/200346

래퍼런스입니다 3안으로 제작되는 듯 합니다

**Comment by n0373** [comment]
![Uploading 482ab20e2a98cdb2821d223b3c205e81040b5ceb0c299b46a3ae414392db93adda8019e166e63fd2374838062057759f367ee5ac1bdb35832e2ef91114408f3d575b27eefbd4f77d31f9fddad935d7dd80f2d87094f12053a4ede48969d48f6a38ad9e208710b802d38bb5e6137ee0f6.jpeg…]()

**Comment by EightonEight** [comment]
![SMETRO_4K_VVVF_4TH](https://user-images.githubusercontent.com/77984422/194470334-0bf497c5-28cf-4e90-9681-a25dad31bb82.png)
`SMETRO_4K_VVVF_4TH`

실차 사진이 공개되어 스프라이트를 이에 맞게 수정해 보았습니다.

ref: 
<https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=327142>
