### ISSUE TITLE
한국철도공사 220000호대 전동차 (ITX-마음)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#307]
![전동차 220000호대 - ITX-새마을 3차 완성](https://user-images.githubusercontent.com/75788864/182014704-997870a5-c8ca-4d0c-b639-3e928a995ecd.png)
![전동차 220000호대 - ITX-새마을 3차 완성 2](https://user-images.githubusercontent.com/75788864/182014705-8ab902df-c748-4549-8d62-000ae0667504.png)
↑일반 버전

![전동차 220000호대 - ITX-새마을 3차 완성 32bpp](https://user-images.githubusercontent.com/75788864/182014710-2b8c7d12-a408-417e-9e9c-664d442fecb4.png)
↑32bpp 버전(실제 색상에 보다 더 가까움, 검은 부분이 훨씬 더 어두움)

적힌 사이즈의 윗줄에 놓인 스프라이트는 모두 그 사이즈입니다. 스프라이트 정렬도 동일합니다.

![전동차 220000호대 - ITX-새마을 3차 완성 32bpp 예](https://user-images.githubusercontent.com/75788864/182014735-567486aa-7de4-44d2-8524-f997164af211.png)

**스프라이트 조정하는 방법**
**1. 우선 모두 일반 객차(예를 들면 통일호 객차)와 같게 합니다.**
**2. 3px씩 위로 올립니다.**

_8x22 가 아니라 8x25이고, 21x18이 아니라 21x20 입니다. 잘못적었습니다;;_

-----------------------------------------------------------------------
다음은 똑같은 스프라이트를 [이 크로마키](https://github.com/KoreanGRF/KoreanTrainSet/issues/369#issuecomment-1545788167)에 맞춘 버전입니다.

-----------------------------------------------------------------------
7월 24일 수정
![전동차 220000호대 - ITX-새마을 3차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/6b95625d-18a7-4354-b21b-a0992a581314)
![전동차 220000호대 - ITX-새마을 3차 완성 32bpp](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/21d55aa9-0bed-40e9-ba11-7bc832b4791b)

수정사항: 전후두부를 똑같이 함, ↑방향 1px 아래로 어긋나있던 점 수정

https://namu.wiki/w/ITX-%EC%83%88%EB%A7%88%EC%9D%84/%EC%B0%A8%EB%9F%89?from=%EC%BD%94%EB%A0%88%EC%9D%BC%20220000%ED%98%B8%EB%8C%80%20%EC%A0%84%EB%8F%99%EC%B0%A8#s-3.2

**Comment by evepoi** [comment]
이차량이 개발중인 EMU-150이였던가요?

**Comment by Gamunbi** [comment]
> 이차량이 개발중인 EMU-150이였던가요?

나무위키에 의하면 같은 건가봅니다. 저는 itx-새마을의 새 차량으로 간주하고 작업했습니다.

**Comment by evepoi** [comment]
> > 이차량이 개발중인 EMU-150이였던가요?
> 
> 나무위키에 의하면 같은 건가봅니다. 저는 itx-새마을의 새 차량으로 간주하고 작업했습니다.

이 열차 맘에 드는데, grf로 추가되는 시기가 언제일지 모르겠죠? ㅠ

색상만 바꾸어 주시거나 선공개여부를 여쭤보고 싶습니다.

**Comment by Gamunbi** [comment]
> 색상을 다르게 한다면. YST로 추가했으면 하는 바람이 있어서 조심스레 의견을 드려봅니다

어떻게 바꾸면 될까요? 회사색상 같은거 말씀하시는 건가요?

**Comment by evepoi** [comment]
> > 이 열차 맘에 드는데, grf로 추가되는 시기가 언제일지 모르겠죠? ㅠ
> > 색상만 바꾸어 주시거나 선공개여부를 여쭤보고 싶습니다.
> 
> 한열셋에 언제 추가될지는 코딩작업자분에게 달려있습니다.
> 
> > 색상을 다르게 한다면. YST로 추가했으면 하는 바람이 있어서 조심스레 의견을 드려봅니다
> 
> 어떻게 바꾸면 될까요? 회사색상 같은거 말씀하시는 건가요? 단순히 색만 바꾸는 것은 금방 합니다.

YST에선 주로 녹색을 주색으로 하고 있습니다. 그외 색은 자유롭게 변경해도 나쁘지 않을듯합니다.
우선 녹색으로 (회사색상 제외)로 YST이슈로 업로드해주시면 적용해보도록 하겠습니다.

**Comment by opentrain** [comment]
![차세대 EMU-150](https://user-images.githubusercontent.com/81477455/149505469-fa371967-65ba-4c0b-8a6b-51f6607e6713.png)
진작에 찍어놓긴했는데 이 이슈에 올라와서 한번 올려보겠습니다.
ITX새마을 수정한거 말고 별차이가 없습니다.

**Comment by evepoi** [comment]
> ![차세대 EMU-150](https://user-images.githubusercontent.com/81477455/149505469-fa371967-65ba-4c0b-8a6b-51f6607e6713.png) 진작에 찍어놓긴했는데 이 이슈에 올라와서 한번 올려보겠습니다. ITX새마을 수정한거 말고 별차이가 없습니다.

제가 볼땐, ITX-새마을과 다른 열차로 보여집니다 ^^ 뭔가 무게감있다고 할까요?

**Comment by opentrain** [comment]
https://m.dcinside.com/board/monorail/262148
실차가 공개되었다고 합니다.

**Comment by EightonEight** [comment]
추가 ref: 
<http://www.redaily.co.kr/news/articleView.html?idxno=3684>
<https://youtu.be/KmH2GgS9plg?t=40>

**Comment by Gamunbi** [comment]
32bpp 파랑색 크로마키 날릴 예정

**Comment by Gamunbi** [comment]
스프라이트 수정중 보류

**Comment by Gamunbi** [comment]
팬터그래프 수정중

**Comment by telk5093** [comment]
이름만 정해지면 바로 추가

**Comment by telk5093** [comment]
![EMU150](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/a626ad67-fb80-4255-8523-1f225a86ab7b)
![EMU150_32bpp](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/9513ef05-d479-4924-a5f9-24cbaf4621d5)

최종 수정된 그래픽 스프라이트
  - 후두부 스프라이트 방향을 반대로 뒤집음 (``dual_head: 1`` 옵션때문에 알아서 뒤집히므로 전두부와 같은 방향을 바라보도록 수정)
  - 32bpp 구매 목록 이미지에 전기 기관차 표시 누락 추가

*TODO*
  - 수송량 변경 적용
  - 편성에 따라 출력 변경 적용. 4량 편성시 2000kW, 5량시 2500kW(가상), 6량시 3000kW, 7량 이상시 1량당 +500kW 추가되도록 (다른 의견 있으면 댓글 바랍니다)
  - 중량 미적용됨. 적용할 필요 있음

이름은 현재 EMU-150이라는 가칭으로 추가해놨고 도입연도 또한 초도분 출고식 날짜인 2023-05-31로 세팅했지만
추후 이름이 결정되고 실투입될 경우 해당 정보로 변경 필요

**Comment by telk5093** [comment]
일단 merge해놓고 _TODO_ 항목은 추후 수정 예정

**Comment by opentrain** [comment]
https://namu.wiki/w/%ED%95%9C%EA%B5%AD%EC%B2%A0%EB%8F%84%EA%B3%B5%EC%82%AC%20220000%2C%20230000%ED%98%B8%EB%8C%80%20%EC%A0%84%EB%8F%99%EC%B0%A8
8.7일 기준 열차 이름명 기존 ITX새마을로 나왔다는 이야기가 있습니다.

**Comment by telk5093** [comment]
> https://namu.wiki/w/%ED%95%9C%EA%B5%AD%EC%B2%A0%EB%8F%84%EA%B3%B5%EC%82%AC%20220000%2C%20230000%ED%98%B8%EB%8C%80%20%EC%A0%84%EB%8F%99%EC%B0%A8 8.7일 기준 열차 이름명 기존 ITX새마을로 나왔다는 이야기가 있습니다.

나무위키는 신빙성이 없는 출처입니다.
코레일 측에서 공식적으로 명칭을 발표하였거나 공신력있는 언론 보도가 있지 않고서야 위키의 설명이나 커뮤니티의 반응 등 만으로 결정할 일이 아닙니다.

**Comment by telk5093** [comment]
이름이 발표되었으므로 a5c4679cdcc1052843bca2204be0f42b12457b4f 에서 8월 16일에 반영했던 것을 참조하며 이슈를 닫겠습니다.
