### ISSUE TITLE
일제강점기 디젤 동차(1930년대)

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#312]
레퍼런스
![image](https://user-images.githubusercontent.com/81477455/149785721-4e048a29-92ac-4ef5-a02c-0f99a17e2ca1.png)
![image](https://user-images.githubusercontent.com/81477455/149785293-c5483e1f-dd6c-4261-9032-aed1fca5550e.png)

1930년 3등 개소린동차
![3등 개소린 동차](https://user-images.githubusercontent.com/81477455/149786401-de015232-6831-4298-a964-a1310bfdbab3.png)
우선 한국열차세트에 있는 3등 객차는 참고하여 제작했습니다.
크기는 1안,2안중 나눠져있습니다.
그중하나로 선택하시면 될듯합니다.

3등 디젤동차 자료가 일단 없어가지고 자료가 모이는데로 업로드예정

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.
