### ISSUE TITLE
새마을호 객차의 가로 그래픽 스프라이트 크기 조정

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#313]
![image](https://user-images.githubusercontent.com/10726524/151756771-9a4acad4-2e9a-4bf7-aa98-b1970d829d53.png)

현행: 32px
변경: 31px

**Comment by telk5093** [comment]
참고) 수정해도 그만, 안 해도 그만임

**Comment by Gamunbi** [comment]
![001](https://user-images.githubusercontent.com/75788864/151970046-ac5c8ace-9cce-4917-a1e9-ca5df340dec0.png)
![002](https://user-images.githubusercontent.com/75788864/151970051-a510630c-342f-4e94-848c-ee431ebc1db1.png)

확인해보니 저 객차뿐만 아니라 새마을호 개조목록의 모든 객차+ITX새마을이 다 이렇습니다(식당차는 정상). 고치려면 시간이 좀 걸릴 겁니다.

**Comment by Gamunbi** [comment]
![SAEMAEUL_CAR](https://user-images.githubusercontent.com/75788864/152289128-ffa437c3-da6a-4dd5-ac89-f5bee3a24253.png)
SAEMAEUL_CAR

![ITX-saemaeul](https://user-images.githubusercontent.com/75788864/152290670-a7573d5b-ac95-4cca-a3fb-755804a62fbc.png)
ITX-saemaeul

사이즈는 그대로입니다. ITX-새마을은 세세하게 살짝 수정한 곳이 몇몇 있습니다.
