### ISSUE TITLE
2.2.0 rc1 파일을 넣어도 게임에서 인식이 안 됨

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#315]
![001](https://user-images.githubusercontent.com/75788864/151804876-37fe9747-e212-475d-ac56-e10ad3c71e1b.png)
![002](https://user-images.githubusercontent.com/75788864/151804880-ea6ed5fe-7035-4aa3-8cba-bc6a087eac53.png)
파일 재검색 해도 뜨지 않음

게임 버전 : 20220130 nightly

**Comment by telk5093** [comment]
tar 압축이 잘못되어서 그런 걸로 알고있는데, 테스트용이므로 압축을 해제하고 사용 바랍니다.

**Comment by Gamunbi** [comment]
으음... 압축을 풀어도 적용이 안 되네요. 그냥 정식버전 기다리겠습니다.

**Comment by EightonEight** [comment]
![#315-4](https://user-images.githubusercontent.com/77984422/151934381-88bf4d7e-e84d-4762-988c-dd560ae44d5f.png)
newgrf 폴더 내에 한국 열차 세트 구버전 파일이 없어야 정상적으로 인식하는 것으로 보입니다.

**Comment by Gamunbi** [comment]
그래도 인식이 안 됩니다. jgr도 46rc2에서 45.1로 내려봤는데도 안 되고, 스팀 바닐라 정식버전에서도 인식이 안 되는 걸 보니 도저히 뭐가 문젠질 알 수가 없네요.
