### ISSUE TITLE
KTX-이음 그래픽 개선안

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#319]
![EUM](https://user-images.githubusercontent.com/24273113/151978594-c48b8ca5-1e8f-439d-80ed-a9aa69765c9a.png)
현재 스프라이트 (실차와의 괴리감이 있음, [참고자료](https://korailtalk.co.kr/698))

![EUM_darkblue](https://user-images.githubusercontent.com/24273113/151978781-b26dc750-a752-4b96-8706-14e30fecedf9.png)
대안 1: **회사 색상**을 적용한 스프라이트 (PALETTE_CC_DARK_BLUE 지정 필요) (OpenTTD 팔레트 적용되어 있음)

![EUM_32bpp](https://user-images.githubusercontent.com/24273113/151980478-0675bc8d-8746-4ec1-b506-689a128d916c.png)
대안 2: **32bpp**를 적용한 스프라이트 ([alternative sprite](https://newgrf-specs.tt-wiki.net/wiki/NML:Alternative_sprites)로 구현 필요) (**OpenTTD 팔레트 적용되어 있지 않음**)

![EUM_preview](https://user-images.githubusercontent.com/24273113/151978591-8cf22072-244a-4965-ae75-8aa145b2c9b1.png)
![EUM_darkblue_preview](https://user-images.githubusercontent.com/24273113/151978650-94cfb7c7-340b-46ce-b25e-07fd60925a09.png)
![EUM_32bpp_preview](https://user-images.githubusercontent.com/24273113/151978667-2933a0b8-50f5-4833-827d-53c7da50cfce.png)
실제 적용 모습

![EUM_compare](https://user-images.githubusercontent.com/24273113/151979367-cdf01654-9ce5-43dd-96ae-90e895371201.png)
비교

**Comment by telk5093** [comment]
3안이 생각보다 구현이 쉬워서 3안으로 가겠습니다.
