### ISSUE TITLE
[Add] Military flat car (군용 평판화차)

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#326]
![FLAT_CAR_TRANSCOM](https://user-images.githubusercontent.com/77984422/153027124-d093fdfa-9888-4460-9722-247b95af6935.png)
``FLAT_CAR_US_*``
``FLAT_CAR_ROK_GREEN``
위에서부터 미군 평판화차(갈색), 미군 평판화차(검정색), 미군 평판화차(파란색), 국군 평판화차입니다.

해당 스프라이트는 #157  (계산1.1 = 27px)을 기준으로 계산1.2 = 30px로 제작되었습니다.
평판화차 중 파란색은 계산1.4이나, 편의상 계산1.2로 통일하였습니다.

해당 화차는 추후 군용화물을 지원하는 산업시설 GRF 세트가 나왔을 때 추가되는 것이 좋을 것 같습니다.

**Vehicle specification**
| Name | Code | Speed | Speed (designed) | Capacity | Power | Weight | Introduction |
|--------|-------|--------|---------------------|-----------|--------|---------|---------------|
| US Army flat car: Brown | ``FLAT_CAR_US_BROWN`` | **70 km/h** | **70 km/h** | **70** |  | **35t** | **1991** |
| US Army flat car: Black | ``FLAT_CAR_US_BLACK`` | **70 km/h** | **70 km/h** | **70** |  | **35t** | **1991** |
| US Army flat car: Blue | ``FLAT_CAR_US_BLUE`` | **70 km/h** | **70 km/h** | **70** |  | **37t** | **2015** |
| ROKTC<sup>[1](#footnote_1)</sup> flat car | ``FLAT_CAR_ROK_GREEN`` | **70 km/h** | **70 km/h** | **70** |  | **37t** | **2021** |

**References**
* 미군 평판화차(갈색)
 <https://blog.naver.com/990104ms/221387471634>
 <https://youtu.be/bN6OWrfucQ4?t=15>
 <https://youtu.be/qHpjm9o7WNA>
* 미군 평판화차(검정색)
 <https://gall.dcinside.com/mgallery/board/view/?id=war&no=1885739>
* 미군 평판화차(파란색)
 <https://blog.naver.com/kp0103/221129386498>
 <https://blog.naver.com/kp0103/220915282764>
 <https://blog.naver.com/jascoco/220377005599>
* 국군 평판화차
 <https://blog.naver.com/tntjrlwl/222613865130>
 <https://blog.naver.com/0426martin/222464252722>
 <https://youtu.be/4eNQJ202cto?t=60>
 <https://youtu.be/ZPwKEX3KWGA?t=30>
* 제원
한국철도공사 물류본부 물류수송차량팀, 「화차제원」, 2010.10

**Example**
![제목 없음2](https://user-images.githubusercontent.com/77984422/153049202-d47178c6-0be6-455f-9d63-1abc363e3b5c.png)
(화물 스프라이트 원본: <https://cafe.naver.com/ottd/16335>)

---

<a name="footnote_1">1</a>: R.O.K. Transportation Command(국군수송사령부)

**Comment by JukjeonWani** [comment]
FIRS 농장 비품 스프라이트가 녹색이라 적옹 시 혼동 우려가 생길 수 있을 듯 해서 농장 비품 스프라이트를 생산 장비와 통일하고 해당 화차를 생산 장비, 농장 비품(+ 자동차) 운송을 가능하게 하면 될 것 같습니다

**Comment by telk5093** [comment]
군용 화물이 존재하지 않으므로 현 상황에서 추가하는 것은 어려울 듯 하며 먼 미래에 다시 오픈하는 것이 좋을 듯 합니다.
