### ISSUE TITLE
7X00에 카페객차 연결 시 개조목록에 새마을호 카페객차가 나타나지 않는 현상

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#328]
![image](https://user-images.githubusercontent.com/88026704/158593384-c5b0ff2a-7d72-4c07-9fb9-791e2296b068.png)
새마을호 카페객차가 개조목록에 보이지 않음
![image](https://user-images.githubusercontent.com/88026704/158594001-1fb3125c-5c42-40b7-ab8f-16d8fe8df257.png)
DHC, PP에선 정상적으로 보임
![image](https://user-images.githubusercontent.com/88026704/158786897-5bddf8f0-cd7a-4457-8ca7-ae30ae533bc3.png)
8X00에서도 정상적으로 나타남

**Comment by telk5093** [comment]
``(철도청 초기 도색: 청색 & 백색)`` 과 ``(새마을호 카페차 / Korail 현 도색)``가 동일하게 3번 자리를 사용하고 있어서 기술적인 문제로 불가능합니다.
