### ISSUE TITLE
발전차와 새마을호 객차가 겹침

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#329]
![image](https://user-images.githubusercontent.com/88026704/158595575-6aa0bc27-6a4b-499b-b610-d6c54dccfd74.png)
![image](https://user-images.githubusercontent.com/88026704/158595600-55196ccd-73e4-4c1b-b1ae-8fa31e8eb1ad.png)
![image](https://user-images.githubusercontent.com/88026704/158595680-6311a3f6-7e13-4716-a875-fad1213ecccd.png)
![image](https://user-images.githubusercontent.com/88026704/158595701-e83a76ab-3298-497c-9b60-c14ff59a95c4.png)

**Comment by telk5093** [comment]
Seems like duplicate of #324
