### ISSUE TITLE
[Add] Uijeongbu LRT

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#33]
의정부경전철

**Comment by troy7737** [comment]
![의정부 경전철 1차 완성](https://user-images.githubusercontent.com/75788864/111804821-ca848b00-8913-11eb-85db-e50bffaef41e.png)
생각난 김에 만들어서 올려드립니다.

**Comment by telk5093** [comment]
![U100](https://user-images.githubusercontent.com/10726524/111807920-d02fa000-8916-11eb-9a6f-9f76b90696eb.png)

이런, 작업하시는 줄 모르고 혼자서 열심히 뚜까뚜까하고 있었네요...ㅎ

**Comment by troy7737** [comment]
앗.. 만든다고 알려드릴걸..;;

**Comment by troy7737** [comment]
![의정부 경전철 1차 완성](https://user-images.githubusercontent.com/75788864/111860541-a06eaf80-898b-11eb-9c13-3b94f7bf9435.png)

어제 스프라이트에 잘못된 부분이 있어서 수정해서 올립니다. 전면부를 더 얇게 했습니다. 스프라이트 찍는 거 힘드실텐데 미리 알려드리고 찍지 않아서 죄송합니다.
