### ISSUE TITLE
발전차와 무궁화호 객차가 겹침

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#330]
#329 와 동일
![image](https://user-images.githubusercontent.com/88026704/158723381-46ade70d-395f-4191-82c3-54991e610ae0.png)
![image](https://user-images.githubusercontent.com/88026704/158723388-e03ffc1a-b1e8-4cf4-9094-8e94d8d6fd07.png)

**Comment by telk5093** [comment]
동일 이슈는 하나로 묶어주세요.
#329 로 이관합니다.
