### ISSUE TITLE
[New] 코레일 전동차(3x71~3x78 대차분) 스프라이트

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#331]
#### 그래픽 스프라이트(Graphic sprite):
![LINE_3_2022 (3)](https://user-images.githubusercontent.com/77984422/174332807-2e3f248e-863f-451a-9aa2-42c14b51df98.png)
`LINE_3_2022`
* from #295 
* 자료 확인 결과 더블암 팬터그래프를 사용

#### References: 
<https://youtu.be/AH_-mdk2eTk>
<https://youtu.be/RJdnTrngoQY?t=15>
<https://youtu.be/C-RB3ZVtdx4?t=35>
<https://blog.naver.com/jinhae-08/222795617357>

**Comment by telk5093** [comment]
(나중에 잊어먹을까봐 적는 comment)
> 파란색 부분은 더블 팬터그래프/싱글 팬터그래프이므로 확률 적으로 나올 수 있도록 처리

**Comment by EightonEight** [comment]
> > 파란색 부분은 더블 팬터그래프/싱글 팬터그래프이므로 확률 적으로 나올 수 있도록 처리

추후 동력차 부분의 자세한 사진이 공개되면 더블암/싱글암 중 확정하여 수정하도록 하겠습니다.

**Comment by JukjeonWani** [comment]
> @telk5093 추후 동력차 부분의 자세한 사진이 공개되면 더블암/싱글암 중 확정하여 수정하도록 하겠습니다.

래퍼런스: https://m.blog.naver.com/jinhae-08/222795617357
![image](https://user-images.githubusercontent.com/88026704/178110838-b1e63cd3-d5c8-4d32-b384-4f091a99b329.png)
더블암으로 하시면 될 것 같습니다
