### ISSUE TITLE
무궁화호 열차 등장년도 수정필요

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#332]
한국열차세트에서 무궁화호가 1972년으로 등장되어있는데
운영을 1977년부터 운행시작되었다고하니
1977년으로 변경하는게 낫지않을까싶습니다.

https://namu.wiki/w/%EB%AC%B4%EA%B6%81%ED%99%94%ED%98%B8

**Comment by EightonEight** [comment]
#299 로 통합하여 작업하면 좋을 것 같습니다.

**Comment by telk5093** [comment]
Duplicate of #299
