### ISSUE TITLE
관광호 조합 사용 불가능 (새마을호 객차 등장년도가 1984년임) 

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#333]
![0001](https://user-images.githubusercontent.com/75788864/167245829-8763d743-549d-4dda-a79f-c0012c022b67.png)

**Comment by telk5093** [comment]
Related with #258

**Comment by telk5093** [comment]
Close by d98c9c470051d2eefe9b08b01eeeee66854cc0fd
