### ISSUE TITLE
4호선 4000호대 초퍼제어 전동차

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#337]
한국열차세트에서는 2,3호선만 GEC초퍼제어전동차만 존재해서
그러는데 과거 서울지하철 4호선에도 (1985~1995)년까지 운영했다고 합니다. 4호선 열차개조목록에 넣어보는거 어떨까싶네요

운행기록 이슈
https://namu.wiki/w/%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%EC%A7%80%ED%95%98%EC%B2%A0%EA%B3%B5%EC%82%AC%204000%ED%98%B8%EB%8C%80%20%EC%B4%88%ED%8D%BC%EC%A0%9C%EC%96%B4%20%EC%A0%84%EB%8F%99%EC%B0%A8

**Comment by EightonEight** [comment]
#230 과 중복되는 이슈이며 이미 반영되었습니다.
다만, 개조 목록에 뜨는 도색명을 `서울교통공사 3k CHOPPER`에서 `서울교통공사 4k CHOPPER`로 바꾸면 좋을 것 같네요. 

reference: <https://images.app.goo.gl/o5Wuvpn7Vcqw1S7n8>
