### ISSUE TITLE
[Bug] 부산 4호선 수송량 조정

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#338]
![image](https://user-images.githubusercontent.com/77984422/171994271-c292aa50-695c-4b0a-8c8b-42bb3997f323.png)
부산 4호선 전동차와 신림선 전동차는 같은 제작사에서 제작됨
차량 크기는 부산4: `9.14m × 2.4m × 3.5m`, 신림선: `9.64m × 2.4m × 3.5m` 로 거의 같고, 
정원은 부산4 (6칸 1편성) 316명, 신림선 (3칸 1편성) 158명으로 사실상 한 칸당 정원이 동일함

따라서 #336 과 연계하여 부산 4호선 전동차도 신림선과 동일하게 전후부를 52명, 객차를 54명으로 설정

References:
 * <https://opengov.seoul.go.kr/sanction/16868705>
 * <https://www.wjis.co.kr/kr/business/railroad.php>

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/172003778-646827dd-63a7-4556-8815-6676e6da76fa.png)
에 따라 실제 좌석 수송량 128명에 가깝게 42x3=126명 수송량으로 설정한 것이므로
동일 크기라고 해서 동일 수송량으로 설정할 계획은 없습니다.
차라리 객차를 44명으로 조정하는 게 더 합리적이라고 생각합니다.

**Comment by Gamunbi** [comment]
실제 길이는 거의 같은데 게임에서는 차이가 조금 있네요. 수정해도 될까요?

**Comment by telk5093** [comment]
> 차라리 객차를 44명으로 조정하는 게 더 합리적
Implemented by 88c9a63
