### ISSUE TITLE
DHC 디젤동차 새마을호 88세계평화열차 도색

### ISSUE THREAD

**Issue by GBLINER** [KoreanGRF/KoreanTrainSet#339]
![88_peace_train_of_Korean_National_Railroad](https://user-images.githubusercontent.com/85421764/172037038-9e85c450-68b3-4862-9bba-7bbfd4c6b920.jpg)
1988년에 새마을호로 운행되었던 관광열차인 <88세계평화열차>입니다.

**그래픽 스프라이트(Graphic sprite):**
![88세계평화열차](https://user-images.githubusercontent.com/85421764/172171679-0aa72f49-7710-4c5c-bc3e-3de4a6d16f35.png)

기존 새마을호를 기반으로 제작하였으며 8bpp로 제작하였습니다.
기존 새마을호에 새로운 도색으로 추가하는것으로 생각하고 있습니다. 실제 운행기간은 1988년 9월 20일부터 10월 31일이라고 합니다.

![9d34c2028c717c45ce30f0888fe3a588](https://user-images.githubusercontent.com/85421764/172037267-9c2ccb54-6465-4ee9-9c70-b4a32c6522be.jpg)

도색이름으로는 공식명칭인 [88세계평화열차](https://newslibrary.naver.com/viewer/index.naver?articleId=1988090300329210013&edtNo=1&printCount=1&publishDate=1988-09-03&officeId=00032&pageNo=10&printNo=13211&publishType=00020)으로 영어명칭은 위 사진과 같이 The '88 World Peace Train으로 하면 좋을것 같습니다.

**Comment by telk5093** [comment]
Will not be implemented
