### ISSUE TITLE
[New] 수도권 광역급행철도 A노선 (GTX-A)

### ISSUE THREAD

**Issue by CoconutKR** [KoreanGRF/KoreanTrainSet#340]
**그래픽 스프라이트(Graphic sprite):**
![GTX](https://user-images.githubusercontent.com/85421764/172389466-405a3664-e5b6-4067-8123-7a30e7d12c42.png)

**제안할 차량 제원(Suggest vehicle specification):**
| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean)  | 수도권 광역급행철도 |
| 영문 이름(Name in English)  | Great Train eXpress |
| 코드(Code)  | ``GTX_A`` |
| 운영 속력(Speed)  | 180km/h |
| 설계 최고 속력(Designed max. speed)  | 198km/h |
| 화물 수송량(Capacity)  | 100 |
| 출력(Power)  | 2000 kW |
| 중량(Weight)  | 20t |
| 도입연도(Introduction year) | 2023 |

[opentrain](https://github.com/opentrain)님이 만드신 [GTX-A 차량](https://github.com/KoreanGRF/KoreanTrainSet/issues/197)에서 퀄리티를 더 세부적으로 하여 제작하여 보았습니다.
[공개된 목업차량](https://blog.hyundai-rotem.co.kr/574)과 [렌더링 이미지](http://www.kharn.kr/data/photos/20210416/art_1619355280231_bef635.png)를 바탕으로 8bpp로 제작하였습니다.

**Comment by EightonEight** [comment]
![GTX-A](https://user-images.githubusercontent.com/77984422/196432452-766b556e-30b4-4643-a4cf-aacf0977b692.png)
추가 ref: 
<https://kepper.tistory.com/m/1578>
<https://blog.naver.com/yds8229/222326032412>

수정해둔 스프라이트를 실차가 나올 때까지 올리지 않고 기다리다 보니 중복이 되버렸네요 😅

**Comment by EightonEight** [comment]
### 최종(안)
![GTX-A](https://user-images.githubusercontent.com/77984422/209462018-3de87ca6-9434-4dd0-a024-0d445b7e0c10.png)
템플릿: `tmpl_snout_*`

팬터그래프 위치:
```
4량: ← TC1 - T'1 - T'2 - TC2 ←
5량: ← TC1 - T'1 - M - T'2 - TC2 ←
6량: ← TC1 - T'1 - M - M - T'2 - TC2 ←
---
7량: ← TC1 - T'1 - M - M - T'2 - M - TC2 ←
---
8량: ← TC1 - M - T'1 - M - M - T'2 - M - TC2 ←
8량 이상: ← TC1 - M - T'1 - M - ⋯ - M - T'2 - M - TC2 ←
```

| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) | GTX A노선 |
| 영문 이름(Name in English) | GTX Line A |
| 코드(Code) | `GTX-A` |
| 운영 속력(Speed) | **180 km/h** |
| 설계 최고 속력(Designed max. speed) | **198 km/h** |
| 화물 수송량(Capacity) | **100** |
| 출력(Power) | 4000 kW |
| 중량(Weight) | 45t |
| 도입연도(Introduction year) | **2023** |

#### References:
<https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000060/167143439007035.jpg>
<https://youtu.be/gi7JFSPlBNc>
<https://youtu.be/ZTAogzECRGQ>
<https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=335313>
<https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=345408>

**Comment by telk5093** [comment]
![SG_A000_1](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/c6bfb673-f4c9-4bca-a25e-5880de80c9b2)

Final graphic sprite

**Comment by SerpensNebula** [comment]
[위에 제가 만든것](https://github.com/KoreanGRF/KoreanTrainSet/issues/340#issuecomment-1282289192)을 수정했습니다.

![지하철 GTX-A](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/8fc093b0-50d2-4116-846f-99720dbac153)
다른 점
 - ↔방향 길이가 33px인 것을 한열셋 규격에 맞는 31px로 바꿈
 - 대각선 방향들이 1px씩 삐져나온 것을 수정

![ezgif-3-d3cec3aac7](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/bc563d98-3859-4a18-8ac9-29bc42fd74aa)
위 움짤은 비교짤입니다. 크로마키에서 삐져나온 게 없는 것이 제것입니다.

**Comment by telk5093** [comment]
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/06d2fb03-9187-4040-9402-dba4a73d6c88)
dual_head 차량의 경우 후두부의 방향은 전두부와 동일하게 맞춰야하므로
@SerpensNebula 님이 제공해주신 마지막 그래픽 스프라이트에서 왼쪽 4개와 오른쪽 4개의 그래픽 스프라이트 위치만 변경하여 적용하겠습니다.


적용 샘플 사진:
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/c247a655-e2db-40cd-9377-ddd0d22bf588)

**Comment by SerpensNebula** [comment]
[↕방향](https://github.com/KoreanGRF/KoreanTrainSet/issues/340#issuecomment-1647895369) 1px씩 어긋나 있습니다!

앞으로 전후두부는 동일하게 작업하면 될까요?

**Comment by telk5093** [comment]
> [↕방향](https://github.com/KoreanGRF/KoreanTrainSet/issues/340#issuecomment-1647895369) 1px씩 어긋나 있습니다!

표준 템플릿의 경우 오프셋이 어긋나는 경우 코드로 조정이 불가하여 그래픽 스프라이트를 수정해야 합니다.


> 앞으로 전후두부는 동일하게 작업하면 될까요?

네. 그래주시면 감사합니다.

**Comment by EightonEight** [comment]
![SG_A000_1](https://github.com/KoreanGRF/KoreanTrainSet/assets/77984422/3c3e72e6-91ae-40d1-acf1-c7dd2377479d)
* `tmpl_standard`+`tmpl_standard_longnose` 적용
* 운전실부 디테일 향상
* 천장 부분 수정
  - 운전실부 공조장치 위치 수정
  - ↔ 방향 공조장치 형상 변경
  - T'차 전력제어장치를 공조장치보다 약간 더 어둡게 수정
* 후두부에 후미등이 켜진 상태로 수정
* 후두부 ↕ 방향 위치 다시 조정
  - ※ 후두부의 방향을 전두부와 동일하게 맞출 때, 크로마키 내 차량 스프라이트의 위치는 그대로 유지해야 게임 내에서 어긋나지 않습니다. (↔ 방향도 동일)

#### 추가 Ref:
<https://youtu.be/PXTHPEAoYW8?t=27>
<https://youtu.be/Ta-I5OXY_Vg>

**Comment by telk5093** [comment]
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/9df4fe41-5dc1-4769-ac49-c4d9fb8c00e4)
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/2b4117e3-0e8c-4889-a3b5-dc1e8efa0199)
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/a9efb6b5-083d-4e30-a3e2-7b3ab6cf8566)
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/870f4ec3-d03f-46d3-a89b-9d8cc362733d)


Result up to here
