### ISSUE TITLE
[Bug] ITX-새마을 출력

### ISSUE THREAD

**Issue by GBLINER** [KoreanGRF/KoreanTrainSet#342]
**한국 열차 세트 버전(Version of Korean Train Set):** 2.3.0

**버그 내용 설명(Describe the bug):**
ITX-새마을의 출력은 한 편성에 3000kW 으로 알려져 있습니다.
[한국철도공사 210000호대 위키백과 링크](https://ko.wikipedia.org/wiki/%ED%95%9C%EA%B5%AD%EC%B2%A0%EB%8F%84%EA%B3%B5%EC%82%AC_210000%ED%98%B8%EB%8C%80_%EA%B0%84%EC%84%A0_%EC%A0%84%EA%B8%B0_%EB%8F%99%EC%B0%A8?tableofcontents=0)

현재 ITX-새마을은 게임 내 실제와 동일하게 편성시 6600kW로 표기됩니다.
![화면 캡처 2022-06-15 174520](https://user-images.githubusercontent.com/85421764/173785214-7f8d3377-5d60-41e9-a7b1-6aaa41bb055a.png)

동력없는 객차로 게임 내 편성시 6000kW로 표기됩니다.
![화면 캡처 2022-06-15 174718](https://user-images.githubusercontent.com/85421764/173785218-b89abbe3-6c63-4861-ad55-d13968352815.png)

게임 내의 문제인가 하고 코딩부분을 살펴보니 코딩도 동일한 값인 6000으로 들어가 있더군요.
![화면 캡처 2022-06-15 180639](https://user-images.githubusercontent.com/85421764/173789262-b63bc3bc-65d4-467a-8850-44fa136c9529.png)

코딩 상 구현이 불가능한 부분인지 아니면 잘못된 값이 들어간지 개인적으로 궁금합니다.

**올바른 상황 설명(Describe the expected situation):**
ITX-새마을의 출력은 3000kW로 적용되어야 합니다.

ITX-새마을은 6량, 동력분산식으로 알려져 있습니다.

동력, 비동력객차를 같이 편성하면 팬터그래프쪽에서 문제가 발생하니
동력 객차를 사용시에는 3000kW를 6으로 나누어 운전 차량, 동력 객차 1량 당 500kW를 적용하는것이 바람직하다고 생각합니다.

이것이 코딩으로 불가능 한것인지 아니면 단순 오류인지도 궁금합니다.

**Comment by telk5093** [comment]
엔진의 출력을 ``6000kW``에서 ``3000kW``로 변경하는 것으로 타협하고 이슈를 닫겠습니다.
