### ISSUE TITLE
[Bug]신림선 스프라이트 정렬이 이상함

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#344]
**한국 열차 세트 버전(Version of Korean Train Set):**
최신 버전

**버그 내용 설명(Describe the bug):**
![image](https://user-images.githubusercontent.com/88026704/175771227-af56cce5-2cdb-406e-a8d6-4925310b593b.png)
4량이상으로 편성 시 객차간 간격이 비정상적으로 벌어지는 현상

**올바른 상황 설명(Describe the expected situation):**
스프라이트 위치 조정이 필요해보입니다

**Comment by telk5093** [comment]
해당 증상이 재현되지 않습니다.
NewGRF를 변경하지 않은 새로운 맵에서 해당 증상이 나온다면 다시 이슈를 열어주시기 바랍니다.
![image](https://user-images.githubusercontent.com/10726524/175814402-4960da58-02a9-4191-86fd-a7f4326e6b20.png)

**Comment by telk5093** [comment]
``기관차 + 기관차`` 편성시 해당 증상 재현 확인
