### ISSUE TITLE
[New] 7호선 신차+인천1호선 검단 연장분

### ISSUE THREAD

**Issue by n0373** [KoreanGRF/KoreanTrainSet#348]
![89095_124830_244](https://user-images.githubusercontent.com/68586069/177060219-9dd6f020-e45d-47a8-9bd5-2d537e939218.png)
**그래픽 스프라이트(Graphic sprite):**

**제안할 차량 제원(Suggest vehicle specification):**
| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(eg. ``KTX 산천``)_ | 이름 |
| 영문 이름(Name in English) _(eg. ``KTX Sancheon``)_ | Name |
| 코드(Code) _(eg. ``KTX2N``)_ | ``제안할_코드명`` |
| 운영 속력(Speed) _(eg. ``300km/h``)_ | 000 km/h |
| 설계 최고 속력(Designed max. speed) _(eg. ``330km/h``)_ | 000 km/h |
| 화물 수송량(Capacity) _(eg. ``100명``)_ | 00 |
| 출력(Power) _(eg. ``4400kW``)_ | 00kW |
| 중량(Weight) _(eg. ``136t``)_ | 00t |
| 도입연도(Introduction year) _(eg. ``2004``)_ | 1900 |

**Comment by EightonEight** [comment]
#304 의 경우처럼 낙찰 직후에 공개된 디자인과 실차 디자인이 달라질 수 있기 때문에, 해당 사진만 가지고는 스프라이트를 만들기 어렵습니다. 

목업/실차 사진이 나오거나 적어도 디자인이 확정된 후에 제작이 가능할 것 같네요.

**Comment by telk5093** [comment]
이슈 템플릿도 하나도 안 채워져있고 언제 나올지도 명확하지 않은 차량이라 이슈를 열어둘 필요가 없어 닫도록 하겠습니다.

**Comment by EightonEight** [comment]
#### 그래픽 스프라이트(Graphic sprite):
![SMETRO_7K_CHEONGNA](https://user-images.githubusercontent.com/77984422/219845158-adc5801e-c35d-4a7a-9e3c-9a61864d209e.png)
_`SMETRO_7K_CHEONGNA`_

![INCHEON_METRO_1K_3RD](https://user-images.githubusercontent.com/77984422/219845261-93373e38-024a-4e9c-9501-ae244e668693.png)
_`INCHEON_METRO_1K_3RD`_

#### References:
_<http://www.koreailbo.co.kr/news/articleView.html?idxno=30674>_
_<http://catn.kr/View.aspx?No=2686314>_
