### ISSUE TITLE
[New] 우진산전 1,3호선 코레일 전동차

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#349]
**그래픽 스프라이트(Graphic sprite):**
 
![1호선,3호선 코레일 신차](https://user-images.githubusercontent.com/81477455/178150199-a3ca4b43-daf6-4154-be13-1e615d404c2b.png)

1호선(우진산전)
https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=297383&exception_mode=recommend&page=1

3호선(우진산전)
https://namu.wiki/w/%ED%95%9C%EA%B5%AD%EC%B2%A0%EB%8F%84%EA%B3%B5%EC%82%AC%203000%ED%98%B8%EB%8C%80%20%EC%A0%84%EB%8F%99%EC%B0%A8#s-3.2

**Comment by EightonEight** [comment]
![LINE_3_2022_W (2)](https://user-images.githubusercontent.com/77984422/178304333-9d9847e2-de15-47eb-80fc-6146dddd4e11.png)
`LINE_3_2022_W`

3호선 스프라이트도 1호선과 함께 제작해두었으나, 실물사진 자료가 없어 따로 공개하지 않고 있었습니다.

**Comment by telk5093** [comment]
1. [그래픽 스프라이트 위치](https://github.com/KoreanGRF/KoreanTrainSet/wiki/Standard-of-graphic-sprite's-positions)를 맞춰주십시오.
 2. 1호선은 #345 와 같은 차량인가요? 같은 차량이라면 #345 를 사용하겠습니다.
 3. 실차조차 나오지 않은 모델을 추가할 필요는 없습니다.
