### ISSUE TITLE
8100호대 & 8200호대 통합

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#35]
https://commons.m.wikimedia.org/wiki/File:KORAIL_EL8100.jpg

8100호대는 현재 신도색으로 다니고 있기 때문에 도색 차이로 이 둘을 분리하는것보디는 통합해서 도색 개조로 처리하는 것이 일관성 측면, 고증 측면에서 나을 것 같습니다.

**Comment by telk5093** [comment]
Done by 279b1445be1e9969e0832b2bbdacbae83b1d35bd
