### ISSUE TITLE
[Bug] 특대형 디젤기관차 중련연결시 후부 버그

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#350]
**한국 열차 세트 버전(Version of Korean Train Set):**
eg. 2.3.0 or 최신 버전

**버그 내용 설명(Describe the bug):**
우선 어제 통일호열차는 시운전하면서 발견했는데 이게맞는건지 안맞는건지 모르겠지만
일단 모든 객차는 테스트해보니 통일호처럼 되어있네요
뭐라고 말을 해야하냐 기관차뒷쪽이 안보인다고해야할까싶네요

통일호 연결시
![Murphy   Co 의 게임 (2023-05-16)](https://user-images.githubusercontent.com/81477455/178271737-a05f249e-c166-47ba-8c0e-74837e1b894f.png)
![Murphy   Co 의 게임 (2023-05-18)](https://user-images.githubusercontent.com/81477455/178271765-620e8504-e563-49b6-b074-510d3ec20654.png)
![Murphy   Co 의 게임 (2023-05-21)](https://user-images.githubusercontent.com/81477455/178271880-fde5867f-b8bd-4d81-abb7-3f7a772bcdc1.png)
![Murphy   Co 의 게임 (2023-05-26)](https://user-images.githubusercontent.com/81477455/178271949-e6fa4aef-1d57-4b3a-a4a0-7bbed868a018.png)
![Murphy   Co 의 게임 (2023-10-01)](https://user-images.githubusercontent.com/81477455/178271991-8d808434-f1f6-4107-b994-d4515f303331.png)
![Murphy   Co 의 게임 (2023-10-12)](https://user-images.githubusercontent.com/81477455/178272030-7d1ae3f2-02d6-4702-b1f0-20b5fdb9c687.png)

비둘기호 연결시
![Murphy   Co 의 게임 (2015-01-06)](https://user-images.githubusercontent.com/81477455/178272161-4fe5311c-3912-4750-b2ab-077a2e4cdb87.png)
![Murphy   Co 의 게임 (2015-01-12)](https://user-images.githubusercontent.com/81477455/178272202-b4acda8c-1c4d-42ba-9fc0-c7b50e982774.png)
![Murphy   Co 의 게임 (2015-01-18)](https://user-images.githubusercontent.com/81477455/178272245-c0e7a98f-f65b-43ee-83a9-e7417289d942.png)
![Murphy   Co 의 게임 (2015-01-24)](https://user-images.githubusercontent.com/81477455/178272293-7aea0a43-e1bd-48d5-b1e4-5d62a53c4bb0.png)

무궁화호연결시
![Murphy   Co 의 게임 (2015-02-14)](https://user-images.githubusercontent.com/81477455/178272364-9b5aeed9-808e-4b8c-9d13-85510bc29110.png)
![Murphy   Co 의 게임 (2015-02-20)](https://user-images.githubusercontent.com/81477455/178272396-41aff371-6bde-4fac-92d8-d1e99f5a010a.png)
![Murphy   Co 의 게임 (2015-02-27)](https://user-images.githubusercontent.com/81477455/178272434-65e6fa94-0e4f-4667-849b-383c412202e5.png)
![Murphy   Co 의 게임 (2015-03-05)](https://user-images.githubusercontent.com/81477455/178272475-4cc7fe05-0c17-4d38-b337-876045d53921.png)

새마을호연결시
![Murphy   Co 의 게임 (2015-04-04)](https://user-images.githubusercontent.com/81477455/178272568-6695ced6-c748-40e0-9ca4-15090f28c24a.png)
![Murphy   Co 의 게임 (2015-04-09)](https://user-images.githubusercontent.com/81477455/178272612-3aa1f850-7d99-48a0-af42-3ac09bf59854.png)
![Murphy   Co 의 게임 (2015-04-16)](https://user-images.githubusercontent.com/81477455/178272647-f2ff010e-6db4-4cc0-a2cf-50f6ea6b74e9.png)
![Murphy   Co 의 게임 (2015-04-22)](https://user-images.githubusercontent.com/81477455/178272677-75cda4f4-1b43-4ab3-b565-50d63aa57c7e.png)

**올바른 상황 설명(Describe the expected situation):**
버그가 이렇게 수정되어야 한다는 점을 설명해주세요.
![Murphy   Co 의 게임 (2015-06-03)](https://user-images.githubusercontent.com/81477455/178273694-ca4fc917-6398-498b-9f8f-bb3479d838e5.png)
![Murphy   Co 의 게임 (2015-05-20)](https://user-images.githubusercontent.com/81477455/178273560-d28cced1-2dbf-4b42-95b5-e5ec0905ff4f.png)
![Murphy   Co 의 게임 (2015-05-28)](https://user-images.githubusercontent.com/81477455/178273590-9a626c84-2281-4b81-b147-5c700a751f50.png)
![Murphy   Co 의 게임 (2015-06-09)](https://user-images.githubusercontent.com/81477455/178273641-f29ab992-07ca-4994-949f-b1c2dcbfb6b4.png)
객차가 연결되면 이런식으로 보여야될지 않을까생각합니다.

**Comment by Gamunbi** [comment]
제가 현재 특대형(7x00호대) 스프라이트들을 한열셋의 기본규격에 맞게 리뉴얼하는 중입니다. 조금 기다려주시기 바랍니다.
