### ISSUE TITLE
[Bug] 7x00호대 디젤 기관차 스프라이트 

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#351]
**한국 열차 세트 버전(Version of Korean Train Set):**
2.3.0 (이슈 개설시점 최신)

**버그 내용 설명(Describe the bug):**
기존 한열셋 스프라이트 기본 규격에 맞지 않던 7x00호대 디젤기관차 스프라이트들을 전부 수정했습니다.

**올바른 상황 설명(Describe the expected situation):**
![디젤기관차 7x00호대 1차 완성](https://user-images.githubusercontent.com/75788864/179188097-b894f30f-da4d-4daf-9180-09b969c1d3bf.png)

달라진 점
- 한열셋 기본 규격(통일호 객차를 기준)에 맞추어 처음부터 다시 만듦
  - 좌우대칭이 아니던 부분(ex)환풍구) 적용
  - 일부 그림자 방향 맞지 않던 것도 고침
  - 세트 도색의 객차와 맞지 않는 색이었던 도색들도 고침(ex)철도청 노랑초록 도색을 통일호 노랑초록 도색과 동일하게 바꿈)
- ↔방향 스프라이트 1px 깎음(한열셋 기준인 31px로 바꿈)
- **대각선 방향 스프라이트들의 재정렬이 필요함**

![ezgif-1-90dbf61a35](https://user-images.githubusercontent.com/75788864/178675955-f63b33f1-ea81-4fcf-9dff-91da12637242.gif)
비교

**Comment by Gamunbi** [comment]
다시 수정중

**Comment by telk5093** [comment]
@Gamunbi 80216afae7603bf418ec3384c6be8938650da91d 에서 반영되었으므로 일단 이슈를 닫겠습니다.
https://github.com/KoreanGRF/KoreanTrainSet/suites/7495255202/artifacts/307902243 에서 반영분을 받아서 의도하신 대로 오프셋이 반영되었는지 확인하시고 문제가 있는 경우 다시 본 이슈를 열어주시면 감사하겠습니다.

**Comment by Gamunbi** [comment]
> @Gamunbi [80216af](https://github.com/KoreanGRF/KoreanTrainSet/commit/80216afae7603bf418ec3384c6be8938650da91d) 에서 반영되었으므로 일단 이슈를 닫겠습니다. https://github.com/KoreanGRF/KoreanTrainSet/suites/7495255202/artifacts/307902243 에서 반영분을 받아서 의도하신 대로 오프셋이 반영되었는지 확인하시고 문제가 있는 경우 다시 본 이슈를 열어주시면 감사하겠습니다.

↘방향과 ↖방향만 1px 내리면 될 것 같습니다.

제가 까먹고 말씀 못드린 게 있는데 스프라이트 크기와 정렬은 통일호 객차와 동일합니다. 이걸 알려드렸으면 더 쉽게 작업하셨을텐데 죄송합니다ㅠ
