### ISSUE TITLE
[Bug] 5000, 6x00호대 디젤기관차 스프라이트

### ISSUE THREAD

**Issue by Gamunbi** [KoreanGRF/KoreanTrainSet#352]
**한국 열차 세트 버전(Version of Korean Train Set):**
2.3.0

**버그 내용 설명(Describe the bug):**
https://github.com/KoreanGRF/KoreanTrainSet/issues/351 와 동일한 내용입니다.

**올바른 상황 설명(Describe the expected situation):**
![디젤기관차 5000호대 1차 완성](https://user-images.githubusercontent.com/75788864/179212985-0838bb19-ecc4-4ab6-bd82-dab1cfe4a355.png)
↑5000호대
![디젤기관차 6x00호대 1차 완성](https://user-images.githubusercontent.com/75788864/179212925-065a8bbe-97c6-447e-808f-50e92a5df2d1.png)

- 배경 없는 버전(스프라이트 복붙하기 쉬움)

5000호대 
![디젤기관차 5000호대 1차 완성 2](https://user-images.githubusercontent.com/75788864/179213156-2fc26c8f-27cb-4923-be16-d14733a6316f.png)

6x00호대 
![디젤기관차 6x00호대 1차 완성 2](https://user-images.githubusercontent.com/75788864/179212931-f8da9a67-c3e3-4ac8-aba2-3ff1679421c7.png)

- 코?부분, 환풍구, 대차 등 고증 미흡했던 부분 모두 교정함
- ↔방향은 어느것은 28px, 어느것은 27px로 되어있던 것을 그냥 27px(길이 7)로 통일함
- 모든 차량들은 스프라이트 크기와 정렬이 동일함
- 대각선 방향은 기존과 조금씩 어긋납니다. 스프라이트 정렬을 하셔야 될 것입니다.

예상도
![디젤기관차 6x00호대](https://user-images.githubusercontent.com/75788864/181046002-d1f280e2-8ac9-4fcf-90f7-d22aac0ccca1.png)

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/192778859-11d5c4f6-abd4-4d94-a46c-cbf714266c8c.png)
Ctrl+Click으로 기관차를 뒤집어서 중련할 경우, 차량이 벌어지는 현상이 있고 이는 기준이 되는 모든 차량의 오프셋이 틀어져있는 것이 원인으로 보이므로 단기간에 수정이 불가한 것으로 판단되어 이대로 반영합니다.
