### ISSUE TITLE
[Bug]무궁화호 객차의 출입문 위치가 안맞음

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#357]
**한국 열차 세트 버전(Version of Korean Train Set):**
최신 버전

**버그 내용 설명(Describe the bug):**
![image](https://user-images.githubusercontent.com/88026704/181689390-a51079fe-bd0f-4cb9-b3fd-8d9796c36f12.png)

**올바른 상황 설명(Describe the expected situation):**
2000~2002년 도색과 현재 도색(리미트 객차) 일반실의 경우 좌우 출입문 위치가 마주보는게 아니라 서로 어긋나있습니다. 즉, 창문 모양만 다르고 출입문 위치는 같아야 고증에 맞습니다.

추가로 3호차에 편성되는  방송실, 휠체어석 설치된 객차만 형태가 약간 다릅니다.

ref. 관광열차로 개조된 차량이지만 외형상 특성은 동일하므로 래퍼런스로 사용합니다.
사진 출처: https://blog.naver.com/insoo9348/221222667106
https://blog.naver.com/tntjrlwl/221174790523

3호차 방송실, 휠체어석
![image](https://user-images.githubusercontent.com/88026704/181689814-65d4d7d6-4517-4fdd-aa5a-25dc284d6161.png)
![image](https://user-images.githubusercontent.com/88026704/181689859-e25fadff-20e8-4082-a0de-fc24bc52f2f3.png)
3호차 방송실, 흴체어석 추가 래퍼런스: https://blog.naver.com/plmokmijn456/222771081113

이외 다른 호차(일반실)
![image](https://user-images.githubusercontent.com/88026704/181690040-cc4b2994-8b79-40c9-9248-2362b4074fea.png)
![image](https://user-images.githubusercontent.com/88026704/181690077-b6f9936b-6358-4167-b86e-a9000a39b5d0.png)

* 래퍼런스로 사용한 충북영동국악와인열차는 카페객차를 개조한 차량이기에 카페객차 스프라이트도 필요합니다.
* 편성 시 3호차 스프라이트만 다르게 나오는 것을 고려해주십시요
* 같은 모델을 개조하여 관광열차로 만든 G트레인, S트레인, A트레인 스프라이트도 점검할 필요성이 있어보입니다.

**Comment by JukjeonWani** [comment]
![무궁화_리미트](https://user-images.githubusercontent.com/88026704/181786479-97c3e746-a22a-481d-bf78-fa1326eed365.png)
일단 현재 도색과 2000~2002년 도색 수정했습니다. 추가로 수정하면서 구도색 카페객차 도색(2010년경까지 운행)도 만들었습니다
(구도색 코레일 로고 지우는거 까먹었는데 카페객차 등장시기상 고증오류는아니네요)

ref. 
https://cafe.naver.com/hkct/83533 (2009년 작성)
![image](https://user-images.githubusercontent.com/88026704/181786707-7f7a3556-8163-497e-8b51-bdf79cd4e033.png)
https://cafe.naver.com/hkct/147544(2011년 작성)
![image](https://user-images.githubusercontent.com/88026704/181786795-301d56eb-d9d1-4a25-b7c3-b7deb64e099a.png)
https://blog.naver.com/kjtksj63/220064725817
https://blog.naver.com/plmokmijn456/221063092656

**Comment by telk5093** [comment]
해당 그래픽은 4방향이 아니고 8방향이므로 왼쪽부터 ↑↗→↘↓↙←↖ 순서입니다. 따라서 현재가 맞습니다. 수정해선 안 됩니다.

**Comment by JukjeonWani** [comment]
@telk5093 해당 객차는 객차 방향에 상관 없이 진행방향 뒤쪽에 출입문이 있는 객차입니다, 현재 스프라이트는 고증오류가 맞습니다

**Comment by telk5093** [comment]
> 추가로 수정하면서 구도색 카페객차 도색(2010년경까지 운행)도 만들었습니다

별도 이슈로 올려주시기 바랍니다.

**Comment by JukjeonWani** [comment]
@telk5093 해당 차량은 8방향으로 작업해주시면 좋겠습니다. 게임상의 한계로 쪽창 크기는 동일하게 제작되었지만 실차는  객실 옆 쪽창 크기와 위치가 다릅니다. 

←방향: 출입문에서 먼 쪽에 위치(화장실)
→방향: 출입문 바로 옆(입석공간, 3호차 객차는 방송실)

**Comment by telk5093** [comment]
> 해당 차량은 8방향으로 작업해주시면 좋겠습니다.

제공하신 그래픽 스프라이트가 8방향이므로 당연히 8방향으로 작업됩니다...

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/189560459-a68bcf2d-542a-4605-9724-18536e8fcb92.png)
해당 픽셀에 사용된 색상이 animated colour이므로 대체 색상으로 변경하여 적용됩니다.
