### ISSUE TITLE
구도색 카페객차 도색

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#358]
#357 
> 별도 이슈로 올려주시기 바랍니다

스프라이트 별도 이슈로 재업
![무궁화_리미트](https://user-images.githubusercontent.com/88026704/181916184-d1904785-10d6-4101-8f1b-69c619e7398a.png)

ref. 
https://cafe.naver.com/hkct/83533 (2009년 작성)
![image](https://user-images.githubusercontent.com/88026704/181786707-7f7a3556-8163-497e-8b51-bdf79cd4e033.png)
https://cafe.naver.com/hkct/147544 (2011년 작성)
![image](https://user-images.githubusercontent.com/88026704/181786795-301d56eb-d9d1-4a25-b7c3-b7deb64e099a.png)
https://blog.naver.com/kjtksj63/220064725817
https://blog.naver.com/plmokmijn456/221063092656

**Comment by telk5093** [comment]
객차 출입문 위치 관련은 #357에서 그대로 처리합니다.
구 도색 카페 객차 관련 이슈로 제목 수정해두겠습니다.

**Comment by JukjeonWani** [comment]
![무궁화_리미트](https://user-images.githubusercontent.com/88026704/181916207-d363f2a8-c1f4-4ad8-9818-23077bc1b729.png)
구도색 카페객차 ↗방향, ↘방향, ↙방향, ↖방향 수정이 안되어있던것 수정 및 명암을 일반실 객차와 통일시켰습니다.
신도색 카페객차 ↘방향, ↖방향 수정이 안되어있던것 수정 및 명암을 일반실 객차와 통일시켰습니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/189559390-8b5dedbc-8bb3-4178-82d2-6c43d36d3014.png)
해당 카페 객차 도색은 현재 구현되어있지 않으므로 바로 반영이 어렵습니다.
별도의 이슈로 추가 등록하여 관리해야할 것 같네요.

**Comment by telk5093** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/commit/a64f00dc23bb5fe7bd299700d3b4b74128baf6c6 에서 일단 반영하였으며 문제가 추가로 있는 경우 별도로 이슈 등록 부탁드립니다.
