### ISSUE TITLE
관광열차 스프라이트 수정

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#361]
#357 해당 이슈와 동일한 차종을 개조하여 관광열차로 만든 정선아리랑열차, 서해금빛열차, 남도해양열차, 레일크루즈 해랑의 스프라이트를 수정하여 업로드합니다.

* 정선아리랑열차
![A-train_passinger](https://user-images.githubusercontent.com/88026704/211728561-f5a7934d-d2f9-4af9-bfbe-4795df9df75e.png)
![A-train_generator](https://user-images.githubusercontent.com/88026704/210037769-780944a0-1c2e-4e46-936e-073bf9aa65eb.png)
ref. https://youtu.be/NvIef-MTuYM
**3호차 ↙ ← ↖ 방향 스프라이트 출입문이 두개인 것은 고증오류가 아닙니다**
**창문 형태를 실차와 비슷한 형태로 수정**
**천장 전망창 및 통로부 전망창 구현**
**발전차 퀄리티 업(동일 차종인 다른 관광열차 발전차와 비슷하게)**

* 서해금빛열차
![G-train_passinger](https://user-images.githubusercontent.com/88026704/182082441-407eaafd-2b78-4557-b682-4cbf04e9c3db.png)
ref. https://youtu.be/GeNMTqQDbN4
https://youtu.be/Cj3Guy2Rrnw
**2호차 ↙ ← ↖ 방향 스프라이트 출입문이 두개인 것은 고증오류가 아닙니다**

* 남도해양열차
8방향으로 수정하는 작업도 같이 했습니다.
![S-train_passinger](https://user-images.githubusercontent.com/88026704/183346005-536cda0a-1275-4995-9879-90d1a955f4ca.png)
ref. https://youtu.be/6qPtzd1MegQ
https://blog.naver.com/sj029/221530847338 (37번째 줄 사진)
https://blog.naver.com/kimhr91/90180716528
**2호차 ↙ ← ↖ 방향 스프라이트 출입문이 두개인 것은 고증오류가 아닙니다**

* 레일크루즈 해랑
8방향으로 수정하는 작업도 같이 했습니다.
![Haerang_passinger](https://user-images.githubusercontent.com/88026704/182099355-2909377a-05b2-44b9-96dc-bd749c7fc8ca.png)
ref. https://youtu.be/HbmImrsPmQQ
https://blog.naver.com/digmon2001/221448654345
**5호차 ↙ ← ↖ 방향 스프라이트 출입문이 두개인 것은 고증오류가 아닙니다**

**Comment by telk5093** [comment]
1. **A-train**:
 ![image](https://user-images.githubusercontent.com/10726524/216774594-977dfd95-bc50-4d1a-a911-9f967f0ca02d.png)

 2. **G-train**:
 ![image](https://user-images.githubusercontent.com/10726524/216774619-8ba12778-30ea-4e5a-af32-6a5b61f0d9dc.png)

먼저 A/G-train을 반영 중입니다. 의도한 대로 반영되었는지 확인 바랍니다.

**Comment by JukjeonWani** [comment]
A-train에는 반영되어있는 방송실 객차 스프라이트가 같은 방향에서 보이는 G-train에선 안보이네요.

G-train 객차 순서의 경우 KTS+ 관광열차 작업하며 코딩 / 게임상 한계인 것을 확인하였기 때문에 수정이 필요하지 않을겁니다.(발전차를 맨 뒤에 편성해 해결 가능)

**Comment by telk5093** [comment]
> A-train에는 반영되어있는 방송실 객차 스프라이트가 같은 방향에서 보이는 G-train에선 안보이네요.

"방송실 객차"라고 하시면 이해가 어렵습니다.
아무튼 마지막 객차가 두 번 중복되어 나타나는 현상은 수정되었으니 확인 바랍니다:
![image](https://user-images.githubusercontent.com/10726524/216775389-a55ac71c-28c5-4b20-b7be-f8fdfe745e17.png)

**Comment by JukjeonWani** [comment]
객차 배치는 해결되었습니다.
↙ ← ↖ 방향 출입문이 두개인 객차가 방송실 객차입니다. A-Train에는 정상적으로 반영되어 있는데 G-Train에는 없네요.

**Comment by telk5093** [comment]
제공해주신 G-train 그래픽 객차 중 2번을 말씀하시는 거라면, → 방향만 출입문이 2개고 ←쪽은 2개가 아닌 걸로 보입니다.
제공된 그래픽이 반대로인가요?

**Comment by JukjeonWani** [comment]
업로드된 그래픽 이미지 계속 확인했는데 A-train과 동일한 방향에 작업이 되어있습니다. 즉, 5번째 객차(2호차) 출입문 그래픽이 2개가 나와야 맞는데 작업 도중 그래픽 위치가 바뀐 것 같습니다.

**Comment by telk5093** [comment]
> 작업 도중 그래픽 위치가 바뀐 것 같습니다.

![image](https://user-images.githubusercontent.com/10726524/216775995-2b86941c-ecf9-40bd-9802-21d0d0a5dea7.png)

이렇게 서로 바뀌어야 한다는 말씀이실까요?

**Comment by JukjeonWani** [comment]
맞습니다.

**Comment by telk5093** [comment]
예 변경해놨습니다.
![image](https://user-images.githubusercontent.com/10726524/216776185-d543b996-9ab3-4352-a0fc-ff4912f0bda7.png)

**Comment by JukjeonWani** [comment]
감사합니다. G-Train도 이제 의도한 대로 나옵니다.
