### ISSUE TITLE
[New] 부산 1호선(우진산전 제작분) 스프라이트

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#363]
#### 그래픽 스프라이트(Graphic sprite):
![BUSAN_METRO_1K_3RD_2](https://github.com/KoreanGRF/KoreanTrainSet/assets/77984422/9c4ba3b0-9c26-400e-9b3d-df3b56e7ac3d)
`BUSAN_METRO_1K_3RD`

#### References:
<https://youtu.be/arLIhwNl7-U?t=40>
<https://youtu.be/UC6XEqaJaY8>
<https://blog.naver.com/dkehd82/223122457861>

**Comment by telk5093** [comment]
최소 시운전 시기까지 추가 보류
