### ISSUE TITLE
[New] EMU-320

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#368]
#### 그래픽 스프라이트(Graphic sprite):
~`EUM` 스프라이트를 그대로 사용~

![EMU320](https://user-images.githubusercontent.com/77984422/202521406-7cb4e7fe-9793-4493-be2e-3e654eafd9c8.png)

![EUM320_32bpp](https://user-images.githubusercontent.com/77984422/202521481-0e0e339c-e8a7-4bcd-aca6-c1c73f100e68.png)

#### 제안할 차량 제원(Suggest vehicle specification):
| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) | ~KTX-이음 (320)~ |
| 영문 이름(Name in English) | ~KTX-EUM (320)~ |
| 코드(Code) | ~`EUM320`~ |
| 운영 속력(Speed) | **320 km/h** |
| 설계 최고 속력(Designed max. speed) | **352 km/h** |
| 화물 수송량(Capacity) | 76 |
| 출력(Power) | 13200kW |
| 중량(Weight) | 60t |
| 도입연도(Introduction year) | **2022** |

1호차(TC1): **46석**
2호차(M'1): **76석**
3호차(M1): **55석**
4호차(Mm2): **68석**
5호차(M2): **74석**
6호차(M3): **68석**
7호차(M'3): **76석**
8호차(TC2): **52석**
**총 515석**

~차량 이름에 괄호를 추가하여 기존 EMU-260과 구분 (_KTX-이음 (260)_, _KTX-이음 (320)_)~

#### References:
* 제원 등
 <http://www.redaily.co.kr/news/articleView.html?idxno=4336>
 <https://www.yna.co.kr/view/AKR20220927034852003>
 <http://www.redaily.co.kr/news/articleView.html?idxno=1856>
* 좌석 수
 <https://youtu.be/3oMcj7txC54>
 <https://gall.dcinside.com/mgallery/board/view?id=monorail&no=164356>

**Comment by telk5093** [comment]
차량을 추가하지 않고 도색 개조로 처리할 예정

**Comment by EightonEight** [comment]
제작사인 현대로템에서는 [EMU-320을 KTX-이음으로 부르지 않고 있으므로](https://m.post.naver.com/viewer/postView.naver?volumeNo=34556365), 등급명이 확실하게 정해지기 전까지는 추가를 보류해야 할 것 같습니다.

**Comment by EightonEight** [comment]
> 차량을 추가하지 않고 도색 개조로 처리할 예정

![image](https://user-images.githubusercontent.com/77984422/193242693-cecc24af-1d34-4a6a-bb40-51f264754c0a.png)
![image](https://user-images.githubusercontent.com/77984422/193242874-5d3f1706-f2fe-4646-9148-41a575c90bb9.png)

혹시 EMU-320에는 KTX-이음에 없는 객차를 따로 반영이 가능할까요?
(팬터그래프가 달린 객차와 형태가 동일하나, 팬터그래프가 달려 있지 않다는 차이가 있음)

ref: <https://youtu.be/vKldZjgXVYU>
![제목 없음](https://user-images.githubusercontent.com/77984422/193243682-45d8401e-24b7-4bdb-8929-6847effcd503.png)

example:
![미리보기 (2)](https://user-images.githubusercontent.com/77984422/193243754-e2108b60-5d56-4eb4-97ff-43a36a6bad7a.png)

**Comment by telk5093** [comment]
> 혹시 EMU-320에는 KTX-이음에 없는 객차를 따로 반영이 가능할까요?

가능합니다.
