### ISSUE TITLE
마터 2형, 파시 5형, 미카 3형 증기기관차

### ISSUE THREAD

**Issue by troy7737** [KoreanGRF/KoreanTrainSet#37]
![마터 2형, 파시 5형, 미카 3형 증기기관차, 비둘기호 객차 스프라이트](https://user-images.githubusercontent.com/75788864/107755403-19179600-6d66-11eb-8198-0e82d00f4c7a.png)

 마터와 파시의 탄수차의 스프라이트는 같습니다. 혹시 코드 짜실 때 편리한 점이 있을까봐 알려드립니다. 

오른쪽의 탄수차와 기관차가 붙은 모습은 꼭 이렇게 해달라는 것은 아닙니다. 상황이 여의치 않다면 저기서 좀 더 떨어뜨리셔도(혹은 붙이셔도)됩니다. 

[마터 2형](https://namu.wiki/w/%EB%A7%88%ED%84%B0%ED%98%95%20%EC%A6%9D%EA%B8%B0%EA%B8%B0%EA%B4%80%EC%B0%A8)

[미카 3형](https://namu.wiki/w/%EB%AF%B8%EC%B9%B4%ED%98%95%20%EC%A6%9D%EA%B8%B0%EA%B8%B0%EA%B4%80%EC%B0%A8#s-2.3)

[파시 5형](https://namu.wiki/w/%ED%8C%8C%EC%8B%9C%ED%98%95%20%EC%A6%9D%EA%B8%B0%EA%B8%B0%EA%B4%80%EC%B0%A8#s-2.5)

**Comment by telk5093** [comment]
* 비둘기호 객차는 고증이 맞지 않아 사용하지 말아달라는 그래픽 원작자의 말이 있었음

**Comment by telk5093** [comment]
Implemented by c1ea5d0
