### ISSUE TITLE
[Bug] 유조차 고증오류

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#372]
**한국 열차 세트 버전(Version of Korean Train Set):**
eg. 2.3.0

![TANK_CAR](https://user-images.githubusercontent.com/88026704/195300695-5aef086f-e10c-4767-a779-5f8d935993ae.png)
유조차 회색 도색은 실제로는 `양회 조차` 이며 석유를 적재하지 않음.
그러나 이 경우 FIRS 산업시설을 사용하지 않는 유저가 회색 도색의 차량을 운용할 수 없게 되므로

회색 도색 차량을 FIRS의 `시멘트` 적재를 가능하게 조치하고 개조 목록에 `양회 조차`로 나타나도록 하는 것을 건의드리는 바입니다.

* 이 차량은 구도색이 존재하지 않습니다.

* ref.
https://youtu.be/ksaFPEQVY7Q

**Comment by EightonEight** [comment]
### 조차 수정(안)

#### 유조차(수정)
![TANK_CAR](https://user-images.githubusercontent.com/77984422/196174886-5be63fa2-f4c3-4385-bb8e-5d98bcfe3512.png)
`TANK_CAR`
* 은색 도색 → 하얀색 도색(프로필렌 화차)
* ref: https://images.app.goo.gl/mQGohXiU69JgRkk27

---
#### 벌크시멘트 화차(신규)
![BULK_CEMENT_CAR](https://user-images.githubusercontent.com/77984422/196176414-dcbe755a-ee27-47c0-b45b-eea07f819352.png)
`BULK_CEMENT_CAR`
* FIRS 미사용 시: `GRAI`, `COAL`, `IORE` 수송(무개화차와 동일)
* FIRS 사용 시: `CMNT`, `QLME`, `SAND`, `SASH` 등 가루/분말형 화물 수송
* ref: 
  - https://images.app.goo.gl/CEYiZ8JeRaGDtEzn9
  - https://youtu.be/enTXovmmYCs?t=20

**Comment by telk5093** [comment]
혹시 이 화차가 앞뒤 구분이 있나요? 있다면 8방향화 하는 게 좋을 것 같네요.
앞뒤 구분이 없다면 제 댓글은 무시해주세요.

**Comment by EightonEight** [comment]
![TANK_CAR (2)](https://github.com/KoreanGRF/KoreanTrainSet/assets/77984422/4fb27c18-9ad1-4248-898c-4a9f17a9368b)

![CEMENT_CAR (2)](https://github.com/KoreanGRF/KoreanTrainSet/assets/77984422/42369d2d-ad92-4cd8-a713-cd5d95b8f48e)

최종 그래픽 스프라이트 수정
* 템플릿에 맞도록 대차 부분 수정

유조차 및 벌크시멘트 화차는 점대칭 구조로 되어있어 8방향화가 불필요합니다.
레퍼런스는 위 링크로 갈음합니다.

**Comment by telk5093** [comment]
> 유조차 및 벌크시멘트 화차는 점대칭 구조로 되어있어 8방향화가 불필요합니다.

#410 의 템플릿은 무조건 8방향을 강제하고 있기 때문에 왼쪽 4방향을 오른쪽에 복제하여 사용하겠습니다.

**Comment by telk5093** [comment]
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/83c2596c-a45f-462a-bbd7-f9d640503f5c)
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/374fe16a-2b6e-474f-b270-3fd055efb213)
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/4a79ecd8-3e57-4661-b1b1-cec3a427f144)
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/2d41dcc1-6d65-4e3a-9918-67e8f54857f7)

실제로 구현해보니 화차가 다소 뚱뚱해보이네요.

**Comment by opentrain** [comment]
https://n.news.naver.com/mnews/article/001/0000459114
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/81477455/eb6dd33b-91c6-4bfa-bbb2-ee7394238378)

벌크화물열차의 경우 사다리가 서로 반대방향에 하나씩 있습니다.
이거 또한 언제간 또 다른사람이 올리지않을까해서 참고용으로 올립니다.
