### ISSUE TITLE
[New] 인천 1호선 1세대 신도색 스프라이트

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#373]
#### 그래픽 스프라이트(Graphic sprite):
![INCHEON_METRO_1K_VVVF_1ST_2](https://user-images.githubusercontent.com/77984422/197381848-27b476fb-2d5a-4956-97f5-bb3192795399.png)
`INCHEON_METRO_1K_VVVF_1ST_2`

#### References:
<https://images.app.goo.gl/3fGWX36NEtMiiA3c8>
<https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=331057>
<https://youtu.be/S7R1AwEex-I>

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/211285489-64ffc6c8-31ce-45a6-93f8-50fe1d4c3085.png)
``INCHEON_METRO_1K_VVVF_1ST_2022``
