### ISSUE TITLE
[Bug]개조 새마을호의 출입문 위치 고증오류

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#378]
**한국 열차 세트 버전(Version of Korean Train Set):**
최신 버전

**버그 내용 설명(Describe the bug):**
![image](https://user-images.githubusercontent.com/88026704/206821981-f9c99ac5-f8f9-4126-9277-65ce01d6d96d.png)
이차량은 무궁화호 리미트 객차를 개조, 격상한 차량입니다. 그렇기 때문에 무궁화호 리미트 객차와 같이 ↗→↘ 방향의 문 위치가 잘못되어있는 문제가 있었고, 추가로 ← 방향의 창문 위치가 무궁화호 리미트 객차와 다른 문제가 추가로 발견되었습니다. 

**올바른 상황 설명(Describe the expected situation):**
이 차량의 래퍼런스는 #357 차량을 개조한 것이므로 여기에 준합니다. 
![Saemaeul_Refurbished_Wagon](https://user-images.githubusercontent.com/88026704/206822117-51c53a72-fffa-4102-842a-fb0383d6092d.png)
* https://blog.naver.com/ndh7782/221999720738
* https://blog.naver.com/jiggy98/221424563520

**Comment by telk5093** [comment]
ITX 새마을의 객차를 그대로 갖다 썼기 때문에 이 문제를 해결하려면 코드 작업도 병행되어야 합니다.
작업 우선 순위를 낮게 잡아두겠습니다.

**Comment by EightonEight** [comment]
#227 에서 ITX 새마을의 객차를 그대로 갖다쓰지 않고, 스프라이트를 새로 만들어 `SAEMAEUL_CAR.png`에 추가한 것으로 알고 있습니다.
별도의 코드 작업 없이 스프라이트 수정만으로 적용이 가능할 것으로 보이네요.
