### ISSUE TITLE
[Add] Ecobee car (Incheon Airport Maglev Line)

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#38]
* car: Ecobee

열차 형식 | 도시철도 입선용 자기부상열차
-- | --
구동 방식 | 전기 동력분산식 열차
운행 노선 | 인천공항 자기부상철도
급전 방식 | 직류 1500V 제3궤조집전식
설계 최고속도 | 110km/h
영업 최고속도 | 80km/h
기동 가속도 | 4.0 km/h/s
신호 방식 | CBTC
제작 회사 | 한국기계연구원, 현대로템
생산량 | 8량
궤간 | 1,850mm
도입 년도 | 2009년~2012년
동력 장치 | 선형유도전동기 (LIM)
제어 방식 | VVVF - IGBT
편성 대수 | 2량 1편성
전동차 비 | M차 100%
전장 | 12m
전폭 | 2.7m
전고 | 3.45m
차중 | 19t(MC)
정원 | 186명

**Comment by telk5093** [comment]
We need discussions since it is already implemented in RIMS

**Comment by troy7737** [comment]
![인천국제공항 자기부상철도 (에코비) 1차 완성](https://user-images.githubusercontent.com/75788864/112130940-56e0c780-8c0c-11eb-9771-5fd3ba382a55.png)
백업용

**Comment by kiwitreekor** [comment]
> We need discussions since it is already implemented in RIMS

2cc Train Set에도 8200호대가 있으니 딱히 큰 문제가 되지는 않을 것 같네요.

**Comment by telk5093** [comment]
f21b9c9에서  반영됨
