### ISSUE TITLE
[Bug] 신림선 전동차의 등장년도 문제

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#381]
**한국 열차 세트 버전(Version of Korean Train Set):**
eg. 2.3.0

**버그 내용 설명(Describe the bug):**
![image](https://user-images.githubusercontent.com/88026704/211199940-e04c32a2-b726-43c9-9a90-ec847f63d04e.png)

**올바른 상황 설명(Describe the expected situation):**
신림선 열차의 개발 년도가 2012년으로 되어있음, 실차는 2020년 도입됨.

**Comment by telk5093** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/blob/main/src/spec.py#L80 confirmed
