### ISSUE TITLE
[Bug] G-train 2차 수정

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#387]
**한국 열차 세트 버전(Version of Korean Train Set):**
작업 완료 후 업데이트는 안된 차량입니다.

**버그 내용 설명(Describe the bug):**
색상 때문인지는 모르겠는데 2호차(방송실 객차) 문 위치가 부자연스럽게 보이더군요.

**올바른 상황 설명(Describe the expected situation):**
![G-train_passinger](https://user-images.githubusercontent.com/88026704/216982752-d8f58c7e-087b-4632-98cb-92f0d2faa7e1.png)

전체 객차의 ↙방향 창문 그래픽(실제 차량에서 화장실 부분)을 교정하고 2호차의 남쪽 출입문 스프라이트를 1px 내렸으며 ↖방향 북쪽 출입문 스프라이트를 1px 올렸습니다.

추가로 
![image](https://user-images.githubusercontent.com/88026704/216980329-89b520e2-be19-433a-b037-9c3c64543748.png)
여기서 G-train 객차는 A-train과 다르게 →방향이 보였던 것 같습니다. 그렇기 때문에
![image](https://user-images.githubusercontent.com/88026704/216980633-4b8d1745-2f1b-4ce7-8541-912701b141e7.png)
←방향과 →방향을 뒤바꾼 부분은 반영하지 않았습니다.

**Comment by telk5093** [comment]
> ←방향과 →방향을 뒤바꾼 부분은 반영하지 않았습니다.

반영하고 다시 알려주십시오.
또한 각 그래픽 스프라이트의 간격은 30px이어야 하니 그것도 같이 수정 바랍니다.

**Comment by JukjeonWani** [comment]
>반영하고 다시 알려주십시오

이부분은 #361 작업 중 확인하는 과정에서 실수가 발생하여  잘못된 답을 드려서 뒤바뀐 부분이라 원래대로 되돌린다 보시면 됩니다. 반영된 이후의 아래 사진처럼 뒤바뀐 채로 유지하면 2호차만 방향이 뒤집어진 형태가 되어 부자연스러운 모습이 연출됩니다.
즉, 뒤바꾸기 전 본문의 스크린샷이 의도한 상태가 되는 것입니다.
![image](https://user-images.githubusercontent.com/88026704/217506011-3caa5136-4924-4daa-838c-a7ff8487a038.png)

>또한 각 그래픽 스프라이트의 간격은 30px이어야 하니 그것도 같이 수정 바랍니다.

이게 수정되면 다른 관광열차도 일괄적으로 수정되어야 합니다.
수정하는 과정에서 스프라이트 간격은 건드리지 않았습니다. #361 이슈에서도 그렇고 그 이전 스프라이트도 스프라이트 간격은 동일합니다.

**Comment by telk5093** [comment]
> 이게 수정되면 다른 관광열차도 일괄적으로 수정되어야 합니다.
> 수정하는 과정에서 스프라이트 간격은 건드리지 않았습니다. #361 이슈에서도 그렇고 그 이전 스프라이트도 스프라이트 간격은 동일합니다.

이미 제가 일괄적으로 수정해서 반영했습니다.
30px 간격으로 작업되지 않은 그래픽 스프라이트의 경우 제가 직접 수정해서 반영하기 때문에 반영에 시간이 더 걸리게 됩니다.

**Comment by JukjeonWani** [comment]
>(추가로 우측의 숫자 부분은 그래픽 스프라이트에 반영하지 않으니 참고 바랍니다.)

알고 있습니다. 객차 순서 참고 목적으로 적어둔 거라서요

그럼 스프라이트 간격 조정해서 다시 올려드리도록 하겠습니다.

**Comment by telk5093** [comment]
간격 조정해서 반영하였으니 신경쓰지 않으셔도 됩니다.
