### ISSUE TITLE
소화물차 스프라이트 개선 및 추가

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#389]
#### 그래픽 스프라이트(Graphic sprite):
![BAGGAGE_CAR](https://user-images.githubusercontent.com/77984422/217911405-2f44d78b-22bb-416c-a8f3-36ca9fe69c00.png)
`BAGGAGE_CAR` - 수정
 * from #126, #225 
 * 일부 도색 제거(적색, 주황색 → 차장차)
 * 실제에 맞게 98년형, 99년형 분리
 * 유개차 개조 소화물차(급행 소화물 도색 포함, [#138(comment)](https://github.com/KoreanGRF/KoreanTrainSet/issues/138#issuecomment-963364360)) 추가
 * 상하차 스프라이트 추가

---
![MUGUNGHWA](https://user-images.githubusercontent.com/77984422/217914406-c40da75e-bd9a-4529-b73c-fe1d34c2fc7a.png)
`MUGUNGHWA` - 신규
 * 상하차 스프라이트 추가

---
![TONGIL](https://user-images.githubusercontent.com/77984422/217915011-fd1511d2-1f1f-4beb-a662-8f4ae4c9e1e7.png)
`TONGIL` - 신규
 * from #226 
 * 스프라이트 규격에 맞게 위치 조정

---
![BIDULGI](https://user-images.githubusercontent.com/77984422/217914603-fc6876a5-1ac3-4f4d-b3d6-7e8acfb18cb7.png)
`BIDULGI` - 수정
 * from #228 
 * 스프라이트 규격에 맞게 위치 조정

---
#### 제안할 차량 제원(Suggest vehicle specification):
| Property | Suggest value (1999) | (1998) | (1966, 유개차 개조) | (1999, 고속소화물) | (통일호) | (비둘기호) |
|--------|--------|--------|--------|--------|--------|--------|
| 이름(Name in Korean) | 소화물 전용 / 1999년: 어두운 파랑 | 소화물 전용 / 1998년: 어두운 파랑 | 유개차 개조 / 어두운 파랑 | 고속소화물 / 무궁화호 파랑 & 빨강 | 소화물 / 통일호 녹색 & 황색 | 소화물 / 비둘기호 녹색 & 황색 |
| 영문 이름(Name in English) | New type / 1999 livery: Dark blue | New type / 1998 livery: Dark blue | Box car type / Dark blue | High-speed type / Mugunghwa Blue & Red | Old type / Tongil Green & Yellow | Old type / Green & Yellow |
| 코드(Code) | `BAGGAGE_CAR_1999_*` | `BAGGAGE_CAR_1998_*` | `BAGGAGE_CAR_BOX_*` | `BAGGAGE_CAR_MUGUNGHWA_*` | `BAGGAGE_CAR_TONGIL_*` | `BAGGAGE_CAR_BIDULGI_*` |
| 운영 속력(Speed) | **120 km/h** | **120 km/h** | 90 km/h | 150 km/h | 110 km/h | 110 km/h |
| 화물 수송량(Capacity) | 35 | 35 | 30 | 35 | 30 | 30 |
| 출력(Power) | - | - | - | - | - | - |
| 중량(Weight) | **26t** | **26t** | **22t** | **33t** | 20t | 20t |
| 도입연도(Introduction year) | **1999** | **1998** | **1966** | **1999** | **1984** | **1962** |

#### References:
* 소화물 전용
 <https://blog.naver.com/osan1290/220387191525>
 <https://blog.naver.com/sg971110/220877563448>
 <http://photozou.jp/photo/show/50802/22084041>
* 유개차 개조
 <https://youtu.be/pe3qRgGusHs?t=95>
 <https://blog.naver.com/yeogistation/220254205297>
* 고속소화물
 <https://cafe.naver.com/korailslr/43972>
 <https://blog.naver.com/sm525v88/50001355224>
 <https://blog.naver.com/anchyo/220819992039>
 <https://youtu.be/4R5rOIsMsJE?t=460>
* 통일호, 비둘기호
 (이전 이슈로 갈음)

#### 참고용 계통도(소화물 전용, 고속소화물 한정)
![계통도](https://user-images.githubusercontent.com/77984422/217926727-cd12b31b-653f-4dc1-b10a-ca52e8079216.png)

**Comment by telk5093** [comment]
여러 건이 하나의 이슈에 몰아져있어 추적 관리 및 작업이 어렵네요.
하나 하나 소량의 작업이 될만한 건으로 이슈를 분리하는 것도 좋을 것 같습니다.

일단 소화물차에 대형 작업이 필요한 건이라 쉽사리 시작하기 어려운 이슈로 보입니다.

**Comment by SerpensNebula** [comment]
![217911405-2f44d78b-22bb-416c-a8f3-36ca9fe69c00](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/8f994f6e-4061-498b-bb0e-100f97a17aa6)
달라진 점
- 새 크로마키에 넣음
- 대각선 방향 새 차량 규격과 달랐던 점들 수정
- % 숫자를 조정함
  - 화물 채우는 단계에 문 닫은 스프라이트까지 추가하면 0-33, 33-66, 66-100%로 나뉘고, 추가하지 않으면 0-50, 50-100%가 됨  

![217914406-c40da75e-bd9a-4529-b73c-fe1d34c2fc7a](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/c2262fa0-1806-4853-b130-ef127169137f)
달라진 점
- 위와 같음
- 일부 지붕 역광인 부분 없앰
- 지붕 좀 더 둥글게 솟아보이게 함
- % 숫자의 경우 위와 동일하여 없앰

![217914603-fc6876a5-1ac3-4f4d-b3d6-7e8acfb18cb7](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/4f29249a-2036-4f13-b77e-786811854fed)
![217915011-fd1511d2-1f1f-4beb-a662-8f4ae4c9e1e7](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/f4deb40b-9a31-44da-b2cd-c450cdbbc0a6)
달라진 점
- 위와 같음

**Comment by SerpensNebula** [comment]
현재 수정해야 할 유개화차 중 일부는 여기 스프라이트에서 그대로 갖다 쓰시면 될 것 같습니다.

**Comment by telk5093** [comment]
고속 소화물(``MUGINGHWA``), ``TONGIL``, ``BIDULGI`` 를 각각 별도의 이슈로 분리하여 등록해주시면 감사드리겠습니다.
첫 번째 새 크로마키 그래픽 스프라이트만 적용하고 본 이슈를 닫을까 합니다.
