### ISSUE TITLE
한국선로세트 제3궤조 지원

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#391]
주요내용:새로 추가된 선로 제3궤조 지원 필요

선로 Label은 "KL3L" 입니다.

단순히 라벨을 알려드리기 위해 작성한 이슈입니다.

https://github.com/SerpensNebula/Korean-Tracks/blob/main/Korean_Tracks.nml 링크에서 KL3L 로 검색

**Comment by SerpensNebula** [comment]
잠깐 보류함. label 수정가능성 있음

**Comment by SerpensNebula** [comment]
"KL3L" 로 작업해주세요.

**Comment by telk5093** [comment]
열차 NewGRF는 한 차량에 하나의 선로만 지원 가능한 것으로 확인됩니다. [(*Ref)](https://www.tt-forums.net/viewtopic.php?p=1115945&sid=16ec5788e7f0ebbb21e70eed80789629#p1115945)
따라서 한국 열차 세트 쪽에서 경전철이 한국 선로 세트의 제3궤조를 지원하도록 만들기 위해서는
경전철의 railtype 매핑을 완전히 끊어야 하며 한국 열차 세트가 한국 선로 세트에 의존되게 만듭니다.

따라서 열차 세트 쪽에서 이를 작업하는 것은 (방송에서 언급했던 것과는 다르게) 다소 부정적인 방향으로 고려해야할 것 같습니다. (∵ 한국 선로 세트가 없으면 경전철 차량 사용이 불가능해짐)
이를 해결할 방안을 마련하기 전까지는 일단 보류하고자 합니다.

**참고(현재 매핑):**
| **차량명** | **현재** |
|---|---|
| 부산 4호선 | ``KRLR`` |
| 부산김해경전철 | ``ELRL`` | 
| 대구 3호선 | ``KRLR`` |
| 김포 골드라인 | ``ELRL`` |
| 인천 2호선 | ``ELRL`` |
| 신림선 | ``ELRL`` |
| 의정부경전철 | ``KRLR`` |
| 우이신설선 | ``ELRL`` |
| 용인경전철 | ``ELRL`` |

**Comment by SerpensNebula** [comment]
기존선과 개량선 선로를 KL3L도 지원하게 바꾼 버전입니다. 이걸로도 확인 부탁드립니다. 

[Korean_Tracks.zip](https://github.com/KoreanGRF/KoreanTrainSet/files/10774408/Korean_Tracks.zip)

**Comment by SerpensNebula** [comment]
다른 방법도 있습니다. 차량은 그대로 두고 한열셋에 있는 KRLR 의 지원 선로 목록에 제3궤조를 넣어도 됩니다.

**Comment by telk5093** [comment]
> 제3궤조에 일반열차가, 일반선로에 제3궤조 차량이 다니는 문제

를 예상해서 ``compatible_railtype_list``와 ``powered_railtype_list``에 선로를 추가하는 것도 이미 생각해봤는데 같은 문제가 예상돼서 말씀드리지 않았습니다.

**Comment by telk5093** [comment]
> 다른 방법도 있습니다. 차량은 그대로 두고 한열셋에 있는 KRLR 의 지원 선로 목록에 제3궤조를 넣어도 됩니다.
> alternative_railtype_list, compatible_railtype_list, powered_railtype_list 에 "KL3L" 추가

한국 열차 세트에서는 이 방법을 사용하고



> KRLR만 지원하는 버전입니다.
> 이 방안도 여전히 한 선로에 여러 차량이 다 나오지만, 최소한 일반선로에는 일반열차만, 경전철 선로류에는 경전철만 나옵니다.

한국 선로 세트에서는 이 방법을 사용하여 양쪽에서 대응하는 건 어떤가요?

**Comment by SerpensNebula** [comment]
네, 이게 좋겠습니다.

**Comment by telk5093** [comment]
1. 한국 열차 세트 + 한국 선로 세트시
![image](https://user-images.githubusercontent.com/10726524/219870505-dc73685c-5b23-4596-bb21-c9e189ff0948.png)

2. 한국 열차 세트 단독 사용시: (기존과 동일)
![image](https://user-images.githubusercontent.com/10726524/219870564-277fa7c2-86fa-490e-918e-cb16d0916805.png)

3. 한국 선로 세트 단독 사용시: (사용 가능한 차량 없음)



LGTM합니다. 논의한 대로 진행하겠습니다.

**Comment by SerpensNebula** [comment]
나중에 가능하면 구매창의 로고를 수정하는 것도 좋겠습니다. 3궤조는 3궤조 로고, 모노레일은 모노레일 로고, 고무차륜은 고무차륜 로고 이런 식으로.. (모노레일 이하는 나중에 선로가 만들어지면 그때)

**Comment by telk5093** [comment]
> 나중에 가능하면 구매창의 로고를 수정하는 것도 좋겠습니다.

그것은 별도 이슈로 추후 알려주시면 감사하겠습니다.
https://github.com/KoreanGRF/KoreanTrainSet/actions/runs/4211570986 에서 현재 커밋 반영본 테스트 가능하니 참고 바랍니다.
한국 선로 세트 측에서도 문제 없으면 이슈 닫도록 하겠습니다.

**Comment by SerpensNebula** [comment]
지금은 어처피 제3궤조 선로 하나만 있어서, 지금 로고를 수정해봐자 큰 의미가 없을 것 같습니다. 이슈 닫으셔도 됩니다.
