### ISSUE TITLE
경전철 차량들의 선로 라벨 수정 필요

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#392]
**한국 열차 세트 버전(Version of Korean Train Set):**
최신 버전

**현재 상황**
차량명 | 라벨
-- | --
부산 4호선 | `KRLR`
부산김해경전철 | `ELRL`
대구 3호선 | `KRLR`
김포 골드라인 | `ELRL`
인천 2호선 | `ELRL`
신림선 | `ELRL`
의정부경전철 | `KRLR`
우이신설선 | `ELRL`
용인경전철 | `ELRL`

**수정 필요**
차량명 | 라벨
-- | --
부산 4호선 | `KRLR`
부산김해경전철 | `ELRL`
대구 3호선 | `KRLR`
김포 골드라인 | `ELRL`
인천 2호선 | `ELRL`
신림선 | `KRLR`
의정부경전철 | `KRLR`
우이신설선 | `ELRL`
용인경전철 | `ELRL`

* #391 의 이슈대로라면 고무차륜경전철과 모노레일 차량만 철차륜 3궤조에 등장하는 모순되는 상황이 발생
* 신림선은 `부산지하철 4호선`, `의정부경전철` 처럼 고무차륜 경전철이므로 선로 라벨을 `KRLR`로 지정하는게 맞다고 봅니다.
* 부산김해경전철, 김포골드, 인천 2호선, 우이신설, 용인경전철 등은 제3궤조 선로이므로 `MetroTracks`, `NuTracks`, `UK Railway Set tracks`, `Japanese Track Set` 등의 선로 grf에 있는 제 3궤조 선로 코드인 `3RDR` 라벨로 분류하는게 맞다 봅니다.(다만 `3RDR`은 공통적으로 적용된 라벨이며, 각 선로별로 자체적인 라벨이 추가로 부여되어 있는 것으로 보이며, 한국 선로 세트의 제 3궤조 선로에서 운행할 차량임을 감안, 수정할 필요성 있으므로 당분간은 기존대로 존치)

**Comment by telk5093** [comment]
> 신림선은 부산지하철 4호선, 의정부경전철 처럼 고무차륜 경전철이므로 선로 라벨을 KRLR로 지정하는게 맞다고 봅니다.

이는 신림선이 다닐 선로가 아직 없는 관계로 게임적 허용이며 의도된 상황입니다.
신림선이 고가 경전철 선로(``KRLR``)에서 달리는 것이 더 이상하므로 변경할 계획이 없습니다.
