### ISSUE TITLE
[Bug] 일부 경전철 차량의 선로 변경 필요

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#395]
**한국 열차 세트 버전(Version of Korean Train Set):**
2.4.0

**버그 내용 설명(Describe the bug):**
부산 김해경전철, 인천 2호선, 용인 에버라인, 서울경전철 우이신설선, 김포 도시철도, 서울 경전철 신림선 

위 차량들은 실제로는 제3궤조를 쓰는데, 현재 전기선로ELRL 지원으로 되어있음

**올바른 상황 설명(Describe the expected situation):**
지원선로를 _한열셋 경전철 선로KRLR_ 로 바꿔야 함

**Comment by telk5093** [comment]
해당 열차가 전기 선로를 쓰는 것은 실제 해당 노선들이 철로 된 궤도를 달리는, 철제 차륜이기 때문이므로 의도된 현상입니다.
한국 열차 세트의 경전철 선로(``KRLR``)는 콘셉상 콘크리트 도상에 (경우에 따라) 고무 차륜을 상정하고 있으므로 적절하지 않습니다.

다만 조금 더 고민이 필요할 듯 합니다.

**Comment by SerpensNebula** [comment]
한국 선로 세트에는 현재 모노레일 선로와 고무차륜 선로 제작이 계획되어있습니다. 그 때 가서 생각해도 될 듯 합니다.

**Comment by SerpensNebula** [comment]
그렇다면 한국선로세트에서 추후 만들어질 선로들(모노레일, 고무차륜 선로 계획중)을 보고 판단하는 것이 좋겠네요. 그 때까진 이 이슈는 열어놓기만 하는 걸로 하겠습니다.

**Comment by JukjeonWani** [comment]
제가 알기로는 `KRLR`은 철차륜 제3궤조 선로인 것으로 알고 있습니다. 고무차륜 궤도의 경우 아직 작업되지 않은 것으로 보입니다.

https://github.com/SerpensNebula/Korean-Tracks/issues/1#issue-1036433556

**Comment by telk5093** [comment]
> 제가 알기로는 `KRLR`은 철차륜 제3궤조 선로인 것으로 알고 있습니다. 고무차륜 궤도의 경우 아직 작업되지 않은 것으로 보입니다.

``한국 열차 세트의 경전철 선로(`KRLR`)는 콘셉상 콘크리트 도상에 (경우에 따라) 고무 차륜을 상정하고 있으므로``

**Comment by JukjeonWani** [comment]
아 본문 내용을 착각했네요. 죄송합니다

**Comment by JukjeonWani** [comment]
관련 이슈를 확인해보고 왔습니다. 위에 나열된 열차 중 신림선을 제외하면 철차륜 제3궤조 전동차로 철차륜 제 3궤조 선로인 `KL3L` 선로에 추가되는게 의도사항인 것으로 파악됩니다. #391 확인 결과 이 선로가 모노레일, 고무차륜 선로인 `KRLR`과 호환되게 코딩되어 있어 발생한 문제로 보입니다.

지금 상황에서 `철차륜 제 3궤조 경전철` 차량을 `철차륜 제 3궤조 경전철 선로`에서 운행하지 못하며 오히려 `고무차륜 3궤조 측면가선방식 전동차`가 운행하는 상황이 되어버려 이렇게 된 듯 하며, 근본적인 문제 해결을 위해서는 한열셋에도 `철차륜 제 3궤조 선로`를 추가하는것이 필요할 것 같습니다.

그리고 한국선로세트 개발 계획에 따라 이번과 같은 문제점이 발생하지 않도록 하기 위해서 장기적으로 `대구 3호선 열차` 전용 모노레일 선로의 추가도 필요할 것으로 보이며 이와 동시에 현재의 `경전철 선로`도 개선이 필요할 듯 합니다.

**Comment by telk5093** [comment]
> 관련 이슈를 확인해보고 왔습니다. 위에 나열된 열차 중 신림선을 제외하면 철차륜 제3궤조 전동차로 철차륜 제 3궤조 선로인 `KL3L` 선로에 추가되는게 의도사항인 것으로 파악됩니다. #391 확인 결과 이 선로가 모노레일, 고무차륜 선로인 `KRLR`과 호환되게 코딩되어 있어 발생한 문제로 보입니다.
> 
> 지금 상황에서 `철차륜 제 3궤조 경전철` 차량을 `철차륜 제 3궤조 경전철 선로`에서 운행하지 못하며 오히려 `고무차륜 3궤조 측면가선방식 전동차`가 운행하는 상황이 되어버려 이렇게 된 듯 하며, 근본적인 문제 해결을 위해서는 한열셋에도 `철차륜 제 3궤조 선로`를 추가하는것이 필요할 것 같습니다.
> 
> 그리고 한국선로세트 개발 계획에 따라 이번과 같은 문제점이 발생하지 않도록 하기 위해서 장기적으로 `대구 3호선 열차` 전용 모노레일 선로의 추가도 필요할 것으로 보이며 이와 동시에 현재의 `경전철 선로`도 개선이 필요할 듯 합니다.

한국 열차 세트는 선로 관련 내용을 되도록 [한국 선로 세트](https://github.com/SerpensNebula/Korean-Tracks)에 일임하려고 하고 있으므로, 큰 이슈가 발생하지 않는다면 한국 열차 세트에 별도의 선로를 추가할 생각은 없으며 장기적으로 ``KRLR`` 역시 한국 선로 세트가 가져가기를 희망합니다.

**Comment by SerpensNebula** [comment]
텔크님 의견이 맞습니다. 한국선로세트는 한열셋 KRKR도 흡수할 계획입니다.(단, 그대로 갖고 가는게 아니라, 제3궤조와 작업예정인 모노레일, 고무차륜 총 3개로 분할계승 느낌으로)

따라서 아직 선로세트에 제3궤조밖에 없는 현재로선 현 상태가 가장 타당하다고 생각합니다.

**Comment by SerpensNebula** [comment]
한국선로세트에서 새 선로를 만들기 전까지는 닫음처리 해놓음
