### ISSUE TITLE
[Bug]관광열차의 일부 객차가 등장하지 않음

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#396]
**한국 열차 세트 버전(Version of Korean Train Set):**
2.4.0

**버그 내용 설명(Describe the bug):**
* S-train(남도해양열차)
둘 다 2호차(방송실) 객차 누락되어 있음
![image](https://user-images.githubusercontent.com/88026704/222733361-47e50629-0157-440d-975d-e6b779a23f83.png)
![image](https://user-images.githubusercontent.com/88026704/222733520-854a85d4-8c0f-4284-a58a-e2dd6686f43c.png)

**올바른 상황 설명(Describe the expected situation):**
* S-train(남도해양열차)
src 확인 결과 8방향만 반영되고 2호차(방송실 객차)는 반영되지 않았음을 확인
그래픽 수정 필요(src 참고하여 스프라이트를 수정, 2호차(방송실 객차) 그래픽 문제도 발견되어 수정함)
![S-train_passinger_Remake](https://user-images.githubusercontent.com/88026704/222735902-1278ba14-7116-4cd2-9ed6-ec8c20ef342d.png)

**Comment by telk5093** [comment]
8bpp 그래픽 상 5px 정도의 차이는 구분이 가지 않습니다.
들이는 공에 비해 보이는 결과가 적습니다.
