### ISSUE TITLE
[Add] 3등객차, 비둘기호 객차

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#40]
* Reference: https://cafe.naver.com/ottd/16120

**Comment by troy7737** [comment]
![비둘기호 3차 완성](https://user-images.githubusercontent.com/75788864/111063958-d0820280-84f4-11eb-93fc-6ef7cd181afd.png)

**Comment by troy7737** [comment]
3등 객차부터 마지막 통일호 도색까지 한 종류로 묶고 개조로 구분하게 하면 될 것 같습니다.

가운데 70s~94 도색의 경우 객차를 사면 두 차량이 랜덤으로 나오게 부탁드립니다.

노랑 초록 도색의 경우 통일호의 그 도색과 미묘하게 다른 걸(초록색이 더 연함) 반영했습니다.

DC 동차의 경우 정식명칭은 DC 혹은 통근형 디젤 동차라고 합니다. 그리고 앞뒤구분이 없습니다.

소화물차는 아마도 우편과 상품 두 가지만 운송할 수 있게 해도 될 것 같습니다.

**Comment by troy7737** [comment]
3등 객차 [https://ko.wikipedia.org/wiki/3%EB%93%B1_%EA%B0%9D%EC%B0%A8](url) 다9형 기준, 70년대 전후로 폐차되거나 비둘기호로 전환

빨간 객차 [https://ko.wikipedia.org/wiki/%ED%86%B5%EC%9D%BC%ED%98%B8#%EA%B8%B0%EB%B3%B8%EC%A0%81%EC%9D%B8_%EC%99%B8%ED%98%95%EC%9D%98_%ED%86%B5%EC%9D%BC%ED%98%B8_%EA%B0%9D%EC%B0%A8(%EC%9B%90%EC%A1%B0_%ED%86%B5%EC%9D%BC%ED%98%B8)](url) 원조 통일호 문단, 도입한지 얼마 안 돼 대부분 비둘기호로 격하

70s~94 객차 [https://ko.wikipedia.org/wiki/%EB%B9%84%EB%91%98%EA%B8%B0%ED%98%B8#%EC%9E%A5%EC%9D%98%EC%9E%90_%EA%B0%9D%EC%B0%A8](url) 고정의자, 장의자 객차 부분

통일호 도색은 바로 위 70s~94 객차와 같은 종류임 (도색만 새로 함)

DC 동차 [https://ko.wikipedia.org/wiki/%ED%86%B5%EA%B7%BC%ED%98%95_%EB%94%94%EC%A0%A4_%EC%95%A1%EC%95%95_%EB%8F%99%EC%B0%A8](url)

소화물차는 이미 있는 객차형 화물차와 그냥 똑같이 하시면 될 것 같습니다. 소화물차는 완전히 자료가 전무합니다..;;

**Comment by troy7737** [comment]
아 3등 객차는 갈색 객차는 뺐습니다. 비중이 큰 것도 아닌데 여러 종류일 필요는 없을 것 같아서요.

**Comment by troy7737** [comment]
![비둘기호 4차 완성](https://user-images.githubusercontent.com/75788864/111121433-fb7d5c80-85af-11eb-9129-958b5b4d9436.png)
