### ISSUE TITLE
[Bug] 평판화차 스프라이트 수정

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#403]
**한국 열차 세트 버전(Version of Korean Train Set):**
2.4.0

**버그 내용 설명(Describe the bug):**
평판화차가 약간 어긋나있어서 수정합니다.

**올바른 상황 설명(Describe the expected situation):**
![화차 평판화차 1차 완성 검정](https://user-images.githubusercontent.com/75788864/231477490-d5b8bd0d-1f94-4994-b3a7-13d7ef7c6b58.png)
![화차 평판화차 1차 완성 파랑](https://user-images.githubusercontent.com/75788864/231477494-1284e905-64b0-4827-86be-7739bfba81bd.png)
![화차 평판화차 1차 완성 갈색](https://user-images.githubusercontent.com/75788864/231477483-a9ea4fcc-29ca-4433-a587-3b9e3877603a.png)

비교
![ezgif-1-abffb4c7d2](https://user-images.githubusercontent.com/75788864/232331666-83302a93-a8aa-43d1-a1f5-86e4f6f2ca56.gif)

스프라이트 프리셋은 일반객차(무궁화호)와 같습니다.

**Comment by SerpensNebula** [comment]
사이즈 조정해봤는데 너무 짧아서 그냥 32px로 함

**Comment by SerpensNebula** [comment]
안타깝게도 그렇습니다. 

어처피 작업하실 거, 아예 원래 길이에 맞는 24px 버전도 만들까요? 한 1/4쯤 만들다 만게 있긴 합니다.

https://github.com/KoreanGRF/KoreanTrainSet/issues/157

**Comment by SerpensNebula** [comment]
아래 스프라이트는 길이를 24px로 수정한 버전입니다.

32px, 24px 둘 중 하나 골라서 해주세요.

![화차 평판화차 3차 완성 검정](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/c7439b8d-5cf0-42f6-8ea6-d3ddbb7e07bc)
![화차 평판화차 3차 완성 파랑](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/39cec7bd-06c7-46a1-9a79-655e77fbbfd0)
![화차 평판화차 3차 완성 갈색](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/7e8d8c9c-9961-4170-aafa-2d406f46a9ea)

**Comment by telk5093** [comment]
> 다음은 https://github.com/KoreanGRF/KoreanTrainSet/issues/157#issuecomment-904044583 스프라이트를 24px로 수정한 것입니다.

![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/16d8ce59-6e5a-4b8b-a86f-139914c46804)
@SerpensNebula 이 차량의 기둥 없는 버전이 필요합니다.


기존:
![STAKE_CAR_without_stake](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/2b4b21e4-9eb2-4860-bfdb-cd4365bfd13c)
