### ISSUE TITLE
[Bug] NDC 동차 수송량 조정 요청

### ISSUE THREAD

**Issue by j-h-p-a-r-k** [KoreanGRF/KoreanTrainSet#407]
**한국 열차 세트 버전(Version of Korean Train Set):**
eg. 2.0.0 or 최신 버전

최신 버전

**버그 내용 설명(Describe the bug):**
버그 내용을 자세히 설명해주세요. 스크린 샷이 있으면 첨부해주세요.
Describe the detail of the bug. Please attach some screenshots if exists.

NDC 동차의 수송량이 1량당 44석으로 적용되었으나, 이는 실제 NDC 동차의 수송량과 다릅니다.
실제 NDC 동차의 1량당 수송량은 60석 내지 64석이었습니다.

**올바른 상황 설명(Describe the expected situation):**
버그가 이렇게 수정되어야 한다는 점을 설명해주세요.
Describe how this bug should be fixed and what is expected.

NDC 동차의 수송량을 1량당 64석으로 변경해주실 것을 요청드립니다.

**Comment by telk5093** [comment]
> 실제 NDC 동차의 1량당 수송량은 60석 내지 64석이었습니다.

출처를 제시해주십시오.

**Comment by j-h-p-a-r-k** [comment]
https://blog.naver.com/lotteno49/221211060860
https://blog.naver.com/sj10913/50001134339
https://cafe.daum.net/kicha/OQb/1424
https://cafe.daum.net/kicha/OQb/1425

퇴역한 지 10년이 넘은 열차라 자료가 많이 없네요... 미약하지만 올려봅니다.

**Comment by JukjeonWani** [comment]
자료를 통해 추정한 수송량(운전차량) - 운전실의 존재로 좌석이 1열 적었던 것으로 보임
· 초기도색: 3+2 좌석배열 - 74석
· 구도색(내부 리모델링 이후 ~퇴역시까지: 2+2 좌석배열 - 60석

창문 갯수 및 의자 배열로 계산한 수송량(객차)
· 초기도색: 3+2 좌석배열 - 80석
· 구도색(내부 리모델링 이후)~퇴역시까지: 2+2 좌석배열 - 64석

추가 래퍼런스
· https://youtu.be/KY4Tih4GBSs
· https://youtu.be/A3UNHKX2tvU

**Comment by telk5093** [comment]
> https://blog.naver.com/lotteno49/221211060860
> https://blog.naver.com/sj10913/50001134339
> https://cafe.daum.net/kicha/OQb/1424
> https://cafe.daum.net/kicha/OQb/1425

를 근거로 64석으로 일괄 처리합니다.




> 자료를 통해 추정한 수송량(운전차량) - 운전실의 존재로 좌석이 1열 적었던 것으로 보임 · 초기도색: 3+2 좌석배열 - 74석 · 구도색(내부 리모델링 이후 ~퇴역시까지: 2+2 좌석배열 - 60석
> 
> 창문 갯수 및 의자 배열로 계산한 수송량(객차) · 초기도색: 3+2 좌석배열 - 80석 · 구도색(내부 리모델링 이후)~퇴역시까지: 2+2 좌석배열 - 64석

와 같은 상세한 분리는 too much이므로 64석으로 일괄 데포르메합니다.
