### ISSUE TITLE
[Bug] DEC 개조목록에 년도표기가 뒤집어짐

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#411]
**한국 열차 세트 버전(Version of Korean Train Set):**
2.4.0

**버그 내용 설명(Describe the bug):**
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/88026704/10cf7fc0-d8e0-4cd9-b86f-5f39f2c96f5e)
년도 표기가 반대로 되어 있음

**올바른 상황 설명(Describe the expected situation):**
| 년도 | 종별 |
|----------|----------|
| 1980~1986년 | 새마을호 |
| 1986~1994년 | 무궁화호 |

**Comment by telk5093** [comment]
가능하다면 반드시 출처를 제시해주시기 바랍니다.

https://ko.wikipedia.org/wiki/%EC%9A%B0%EB%93%B1%ED%98%95_%EB%94%94%EC%A0%A4_%EB%8F%99%EC%B0%A8
> [1980년](https://ko.wikipedia.org/wiki/1980%EB%85%84)에 전후 동력형 새마을호 열차로, [대우중공업](https://ko.wikipedia.org/wiki/%EB%8C%80%EC%9A%B0%EC%A4%91%EA%B3%B5%EC%97%85)에서 5량 단위 2개 편성(총 10량)으로 제작 도입하였다. 도입 당시에는 객차형 [새마을호](https://ko.wikipedia.org/wiki/%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8) 객차와 같은 분위기의 실내 배경이었으며, 서울-남원간 새마을호 열차로 운행하였다. [1986년](https://ko.wikipedia.org/wiki/1986%EB%85%84)에 사각형 창문의 기존 객차가 현재와 같은 둥근 창문 형태의 유선형 새마을호 객차로 바뀌어 운행되면서, [무궁화호](https://ko.wikipedia.org/wiki/%EB%AC%B4%EA%B6%81%ED%99%94%ED%98%B8)로 격하되었고
