### ISSUE TITLE
[New] 양산도시철도 전동차

### ISSUE THREAD

**Issue by n0373** [KoreanGRF/KoreanTrainSet#413]
**그래픽 스프라이트(Graphic sprite):**

![Screenshot_20230522_170044_Chrome](https://github.com/KoreanGRF/KoreanTrainSet/assets/68586069/ac421d86-6582-4b48-8091-884eb188dfec)

**제안할 차량 제원(Suggest vehicle specification):**
| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) _(eg. ``KTX 산천``)_ | 이름 |부산교통공사 Y100호대 전동차
| 영문 이름(Name in English) _(eg. ``KTX Sancheon``)_ | Busan Transportation Corporation series Y100 EMU|
| 코드(Code) _(eg. ``KTX2N``)_ | ``BY100`` |
| 운영 속력(Speed) _(eg. ``300km/h``)_ | 60 km/h |
| 설계 최고 속력(Designed max. speed) _(eg. ``330km/h``)_ | 80 km/h |
| 화물 수송량(Capacity) _(eg. ``100명``)_ | 80명 |
| 출력(Power) _(eg. ``4400kW``)_ | 1000kW |
| 중량(Weight) _(eg. ``136t``)_ | 50t |
| 도입연도(Introduction year) _(eg. ``2024``)_ | 1900 |

**Comment by telk5093** [comment]
개통까지 수 년은 남은 노선으로 보이는데 지금부터 벌써 이슈로 등록할 필요는 없어보입니다.
