### ISSUE TITLE
[Bug] 화차 유지비용이 매우 낮음?

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#414]
**한국 열차 세트 버전(Version of Korean Train Set):**
2.4.0

의도된 사항인지 궁금합니다.

![1](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/68e4d39a-dfcc-4808-b404-6def35af2436)
![2](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/9cee717c-e8c4-4654-8256-6726ab11256d)

**Comment by telk5093** [comment]
객차의 경우 ``running_cost_base`` 값이 ``RUNNING_COST_DIESEL`` 또는 ``RUNNING_COST_ELECTRIC`` 으로 되어있고
화차의 경우 ``150``의 magic number로 하드 코딩되어 있는데, 버그로 보입니다.

**Comment by SerpensNebula** [comment]
제 예상으로는 화차도 객차만큼 비싸게 조정하실 것 같았는데, 반대군요.

※발전차도 유지비용이 객차처럼 설정되어있으니 수정하실때 같이 부탁드립니다.

**Comment by telk5093** [comment]
바닐라 객화차의 경우 유지비가 모두 없는 점,
NML spec 상 running_cost_base는 기관차에 사용하는 값(eg. ``RUNNING_COST_DIESEL`` 등)만 있는 점
등을 이유로 화차에서 유지비를 제거하는 것이 맞다고 판단하여 그렇게 변경합니다.
