### ISSUE TITLE
[New] 대구권 광역철도 전동차

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#415]
#### 그래픽 스프라이트(Graphic sprite):
![392K_2023 (2)](https://github.com/KoreanGRF/KoreanTrainSet/assets/77984422/60b83def-e3ff-4204-805b-60adcb931259)
실제 열차는 2량 1편성이나, 게임 플레이 편의를 위해 가상의 중간 객차가 포함되었습니다.

#### 제안할 차량 제원(Suggest vehicle specification):
| Property | Suggest value |
|--------|--------|
| 이름(Name in Korean) | 대구권 광역철도 |
| 영문 이름(Name in English) | Daegu Metropolitan Railroad |
| 코드(Code) | ``392K_2023`` |
| 운영 속력(Speed) | **100 km/h** |
| 설계 최고 속력(Designed max. speed) | **110 km/h** |
| 화물 수송량(Capacity) | 100 |
| 출력(Power) | 1000kW |
| 중량(Weight) | **57t/1량** |
| 도입연도(Introduction year) | **2023** |

#### References / 실차 현황:
* 갑종수송
  - <https://youtu.be/HPPVk4QLTc0>
  - <https://youtu.be/hBtOIIszuho?t=10>
* 시운전
  - <https://youtu.be/z17zy8RD2t4> (차량)
  - <https://youtu.be/mF--VtGMgfo> (본선)
* 제원
  - <https://youtu.be/YoSNXC1Q5s4?t=120>

**Comment by telk5093** [comment]
1안) 새로운 차량으로 추가할 것인지
2안) ``수도권 1호선, 통근형`` 아래에 도색 개조로 추가할 것인지
3안) #301 의 1안을 반영하면서 ``통근형`` 차량 아래에 도색 개조로 추가할 것인지

명확히 판단이 서지 않는 상황입니다.
가장 좋은 것은 3안이지만 작업량이 방대하고, 1, 2안은 반대로 작업량이 적습니다.

**Comment by JukjeonWani** [comment]
MC-MC라는 기술적 차이와 게임상에서 구매 시 공통객차 연결이 필수적으로 요구되지 않는 것을 감안하면

> 1안) 새로운 차량으로 추가

가 가장 적당할 것으로 보입니다.

**Comment by EightonEight** [comment]
1안을 따르되, [#301의 3안](https://github.com/KoreanGRF/KoreanTrainSet/discussions/301#discussioncomment-6184463)을 반영하여 묶음 리스트로 그룹화하는 것이 좋을 것 같습니다.

**Comment by SerpensNebula** [comment]
![전동차 대구권 광역철도 392000호대](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/d3c21cf1-0eac-49d4-b82d-ec6d476c0304)
새 크로마키 규격에 맞게 고쳤습니다.

주된 수정사항
- 대각선 방향들 1px씩 크로마키 밖으로 삐져나온 것들 고침
- ↔방향 길이가 33px인 것들을 한열셋 길이인 31px로 고침
- 스프라이트들을 크로마키 규격에 넣음

**Comment by EightonEight** [comment]
![392K_2023](https://github.com/KoreanGRF/KoreanTrainSet/assets/77984422/36674c8d-4d2e-4df6-ade8-765eda738c05)
* `tmpl_standard`+`tmpl_standard_longnose` 적용
* 차량 순서 변경
* 운전실부 수정
