### ISSUE TITLE
차막이 그래픽에 눈 그래픽 제공

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#425]
아한대 기후에서 차막이 오브젝트 지형 그래픽에 눈 그래픽을 제공

**Comment by SerpensNebula** [comment]
차막이에 눈이 쌓인 스프라이트를 새로 만드실게 아니라면, GROUNDSPRITE_XXX 를 NORMAL에서 SNOW로 바꾸시면 됩니다.

**Comment by telk5093** [comment]
> 차막이에 눈이 쌓인 스프라이트를 새로 만드실게 아니라면, GROUNDSPRITE_XXX 를 NORMAL에서 SNOW로 바꾸시면 되고, 계절 switch는 한국선로세트 등의 코드를 참고하시면 됩니다.

도움 말씀 감사합니다만 본 이슈는 이미 작업이 되어있고 모종의 이유로 커밋만 되지 않았습니다 :)
