### ISSUE TITLE
[Bug] FIRS 아한대 기후 기본 사용시 고령토 적재 화차가 잘못됨

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#426]
**한국 열차 세트 버전(Version of Korean Train Set):**
2.5.0

**버그 내용 설명(Describe the bug):**

![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/a2e29bd3-005b-413f-952f-a938fa875a95)

아한대 기후에서 FIRS 아한대 기후 기본 사용시, 유조차가 고령토를 실음

**올바른 상황 설명(Describe the expected situation):**
고령토(``KAOL``)는 무개화차나 유개화차가 실을 수 있어야 함

**Comment by EightonEight** [comment]
가루형 화물을 싣는 벌크시멘트 화차를 사용하는 것도 괜찮을 것 같습니다.

**Comment by telk5093** [comment]
수정됨 (모종의 이유로 커밋만 안 됨)
