### ISSUE TITLE
[New] KTX-1 (새 스프라이트, 새 크로마키 규격)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#427]
중복작업을 피하기 위해 먼저 적어둡니다. 

특이사항: 전후두부의 길이가 객차보다 더 길어서, 전후두부 규격을 쓸 예정
전후두부 바로 뒷객차도 길이가 긴데, 반드시 중간에 껴있어야하는 차량이라 일반객차 규격으로 할 예정

코딩 작업자에게 건의: KTX-1는 연접대차라서, 가능하면 32px 꽉 채워 만들고 싶습니다. 어떻게 안될까요?

**Comment by telk5093** [comment]
> KTX-1는 연접대차라서, 가능하면 32px 꽉 채워 만들고 싶습니다. 어떻게 안될까요?

잘 이해가 안 되는데 이 1px 부분까지 쓰고싶다는 말씀이실까요?
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/9fa01424-d28b-4dd6-bd80-36069717d8e4)

**Comment by SerpensNebula** [comment]
네, 맞습니다. 그래야 붙어보이니까요. 

개발방향에 맞지 않다면 그대로 31px로 작업하겠습니다.

**Comment by SerpensNebula** [comment]
![2](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/8dc9d28d-31af-473a-88b2-6165d1de4c05)
작업중인 스프라이트

**Comment by SerpensNebula** [comment]
![KTX](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/d8e9aee7-149a-48d7-8fed-a88e998055e6)

예상도에선 오류가 보이지 않았지만 혹시 모르니 만드시고 한 번 더 확인해보시기 바랍니다.

**Comment by telk5093** [comment]
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/9f7d508d-b77d-4cdf-bc23-256705fb3801)
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/31e85d34-2b92-4794-b6a5-7ec0fec1466e)

문제 없이 완벽하네요.
