### ISSUE TITLE
ITX-새마을 그래픽 개선

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#428]
#307 에서 추가된 EMU-150 과 비교했을 때 기존의 ITX-새마을이 조금 더 밝은 느낌의 붉은 색으로 구현되어 있음.
실물 사진에서는 그닥 차이가 없으나 인게임에서 구현된 모습은 서로 색감이 매우 달라 통일이 필요함.

ITX-새마을 쪽 그래픽에 KTX-이음, EMU-150과 마찬가지로 32bpp 그래픽을 추가하여 현실에 가까운 색상을 구현하는 것이 좋을 것으로 보임

1. 실물 사진 비교
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/4d253c18-cf0d-42a6-920a-fbd25e004fcd)
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/3ef1b548-c986-4e7f-a8fa-3e081cd94306)

2. 인게임 구현물 비교
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/fffd642f-4b1b-4a49-b770-5fdf6a6b2876)

**Comment by EightonEight** [comment]
추가 ref: <https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=324098> (<https://youtu.be/f_Z6joXhd8g>)

**Comment by SerpensNebula** [comment]
오히려 기존 itx-새마을이 미세하지만 더 탁한색으로 보입니다. 스프라이트로는 새 차량이 더 탁해보이는데

**Comment by SerpensNebula** [comment]
![전동차 220000호대 - ITX-새마을 4차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/7954c079-b1f4-4dd2-865d-5d0c0a82e8d4)
![전동차 220000호대 - ITX-새마을 4차 완성 32bpp](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/42dc0f3a-ed5a-4ea2-a0f1-be1b2209ebc6)

달라진점
- [링크](https://github.com/KoreanGRF/KoreanTrainSet/issues/428#issuecomment-1684919572)를 보니 스프라이트와는 반대로  새 ITX-새마을의 빨간색 부분이 오히려 채도가 더 높아보임. 따라서 새 차량의 빨간색 부분의 채도를 한단계 높임(기존과 큰 차이는 없음)
- 구 ITX-새마을과 새 ITX-새마을의 검은색 부분은 약간 색이 다르고('새' 쪽은 분명 탁한 남색계열로 보일만큼 밝지만, '구' 쪽은 더 어두워보임), 스프라이트에서 적당하게 반영된것 같음. 더 고칠 필요는 없는 듯 함.

**Comment by telk5093** [comment]
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/653de4ce-e7c6-41d1-aafc-33ca54ca5b8b)

훌륭합니다. 반영되었으므로 이슈를 닫겠습니다. (커밋은 추후)

**Comment by telk5093** [comment]
EMU-150의 그래픽을 ITX-새마을에 적용하는 실수가 있어 다시 이슈를 엽니다.

**Comment by telk5093** [comment]
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/f872da22-8c96-4b8c-bf25-c71ef5022cfc)

1번의 차량 오프셋이 2번과 같아야 해서 1px 왼쪽으로,
3번의 차량 오프셋이 4번과 같아야 해서 1px 오른쪽으로 이동합니다.

**Comment by SerpensNebula** [comment]
> 1번의 차량 오프셋이 2번과 같아야 해서 1px 왼쪽으로, 3번의 차량 오프셋이 4번과 같아야 해서 1px 오른쪽으로 이동합니다.
혹시 다른 전후두부 규격 쓰는 차량들도 이렇게 작업하셨나요? 이러면 차량을 같은 한쪽에 붙여야 한다는 조건이 깨져서, 스프라이트가 아니라 오프셋을 수정하셔야 합니다.

**Comment by telk5093** [comment]
> 혹시 다른 전후두부 규격 쓰는 차량들도 이렇게 작업하셨나요?

``KTX1N``도 동일하게 처리되었고, 저 또한 차량을 한쪽에 붙이는 게 좋은 것 같아서 방법을 고민 중입니다.
 1. 후두부에 한해 ``tmpl_standard_r`` 템플릿을 사용하는 방법 (1~4와 5~8을 뒤집은 템플릿)
 2. ``tmpl_standard``의 offset 자체를 수정하는 방법
등이 있겠네요.

**Comment by SerpensNebula** [comment]
솔직히 전 1~2미터 정도의 길이 차이는 무시하고 모두 표준규격으로 합치는게 제일 좋다고 생각합니다.

**Comment by SerpensNebula** [comment]
> 혹시 다른 전후두부 규격 쓰는 차량들도 이렇게 작업하셨나요? 이러면 차량을 같은 한쪽에 붙여야 한다는 조건이 깨져서, 스프라이트가 아니라 오프셋을 수정하셔야 합니다.

위 글은 무시해주세요. 아무래도 저건 규격의 문제가 아니라, nml쪽의 문제 같아 보입니다. 후두부는 그냥 저렇게 작업하는게 가장 좋을 것 같습니다.

**Comment by EightonEight** [comment]
> 혹시 다른 전후두부 규격 쓰는 차량들도 이렇게 작업하셨나요?

새 규격이 올라가고 나서 제작된 모든 동차 스프라이트가 동일하게 처리되었습니다.

> 1. 후두부에 한해 `tmpl_standard_r` 템플릿을 사용하는 방법 (1~4와 5~8을 뒤집은 템플릿)
> 2. `tmpl_standard`의 offset 자체를 수정하는 방법

1. 윗 의견대로 템플릿 개수가 4개가 되는 단점이 있습니다.
2. 객화차형 차량과 동차형 차량의 위치를 모두 만족하는 오프셋으로 변경해야 합니다.
  2.1. 길이 8의 차량은 ↕ ↔ 방향만 변경하면 되나, 7 이하는 모든 방향의 변경이 필요합니다.

개인적으로는 스프라이트 단에서 동차형 차량의 후두부만 뒤집어 처리하는 방식을 그대로 유지했으면 합니다.
