### ISSUE TITLE
[New] 새마을호 객차 (새 차량규격, 새 크로마키)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#429]
![객차 새마을호 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/76342b40-66ee-4b3c-8a1f-6aae4df1a142)

다음은 무궁화호 격하객차(+무궁화호 크로마키에 맞춤) 작업예정

--------------------
아래는 기본형태와 창문만 떼어놓은 것입니다. (투명)
![2](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/d7475a37-281b-419b-8f20-6a61134a65a5)
![3](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/95856286-9dec-4d91-a26b-3242b6e99e06)

**Comment by telk5093** [comment]
반영 완료
