### ISSUE TITLE
[New] 무궁화호 객차 (새 크로마키, 차량 규격)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#430]
![객차 무궁화호 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/a5ab2515-6b75-4c63-bf22-e6c01251ef07)

달라진 점
- 우선 새 크로마키 규격으로 옮김
- 일부 차량 역광인 부분 없앰
- 새마을호 격차 객차들 새 새마을호 객차로 리뉴얼함

8.21 수정
- 구식 객차들(위에서부터 3개) 지붕 둥글게 솟아보이게 함
- 일부 객차 창문 좌우반전되었던 것 수정(제가 만든 차량이 아니라 놓칠 뻔)

**Comment by SerpensNebula** [comment]
구식 객차 지붕 곡선 추가중입니다.

**Comment by telk5093** [comment]
다른 이슈와 마찬가지로 문제없고 반영 후 이슈 닫겠습니다.

다만, 무궁화호 객차는 아래 그래픽이 별도로 있어 추후 동일한 템플릿 변경이 필요하므로, 추적의 용이성을 위해 추가로 남겨둡니다.
G-train
S-train
A-train
Haerang

**Comment by SerpensNebula** [comment]
관광차량들은 나중에... ㅎㅎ
