### ISSUE TITLE
[New] 통일호 객차 (새 크로마키)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#431]
![객차 통일호 2차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/1f2a11a9-4938-4a16-b396-79bd08a21a12)

달라진 점
- 새 크로마키로 옮김
- 일부 지붕 역광인 부분 없앰
- 일부 벽 높이 안맞았던 것 수정

8.21 수정
- 지붕 좀 더 둥글게 솟아보이게 함

**Comment by SerpensNebula** [comment]
지붕 곡선 추가중입니다.

**Comment by telk5093** [comment]
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/2632e88b-3b8f-44a9-b28f-9a7ab6c8a3d2)

문제 없네요. 반영 후 이슈 닫겠습니다. (커밋은 추후)
