### ISSUE TITLE
[New] 관광호 객차 (새 크로마키)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#433]
![객차 관광호 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/9eed65ff-342a-4c01-9e3b-293ce0ee6428)

달라진 점
- 새 크로마키로 옮김
- 지붕 일부 역광인 부분 수정
- 지붕 약간 둥글게 솟아보이게 수정

**Comment by telk5093** [comment]
반영 완료
