### ISSUE TITLE
[New] CDC/RDC (새 크로마키, 새 차량 규격)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#434]
식당차에 rdc 차량도 있어서 cdc/rdc도 작업하고 있씁니다.

할게 많고 도색도 복잡해서 좀 오래걸릴겁니다.

**Comment by SerpensNebula** [comment]
두종류 빼고 다 완성한 상황입니다.

**Comment by SerpensNebula** [comment]
새벽중에 올라갈 예정입니다.

**Comment by SerpensNebula** [comment]
![동차 CDC 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/4eaa8527-4fc3-4482-83c1-ca0dab9d5b0f)

달라진점
- 퀄리티 전반적으로 약간만 개선
- 새 크로마키 틀에 넣음

**Comment by telk5093** [comment]
Perfect 👍
