### ISSUE TITLE
[New] 식당/카페차 (새 크로마키, 새 차량 규격)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#435]
![객차 식당차 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/c589ac0a-2adc-4bcc-8b8d-1ab1925bf3ff)

작업하신 뒤 이상한 곳이 없나 꼭 한번 확인해주세요.

**Comment by telk5093** [comment]
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/fc3e16db-149d-4fc4-b2c6-ad421f7bace4)

![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/f49fc7b2-6358-4a8c-b7a4-d934eebc2f60)

대체로 문제가 없으나 →, ← 쪽에서 오프셋이 안맞고 연결부 색감이 조금 다른 문제가 있네요.

**Comment by SerpensNebula** [comment]
![객차 식당차 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/e4e4da70-6c3f-4273-b02d-eed048d4b5f4)

**Comment by SerpensNebula** [comment]
다른 오류가 발견돼서 확인중

**Comment by SerpensNebula** [comment]
다시 고쳐서 엶

**Comment by telk5093** [comment]
Many thanks
