### ISSUE TITLE
Support 3rd (steel) rail

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#44]
- [ ] 인천 2호선
 - [ ] 서울 우이신설경전철
 - [ ] 김포골드라인
 - [ ] 부산김해경전철
 - [ ] 용인 경전철

**Comment by Gamunbi** [comment]
![THIRD_RAIL](https://user-images.githubusercontent.com/75788864/201404531-16cd854c-5fa7-4841-93a1-b3da20a59d7f.png)

나중에 적용하실 때 스프라이트 위치는 편하신대로 옮기시면 됩니다.

한열셋과는 별개로, 한국선로셋에 제3궤조 선로를 빠른 시일 내에 추가할 예정입니다. 제3궤조 선로에 대해 생각해두신 label 이 있다면 알려주세요. 그걸 사용하겠습니다.

**Comment by telk5093** [comment]
> 나중에 적용하실 때 스프라이트 위치는 편하신대로 옮기시면 됩니다.

본 이슈는 선로를 추가한다는 의미가 아니라 이미 존재하는 선로를 지원해야 한다는 의미입니다.
한국 선로 세트에 제3궤조가 추가된다면 해당 목록의 차량에서 해당 궤조를 지원하게 만들면 되므로 신경쓰지 마시고 작업하시면 됩니다.

작성해주신 코멘트는 이슈와 관련이 없으므로 hide 처리하겠습니다.

**Comment by Gamunbi** [comment]
알겠습니다. 그럼 작업하겠습니다.

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.
