### ISSUE TITLE
[Bug] ITX-마음 팬터그래프, 미등 관련 스프라이트 오류

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#444]
#### 한국 열차 세트 버전(Version of Korean Train Set):
2.6.0-RC1

#### 버그 내용 설명(Describe the bug):
![#444(1)](https://github.com/KoreanGRF/KoreanTrainSet/assets/77984422/974e8bc7-2bbf-4885-a93b-8b1fe173aae6)
* 진행방향 앞쪽 팬터그래프가 올라가 있음
* 진행방향 뒤쪽 운전실에 전조등이 점등되어 있음

#### 올바른 상황 설명(Describe the expected situation):
![#444(2)](https://github.com/KoreanGRF/KoreanTrainSet/assets/77984422/23489b6d-c1a7-4115-869e-d4fe31ce6f2b)

#### References:
<https://youtu.be/LgMVpZ5kTJU?t=40> - 팬터그래프
<https://youtu.be/5vC2GXEvnKk?t=30> - 미등

**Comment by SerpensNebula** [comment]
수정중

**Comment by SerpensNebula** [comment]
![전동차 220000호대 - ITX-새마을 4차 완성 32bpp](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/616b6797-3473-442d-a2b1-e0ff134e00f3)
![전동차 220000호대 - ITX-새마을 4차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/c7f14104-f99f-443f-a0c1-a59fe14a6bea)
