### ISSUE TITLE
[Bug] 증기기관차 (새 그래픽, 새  크로마키)

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#445]
![증기기관차 미카형 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/eac5512b-81c9-4a47-b3f5-8922a65a857f)
![증기기관차 파시형 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/010869da-fc7c-4e84-a8c3-daa0c849b991)
![증기기관차 마터형 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/65fbc1dc-46ea-4ced-9a9d-58f84a113842)
위부터 미카3, 파시5, 마터2

※각 차량의 길이도 참고해 주세요.
미카3: 7, 4
파시5: 8, 4
마터2: 8, 4

스프라이트 달라진점(모두 한국초기열차셋에서 그대로 가져옴)
- 새 크로마키에 넣음
- 동륜 부분 퀄리티 높임
- 마터2형: 창작도색이었던 걸 옛 도색으로 바꿈

**Comment by telk5093** [comment]
![1](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/0be37ed2-ee3a-4439-bc74-816ab5027913)
1x1 픽셀이 깜빡거리는데 의도된 그래픽인가요?
미카, 파시, 마터 모두 1~2개씩 있습니다.

**Comment by SerpensNebula** [comment]
아 초기열차셋이 도스팔레트를 쓰는걸 깜박했습니다. 다시 수정해서 올려드리겠습니다.
