### ISSUE TITLE
[Bug] 평판화차 코일류 화물들 싣기 전과 후의 화차 모양이 다름

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#447]
![일러스트](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/68e2f0d8-0a55-4060-aebf-ba586cec831b)
화물 종류가 너무 많아 다 확인해보지는 못했습니다. 코일화차 그래픽을 쓰는 화물들을 모두 확인해보는게 좋을 것 같습니다.

바라는 방향:
[STAKE_CAR_without_stake](https://github.com/KoreanGRF/KoreanTrainSet/blob/main/src/wagon/stake_car/STAKE_CAR_without_stake.png) 를 쓰는게 더 나아보임

**Comment by telk5093** [comment]
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/675adc21-1f55-4378-b52d-fa990bc9b4ee)
Fixed

**Comment by EightonEight** [comment]
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/77984422/c42d5ca9-7097-4a7d-8b27-e83057802f80)
`cargo_COPR`에 있는 빈 화물 그래픽을 사용하는게 조금 더 자연스러울 것 같습니다.

**Comment by telk5093** [comment]
> `cargo_COPR`에 있는 빈 화물 그래픽을 사용하는게 조금 더 자연스러울 것 같습니다.

![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/d11f6732-241a-4810-8192-71aedbc3010c)
네 그게 더 낫네요

**Comment by SerpensNebula** [comment]
> ![image](https://user-images.githubusercontent.com/77984422/265447653-c42d5ca9-7097-4a7d-8b27-e83057802f80.png) `cargo_COPR`에 있는 빈 화물 그래픽을 사용하는게 조금 더 자연스러울 것 같습니다.

만들었는데 제가 까먹었나보군요.
