### ISSUE TITLE
차막이 그래픽 신규 추가

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#451]
[Kiwitree Korean Stations Set](https://github.com/kiwitreekor/korean_station/blob/master/images/platforms.png)의 차막이 그래픽을 가져와서 써도 될 듯. (라이선스 CC-BY-NC-SA v3.0으로 호환 가능)

**Comment by JukjeonWani** [comment]
- 콘크리트 궤도
![Train stopper_CON_object](https://github.com/KoreanGRF/KoreanTrainSet/assets/88026704/9e4e46c3-80eb-4fed-8b16-06c35a1fde23)
- 자갈궤도
![Train stopper_Gra_object](https://github.com/KoreanGRF/KoreanTrainSet/assets/88026704/c7656b54-8226-4fe5-80d8-7b336953eab6)

예전에 작업헤둔 것이 있습니다. 원한다면 살짝 변형해서 사용하셔도 괜찮습니다.

**Comment by SerpensNebula** [comment]
만드신건 좋아보이는데, 한열셋은 기본적으로 디폴트선로를 이용하고 있습니다. 위 차막이는 한열셋보단 한국선로세트에서 쓰는게 더 어울릴 것 같네요.

**Comment by SerpensNebula** [comment]
한국선로세트에 추가할 예정입니다. 한열셋에는 굳이 넣을 필요 없을 것 같습니다.
