### ISSUE TITLE
[New] 사운드 추가 관련

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#453]
열차가 역에서 출발하거나 차량기지에서 나올 때 재생되는 소리
- 동일차종이나 전동기 종류가 여러종류인 경우, 개조를 통해 성능이 다른 차종으로 바꿀 수 있는 경우는 제외  (ex. 수도권 1호선 전동차, 수도권 2호선 전동차, 수도권 3호선 전동차, 대구 1호선 전동차, 부산 2호선 전동차, 8×00호대 전기기관차, KTX-산천 외 다수)

**사운드는 모두 8bit mono wav 파일입니다.**
- 확장자가 wav가 아닌 경우 게임에서 파일을 불러오지 못함
- wav 확장자여도 8bit mono 파일이 아닌 경우 콜백은 성공하나 사운드 재생이 되지 않음

현재 사운드 제공 가능 열차
- [ ] 7×00호대 디젤전기기관차
- [ ] 7000호대 디젤전기기관차
- [ ] 7600호대 디젤전기기관차
- [ ] 누리로
- [ ] ITX-새마을
- [ ] ITX-청춘
- [ ] ITX-마음
- [ ] 대전 1호선, 광주 1호선 전동차
- [ ] KTX-1
- [ ] SRT
- [ ] KTX-이음 (260, 320)

원하지 않을 경우 닫으셔도 됩니다.

**Comment by telk5093** [comment]
해당 기능을 도입할 경우 별도의 매개변수 설정 추가가 필요할 것으로 보입니다.
없어서 나쁠 것은 없으나 추가에 대해서 여러 곳에서 의견을 받아보는 게 좋을 것 같습니다.

**Comment by JukjeonWani** [comment]
알겠습니다. 조만간 의견 수렴을 한번 하겠습니다.

**Comment by telk5093** [comment]
From: https://cafe.naver.com/ottd/47727
> https://github.com/KoreanGRF/KoreanTrainSet/issues/453
> 에서 여러 곳의 의견을 들어보는 게 좋겠다고 말씀드리긴 했지만,
> 지금 작성하신 이 글을 보니 Issue의 의도가 결국 한국 열차 세트를 통해 DTS의 완성도를 높이겠다는 의도로 받아들여집니다.
> 한국 열차 세트를 다른 NewGRF의 완성도를 위해 사용하겠다는 것은 불순한 의도로 보입니다.

> 최초 github에 올리신 issue만 보았을 때에는 상당히 긍정적으로 생각했으나, 이 글을 보니 반대로 상당히 회의적인 생각이 드네요.
> 작성자 분의 글 작성 의도가 그게 아니었다 하더라도 은연 중에 본심을 글 내용에 드러낸 것이 아닌가 할 정도로 느껴졌습니다.

> 한국 열차 세트에 DTS에서 사용하는 차량 사운드 추가에 관한 건은 회의적으로 생각하고 있겠습니다.
