### ISSUE TITLE
[Bug] KTX-1 스프라이트 겹침, 엇나감

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#454]
![일러스트](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/9fa5a52b-a173-4041-8745-9dc7809af2c9)

중련했더니 전후두부가 겹치는 문제와 후두부가 1px 어긋난 문제가 있음

- 해결방법
전후두부를 표준 스프라이트 규격으로 바꿀 예정

1px 어긋난 문제는 크로마키에서 스프라이트를 반대쪽으로 붙여야 할듯

**Comment by SerpensNebula** [comment]
![전동차 KTX](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/90d88b25-efa6-47a9-bfa0-56ba7535485f)

**Comment by telk5093** [comment]
LGTM
