### ISSUE TITLE
[Bug] 전기기관차 새 크로마키

### ISSUE THREAD

**Issue by SerpensNebula** [KoreanGRF/KoreanTrainSet#456]
![전기기관차 8x00호대, 8500호대 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/5e7d85f0-97dd-4b3d-961d-1be7187e1ab2)
8x00호대, 8500호대

![전기기관차 8000호대 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/098dd41f-3256-4d29-837d-9546a8c4015d)
8000호대

객차랑 화차가 어느정도 되고나니 이제 기관차가 눈에 띄기 시작해서 올립니다.

**Comment by telk5093** [comment]
Great
