### ISSUE TITLE
[Bug] 수도권 3호선 열차구매창오류 표기

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#458]
**한국 열차 세트 버전(Version of Korean Train Set):**
2.6.2

**버그 내용 설명(Describe the bug):**
![텔크 운송의 게임 (2339-11-27)](https://github.com/KoreanGRF/KoreanTrainSet/assets/81477455/016b3d91-78c3-4e02-8c3a-6c42e2b73d6c)
이미지하고 다르게 열차구매시 VVVF 1차 도색으로 나옵니다.

**올바른 상황 설명(Describe the expected situation):**
![텔크 운송의 게임 (2339-11-27)2](https://github.com/KoreanGRF/KoreanTrainSet/assets/81477455/1226be45-d5a1-47e5-96aa-3e148e184975)
일단은 도색개조로 이런식으로 처리했습니다.
일단은 지하철들은 확인해볼필요가 있긴한데 일단 3호선만 다르게 나오네요

**Comment by telk5093** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/blob/dd81a212d29d1252a17b1acbd8613fcb2bf1cd7f/src/metro/seoul_metro_3/seoul_metro_3_graphic.pnml#L146

This is not intended but they COULD be different.
If I change the default graphic then consistness could be broken
