### ISSUE TITLE
[New] 사운드 추가 관련 (2)

### ISSUE THREAD

**Issue by JukjeonWani** [KoreanGRF/KoreanTrainSet#459]
열차가 역에서 출발하거나 차량기지에서 나올 때 재생되는 소리
**사운드는 모두 8bit mono wav 파일입니다.**
- 확장자가 wav가 아닌 경우 게임에서 파일을 불러오지 못함
- wav 확장자여도 8bit mono 파일이 아닌 경우 콜백은 성공하나 사운드 재생이 되지 않음

자세한 사항은 아래 참고
- DTS 코딩 작업자가 작업 도중 개조를 통해 사운드를 바꾸는 방법을 찾았습니다.
- 즉, **현재 제작되어 있는 사운드는 한국 열차 세트의 차량에도 적용이 가능하다는 뜻입니다.**
- 도색이 여러개인 차량은 개조 항목에서 도색을 바꾸게 되면 해당 차량에 맞는 사운드가 재생되게끔 할 수 있습니다.
  - https://youtu.be/30wKc5dg_Xc
- 게임 상 한계로 여러 차종을 섞게 되면 재생되는 사운드는 맨 앞 운전차량의 사운드가 됨을 인지하고 계십시오.
- VVVF 인버터 교체로 한 차종에 여러 사운드 파일이 해당할 경우 도입 당시를 기준으로 적용할 생각입니다.
  - 단, 해당 구동음에 맞는 도색이 추가된다면 모두 반영 가능합니다. (예: 수도권 1호선 전동차의 한국철도공사 1세대 VVVF 전동차 도색을 도시바 GTO와 도시바 IGBT로 구분) 

**현재 사운드 제공 불가능 열차 (사운드 작업 되어있지 않음)**
- 8000호대 전기기관차
- 2000호대~5000호대 디젤기관차
- 4400호대 디젤기관차
- DC디젤동차(니가타 디젤동차)
- DHC 동차(PP동차)
- 대구 1호선 전동차
- 부산 1호선 전동차(초퍼제어 차량만)
- 부산 4호선 전동차
- 인천 1호선 전동차(1세대 차량만)
- 인천 2호선 전동차
- 일부 경전철 차량
- 그 외 일부

![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/88026704/1478628a-80a2-4c58-840f-b9f862884c78)
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/88026704/4e9b81b4-ebc0-4cbf-abba-db66c889f857)

**증기기관차는 기본 사운드 그대로 유지할 생각입니다.**

**Comment by telk5093** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/issues/453#issuecomment-1755442270
