### ISSUE TITLE
[차량 통합] KTX-산천 & SRT 통합

### ISSUE THREAD

**Issue by CoconutKR** [KoreanGRF/KoreanTrainSet#460]
`KTX-산천`과 `SRT` 차량은 실질적으로 동일 차량이며 실제 제작사인 현대로템에서도https://www.hyundai-rotem.co.kr/ko/business/rail/details.do?productNm=%EA%B3%A0%EC%86%8D%EC%A0%84%EC%B2%A0
 SRT 차량은 KTX-산천의 일부로 취급하고 있습니다. 영업최고속도와 설계최고속도 또한 305km/h, 320km/h 동일하고 출력 또한 8,800kW으로 두 차량의 기술적, 외형적 차이가 없다고 생각합니다. 

또한 실제 SRT의 차량 일부는 KTX 호남고속선 전용 차량으로도 운행된 바가 있어 `KTX-산천` 단일 차량으로 통합하고 현 `SRT` 차량을 산천의 도색으로 추가하는것이 바람직하다고 생각합니다.

**Comment by telk5093** [comment]
하위호환성을 이유로 차량을 통합하는 것은 곤란하며, 차라리 차량을 그룹으로 묶는 게 낫습니다.

**Comment by CoconutKR** [comment]
`KTX-산천`과 `SRT` 차량을 그룹화 하여 구매창에서 

  KTX-산천
>  KTX-산천
SRT

위와 같은 방식으로 통합하는 방식을 건의드립니다.
