### ISSUE TITLE
2호선 VVVF 3차분 스프라이트

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#47]
![2K_VVVF_3RD](https://user-images.githubusercontent.com/24273113/111904440-6801cb00-8a8a-11eb-9a16-11e31440380f.png)
원본

![2K_VVVF_3RD_modify1](https://user-images.githubusercontent.com/24273113/111904430-5ddfcc80-8a8a-11eb-9fe5-74af6b6e01b9.png)
수정본 1

![2K_VVVF_3RD_modify2](https://user-images.githubusercontent.com/24273113/111904432-5f10f980-8a8a-11eb-830a-4242b6a1250d.png)
수정본 2

원본 스프라이트의 초록색이 다른 2호선 스프라이트의 초록색에 비해 너무 밝습니다.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/111909037-f97b3800-8a9e-11eb-82b1-9cafe3fd0b39.png)

보시다시피 바탕이 흰색이라 밝게 보이는 게 좋다고 판단했고, 그렇기 때문에 의도적으로 밝은 초록색을 사용했던 그래픽 스프라이트입니다. 그래도 변경하는 게 좋겠다고 생각하시는지요?

**Comment by kiwitreekor** [comment]
다원시스 차가 다른 차들에 비해서 밝아 보이는 느낌은 맞는데, 지금 상태로는 다른 도색과 섞여 다닐 때 어울리지 않는 느낌이 들기도 합니다.

**Comment by telk5093** [comment]
수정본 2는 회사 색상이 들어있으니 수정본 1로 반영하겠습니다.
![image](https://user-images.githubusercontent.com/10726524/111910525-13b81480-8aa5-11eb-94e7-353a76ffd483.png)

**Comment by kiwitreekor** [comment]
> 수정본 2는 회사 색상이 들어있으니 수정본 1로 반영하겠습니다.
> ![image](https://user-images.githubusercontent.com/10726524/111910525-13b81480-8aa5-11eb-94e7-353a76ffd483.png)

저 2CC는 별도의 플래그를 설정해 줘야 활성화되므로 특이 케이스가 아닌 이상 일반적으로 사용해도 무방합니다.
misc_flags의 TRAIN_FLAG_2CC를 지우면 됩니다.

**Comment by telk5093** [comment]
해당 부분을 4d3e21edf116d23b265611330587fe02ec98c72c 에 반영했습니다.
