### ISSUE TITLE
[Bug] DEC 우등형 디젤 전기 도색개조 위치 오류

### ISSUE THREAD

**Issue by opentrain** [KoreanGRF/KoreanTrainSet#475]
**한국 열차 세트 버전(Version of Korean Train Set):**
 2.7.1

**버그 내용 설명(Describe the bug):**
DEC 우등형 디젤 전기동차 도색 확인하는데 무궁화호 1994~1999 도색은 멀쩡합니다.
반면 무궁화호 도색이 새마을호로 적용되어있구요 반대로는 새마을호 도색이 무궁화호로 바꿔져있습니다.
1986 1994 무궁화호 도색이 새마을호 도색으로 적용되어있음
1980 1986 새마을호 도색이 무궁화호 도색으로 적용되어있음

버그 내용을 자세히 설명해주세요. 스크린 샷이 있으면 첨부해주세요.
<img width="1280" alt="DEC 도색오류" src="https://github.com/KoreanGRF/KoreanTrainSet/assets/81477455/ddbfefc2-bfb8-4f88-9de4-6daec40e560f">

**올바른 상황 설명(Describe the expected situation):**
버그가 이렇게 수정되어야 한다는 점을 설명해주세요.
1980 1986 새마을호 도색 및 1986 1994 무궁화호 도색이 위치가 바뀐점을 고쳐야될지 않을까싶습니다.

**Comment by telk5093** [comment]
Fixed by 452f7cf11df1f793181876709a3e31b3d7e5a0bd
