### ISSUE TITLE
[New] 경춘선 2024년 2차 도입분 도색

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#476]
**그래픽 스프라이트(Graphic sprite):**
(TODO)

* Ref: https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=510434&page=1

**Comment by EightonEight** [comment]
![361K_2024](https://github.com/user-attachments/assets/08242386-5377-4489-a6ef-14e3fa0d0fbe)
`361K_2024`

![361K_2024_32bpp](https://github.com/user-attachments/assets/4035ab6e-8bae-44e8-9d4a-44c319121d4f)
`361K_2024_32bpp`
* 실제 도색(노선색)에 가까운 버전
