### ISSUE TITLE
[New] 경의중앙선 2024년 도입분 도색

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#477]
#### 그래픽 스프라이트(Graphic sprite):
![331K_2024](https://github.com/user-attachments/assets/db6a60b4-6712-4947-b1b0-1fca04ae6b3f)
`331K_2024`

`361K_2024`에서 한 단계 밝은 도색
스프라이트 관리 편의성을 고려하여 `361K_2024`를 그대로 사용 가능

#### References:
* <https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=507603>
* <https://gall.dcinside.com/mgallery/board/view/?id=monorail&no=516800>

**Comment by telk5093** [comment]
Implemented by a628f05d58a112513b01b09da900d2725aeff8b6
