### ISSUE TITLE
[Bug] 비둘기호 객차 녹/황 도색 그래픽 오류

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#479]
**한국 열차 세트 버전(Version of Korean Train Set):**
2.8.0

**버그 내용 설명(Describe the bug):**
디젤 액압 동차와 비둘기호 객차의 그래픽이 일치하지 않음 (상단 노란 선)
![image](https://github.com/user-attachments/assets/6ea4c86a-5544-493c-a322-da95cebdfc5e)

**올바른 상황 설명(Describe the expected situation):**
노란색 선이 이어져야 함

**Comment by SerpensNebula** [comment]
![Uploading BIDULGI_CDC.png…]()

**Comment by SerpensNebula** [comment]
![BIDULGI_CDC](https://github.com/user-attachments/assets/1b3fe8b3-5985-4f4b-ae95-66e51b31f2a8)
