### ISSUE TITLE
화물차 화물별 그래픽 추가

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#48]
https://cafe.naver.com/ottd/15106

**Comment by telk5093** [comment]
Thanks for reminding me.

![wagons](https://user-images.githubusercontent.com/10726524/111913556-0ce3ce80-8ab2-11eb-99b8-64da2ab04e0e.png)
This is for backup.

**Comment by telk5093** [comment]
@kiwitreekor VEBO 화물은 혹시 어떤 화물이죠? https://newgrf-specs.tt-wiki.net/wiki/CargoTypes#Cargo_Labels 에 없는 화물이네요

**Comment by kiwitreekor** [comment]
https://bundles.openttdcoop.org/firs/releases/LATEST/docs/html/code_reference.html
거의 대부분이 여기 있는 화물입니다.

**Comment by telk5093** [comment]
@kiwitreekor ``VEBO``가 아니라 ``VBOD``였네요. ~~당신이 잘못했어요(?)~~

**Comment by kiwitreekor** [comment]
그러네요. ㅋㅋ

**Comment by telk5093** [comment]
Implemented by 6a55637583b2b9730c4cb2081776d66f59436a5c, b2210d05b8b285fca14d45efee782b6d454520a2 and 40a3f9bec89d2a53e7ab5edefa8e52961140fdc4
