### ISSUE TITLE
[Add] 무개 컨테이너 화차

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#50]
![image](https://user-images.githubusercontent.com/10726524/111971119-5f1f0100-8b3f-11eb-9919-3c763dd9cc21.png)

Reference: https://www.google.com/url?sa=i&url=http%3A%2F%2Fm.blog.naver.com%2Flovtrout%2F90127814855&psig=AOvVaw3_dz8bDBNiT8iDnJCQjrFC&ust=1616492844637000&source=images&cd=vfe&ved=0CA0QjhxqFwoTCOCAvKHPw-8CFQAAAAAdAAAAABAN

**Comment by kiwitreekor** [comment]
![image](https://user-images.githubusercontent.com/24273113/112721051-3171f780-8f45-11eb-91f9-a870749f9c45.png)

시안

**Comment by kiwitreekor** [comment]
이 다음은 색깔별 노가다라 계속 진행할지 말지 말씀을 해주시면 좋을 것 같네요.

**Comment by telk5093** [comment]
있는 게 좋을 것 같습니다. 계속 작업해주시면 감사하겠습니다.

**Comment by telk5093** [comment]
https://github.com/KoreanGRF/KoreanTrainSet/issues/157#issuecomment-817293024 에 무개 컨테이너 화차 그래픽 있음

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.
