### ISSUE TITLE
[Add] Seoul Line 3: 3rd gen.

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#51]
https://www.youtube.com/watch?v=2YTURhzOMcI

**Comment by kimgas** [comment]
![seoul3_3rd](https://user-images.githubusercontent.com/79271602/112293116-1e58f080-8cd5-11eb-9817-b2662e86b0a7.png)

서울 3호선 3차분

+

![seoul5_4th](https://user-images.githubusercontent.com/79271602/112293580-a3dca080-8cd5-11eb-84cc-c9cda6151549.png)

서울 5호선 4차분

띠 방향에 주의

https://youtu.be/VlcLlCohbio

**Comment by telk5093** [comment]
반영되었습니다.
