### ISSUE TITLE
FIRS 철강도시용 화물 추가

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#53]
https://grf.farm/firs/4.0.0-beta-8/html/code_reference.html

STAL, ALUM, STCB, CSTI, IRON, STST, STSH, STWR, ZINC를 STEL과 공용, STSE는 PIPE와 공용하면 될 듯 합니다.

**Comment by telk5093** [comment]
Close by ef023a3
