### ISSUE TITLE
Livery for Tongil-ho wagon

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#54]
각종 통일호 객차의 도색이 필요

![image](https://user-images.githubusercontent.com/10726524/112427486-05a41580-8d7d-11eb-910e-44b2fcc42ad3.png)

이 도색은 현재 없음
<br><br>

![TILCW](https://user-images.githubusercontent.com/10726524/112623280-7fb4c700-8e6f-11eb-88ae-31bbd6636366.png)
* 아랫줄 차량이 뭔지 확인이 필요
  * 레퍼런스 필요
  * Author: 오픈기차

**Comment by opentrain** [comment]
제가 아는선에서 통일호 도색 찾았습니다.
일단 찍는데로 올리겠습니다.~~
