### ISSUE TITLE
Add Bubble graphic for Stake car

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#55]
![image](https://user-images.githubusercontent.com/10726524/112124776-13835a80-8c06-11eb-8ba5-e159c7ad4db2.png)
Blank car for Stake car

**Comment by troy7737** [comment]
![Uploading 112124776-13835a80-8c06-11eb-8ba5-e159c7ad4db2.png…]()

**Comment by telk5093** [comment]
Implemented by 0ccfc496a64f2e9d2ae48bd3e20184de79c41622
