### ISSUE TITLE
Add default cargo graphics for Hopper/Stake car

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#56]
If there is no specified graphics for a certain cargo, it shows emtpy wagon graphic currently.
So we need default cargo graphic, such as a boxes, for hopper & stake car.
* * * * *
특정 화물을 지정하지 않으면 현재는 빈 차 그래픽으로 나옴.
그러므로 상자같은 기본 화물이 적재되는 그래픽을 추가해야할 필요가 있음

**Comment by EightonEight** [comment]
실제 사례를 *참고*하여 무개화차의 기본 화물 적재 스프라이트를 제작하였습니다. 

### 1안
![cargo_GENERAL1](https://user-images.githubusercontent.com/77984422/125168489-c640ee00-e1e0-11eb-85a9-e0b9bb413ca9.png)
나무 상자(~50%)와 물건(~100%)이 적재된 그래픽

Reference: 
* <https://cafe.naver.com/korailslr/59064>
![image](https://user-images.githubusercontent.com/77984422/125168572-1f108680-e1e1-11eb-8699-81493ef8516c.png)

### 2안
![cargo_GENERAL2](https://user-images.githubusercontent.com/77984422/125168667-8c241c00-e1e1-11eb-87e9-51231b0425ad.png)
방수포가 씌워진 그래픽

References: 
* <https://youtu.be/gvaCwJ70KGw?t=25>
![캡처](https://user-images.githubusercontent.com/77984422/125168922-d3f77300-e1e2-11eb-82c6-e3ceaf72c527.PNG)

* <https://youtu.be/zE4DqEwU6Mk?t=25>
![캡처2](https://user-images.githubusercontent.com/77984422/125169003-33ee1980-e1e3-11eb-9aea-23fe7610ba7f.PNG)

**Comment by EightonEight** [comment]
평판화차(장물차)의 경우 [#157 (comment)](https://github.com/KoreanGRF/KoreanTrainSet/issues/157#issuecomment-817293024)에서 덮개 있는 냉연코일화차 그래픽을 적용하면 괜찮을 것 같습니다.

**Comment by telk5093** [comment]
1안과 2안 모두 괜찮네요. 굳이 고르자면 개인적으로는 2안이 마음에 듭니다.

**Comment by telk5093** [comment]
It is staled and not be implemented at currently.
