### ISSUE TITLE
FIRS용 누락된 화물 추가

### ISSUE THREAD

**Issue by kiwitreekor** [KoreanGRF/KoreanTrainSet#61]
FIRS 3
Packaging
Metal
Peat

FIRS 4
Coke

**Comment by telk5093** [comment]
* [FIRS 3](https://grf.farm/firs/3.0.12/html/code_reference.html)
   * Packaging: ``MNSP``
   * Metal: ``METL``

 * Peat(``PEAT``)와 Coke(``COKE``)는 무개화차(``HOPPER_CAR``)에 있는 것을 확인
https://github.com/KoreanGRF/KoreanTrainSet/blob/18e5a66c47bfa808a81f9df8d85a112aa30a727f/src/wagon/hopper_car/hopper_car.pnml#L68
https://github.com/KoreanGRF/KoreanTrainSet/blob/18e5a66c47bfa808a81f9df8d85a112aa30a727f/src/wagon/hopper_car/hopper_car.pnml#L71

**Comment by kiwitreekor** [comment]
실제로 적용해보면 안 뜨던데 원인이 뭘까요..?

**Comment by kiwitreekor** [comment]
개조 목록에서도 안뜨네요..

**Comment by telk5093** [comment]
그래픽만 있고 ``cargo_allow_refit``에 등록을 안 해놓았네요. 확인 감사합니다.
