### ISSUE TITLE
탄수차 스프라이트 조정

### ISSUE THREAD

**Issue by troy7737** [KoreanGRF/KoreanTrainSet#62]
![1](https://user-images.githubusercontent.com/75788864/112181826-19962d00-8c40-11eb-8146-ddcf51456ab2.png)
탄수차 스프라이트가 3번, 7번 방향에서 약간 어긋났습니다.

**Comment by troy7737** [comment]
탄수차 조정 하려면 아마도 높은 확률로 기관차까지 조정해야 할 것 같은데, 아무래도 스프라이트 자체를 약간 수정해야 할까요?

**Comment by telk5093** [comment]
어긋난 이유는 1604b7054c9a7fcc04a6afde880d4bc56e6dbfe3 에서 전체 일반 기관차의 좌우 위치(3, 7번 방향)를 조절해서 그렇습니다. 그래픽 스프라이트를 수정할 필요는 아직은 없어보입니다.

**Comment by troy7737** [comment]
알겠습니다.
