### ISSUE TITLE
의정부 경전철 스프라이트 수정

### ISSUE THREAD

**Issue by troy7737** [KoreanGRF/KoreanTrainSet#63]
![의정부 경전철 1차 완성](https://user-images.githubusercontent.com/75788864/112187370-63354680-8c45-11eb-9ecf-faaa67d9224f.png)

고생이 많으십니다. 

시험삼아 돌려보니 미처 끝까지 완성하지 못한 부분이 있어서 수정해서 올립니다(+다시 보니 조금 미묘한 부분도 수정 ex)자동문 색). 스프라이트 규격?은 변하지 않았으니 그대로 바꿔치기 하시면 됩니다.

**Comment by telk5093** [comment]
감사합니다. 38d3a71 로 반영했습니다.
