### ISSUE TITLE
일부 객차 상세 수치 잘못 적용됨

### ISSUE THREAD

**Issue by troy7737** [KoreanGRF/KoreanTrainSet#68]
![006](https://user-images.githubusercontent.com/75788864/112260321-0bcac100-8cad-11eb-8932-b6d54f930613.png)

설명:객차간 밸런스가 맞지 않거나 잘못 적용된 부분이 있습니다.

무궁화호 객차:가격, 유지비, 중량 정상(기준)
비둘기호 객차:유지비와 중량이 유독 높음(가격이 살짝 낮은 건 의도하신 걸 수도)
새마을포 객차 가격이 유독 낮음

**Comment by telk5093** [comment]
가격이 매개변수와 연동되지 않아서 생긴 문제였습니다.
동력차의 유지비는 별도 이슈로 작성해두겠습니다.

**Comment by troy7737** [comment]
감사합니다~
