### ISSUE TITLE
승객 수송 차량(공통 객차) 유지비 적용 안 됨

### ISSUE THREAD

**Issue by troy7737** [KoreanGRF/KoreanTrainSet#69]
![001](https://user-images.githubusercontent.com/75788864/112260753-e25e6500-8cad-11eb-9228-b383d8e26ad3.jpg)
![003](https://user-images.githubusercontent.com/75788864/112260760-e4c0bf00-8cad-11eb-9291-67cddf825fc2.jpg)

동력차, 무동력차 모두 유지비만 추가가 되지 않습니다. 공통 객차가 적용되는 모든 기차(지하철, 김포 골드라인, KTX 등등..)가 해당됩니다.

**Comment by troy7737** [comment]
그리고 이건 제 의견인데 동력차는 유지비를 무동력차보다 약간 더 높게 해야하지 않을까 싶습니다.

**Comment by telk5093** [comment]
가격이 매개변수와 연동되지 않아서 생긴 문제였습니다.
동력차의 유지비는 별도 이슈로 작성해두겠습니다.
