### ISSUE TITLE
1호선 신조 저항 명칭 오류

### ISSUE THREAD

**Issue by NuclearBread** [KoreanGRF/KoreanTrainSet#72]
수도권 1호선 차량의 명칭 중, 코레일/철도청 개조저항 은 저항제어 중기형 이라 칭하는게 맞으며,

코레일/철도청 신조저항은 3VF 초기형 이라 칭하는게 맞습니다

GRF상의 개조저항 차량의 그래픽은 저항제어 중기형 차량과 일치하는 것으로 보이며,
(전두부 형상이 중기형의 그것과 유사함)

GRF상의 신조저항 차량의 그래픽은 납작이라 칭하는 3VF 초기형과 일치하는 것으로 보입니다
(차량 상단의 슈트락 개수가 신조저항은 3개, 납작이는 2개 입니다)

**Comment by telk5093** [comment]
여러 가지 제보 감사합니다.
문제를 확인하고 각 문제별로 분리해서 새로운 이슈로 등록해두겠습니다.

**Comment by telk5093** [comment]
1호선 개조 저항은 127651b 에서 ``(철도청 1k 중기 저항 / 초기 도색)``, ``(철도청 1k 중기 저항 / 구 도색)``, ``(Korail 1k 중기 저항 / 현 도색)``으로 이름이 이미 변경되었습니다. 2.0.0-beta2에 반영될 것입니다.

**Comment by telk5093** [comment]
*한국철도공사 1000호대 전동차*의 초기 모델의 경우, [나무위키](https://namu.wiki/w/%ED%95%9C%EA%B5%AD%EC%B2%A0%EB%8F%84%EA%B3%B5%EC%82%AC%201000%ED%98%B8%EB%8C%80%20%EC%A0%84%EB%8F%99%EC%B0%A8/%EC%B0%A8%ED%98%B8%EB%B3%84%20%EC%83%81%EC%84%B8%EC%84%A4%EB%AA%85#s-2.3)는 초기, 중기, 후기로 분류하고 있고, [위키백과](https://ko.wikipedia.org/wiki/%ED%95%9C%EA%B5%AD%EC%B2%A0%EB%8F%84%EA%B3%B5%EC%82%AC_1000%ED%98%B8%EB%8C%80_%EC%A0%84%EB%8F%99%EC%B0%A8#%EA%B5%AC%EB%B6%84) 또한 1, 2, 3세대 분류법을 따르고 있습니다.
따라서 한국 철도 세트는 이를 참고로 '초기 저항', '중기 저항', '신조 저항'의 분류를 따르고 있습니다.
따라서 ``신조 저항``을 ``VVVF 초기형``으로 변경하는 안이 적절할 것 같지 않습니다.

혹 제가 오해하고 있는 부분이 있다면 다시 알려주세요.

**Comment by NuclearBread** [comment]
> _한국철도공사 1000호대 전동차_의 초기 모델의 경우, [나무위키](https://namu.wiki/w/%ED%95%9C%EA%B5%AD%EC%B2%A0%EB%8F%84%EA%B3%B5%EC%82%AC%201000%ED%98%B8%EB%8C%80%20%EC%A0%84%EB%8F%99%EC%B0%A8/%EC%B0%A8%ED%98%B8%EB%B3%84%20%EC%83%81%EC%84%B8%EC%84%A4%EB%AA%85#s-2.3)는 초기, 중기, 후기로 분류하고 있고, [위키백과](https://ko.wikipedia.org/wiki/%ED%95%9C%EA%B5%AD%EC%B2%A0%EB%8F%84%EA%B3%B5%EC%82%AC_1000%ED%98%B8%EB%8C%80_%EC%A0%84%EB%8F%99%EC%B0%A8#%EA%B5%AC%EB%B6%84) 또한 1, 2, 3세대 분류법을 따르고 있습니다.
> 따라서 한국 철도 세트는 이를 참고로 '초기 저항', '중기 저항', '신조 저항'의 분류를 따르고 있습니다.
> 따라서 `신조 저항`을 `VVVF 초기형`으로 변경하는 안이 적절할 것 같지 않습니다.
> 
> 혹 제가 오해하고 있는 부분이 있다면 다시 알려주세요.

신조저항(이하 신저항)과 VVVF 초기형(이하 납작이)이 외형적으로 아주 유사하게 생겼습니다만
신저항의 경우 기본 바탕색이 흰색이며, 차량 상부 냉방기가 3개가 달려 있습니다
납작이의 경우 스테인리스 색이며, 차량 상부 냉방기가 2개입니다

인게임에서 신저항이라는 차량의 그래픽이 냉방기가 2개여서 어 이건 납작이 아닌가 하고 제보드린겁니다

**Comment by telk5093** [comment]
@NuclearBread 확인 결과 https://telk.kr/tb/free/101 에 같은 의견이 있었습니다. 말씀하신 게 맞는 것 같습니다.
명칭은 ``개조 저항``을 ``Korail 1k 저항 중후기형``으로, ``신조 저항``을 ``311k 초기형``으로 변경하도록 하겠습니다.
