### ISSUE TITLE
7x00에 무궁화 객차 조합시 그래픽 문제

### ISSUE THREAD

**Issue by kimgas** [KoreanGRF/KoreanTrainSet#77]
7x00 기관차와 무궁화 객차 조합에서 뭔가 잘못된 것 같습니다

![2](https://user-images.githubusercontent.com/79271602/112303656-e4d9b280-8cdf-11eb-8e18-a0788dd84a89.jpg)

**Comment by telk5093** [comment]
수정되었습니다. 감사합니다.
