### ISSUE TITLE
Improve DEC, EEC livery names

### ISSUE THREAD

**Issue by EightonEight** [KoreanGRF/KoreanTrainSet#78]
![screenshot (2022-12-24)](https://user-images.githubusercontent.com/77984422/112307633-87943000-8ce4-11eb-8240-85489fb4af24.png)

DEC, EEC(#15) 도색 이름을 무궁화호 객차와 비슷하게 '(yyyy~yyyy년 도색)'으로 개선

reference: <https://ko.wikipedia.org/wiki/%EC%9A%B0%EB%93%B1%ED%98%95_%EB%94%94%EC%A0%A4_%EB%8F%99%EC%B0%A8>
<https://ko.wikipedia.org/wiki/%EC%9A%B0%EB%93%B1%ED%98%95_%EC%A0%84%EA%B8%B0_%EB%8F%99%EC%B0%A8>
<https://gall.dcinside.com/mgallery/board/view?id=monorail&no=3742>

**Comment by telk5093** [comment]
반영되었습니다.
