### ISSUE TITLE
명칭을 '한국 철도 세트'로 복귀

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#79]
열차 차량이 주이긴 하지만 선로(경전철 선로)나 오브젝트(차막이)도 같이 추가하므로 '열차 세트'보다는 '철도 세트'가 적합.
차량이 주이긴 하지만 선로(경전철 선로)나 오브젝트(차막이)도 같이 추가하므로 '열차 세트'보다는 '철도 세트'가 적합하지 않을까 함
(eg. Korail의 이전 이름은 *한국열차공사*가 아니라 *한국철도공사*)

**Comment by EightonEight** [comment]
그럼 영문명과 레포지토리 이름도 Korean Railroad Set로 변경되는 건가요? 

추후에는 
- 한국 일반열차 세트 Korean Train Set 
- 한국 지하철/경전철 세트 Korean Metro & LRT Set 
- 한국 선로 세트 Korean Track Set 
이런 식으로 분리하는 것도 괜찮을것 같습니다.

**Comment by telk5093** [comment]
비슷하게 열차와 선로를 추가해주는 일본 철도 세트도 Japanese Train Set 이라서 영문명에는 변화가 없을 것 같습니다.
GRF 분리는 지금은 먼 얘기입니다.

**Comment by telk5093** [comment]
일단 현재 이름으로 그대로 가는 것으로...
