### ISSUE TITLE
중량 제원 고증

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#80]
일반 열차는 대부분 중량 제원이 고증에 맞춰져 있으나 그 외의 열차(eg. 지하철, 경전철)는 무게가 일괄적으로 20t으로 되어 있으므로 실제 한 량당 제원을 확인해서 고증해야할 필요가 있음. (단, 게임적 허용을 적용하게 될 수도 있음)

일반 열차 역시 고증을 맞춘다고 맞추긴 했으나 검증은 필요함

**Comment by EightonEight** [comment]
![1일반](https://user-images.githubusercontent.com/77984422/124453989-e7f63b80-ddc2-11eb-8b3d-7d43bbe9a037.png)
![2광역, 도시](https://user-images.githubusercontent.com/77984422/124454001-eb89c280-ddc2-11eb-9e99-7f107732c127.PNG)
![3도시](https://user-images.githubusercontent.com/77984422/124454013-edec1c80-ddc2-11eb-93ad-d937a99a5b9c.png)
![4도시](https://user-images.githubusercontent.com/77984422/124454019-efb5e000-ddc2-11eb-8859-8caafed11689.PNG)
![5도시](https://user-images.githubusercontent.com/77984422/124454022-f17fa380-ddc2-11eb-8407-bb4ec17e94b4.png)

[2019 철도통계연보](http://www.kric.go.kr/jsp/handbook/sta/statisticsTechList.jsp)에 나온 열차 제원이 도움이 될 것 같습니다.

**Comment by telk5093** [comment]
수도권 전철의 경우 아래와 같이 평균을 계산하여 반영합니다.
(1) 각 차량 종류별 평균을 계산하여
(2) 해당 노선에 해당하는 차량 종류 평균의 평균을 계산
![image](https://github.com/KoreanGRF/KoreanTrainSet/assets/10726524/b52015de-cd1a-4db7-8edf-a3acffc4f58a)


* 1호선: 평균 = 37.125 t / 37 t 으로 설정
* 2호선: 평균 = 34.403.. t / 35 t 으로 설정
* 3호선: 평균 = 35.2675 t / 35 t 으로 설정
* 4호선: 평균 = 34.2 t / 34 t 으로 설정
* 5~9호선: 평균 = 33.2 t / 33 t 으로 설정
* 부산 1호선: 평균 = 31.233.. t / 31 t 으로 설정
* 부산 2호선: 평균 = 29.475 t / 29 t 으로 설정
* 부산 3호선: 평균 = 32.1 t / 32 t 으로 설정
* 부산 4호선: 평균 = 11.96... t / 12 t 으로 설정 (이미 12 t 으로 설정되어 있음)
* 대구 1호선: 평균 = 32.525 t / 33 t 으로 설정
* 대구 2호선: 평균 = 30.625 t / 31 t 으로 설정
* 인천 1호선: 평균 = 30.16 t / 30 t 으로 설정
* 인천 2호선: 31.5 t / 현재 32 t 으로 설정되어 있는 것을 유지
* 대전 1호선: 평균 = 29.9 t / 30 t 으로 설정
* 광주 1호선: 평균 = 29.55 t / 30 t 으로 설정

* ``METRO_wagon``: 위 전반적인 무게가 30 t 언저리임을 감안하여 30 t 으로 설정 (부산 4호선만 12 t 유지)

**Comment by telk5093** [comment]
반영 완료되었으며 추가 중량 제원 고증 문제는 별도 이슈로 등록 바랍니다.
