### ISSUE TITLE
수도권 4호선 1·2차 도입분 도색이 3호선 도색을 대신 이용하고 있음

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#83]
``SMETRO_4K_VVVF_1ST_2ND``가 현재는 ``3K_VVVF_1ST_1``를 대신 사용하고 있으나, 실제로는 살짝 다름.
(eg. 빨간 띠와 파란 띠의 위아래 위치가 다름)

* 현재 대신 사용 중인 3호선의 ``3K_VVVF_1ST_1`` 도색:
 ![3K_VVVF_1ST_1](https://user-images.githubusercontent.com/10726524/112513039-4a5c9a80-8dd7-11eb-9b77-0bd7279a5840.png)
 ![image](https://user-images.githubusercontent.com/10726524/112512648-e9cd5d80-8dd6-11eb-9f87-9f3487ba6055.png)

* 4호선 1·2차 도입분의 실제 도색:
![image](https://user-images.githubusercontent.com/10726524/112512755-ffdb1e00-8dd6-11eb-9dd7-07bd806f9485.png)

**Comment by EightonEight** [comment]
``SMETRO_4K_VVVF_1ST_2ND``

![SMETRO_4K_VVVF_1ST_2ND](https://user-images.githubusercontent.com/77984422/117804258-89b14e80-b292-11eb-9a86-71efb7ca83b0.png)

※  ``3K_VVVF_1ST_1`` 스프라이트를 참고하여 ``SMETRO_1K_VVVF``를 수정하였습니다.
