### ISSUE TITLE
무개화차 개조하는데, 화물 수송량"없음" 뜹니다.

### ISSUE THREAD

**Issue by jsg49** [KoreanGRF/KoreanTrainSet#84]
도색만 바뀌고 "수송량:없음" 으로 화물을 싣지 못합니다.
![image](https://user-images.githubusercontent.com/57122504/112558413-0f2b8d00-8e12-11eb-89e4-c2c022baa65a.png)

**Comment by telk5093** [comment]
2.0.0-beta3 에서 확인되지 않습니다. 매개변수에서 '화물 수송량'이 제대로 되어있는지 확인해주시겠어요?

**Comment by jsg49** [comment]
![image](https://user-images.githubusercontent.com/57122504/112576755-41e77c80-8e36-11eb-9b7b-0ba86d0bfdbc.png)
화물수송량이 0으로 되어있는데, 화물수송량 매개변수를 변경한 적이 없습니다.

**Comment by telk5093** [comment]
@jsg49 기존 1.x.x에서는 화물 수송량에 0(=2^0=1배)를 지정할 수 있었고, 2.0.0부터 최솟값이 1로 변경되어 생긴 현상입니다.
기존에 사용하던 한국 열차 세트의 NewGRF 매개변수 설정값 0을 2.0.0이 다시 사용하려고 들면서 생긴 것으로 봅니다.
화물 수송량을 변경하고 열차를 다시 만들면 해결될 것이며, 코드 상으로 해결할 수 있는 문제는 아닌 듯 합니다.

**Comment by telk5093** [comment]
이 문제를 방어할 수 있도록 코드를 개선했습니다.
