### ISSUE TITLE
[Add] Seoul Line 2: 4th gen. (a.k.a. Baptong car)

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#9]
2호선 4차 도입분(일명 밥통 차량)

Reference: http://i11o3.blog.me/221497203054

**Comment by kiwitreekor** [comment]
밥통차 스프라이트는 준비되어 있는 상태인가요?

**Comment by telk5093** [comment]
@kiwitreekor 아직 없습니다. graphic 라벨이 붙어있으면 그래픽 스프라이트가 없어서 그래픽 작업이 필요하다는 뜻입니다.

**Comment by kiwitreekor** [comment]
![2K_VVVF_4TH](https://user-images.githubusercontent.com/24273113/111904485-9384b580-8a8a-11eb-8f85-599aa3a50c5a.png)

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/111910863-6a721e00-8aa6-11eb-9e13-ad0a31ff0b75.png)
회사 색상이 사용되어 있어서 대체 색상을 사용하여 구현했습니다.

![image](https://user-images.githubusercontent.com/10726524/111910857-647c3d00-8aa6-11eb-8b50-3c458ccdd09f.png)

**Comment by kiwitreekor** [comment]
> ![image](https://user-images.githubusercontent.com/10726524/111910863-6a721e00-8aa6-11eb-9e13-ad0a31ff0b75.png)
> 회사 색상이 사용되어 있어서 대체 색상을 사용하여 구현했습니다.
> 
> ![image](https://user-images.githubusercontent.com/10726524/111910857-647c3d00-8aa6-11eb-8b50-3c458ccdd09f.png)

TRAIN_FLAG_2CC를 끄면 됩니다.

**Comment by telk5093** [comment]
해당 부분을 b3c9227 및 4d3e21edf116d23b265611330587fe02ec98c72c 에 반영했습니다.
