### ISSUE TITLE
[Add] 2000 locomotive

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#90]
* 철도청 녹+황 도색:
  ![image](https://user-images.githubusercontent.com/10726524/112874964-8b69ed00-90fe-11eb-9e62-0fe1a4127a61.png)
  Author: @opentrain (from #122)

* 일명 호랑이 도색:
  ![2000호대 디젤기관차(호랑이도색)](https://user-images.githubusercontent.com/10726524/112620654-2a2aeb00-8e6c-11eb-8b3b-b070ea6d5259.png)

**Comment by opentrain** [comment]
이것도 제가 시간되면 구도색 반영해드리겠습니다.

**Comment by telk5093** [comment]
스펙
 * 차량 중량: 94.5 t
 * 출력: 800 hp
 * 영업 최고 속도: 105 km/h

**Comment by opentrain** [comment]
![2000호대 검정도색](https://user-images.githubusercontent.com/81477455/116853399-f1332280-ac30-11eb-9d41-4f0cd2c9b8c9.png)

검정도색
https://www.google.co.kr/search?q=2000%ED%98%B8%EB%8C%80+%EB%94%94%EC%A0%A4%EA%B8%B0%EA%B4%80%EC%B0%A8&tbm=isch&ved=2ahUKEwirgbHKha3wAhUK5JQKHahvBwYQ2-cCegQIABAA&oq=2000%ED%98%B8%EB%8C%80+%EB%94%94%EC%A0%A4%EA%B8%B0%EA%B4%80%EC%B0%A8&gs_lcp=CgNpbWcQA1CT1BBY49cQYNrZEGgAcAB4AIABsgKIAcQDkgEHMC4xLjAuMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=gq2PYKu4HYrI0wSo350w#imgrc=KcgXGtLXLIvBjM

![2100호대 호랑이도색](https://user-images.githubusercontent.com/81477455/116853419-f85a3080-ac30-11eb-9f30-2b5c07441ce4.png)

2100호대 호랑이도색 역삼각마크도색추가는 2000호대하고 별차이 없어서 안했습니다.
https://www.google.co.kr/search?q=2100%ED%98%B8%EB%8C%80+%EB%94%94%EC%A0%A4%EA%B8%B0%EA%B4%80%EC%B0%A8&tbm=isch&ved=2ahUKEwiOvInIha3wAhWXAqYKHQUVANMQ2-cCegQIABAA&oq=2100%ED%98%B8%EB%8C%80+%EB%94%94%EC%A0%A4%EA%B8%B0%EA%B4%80%EC%B0%A8&gs_lcp=CgNpbWcQAzoCCABQMFjuFWD7FmgFcAB4AYAB1AGIAe0IkgEFMC44LjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=fa2PYM6JJ5eFmAWFqoCYDQ#imgrc=euRnekThaUMxPM

**Comment by telk5093** [comment]
0383e42 에서 반영되었습니다.
