### ISSUE TITLE
[Add] 레이디버드 관광열차

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#92]
![image](https://user-images.githubusercontent.com/10726524/112621696-6743ad00-8e6d-11eb-9f9e-b4cfe468eaa4.png)

 * 그래픽 개선 작업 필요할 수 있음
 * 레퍼런스 필요
 * 넣을지 말지 의견 필요
 * Author: 오픈기차

**Comment by telk5093** [comment]
From #179 
> #92 레이디버드를 수정해봤습니다.
> 지붕이 빨간색로 안돼어있던 부분수정 디젤기관차도 레이디버드객차하고 같은색상으로 통일
> 
> ![레이디버드](https://user-images.githubusercontent.com/81477455/113692590-a80eb200-9708-11eb-95d7-7483fb280b38.png)
> 
> 수정 요청하시면 다시 수정하겠습니다.
> 
> 레이디버드 운행영상
> https://www.youtube.com/watch?v=I_otwpiI4iI
> 
> 레이디버드 관련이긴한데 현재 e-train이긴한데 e-train도 다시 수정하든가 하겠습니다.
> https://ko.wikipedia.org/wiki/%EA%B5%90%EC%9C%A1%ED%85%8C%EB%A7%88%EC%97%B4%EC%B0%A8#cite_note-2
> 
> 레이디버드 이미지
> https://www.google.co.kr/search?q=%EB%A0%88%EC%9D%B4%EB%94%94%EB%B2%84%EB%93%9C+%EC%97%B4%EC%B0%A8&tbm=isch&ved=2ahUKEwi9o87KnunvAhXHEKYKHWXXDqAQ2-cCegQIABAA&oq=%EB%A0%88%EC%9D%B4%EB%94%94%EB%B2%84%EB%93%9C+%EC%97%B4%EC%B0%A8&gs_lcp=CgNpbWcQAzICCAA6BAgAEBg6BggAEAUQHlCdKFiWMmDeM2gAcAB4AIABjgGIAf4GkgEDMC44mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=6yBsYP2BJ8ehmAXlrruACg&bih=609&biw=1366
> 
> 한국열차세트에 해랑을 있는데 레이디버디가 없어서 수정해서 올렸습니다.

**Comment by opentrain** [comment]
아 참고로 발전차를 제외 시켰습니다.
나중에 발전차크기가 조정되면 따로하겠습니다.
