### ISSUE TITLE
[Add] 정선꼬마열차

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#95]
![image](https://user-images.githubusercontent.com/10726524/112622360-46c82280-8e6e-11eb-9eb7-4fc69067e811.png)

 * 그래픽 개선 작업 필요할 수 있음
 * 레퍼런스 필요
 * 넣을지 말지 의견 필요
 * Author: 오픈기차

**Comment by opentrain** [comment]
![1617757286727](https://user-images.githubusercontent.com/81477455/113795693-6e7d8b80-9788-11eb-8d81-af7974fb4c40.png)
정선꼬마 열차 도색입니다.
