### ISSUE TITLE
Livery for Saemaeul car

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#97]
![image](https://user-images.githubusercontent.com/10726524/112625109-d1f6e780-8e71-11eb-9d25-2fc33233a005.png)

 * Reference: https://ko.wikipedia.org/wiki/%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8#%EC%A7%81%EA%B0%81%ED%98%95_%EA%B0%9D%EC%B0%A8
 * Author: 오픈기차

**Comment by opentrain** [comment]
https://m.search.daum.net/search?w=img&nil_search=btn&DA=NTB&enc=utf8&q=%5B%EB%B0%B0%ED%8F%AC%EC%9E%AC%EA%B0%9C%5D%20%EC%9C%A0%EC%84%A0%ED%98%95%20%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8%20%2B%20%EC%A0%84%EC%9A%A9%EA%B8%B0%EA%B4%80%EC%B0%A8%287000%ED%98%B8%EB%8C%80%20%EB%94%94%EC%A0%A4%EA%B8%B0%EA%B4%80%EC%B0%A8%29#&gid=223&pid=336SGgpYVyWvXgNxx3
직각형 새마을호라고 하네요

**Comment by telk5093** [comment]
> https://m.search.daum.net/search?w=img&nil_search=btn&DA=NTB&enc=utf8&q=%5B%EB%B0%B0%ED%8F%AC%EC%9E%AC%EA%B0%9C%5D%20%EC%9C%A0%EC%84%A0%ED%98%95%20%EC%83%88%EB%A7%88%EC%9D%84%ED%98%B8%20%2B%20%EC%A0%84%EC%9A%A9%EA%B8%B0%EA%B4%80%EC%B0%A8%287000%ED%98%B8%EB%8C%80%20%EB%94%94%EC%A0%A4%EA%B8%B0%EA%B4%80%EC%B0%A8%29#&gid=223&pid=336SGgpYVyWvXgNxx3
> 직각형 새마을호라고 하네요

가상의 이미지는 레퍼런스가 될 수 없습니다.

**Comment by opentrain** [comment]
![1618791920084](https://user-images.githubusercontent.com/81477455/115167131-44658b00-a0f1-11eb-9fc5-5bf8ab2084c6.png)
실물 사진입니다.
