### ISSUE TITLE
[Add] HEMU (Highspeed Electric Multiple Unit)

### ISSUE THREAD

**Issue by telk5093** [KoreanGRF/KoreanTrainSet#98]
![HEMU(해무)](https://user-images.githubusercontent.com/10726524/112625405-34e87e80-8e72-11eb-9da2-ccaf9f106255.png)

 * Reference: https://ko.wikipedia.org/wiki/HEMU-430X
 * 실차는 있으나 여객 영업에 투입되고 있지 않아서 약간의 discussion이 필요
 * Author: 오픈기차

vs

![image](https://user-images.githubusercontent.com/10726524/112634922-87c83300-8e7e-11eb-9dbe-544cd0d38295.png)

* Author: Las (https://cafe.naver.com/ottd/11301)

**Comment by NuclearBread** [comment]
비록 시제차이긴 하나, 한국에서 가장 빠른 철도 차량이라는 상징성이 있는지라 추가하는게 좋다 생각합니다
여담이지만 Las님의 스프라이트가 실차의 느낌이 더 많이 나는 듯 합니다

**Comment by EightonEight** [comment]
만약 해무가 추가된다면 형평성에 맞게 다른 시제차들도 추가하는게 좋을것 같네요. 
사진 첨부시 너무 길어지는것 같아 링크로 대체합니다.

HSR-350X - High Speed Rail - 350km/h eXperiment 
<https://blog.naver.com/hunza7/221092537406>

TTX - Tilting Train Express 
<https://ko.wikipedia.org/wiki/%ED%95%9C%EA%B5%AD%ED%98%95_%ED%8B%B8%ED%8C%85%EC%97%B4%EC%B0%A8>

AUTS - Advanced Urban Transit System 
<https://blog.naver.com/ianhan/220322890750>

**Comment by telk5093** [comment]
@EightonEight 이 이슈 스레드에서 얘기할 것이 아닌 것 같습니다.

**Comment by EightonEight** [comment]
![image](https://user-images.githubusercontent.com/77984422/118011670-4a1a5d80-b38b-11eb-8b38-c53410555d00.png)
Las 님의 스프라이트를 고증에 맞게 수정하고 2층객차를 추가하였습니다.

**Vehicle specification**
| Name                             | Code                | Speed             | Speed (designed) | Capacity | Power         | Weight | Introduction |
|---------------------------|-----------------|-----------------|---------------------|----------|--------------|---------|---------------|
| HEMU430X                    | ``HEMU430X``  |  **421 km/h** | **430 km/h**        |               | **8200kW** | 51t      | **2012**       |

1호차(TC): **특실 22석**
2호차(M1): **특실 34석**
3호차(M2): **시험계측실**
4호차(T1): 일반실 40석(1층) + 78석(2층)
5호차(T2): 일반실 40석(1층) + 78석(2층)
6호차(M3): **스낵카 및 가족실 18석**
7호차(M4): **일반실 55석**
8호차(MC): **검측실 및 동력실**

참고자료가 부족하여 2층객차인 4, 5호차의 좌석수는 임의로 계산하였습니다.

**References**
* <https://youtu.be/VPMkVRk1YN8>
* <https://youtu.be/bAf5KlV7MF8?t=40>
* <https://youtu.be/HV9-7bVqoHQ?t=20>
* <https://blog.naver.com/korail5148/50176576193>
* <https://blog.naver.com/npbs1122/221103694851>
* <https://blog.naver.com/digmon2001/221057363270>

**Example**
![예상도](https://user-images.githubusercontent.com/77984422/118016855-dda25d00-b390-11eb-924b-afd68768e200.png)

**Comment by telk5093** [comment]
OpenCreative/KR_Plus_Set/issues/47 에서 구현되었으므로 한국 열차 세트에서 구현할 이유가 없을 듯하므로 이슈를 닫습니다.

**Comment by SerpensNebula** [comment]
![전동차 HEMU-430X 1차 완성](https://github.com/KoreanGRF/KoreanTrainSet/assets/75788864/44945bff-cbb6-4d97-9faf-2a7b058637a0)

제대로 만들어보고싶었기 때문에 우선 만들어둡니다.

1과 1', 3과 3', 4와 4'는 늘 같이 있어야 합니다. 2와 2'는 3과 3'이 없을때 같이 있어야 하고, 3과 3'은 2와 2' 사이에 있어야 합니다.

**Comment by telk5093** [comment]
8량 이상의 짝수 차량 편성일 경우는 어떻게 되나요?
``1 - 1' - 4 - ... - 4 - 2 - 3 - 3' - 2' - 4 - ... - 4 - 5' - 5``` 면 되나요?

**Comment by SerpensNebula** [comment]
그렇게 하시면 될 것 같습니다. 사실 9량부턴 가상이라 마음대로 하셔도 상관 없습니다. 지붕이 튀어나온 부분끼리 붙어있어야 한다는 것만 주의하시면 됩니다. 

매우 긴 길이에서 4가 너무 많아지는것 같으면, 2 - 3 - 3' - 2' 배치가 하나 더 생긴다거나 이렇게 해도 되겠지요.
